### ISSUE TITLE
希望能出一个无密码功能的版本

### ISSUE THREAD

**Issue by lyizhuo** [yuantuo666/baiduwp-php#1]
希望能出一个无密码功能的版本，现在的版本把带有密码的几行代码删掉以后，点「打开」会跳转回首页，无法使用。

**Comment by lc6464** [comment]
## 我把这个功能实现了
- 你可以看一下我提交的 pr 或者我 fork 的储存库
- 我已经通知原作者了。

**Comment by lyizhuo** [comment]
> ## 我把这个功能实现了
> * 你可以看一下我提交的 pr 或者我 fork 的储存库
> * 我已经通知原作者了。

- 把 true 改成 flase 以后，还是会显示密码的输入框

- 可以把这个框去掉吗

**Comment by lc6464** [comment]
会吗？？
你用的是哪个版本的？
我记得我第一次增加选择密码功能就设计了如果不用密码的话不输出密码输入框啊？
后面完善的版本就更别说了，我从来都没遇到过这个问题。
- 你是不是三个 php 文件版本不同？
- 或者你误删了相关的设置？
- 或者你用的版本不支持？
你重新下载一下1.3.5的程序文件或者把我的整个储存库 Clone 下来试试。

**Comment by lyizhuo** [comment]
![image](https://user-images.githubusercontent.com/64514694/90465264-98bf0200-e141-11ea-9a68-f55b462154ba.png)
我这样修改正确吗

**Comment by lc6464** [comment]
如何修改？

**Comment by lc6464** [comment]
我这出了点问题，看不到你发的代码。

**Comment by yzy613** [comment]
> ![image](https://user-images.githubusercontent.com/64514694/90465264-98bf0200-e141-11ea-9a68-f55b462154ba.png)
> 我这样修改正确吗

What the fuck is 'flase'?
Why not is 'false'????

**Comment by lyizhuo** [comment]
> > ![image](https://user-images.githubusercontent.com/64514694/90465264-98bf0200-e141-11ea-9a68-f55b462154ba.png)
> > 我这样修改正确吗
> 
> What the fuck is 'flase'?
> Why not is 'false'????

Oh

**Comment by lyizhuo** [comment]
Thx

**Comment by lc6464** [comment]
不是吧照着注释抄还能把 false 抄错？
