### ISSUE TITLE
IDM下载降速

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#103]
群友反馈，电脑idm下载一会就降速，我自己的解析站，还有这个demo都试了，手机正常下载
 链接:https://pan.baidu.com/s/1l18wLN37sRgWRSW4_OHrvg 提取码:608u
![6b2b88b4670e0fe1](https://user-images.githubusercontent.com/77104800/113469836-5bff0b80-9483-11eb-9f50-cfbfe1b4b32e.jpg)
![235307d153448433](https://user-images.githubusercontent.com/77104800/113469840-5e616580-9483-11eb-8fab-91ee2712bf89.jpg)

**Comment by yuantuo666** [comment]
我这边测试没有问题，请尝试 降低分片次数 或 使用其他软件。
IDM效果不一定是最好的，只要是能够修改UA的都可以下载。
