### ISSUE TITLE
aria2无法推送到自己的服务器

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#104]
输入ip地址+端口+密钥后，点击发送窗口直接关闭，aria2控制台没看推送的文件。

**Comment by yuantuo666** [comment]
打开浏览器的控制台并截图

**Comment by yuantuo666** [comment]
我没有测试过推送服务器，请提供一下服务器网络环境，是局域网还是公网。
公网请确认开启对应端口

**Comment by jiemo9527** [comment]
同上，没有出错也没有推送任务

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/113495493-c4ea9000-9524-11eb-9aca-d716dd6d38dc.png)
![image](https://user-images.githubusercontent.com/44130602/113495503-d16ee880-9524-11eb-8e26-c8f4c001ada0.png)
似乎https发出的请求必须要连接加密的websocket

![image](https://user-images.githubusercontent.com/44130602/113495534-1abf3800-9525-11eb-8b27-983f5e8d75e1.png)

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/113495579-6245c400-9525-11eb-9575-05f37f8506f2.png)
![image](https://user-images.githubusercontent.com/44130602/113495584-6671e180-9525-11eb-8b3f-e5ae9854ce10.png)
使用http网页即可推送

**Comment by jiemo9527** [comment]
我用的是，http→ws
f12如下↓
MessageEvent {isTrusted: true, data: "{"id":"baiduwp-php","jsonrpc":"2.0","error":{"code":1,"message":"Unauthorized"}}", origin: "ws://自己的域名:6800", lastEventId: "", source: null, …}
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: WebSocket {url: "ws://自己的域名:6800/jsonrpc", readyState: 1, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
data: "{"id":"baiduwp-php","jsonrpc":"2.0","error":{"code":1,"message":"Unauthorized"}}"
defaultPrevented: false
eventPhase: 0
isTrusted: true
lastEventId: ""
origin: "ws://自己的域名:6800"
path: []
ports: []
returnValue: true
source: null
srcElement: WebSocket {url: "ws://自己的域名:6800/jsonrpc", readyState: 1, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
target: WebSocket {url: "ws://自己的域名:6800/jsonrpc", readyState: 1, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
timeStamp: 433641.91500000015
type: "message"
userActivation: null
__proto__: MessageEvent

**Comment by yuantuo666** [comment]
Unauthorized 可能是token验证失败，之前本地测试时似乎也存在这个问题，可以尝试删除token推送

**Comment by lc6464** [comment]
HTTPS  WSS 才是最佳解决方案，但是那个 aria2 的服务端（其实我不是很清楚 aria2 的服务端和客户端分别指什么，我甚至基本不了解 aria2）是否支持 WSS 是个问题。

**Comment by jiemo9527** [comment]
> Unauthorized 可能是token验证失败，之前本地测试时似乎也存在这个问题，可以尝试删除token推送

token留空不太安全；我用的aria2配置上也不允许

**Comment by jiemo9527** [comment]
> HTTPS WSS 才是最佳解决方案，但是那个 aria2 的服务端（其实我不是很清楚 aria2 的服务端和客户端分别指什么，我甚至基本不了解 aria2）是否支持 WSS 是个问题。

支持wss的

**Comment by lc6464** [comment]
> 支持wss的

所以现在问题就出在为什么不能连上 wss

**Comment by lc6464** [comment]
> 支持wss的

还有就是证书从何而来，wss 也是要证书的吧。

**Comment by GreenTeodoro839** [comment]
> Unauthorized 可能是token验证失败，之前本地测试时似乎也存在这个问题，可以尝试删除token推送

经测试，在aria2.conf注释token那一行，然后token留空，服务器地址直接填ip，就能以http协议推送，我是内网服务器

**Comment by GreenTeodoro839** [comment]
http不设置token就行了，https无解，希望能改回原来的aria2推送

**Comment by jiemo9527** [comment]
> http不设置token就行了，https无解，希望能改回原来的aria2推送

不设置token有效，但是不倾向于这种方法

**Comment by lc6464** [comment]
> http不设置token就行了，https无解，希望能改回原来的aria2推送

既 HTTP 又不设置 TOKEN？
这安全性？

**Comment by yuantuo666** [comment]
目前准备实现
http→ws(远程服务器) 可带token
https→wss(远程服务器) 可带token
http(s)→ws(本地) 可带token
原来的推送有跨域问题，除非域名一致无法正常推送

**Comment by GreenTeodoro839** [comment]
> 目前准备实现
> http→ws(远程服务器) 可带token
> https→wss(远程服务器) 可带token
> http(s)→ws(本地) 可带token
> 原来的推送有跨域问题，除非域名一致无法正常推送

请问需要多久，如果难度大的话我就换回旧版，好多群友需要这个功能

**Comment by yuantuo666** [comment]
可以尝试这个版本，修复了token的问题 https://github.com/yuantuo666/baiduwp-php/pull/106/commits/8b1900d3c2ad5febd0c2d75f4b529048ce00e069

**Comment by chwl66** [comment]
> 可以尝试这个版本，修复了token的问题 [8b1900d](https://github.com/yuantuo666/baiduwp-php/commit/8b1900d3c2ad5febd0c2d75f4b529048ce00e069)

我使用了这个版本后，远程服务器还是不能连接！

**Comment by yuantuo666** [comment]
> > 可以尝试这个版本，修复了token的问题 [8b1900d](https://github.com/yuantuo666/baiduwp-php/commit/8b1900d3c2ad5febd0c2d75f4b529048ce00e069)
> 
> 我使用了这个版本后，远程服务器还是不能连接！

请打开浏览器控制台截图反馈

目前支持
http→ws(远程服务器) 可带token
https→wss(远程服务器) 可带token
http(s)→ws(本地) 可带token

**Comment by chwl66** [comment]
> > > 可以尝试这个版本，修复了token的问题 [8b1900d](https://github.com/yuantuo666/baiduwp-php/commit/8b1900d3c2ad5febd0c2d75f4b529048ce00e069)
> > 
> > 
> > 我使用了这个版本后，远程服务器还是不能连接！
> 
> 请打开浏览器控制台截图反馈
> 
> 目前支持
> http→ws(远程服务器) 可带token
> https→wss(远程服务器) 可带token
> http(s)→ws(本地) 可带token

上次我使用的是https连接的，所以才链接不上，换成wss以后就可以了！不好意思，没仔细测试！

**Comment by lc6464** [comment]
根据 [Comment 817865702](https://github.com/yuantuo666/baiduwp-php/issues/104#issuecomment-817865702)， 目前支持的连接方式有（均支持 TOKEN）：
| 访问项目使用的协议（浏览器地址栏）| 连接 Aria2 使用的协议（WebSocket）| Aria2 服务器位置 |
| :----------: | :----------: | :----------: |
| HTTP | ws | Remote |
| HTTPS | wss | Remote |
| HTTP | ws | Local |
| HTTPS | ws | Local |
