### ISSUE TITLE
svip总是限速

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#108]
短时间解析大量文件，svip会被标记为限速，实际官方客户端仍然能满速下载，cookie未失效。这种情况只能在后台重置账号状态解决

**Comment by yuantuo666** [comment]
可以设置会员账号切换模式
手动模式则会忽视账号是否限速，一直解析

建议多添加几个账号，然后使用轮换模式

**Comment by GreenTeodoro839** [comment]
> 可以设置会员账号切换模式
> 手动模式则会忽视账号是否限速，一直解析
> 
> 建议多添加几个账号，然后使用轮换模式

我这个是轮换模式，但是解析3-5个文件就提示限速，可能是百度限制了单ip请求数量。后台重置状态后svip仍然能用

**Comment by GreenTeodoro839** [comment]
目前已知qdall01开头的是限速直链，不能下载，能否自动清除这类链接的记录？要不重新解析要么得联系站长删除这些东西，要么得等8小时

**Comment by yuantuo666** [comment]
本身这个项目就不是用来运营的
可能不会添加该功能

如果想要增加此功能，请自行研究，实现方法很简单

**Comment by yuantuo666** [comment]
我的初衷是希望这个项目能**帮**到一些人，让他们能从这个小项目开始学习编程，走近编程。

**Comment by GreenTeodoro839** [comment]
我用的是最新dev版，svip没限速，却提示限速，自动切换时提示post传参错误，然后跳转后数据库里所有的svip都被标记为限速，是轮换模式

**Comment by yuantuo666** [comment]
下一个版本增加不标记限速的轮换模式

**Comment by yuantuo666** [comment]
此问题与 #113 原因相同，可能是因为百度限制了分享下载接口导致的

**Comment by yuantuo666** [comment]
参加 #113
