### ISSUE TITLE
希望能增加黑白名单定时删除和编辑功能

### ISSUE THREAD

**Issue by w1915591935** [yuantuo666/baiduwp-php#110]
定时删除和编辑功能

**Comment by yuantuo666** [comment]
参见https://github.com/yuantuo666/baiduwp-php/issues/108#issuecomment-819620649

这个项目的目的不是用来运营，仅仅提供一个学习代码的机会，希望更多人能从中学到一些知识，尽管有的代码写的确实不好，但至少也有一些可取之处。

**Comment by yuantuo666** [comment]
会考虑增加的

**Comment by yuantuo666** [comment]
定时删除实现思路：①增加定时任务功能，新建数据表存储sql指令，定时执行。②修改白名单数据表，增加删除时间一栏，定时任务检测如果有超时的ip进行删除。

**Comment by lc6464** [comment]
研究了一下，临时授权码需要更改数据库结构，我们需要先把相关的准备工作（比如说数据导出、导入什么的）做好才行，这个优先级将会比较低。

**Comment by yuantuo666** [comment]
意义不大，不再考虑此提议
