### ISSUE TITLE
增加临时授权码功能

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#111]
现在这样有些人换ip调用，导致几秒钟就黑了服务器ip，一天的解析量接近2T。能不能添加多个密码，每个密码有最多使用次数或者每天使用次数

**Comment by lc6464** [comment]
其实这个功能，还有临时授权码之类的功能，我们都在设想。

**Comment by GreenTeodoro839** [comment]
我认为可以在config.php设置ip/授权码模式，然后数据库里写入可用的授权码，解析时就像svip那样标记是否过期，和现在的ip模式一样判断当天的使用次数

**Comment by JMVoid** [comment]
> 现在这样有些人换ip调用，导致几秒钟就黑了服务器ip，一天的解析量接近2T。能不能添加多个密码，每个密码有最多使用次数或者每天使用次数

请问黑了服务器IP是指百度拉黑服务器IP吗？不是应该会拉黑百度账户吗？

**Comment by yuantuo666** [comment]
> > 现在这样有些人换ip调用，导致几秒钟就黑了服务器ip，一天的解析量接近2T。能不能添加多个密码，每个密码有最多使用次数或者每天使用次数
> 
> 请问黑了服务器IP是指百度拉黑服务器IP吗？不是应该会拉黑百度账户吗？

大量解析>50TB才会导致封ip，报错110

**Comment by JMVoid** [comment]
感谢回复先。我还有二个疑问：1. 百度是以解析过下载链接的文件大小总量来决定是否封锁IP？ 2. 如果购买SVIP账户又用来做解析，有可能会被拉黑SVIP帐户吗？多谢了

**Comment by yuantuo666** [comment]
> 感谢回复先。我还有二个疑问：1. 百度是以解析过下载链接的文件大小总量来决定是否封锁IP？ 2. 如果购买SVIP账户又用来做解析，有可能会被拉黑SVIP帐户吗？多谢了

1.以所有账号总量确定封禁ip。
2.SVIP账号解析，超过5TB会被限速。

即 当每个SVIP账号解析达到5TB会被限速，更换账号后可继续解析。解析总量达到50TB后（也有可能是对应的次数），服务器ip会被封禁。

**Comment by GreenTeodoro839** [comment]
请问ip被封禁了有没有办法解开？vps一下买了好几年，不能换ip

**Comment by yuantuo666** [comment]
> 请问ip被封禁了有没有办法解开？vps一下买了好几年，不能换ip

设置curl的代理

**Comment by lc6464** [comment]
研究了一下，临时授权码需要更改数据库结构，我们需要先把相关的准备工作（比如说数据导出、导入什么的）做好才行，这个优先级将会比较低。

**Comment by budingjiangya** [comment]
> 感谢回复先。我还有二个疑问：1. 百度是以解析过下载链接的文件大小总量来决定是否封锁IP？ 2. 如果购买SVIP账户又用来做解析，有可能会被拉黑SVIP帐户吗？多谢了

日ip超过6t 7t左右有极大概率锁掉ip 
![image](https://user-images.githubusercontent.com/88592129/141603222-1a1ec610-2d37-4e27-b25e-20e3e3aaf904.png) 我已经锁了10多个ip了 解决方法很简单 弹性服务器 购买多ip  设置cdn权重 建议一次性弄3个ip  这样一天解析20多g都没问题  原理就算每一个ip解析了几十次 会进行锁定并且替换新ip 这样3个ip一直在轮流切换  缺点很明显  就算烧钱
