### ISSUE TITLE
解析＜50M的文件会卡bug

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#112]
可能是微信api这个方法无效？＜50M的文件解析就会导致正在使用的svip标记为限速，然后报post传参错误，再解析会使下一个svip标记为限速，最后所有正常的svip都会标记为限速。如果不方便改能否说一下怎样去掉微信api这个方法
复制这段内容后打开百度网盘App，操作更方便哦。 链接:https://pan.baidu.com/s/1gNAsTWEQeKIoCm-rBDturA 提取码:b9kq--来自百度网盘超级会员V2的分享

**Comment by yuantuo666** [comment]
解决方法：取消index.php 352行的注释
问题原因：本地普通账号账号限速，导致小文件获取方法失效，错误的将会员账号标记。
与微信api无关。


问题出现在dev分支中，master分支无无问题。
建议生产环境不要使用dev分支。

**Comment by GreenTeodoro839** [comment]
> 解决方法：取消index.php 352行的注释
> 问题原因：本地普通账号账号限速，导致小文件获取方法失效，错误的将会员账号标记。
> 与微信api无关。
> 
> 问题出现在dev分支中，master分支无无问题。
> 建议生产环境不要使用dev分支。

我要换回master分支，但是aria2推送不能带token，我应该把dev分支里哪个管理aria2推送的文件替换上

**Comment by yuantuo666** [comment]
> 解决方法：取消index.php 352行的注释

写的很清楚了

**Comment by GreenTeodoro839** [comment]
能否把dev里修复aria2合并的master
