### ISSUE TITLE
解析方法存在易被限速问题

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#113]
现在这个方法似乎被盯上了，很容易限速，限速的账号手机百度网盘客户端也不能正常svip加速，但电脑端可以正常使用svip加速。能不能用电脑端这个方法去获取链接

**Comment by yuantuo666** [comment]
①请使用官方账号解析；
②不建议做公益解析，建议自己或与朋友使用；
③如果百度方面对此项目有意见，我愿意与他们沟通，探讨相关问题。

![Screenshot_20210429_231512](https://user-images.githubusercontent.com/44130602/116574986-d1ee7980-a940-11eb-8a65-168dc322d1ea.jpg)

**Comment by GreenTeodoro839** [comment]
你确定这不是修改版的源代码吗？

**Comment by yuantuo666** [comment]
你有能力可以修改，仅需保存版权即可

**Comment by yuantuo666** [comment]
测试确实发现存在此问题，分享下载的接口似乎已经被限制了
解析不到5TB就会被限速

**Comment by JMVoid** [comment]
分享下载接口被限制是指 通过getDlink() 拿到的直接下载链接分享使用后，在解析的数据量达到几百G或者数T后,该SVIP帐户就被限速了。我的理解对吗？

**Comment by yuantuo666** [comment]
你的理解是对的


这里有两个限制
一个是SVIP账号限速，就是上文提到的。
  原先达到5TB就会将SVIP账号限速，现在达到几百GB就会限速。

另外一个是服务器IP被封禁，报错110，解析达到几十TB时出现。

**Comment by JMVoid** [comment]
感谢回复了，再请教一个问题。百度的客户端(电脑，手机端)也是通过获取直连下载方式进行下载的吗？百度的官方客户端是否也有每月下载的数据量的限制？

**Comment by yuantuo666** [comment]
> 感谢回复了，再请教一个问题。百度的客户端(电脑，手机端)也是通过获取直连下载方式进行下载的吗？百度的官方客户端是否也有每月下载的数据量的限制？

也存在限制，但并不是通过此接口获取下载链接

**Comment by yuantuo666** [comment]
此接口（项目中使用的）目前是最稳定的，自从去年开始一直没有被百度封禁，其它接口很容易就被封禁
此外，#144 中提到的客户端没限速而此项目限速问题是存在的，因能力所限不能逆向百度网盘客户端拿到相关算法，所以更换不了接口

**Comment by lc6464** [comment]
暂时关闭此议题，如有更新进展我们会重新打开，如果您有关于此方面的新的议题或建议，您可以重新打开。

**Comment by budingjiangya** [comment]
[![image]https://user-images.githubusercontent.com/88592129/141603054-05bbcf93-6b08-4a92-a843-98832830c87c.png](https://user-images.githubusercontent.com/88592129/141603054-05bbcf93-6b08-4a92-a843-98832830c87c.png)   限速很正常公益维护成本高同时还要面临锁ip的风险

**Comment by yuantuo666** [comment]
自四月份开始，百度加强了对账号的封禁力度。测试显示，很多 SVIP 账号解析下载 200 - 300 GB 就会遭到限制，报错 9013。

**Comment by pinyangcong** [comment]
> 自四月份开始，百度加强了对账号的封禁力度。测试显示，很多 SVIP 账号解析下载 200 - 300 GB 就会遭到限制，报错 9013。

我想问一下，是频率达到多少出触发限制，一天几百GB还是一个月几百GB，第二个月会解除限制吗

**Comment by yuantuo666** [comment]
> > 自四月份开始，百度加强了对账号的封禁力度。测试显示，很多 SVIP 账号解析下载 200 - 300 GB 就会遭到限制，报错 9013。
> 
> 我想问一下，是频率达到多少出触发限制，一天几百GB还是一个月几百GB，第二个月会解除限制吗

12月测试结果：账号在5分钟内下载100GB左右会遭到封禁，等待3天后会解封。不同时间长度的封禁情况还有待测试。

**Comment by pinyangcong** [comment]
> > > 自四月份开始，百度加强了对账号的封禁力度。测试显示，很多 SVIP 账号解析下载 200 - 300 GB 就会遭到限制，报错 9013。
> > 
> > 
> > 我想问一下，是频率达到多少出触发限制，一天几百GB还是一个月几百GB，第二个月会解除限制吗
> 
> 12月测试结果：账号在5分钟内下载100GB左右会遭到封禁，等待3天后会解封。不同时间长度的封禁情况还有待测试。

你好，一个帐号限速切换后到另一个SVIP还是限速是怎么回事，是网站本身使用的Cookie还没更新吗

**Comment by yuantuo666** [comment]
> > > > 自四月份开始，百度加强了对账号的封禁力度。测试显示，很多 SVIP 账号解析下载 200 - 300 GB 就会遭到限制，报错 9013。
> > > 
> > > 
> > > 我想问一下，是频率达到多少出触发限制，一天几百GB还是一个月几百GB，第二个月会解除限制吗
> > 
> > 
> > 12月测试结果：账号在5分钟内下载100GB左右会遭到封禁，等待3天后会解封。不同时间长度的封禁情况还有待测试。
> 
> 你好，一个帐号限速切换后到另一个SVIP还是限速是怎么回事，是网站本身使用的Cookie还没更新吗

使用的是最新版本吗？最新版本切换之后还是限速的话，说明账号都用光了，全都是限速账号了。如果需要报告 bug 请提起新的 issue。

**Comment by pinyangcong** [comment]
> > > > > 自四月份开始，百度加强了对账号的封禁力度。测试显示，很多 SVIP 账号解析下载 200 - 300 GB 就会遭到限制，报错 9013。
> > > > 
> > > > 
> > > > 我想问一下，是频率达到多少出触发限制，一天几百GB还是一个月几百GB，第二个月会解除限制吗
> > > 
> > > 
> > > 12月测试结果：账号在5分钟内下载100GB左右会遭到封禁，等待3天后会解封。不同时间长度的封禁情况还有待测试。
> > 
> > 
> > 你好，一个帐号限速切换后到另一个SVIP还是限速是怎么回事，是网站本身使用的Cookie还没更新吗
> 
> 使用的是最新版本吗？最新版本切换之后还是限速的话，说明账号都用光了，全都是限速账号了。如果需要报告 bug 请提起新的 issue。

是最新版，但是另一个SVIP还是新买的，不太可能因为下载太多就限速了。。。

**Comment by xuexiaokang** [comment]
发现SVIP账号只要不正常过，现在哪怕已经恢复正常了，系统后台还是显示会员账号状态“”账号失效“”
