### ISSUE TITLE
WebSocket 地址验证正则有误

### ISSUE THREAD

**Issue by lc6464** [yuantuo666/baiduwp-php#114]
直接使用 IPv6 地址作为域名的 WebSocket 连接地址无法正常使用。

**Comment by lc6464** [comment]
（我重新写的正则明明没有问题的）

**Comment by yuantuo666** [comment]
`/^wss?\:\/\/(((([A-Za-z0-9]+[A-Za-z0-9\-]+[A-Za-z0-9]+)|([A-Za-z0-9]+))(\.([A-Za-z0-9]+[A-Za-z0-9\-]+[A-Za-z0-9]+)|([A-Za-z0-9]+))*(\.[A-Za-z0-9]{2,10}))|localhost|(([01]?\d?\d)|(2[0-4]\d)|(25[0-5]))(\.([01]?\d?\d)|(2[0-4]\d)|(25[0-5])){3}|((\[[A-Za-z0-9:]{2,39}\])|([A-Za-z0-9:]{2,39})))(\:\d{1,5})?(\/.*)?$/`
就是有**一**点长
