### ISSUE TITLE
如何进入后台管理页面

### ISSUE THREAD

**Issue by woshinibb66** [yuantuo666/baiduwp-php#116]
新手，刚接触，请问一下设置vip账号也没有一个后台进入，只能在setting里面看嘛，看不到php。。

**Comment by woshinibb66** [comment]
看不懂

**Comment by lc6464** [comment]
你指的是后台管理？
试试 settings.php

**Comment by woshinibb66** [comment]
用网页打开后台是吗

**Comment by woshinibb66** [comment]
就是我想加一个vip账号，我需要在settings.php.里面打开设置是吗？

**Comment by lc6464** [comment]
浏览器访问 settings.php

**Comment by woshinibb66** [comment]
太多了，找不到，我现在都是在那个config里面修改，买了一个微博会员号，速度1m/s，这个速度是因为共享号的原因还是我没设置好的原因，还有在哪里看那个普通会员和vip的状态呢，谢谢了，新手表达不充分之处，还望体谅

**Comment by GreenTeodoro839** [comment]
不要使用共享号，必须自己购买svip，否则基本是几个小时就限速

**Comment by GreenTeodoro839** [comment]
另外1M左右的速度是账号处于限速临界点上

**Comment by woshinibb66** [comment]
> 不要使用共享号，必须自己购买svip，否则基本是几个小时就限速

谢谢谢谢

**Comment by woshinibb66** [comment]
请大佬关闭问题把，我反复看了作者的教程都知道了，谢谢大佬有时间回复小白！

**Comment by woshinibb66** [comment]
> 另外1M左右的速度是账号处于限速临界点上

就是后台显示正常，但是解析显示限速，下载的话还是1m左右，如果一直可用的话，自用还是可以的hhh

**Comment by woshinibb66** [comment]
> 不要使用共享号，必须自己购买svip，否则基本是几个小时就限速

共享号不行，那3·4个人合租的vip理论是否比较稳定，可实施吗？

**Comment by yuantuo666** [comment]
建议购买百度网盘官方会员
