### ISSUE TITLE
接口废了

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#117]
https://user-images.githubusercontent.com/77104800/117923011-f0337c80-b325-11eb-80d0-b5628938c63b.mp4

假限速
![2df408863f2c11c42b6ee4816434416e](https://user-images.githubusercontent.com/77104800/117923028-fc1f3e80-b325-11eb-8fbf-c97500df1d7b.jpg)这是真的限速

**Comment by pongfcnkl** [comment]
官方的客户端有p2p

**Comment by GreenTeodoro839** [comment]
你仔细看过吗？用了这个解析，限速只显示封禁原因。而下载过量限速。会带着当前速度。而且我测试的是我重新打包上传的文件，没有分享过

**Comment by yuantuo666** [comment]
麻烦详细描述一下
你的意思是指使用了本项目后，账号会进入“假限速”状态吗

**Comment by GreenTeodoro839** [comment]
是的，大约300G左右，会被假限速，不能再用来直链解析，但是电脑/手机都能正常用svip加速，且客户端的限速诊断与超量下载不同

**Comment by yuantuo666** [comment]
https://github.com/yuantuo666/baiduwp-php/issues/113#issuecomment-832001591
现在已经确定 百度对分享下载接口有限制
我之前测试也发现有这个情况

**Comment by pongfcnkl** [comment]
P2P是从一大堆别人的设备上传下载数据块，相当于给百度做cdn，和是不是新文件或者分享过都无关。
如果要加入P2P，那得魔改aria2c

**Comment by GreenTeodoro839** [comment]
> P2P是从一大堆别人的设备上传下载数据块，相当于给百度做cdn，和是不是新文件或者分享过都无关。
> 如果要加入P2P，那得魔改aria2c

这不是因为P2P，你可以看一下下面的视频，同样环境下下载过量导致的黑号(试用svip加速，是一个svip过期了，但没有放出来)，一个是做解析用的svip假限速之后(有svip加速)

https://user-images.githubusercontent.com/77104800/118078865-94cac280-b3e9-11eb-8503-7919c7e8379c.mp4

https://user-images.githubusercontent.com/77104800/118078873-985e4980-b3e9-11eb-837b-44e7ebe08ad8.mp4

**Comment by pongfcnkl** [comment]
> 
> 
> > P2P是从一大堆别人的设备上传下载数据块，相当于给百度做cdn，和是不是新文件或者分享过都无关。
> > 如果要加入P2P，那得魔改aria2c
> 
> 这不是因为P2P，你可以看一下下面的视频，同样环境下下载过量导致的黑号(试用svip加速，是一个svip过期了，但没有放出来)，一个是做解析用的svip假限速之后(有svip加速)
> SVID_20210513_124300_1.mp4
> SVID_20210513_124419_1.mp4

你不要拿新版本说事，直接找个老版本看看还有没有速度吧。

**Comment by pongfcnkl** [comment]
> 
> 
> > P2P是从一大堆别人的设备上传下载数据块，相当于给百度做cdn，和是不是新文件或者分享过都无关。
> > 如果要加入P2P，那得魔改aria2c
> 
> 这不是因为P2P，你可以看一下下面的视频，同样环境下下载过量导致的黑号(试用svip加速，是一个svip过期了，但没有放出来)，一个是做解析用的svip假限速之后(有svip加速)
> SVID_20210513_124300_1.mp4
> SVID_20210513_124419_1.mp4

这个技术也不叫P2P

> 
> 
> > P2P是从一大堆别人的设备上传下载数据块，相当于给百度做cdn，和是不是新文件或者分享过都无关。
> > 如果要加入P2P，那得魔改aria2c
> 
> 这不是因为P2P，你可以看一下下面的视频，同样环境下下载过量导致的黑号(试用svip加速，是一个svip过期了，但没有放出来)，一个是做解析用的svip假限速之后(有svip加速)
> SVID_20210513_124300_1.mp4
> SVID_20210513_124419_1.mp4

最主要的就是现在的api太老，没有p2pcdn，这个不应该叫假限速，应该说是百度自己的CDN限速。

**Comment by GreenTeodoro839** [comment]
> > > P2P是从一大堆别人的设备上传下载数据块，相当于给百度做cdn，和是不是新文件或者分享过都无关。
> > > 如果要加入P2P，那得魔改aria2c
> > 
> > 
> > 这不是因为P2P，你可以看一下下面的视频，同样环境下下载过量导致的黑号(试用svip加速，是一个svip过期了，但没有放出来)，一个是做解析用的svip假限速之后(有svip加速)
> > SVID_20210513_124300_1.mp4
> > SVID_20210513_124419_1.mp4
> 
> 最主要的就是现在的api太老，没有p2pcdn，这个不应该叫假限速，应该说是百度自己的CDN限速。

其实没有必要去搞p2pcdn，可以尝试把接口换成旧版客户端，分享下载接口基本不能用了。如果要是能用p2pcdn，那还用什么svip，普通账号都能满速，凉的更快

**Comment by yuantuo666** [comment]
这个接口限速的状况时好时坏吧，但还是能用
