### ISSUE TITLE
请问"发送到 Aria2"能否自定义存放路径？

### ISSUE THREAD

**Issue by 49470488** [yuantuo666/baiduwp-php#118]
"发送到 Aria2"自动下载的路径是"./baiduwp-php"，如图
![12](https://user-images.githubusercontent.com/71637330/118350667-9d0e3380-b58a-11eb-8018-49ac8c4ec9c8.jpg)

我是用群晖docker安装的aria2，默认映射的存放路径是/downloads，导致群晖里无法显示下载的文件，能否有办法自定义存放？

**Comment by yuantuo666** [comment]
之后版本中将会使用本地设置的地址

**Comment by 49470488** [comment]
> 之后版本中将会使用本地设置的地址

十分感谢

**Comment by 49470488** [comment]
> 之后版本中将会使用本地设置的地址

大佬，我刚刚更新了2.1.7版本，但故障还是依旧，用电脑版的motrix也无法下载到设置的下载路径里

**Comment by yuantuo666** [comment]
因为更新了js文件，需要清除缓存后使用

请先确认服务器（网页端）端是否有缓存，然后浏览器中按Crtl+F5刷新

**Comment by 49470488** [comment]
> 因为更新了js文件，需要清除缓存后使用
> 
> 请先确认服务器（网页端）端是否有缓存，然后浏览器中按Crtl+F5刷新

可以了，十分感谢
