### ISSUE TITLE
缺少config.php文件

### ISSUE THREAD

**Issue by 0x01x0** [yuantuo666/baiduwp-php#119]
安装结果： 不启用数据库
写入 config.php 文件失败，请检查 config.php 文件状态及当前用户权限。

**Comment by yuantuo666** [comment]
请检查是否给予PHP足够权限

**Comment by yuantuo666** [comment]
默认根目录下不存在config.php

在install文件夹下检查是否有模板文件及其权限是否足够

**Comment by 0x01x0** [comment]
install文件夹下有bdwp.sql和config_raw 全目录都给了0755权限 问题依旧

**Comment by 0x01x0** [comment]
全目录的意思是给了整个baiduwp-php权限

**Comment by yuantuo666** [comment]
提供一下系统环境

如果实在不行，可以自行复制config_raw到根目录，修改后保存为config.php

**Comment by 0x01x0** [comment]
Debian10

**Comment by yuantuo666** [comment]
请自行解决环境配置问题

**Comment by lc6464** [comment]
在 0755（`-rwxr-xr-x`）权限下仅有 root 和文件所有者有权写入文件，请检查运行 PHP 的用户是否为文件所有者或 root，若不是则无法写入。
