### ISSUE TITLE
解析到的链接无法使用

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#122]
ua设置了，尝试了浏览器，adm，aria2，提示图中这个
![Screenshot_20210522_060705_mark via](https://user-images.githubusercontent.com/77104800/119202874-4f328780-bac4-11eb-80e4-a15ffd11e524.jpg)
![Screenshot_20210522_060632_com dv adm](https://user-images.githubusercontent.com/77104800/119202880-50fc4b00-bac4-11eb-8219-861260c15e1a.jpg)
![Screenshot_20210522_060723_com xmader aria_ng_gui_android](https://user-images.githubusercontent.com/77104800/119202883-5194e180-bac4-11eb-97b0-0f73f3b9e6e0.jpg)

**Comment by imyxuan** [comment]
换个账号，或者重新获取token这两个参数试试

**Comment by yuantuo666** [comment]
sign error 有多种原因导致出错，建议重新获取该文件。
如果还是不能解决，请将该文件分享链接发送出来。

**Comment by yuantuo666** [comment]
1. 更换账号
2. 重新解析
