### ISSUE TITLE
settings.php无法访问

### ISSUE THREAD

**Issue by misaka-h** [yuantuo666/baiduwp-php#124]
安装成功后，若要再次访问settngs.php，输入密码后会跳转到空白页面，且更换设备也无法加载（连输入密码的页面也没有了），刷新也不行。
部署环境：安卓，termux，可以正常解析。

**Comment by yuantuo666** [comment]
是什么PHP版本呢，看安装页面install.php能不能正常访问

**Comment by misaka-h** [comment]
> 是什么PHP版本呢，看安装页面install.php能不能正常访问

php8.0.2，install.php可以进入，也可以正常安装。

**Comment by GreenTeodoro839** [comment]
php8......，php7.4兼容性最好

**Comment by yuantuo666** [comment]
请自行解决环境配置问题，不推荐使用termux
