### ISSUE TITLE
举报网站

### ISSUE THREAD

**Issue by muzihuaner** [yuantuo666/baiduwp-php#125]
https://pan.shuma.ink/

去掉了版权，貌似有盈利行为

**Comment by GreenTeodoro839** [comment]
这不只是去掉版权，还侮辱kinhdown作者。现在已经对这个网站进行攻击。站长还是捐赠的，建议作者把他拉黑

**Comment by yuantuo666** [comment]
感谢你的反馈
已尝试联系站长

**Comment by lc6464** [comment]
好像没什么效果的样子，真的解决了吗？

**Comment by lc6464** [comment]
它又504了，这段时间将会以很低的频率跟踪中（因为没什么时间）。

**Comment by lc6464** [comment]
好像又没问题了。
