### ISSUE TITLE
设置UA后还是服务器禁止访问此文件

### ISSUE THREAD

**Issue by HanaB-chan** [yuantuo666/baiduwp-php#127]
http 403 forbidden
是百度改了吗，今天才发现不能正常使用了
能获取到链接，但是下载出问题了，设置过UA
可能UA不行了？

**Comment by GreenTeodoro839** [comment]
有可能，我用的修改版，没这个问题

**Comment by yuantuo666** [comment]
所有版本都有这个问题的，有时候会出现部分文件无法下载，目前只能删除记录重新解析。
你可以尝试一下其他文件能否下载，如果其他文件可以下载，说明就是上述这种情况。

**Comment by budingjiangya** [comment]
很正常  只需要今天解析 001.zip  之后9小时 等链接失效了 然后再去 解析001.zip  你会发现已经失效了 导致无法下载
