### ISSUE TITLE
增加临时授权码功能

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#128]
我的解析网站今天一下被换ip刷了4T流量，还查不出来是谁。能不能给每个用户设置单独的密码，谁的出了问题就找他

**Comment by lc6464** [comment]
如果你说的是账户+密码的模式的话这个我们曾经讨论过，但并没有决定实现，或者说仍在讨论阶段。
还有一种可能的形式是临时授权码，也仍在讨论阶段中。

**Comment by GreenTeodoro839** [comment]
临时授权码，可以设置有效期那种

**Comment by lc6464** [comment]
#111
