### ISSUE TITLE
已获取到文件，但未能获取到下载链接！

### ISSUE THREAD

**Issue by zhucaidan** [yuantuo666/baiduwp-php#129]
最近才开始的，获取账号和SVIP账号不是用一个，错误如下：
"获取下载链接失败
已获取到文件，但未能获取到下载链接！

请检查你是否在 config.php 中配置 SVIP 账号的 BDUSS 和 STOKEN！

未配置或配置了普通账号的均会导致失败！必须要 SVIP 账号！"

尝试用百度客户端使用SVIP账号倒是可以正常满速下载

**Comment by yuantuo666** [comment]
此问题是由于普通账号配置问题导致的，请确认普通账号cookie是否正确且账号未退出登录。

错误提示SVIP账号有问题是因为以前普通账号和会员账号的数据是合并的，所以就写成了一个数据，下一版本会对提示内容进行修改。

**Comment by zhucaidan** [comment]
真的很奇怪，我换了个全新IP的服务器，然后跟朋友借了个SVIP账号从来没用过这个项目的，还是弹出一样的错误

解析是可以，但是不让下载。。。

**Comment by yuantuo666** [comment]
跟服务器ip和SVIP账号无关

这个错误是因为普通账号设置错误导致的

**Comment by yuantuo666** [comment]
检查 config.php 中 BDUSS 和 STOKEN 的设置。

**Comment by zhucaidan** [comment]
> 检查 config.php 中 BDUSS 和 STOKEN 的设置。

可是普通账户和SVIP账户用的是一样的BDUSS 和 STOKEN啊

**Comment by yuantuo666** [comment]
自行解决账号设置问题
