### ISSUE TITLE
发现一个BUG，如果分享链接没密码，就会获取链接错误

### ISSUE THREAD

**Issue by 5536086** [yuantuo666/baiduwp-php#13]
“获取下载链接失败
未知错误！”

**Comment by yuantuo666** [comment]
那应该是js版本的，最新的PHP版错误有详细提示

**Comment by 5536086** [comment]
就是你这个版本哦，我随便找个没分享密码的链接你看看：https://pan.baidu.com/s/1kJ26A6S536olP4qCkSoaIQ

**Comment by yuantuo666** [comment]
哦哦 这个是因为文件太大了 js就使用科学计数法了

**Comment by yuantuo666** [comment]
刚刚提了pr https://github.com/yuantuo666/baiduwp-php/pull/14 现在应该修复了

**Comment by 5536086** [comment]
好的，我更新下再试试

**Comment by 5536086** [comment]
貌似还不行

**Comment by yuantuo666** [comment]
应该是百度限制了大文件，这个链接也没有密码，但可以下载：https://pan.baidu.com/s/1i5IkrQl 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by lc6464** [comment]
无论是否有密码的分享链接，10MB以内的文件我都试过，都可以下载。

**Comment by lc6464** [comment]
PHP 的详细错误提示好像在我增加打开文件夹功能的时候修改了一下获取文件列表的方式，导致没用了……

**Comment by 5536086** [comment]
> 应该是百度限制了大文件，这个链接也没有密码，但可以下载：https://pan.baidu.com/s/1i5IkrQl

但是我试了好几个文件，只有没密码的会获取错误，有密码的都能正常获取，好奇怪的问题

**Comment by lc6464** [comment]
- `1dfg34`
- `1qWsJVJ2`

这两个你试试，网上随便找的，都没有提取码。

**Comment by lc6464** [comment]
现在百度网盘好像都不能无需提取码分享文件了。。

**Comment by 5536086** [comment]
> * `1dfg34`
> * `1qWsJVJ2`
> 
> 这两个你试试，网上随便找的，都没有提取码。

这些确实可以，但是我找的哪些长点的那种就不行了

**Comment by lc6464** [comment]
发一个给我试试？

**Comment by 5536086** [comment]
> 发一个给我试试？

你试试：https://pan.baidu.com/s/1r0tAzkTYjdJywnhwHGJQmA

**Comment by lc6464** [comment]
这个确实不行……

**Comment by 5536086** [comment]
> 这个确实不行……

哈哈，对吧，也不知道啥原因

**Comment by lc6464** [comment]
估计是百度做了一些限制了。

**Comment by yuantuo666** [comment]
已经找到问题了，在没有密码时，randsk会被设置为空，部分文件没有这个参数就无法下载，报118错误。
新版本将修复此问题。

**Comment by 5536086** [comment]
好的，谢谢大佬！奥利给！

**Comment by yuantuo666** [comment]
https://github.com/yuantuo666/baiduwp-php/releases/tag/1.4.2 新版本已经修复 请更新尝试

**Comment by 5536086** [comment]
好像还是不行，以上面的无密码分享为例：https://pan.baidu.com/s/1r0tAzkTYjdJywnhwHGJQmA
错误如下图：
![QQ截图20200830174808](https://user-images.githubusercontent.com/20472307/91656167-23601380-eae9-11ea-8d99-fbefbd78af1a.jpg)

**Comment by yuantuo666** [comment]
新版本更新了js文件，请尝试更新服务器和浏览器缓存后重试。
浏览器可以按CTRL+F5强制刷新。

**Comment by yuantuo666** [comment]
![Screenshot_20200831_115937_com android chrome](https://user-images.githubusercontent.com/44130602/91681612-8d2bfc00-eb81-11ea-8bff-fc380cb0279c.jpg)
1.4.2版测试无问题
