### ISSUE TITLE
关于未来项目维护的声明

### ISSUE THREAD

**Issue by nick0425** [yuantuo666/baiduwp-php#130]
Donate 给你噢@@!
请继续更新

**Comment by yuantuo666** [comment]
马上就要高三了，之后很少有时间来维护这个项目了

**Comment by lc6464** [comment]
我也没什么时间维护了，可以在仓库数据中看到最近我的代码提交基本都没有了，也就提了些议题、回复了一些议题、审查了一些代码以及和 @yuantuo666 在QQ上有些交流。
过段时间我的贡献可能会更少。
