### ISSUE TITLE
奇怪的问题。这个文件名会导致数据库错误。后台无解析记录

### ISSUE THREAD

**Issue by dylanbai8** [yuantuo666/baiduwp-php#131]
奇怪的问题。这个文件名会导致数据库错误。后台无解析记录
把文件改名后可以正常解析。

![image](https://user-images.githubusercontent.com/26950227/123511083-e1c0da80-d6b1-11eb-90b1-d9da2225fa3d.png)

![image](https://user-images.githubusercontent.com/26950227/123511087-ea191580-d6b1-11eb-8181-9919b244ce4b.png)

链接: https://pan.baidu.com/s/1uhGFeixyEYlysE8WeiYs1g 提取码: mdbq 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by GreenTeodoro839** [comment]
部分中文特殊符号不符合mysql的要求，会插入失败

**Comment by lc6464** [comment]
你手动把 `index.php` 的第 476 行和第 477 行改为
```
$Sqlfilename = htmlspecialchars($filename, ENT_QUOTES);
$Sqlpath = htmlspecialchars($path, ENT_QUOTES);
```
试试？
