### ISSUE TITLE
希望可以解析整个文件夹

### ISSUE THREAD

**Issue by zzzqu** [yuantuo666/baiduwp-php#133]
一个一个点有点麻烦，后续可以支持一下吗

**Comment by yuantuo666** [comment]
百度没有提供分享打包下载接口
无法实现将文件夹打包下载

**Comment by lc6464** [comment]
倒不是没有解决方法，在前端用 JS 把链接遍历一遍，每个点一下😂

**Comment by lc6464** [comment]
后端逐个获取也是可以的，就是会有亿点慢，前端点起码还能感觉到在一个个加载，后端逐个加载前端就看不到了。
