### ISSUE TITLE
发送到aria2界面地址正则表达式有问题

### ISSUE THREAD

**Issue by yaowans** [yuantuo666/baiduwp-php#137]
刚好服务器IP的最后一位是200以上，发送的时候会提示地址不正确，然后域名刚好是非主流后缀的，也会提示地址不正确，建议把这个正则表达式取消

**Comment by lc6464** [comment]
您好，可以私发一下地址吗？我们对此分析一下。
你可以发给我 `lc@lcwebsite.cn` 或 `lclc6464@outlook.com` 或 `lcnull.64@gmail.com`
也可以发给 @yuantuo666

**Comment by yaowans** [comment]
> 您好，可以私发一下地址吗？我们对此分析一下。
> 你可以发给我 `lc@lcwebsite.cn` 或 `lclc6464@outlook.com` 或 `lcnull.64@gmail.com`
> 也可以发给 @yuantuo666

已经发送到 lc@lcwebsite.cn

**Comment by lc6464** [comment]
进度更新：问题正在受理中。

**Comment by lc6464** [comment]
问题已经解决，域名问题主要是因为一个 `\.` 放错位置了，导致所有多级域名（除非带有 `-`）都会无法通过，而 IP 地址问题原因暂时不是很清楚，可能是因为 JavaScript 引擎对正则表达式括号处理的一些我们不清楚的情况导致的 bug.
目前已经重写了一个表达式。

**Comment by lc6464** [comment]
欢迎下载 2.1.9 版本体验！

**Comment by 1219099256** [comment]
用eu.org的域名还是有问题

![image](https://user-images.githubusercontent.com/63403797/140283644-4ac9d60a-5a50-47a0-952f-3c052269d46c.png)

**Comment by 1219099256** [comment]
> 欢迎下载 2.1.9 版本体验！

用eu.org的域名还是有问题

![image](https://user-images.githubusercontent.com/63403797/140283644-4ac9d60a-5a50-47a0-952f-3c052269d46c.png)
![image](https://user-images.githubusercontent.com/63403797/140284496-d300cf2c-e00b-47e4-b7fa-9f4bdbbe00b6.png)

**Comment by lc6464** [comment]
> 用eu.org的域名还是有问题
> 
> ![image](https://user-images.githubusercontent.com/63403797/140283644-4ac9d60a-5a50-47a0-952f-3c052269d46c.png)
> ![image](https://user-images.githubusercontent.com/63403797/140284496-d300cf2c-e00b-47e4-b7fa-9f4bdbbe00b6.png)
> 


等我有空检查一下。
你也可以自己看看，正则应该在 `static/function.js` 里面。


（刚才本来点回复点成了编辑，不好意思）

**Comment by lc6464** [comment]
![Screenshot](https://user-images.githubusercontent.com/64722907/162598213-9859bfe5-1d82-4fa4-8050-512dc84574d9.png)

经测试，没有问题，请通过邮件提供完整域名以供测试。

**Comment by lc6464** [comment]
如果还有更多问题请重开议题。
