### ISSUE TITLE
解析后下载提示403

### ISSUE THREAD

**Issue by linkea131** [yuantuo666/baiduwp-php#138]
解析后下载提示403
![asdad](https://user-images.githubusercontent.com/50718406/123922557-bcd2ad00-d9ba-11eb-9a87-46e685241d9b.PNG)

**Comment by yuantuo666** [comment]
1. 检查是否设置ua
2. 链接失效，需重新解析
3. 文件有问题，重新分享
4. 实在不行把分享链接发出来

**Comment by linkea131** [comment]
链接:https://pan.baidu.com/s/1-Tf8qr_4-YNDJaXa6dep_w 提取码:725n

**Comment by linkea131** [comment]
链接:https://pan.baidu.com/s/1-Tf8qr_4-YNDJaXa6dep_w 提取码:725n
ua是问别人要的一个

**Comment by yuantuo666** [comment]
ua要设置成帮助中写的

**Comment by yuantuo666** [comment]
如果仍有问题，请再次打开此issue
