### ISSUE TITLE
无法正常下载

### ISSUE THREAD

**Issue by yzq313** [yuantuo666/baiduwp-php#139]
## 描述问题
现有下载接口疑似失效，motrix和idm均不能下载
https://bjbgp01.baidupcs.com/file/接口失效
尝试别人的接口可以正常下载

## 期望
下载接口更新

## 截图
![image](https://user-images.githubusercontent.com/67686611/125057961-5a755d00-e0dc-11eb-8b0a-287071d1ef30.png)

**Comment by lc6464** [comment]
您好，能否提供更加详细的信息？

**Comment by lc6464** [comment]
您好？

**Comment by lc6464** [comment]
您已经过长时间没有回复，我们无法得知您的状态，现关闭议题处理，如有需要可以再次打开。
