### ISSUE TITLE
【建议】精细化静态文件缓存控制

### ISSUE THREAD

**Issue by lc6464** [yuantuo666/baiduwp-php#143]
## 描述建议
静态文件用用户的 HTTP 服务器虽然效率高，但是缓存是个问题。

## 相关的技术
我想能不能用 PHP 来发送静态文件，方便配置缓存，也可以用 `ETag` 来更加精细地控制版本，问题就是效率比较低。

**Comment by yuantuo666** [comment]
一般使用NGINX来进行静态文件发放，有的人可能还想将静态文件部署到CDN，所以这不是一个有意义的提议
