### ISSUE TITLE
【寻求帮助】正常 SVIP 账号显示限速

### ISSUE THREAD

**Issue by zgx1996** [yuantuo666/baiduwp-php#144]
直接用百度网盘svip下载是能提速的，但是把这些账号的stoken与BDUSS 加入到后台，用这些账号去获取直链的时候，显示账号被限速，请问这是账号的问题还是有bug呢？
![image](https://user-images.githubusercontent.com/21330181/125645167-f6c63cb2-e375-4c30-9ecc-f8c585f087a5.png)
![image](https://user-images.githubusercontent.com/21330181/125645240-af6c76dd-2241-4b5a-8574-878f1fb6d0f4.png)

**Comment by lc6464** [comment]
似乎确实存在一个问题，可见 #113
但给我们提供了反馈的用户中的一部分又没有遇到这种情况。
这个问题我们仍在研究当中。

**Comment by lc6464** [comment]
参见 #113
如有新的进展我们会在此发布。

**Comment by yuantuo666** [comment]
现在的百度网盘客户端有P2P下载机制。如果SVIP账号被限制了，在百度网盘客户端上，热门文件仍然可以通过P2P进行下载，实际上并没有通过百度pcs服务器下载文件。
