### ISSUE TITLE
【建议】加入后台设置默认语言选项功能

### ISSUE THREAD

**Issue by HHHHHHLAN** [yuantuo666/baiduwp-php#145]
能否可以在后台设置默认语言为中文而不是跟随浏览器，因为在某些情况下它会识别为英文，而且这个项目外国友人应该使用也不多。

**Comment by yuantuo666** [comment]
我们会考虑加入后台设置默认语言的功能
能否提供一下错误识别的浏览器，以便于我们进行优化
此外，本项目在国外也有一定的使用量，对于外国友人来说，下载百度网盘的文件是件很麻烦的事，因为他们不能注册百度账号，而且百度也没有提供英文版页面。参见 https://youtu.be/8u8jx3Owuc8

**Comment by HHHHHHLAN** [comment]
我今天访问多个网站，已经在Safari（iPhone Xr ios14.6）、微信内部浏览器以及PC火狐浏览器随机出现，刷新就会变回去。
![QQ图片20210716165609](https://user-images.githubusercontent.com/29828228/125921616-78eadd1c-125f-44f3-aa6f-e636fa78d82c.png)
![QQ图片20210716165606](https://user-images.githubusercontent.com/29828228/125921599-85590e8c-65df-4d84-bc4a-3975ea21f4ae.jpg)

**Comment by lc6464** [comment]
这个识别功能似乎存在一个 bug，我也遇到过相同的问题。

**Comment by lc6464** [comment]
但是手动编辑一些语言列表来手动执行分析语言的函数，输出的语言优先级列表并没有问题，是否是因为浏览器的一些功能导致的问题？

**Comment by yuantuo666** [comment]
似乎是苹果Safari浏览器设置的标记是 zh-cn (小写)导致的

**Comment by yuantuo666** [comment]
![16294270360565886317418485417748](https://user-images.githubusercontent.com/44130602/130170387-ef9fcee1-d4bb-4019-8dac-fbeaae89fdce.jpg)

**Comment by lc6464** [comment]
> 似乎是苹果Safari浏览器设置的标记是 zh-cn (小写)导致的

就离谱。

**Comment by yuantuo666** [comment]
已经在新版本支持 https://github.com/yuantuo666/baiduwp-php/releases/tag/v2.2.0
