### ISSUE TITLE
【寻求帮助】IDM下载速度不稳定

### ISSUE THREAD

**Issue by po888375** [yuantuo666/baiduwp-php#146]
## 描述问题
解析完后使用idm下载，速度飙升后几秒归零，然后一直不稳定，100多K--10多K的下载

## 你需要的帮助
想知道是idm的问题还是解析的问题，使用的版本是最新版本

**Comment by yuantuo666** [comment]
有可能是因为账号被限速
或者下载到一半时限速

**Comment by po888375** [comment]
> ## 描述问题
> 解析完后使用idm下载，速度飙升后几秒归零，然后一直不稳定，100多K--10多K的下载
> 
> ## 你需要的帮助
> 想知道是idm的问题还是解析的问题，使用的版本是最新版本



> 有可能是因为账号被限速
> 或者下载到一半时限速

我感觉不是，我录个屏,
https://www.xiaorenjc.net/1.mp4

**Comment by yuantuo666** [comment]
是否是因为你的网络环境有问题呢
尝试下载一下其他网站的大文件看有没有问题

**Comment by po888375** [comment]
> 是否是因为你的网络环境有问题呢
> 尝试下载一下其他网站的大文件看有没有问题

请帮我看下，如果你下的正常的，那么就是我idm的问题
https://bjbgp01.baidupcs.com/file/5a48d42b1h3bafc86d8155ea36e4d9ef?bkt=en-2e2b5030dd6ff03717cfdfbe7c1916a0bd674ad862f3fb3c2202097bf785e731279f1408cdf63853&fid=890333412-250528-42743983026568&time=1626509160&sign=FDTAXUbGERLQlBHSKfWaqiu-DCb740ccc5511e5e8fedcff06b081203-NxEW%2FOvz0RrPE%2B688ghwxtyoKXI%3D&to=14&size=1080759172&sta_dx=1080759172&sta_cs=35&sta_ft=ts&sta_ct=6&sta_mt=5&fm2=MH%2CXian%2CAnywhere%2C%2Cbeijing%2Cany&ctime=1610899132&mtime=1619789703&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=1080759172&vuk=1881996509&iv=0&htype=&randtype=&tkbind_id=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-4f0f77db3c589bb8060b2888f13ee921f7a44657ca8f7b6b3cf4fe1cc3d6f63aeadea9805f43728f&sl=76480590&expires=8h&rt=sh&r=373803511&vbdid=-&fin=9seo%E6%A0%B8%E5%BF%83%E5%86%85%E5%AE%B9-%E9%A1%B5%E9%9D%A2%E5%B8%83%E5%B1%80%E4%B8%8E%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%EF%BC%881%EF%BC%89.ts&rtype=1&dp-logid=9196230769954410026&dp-callid=0.1&tsl=80&csl=80&fsl=-1&csign=jaD0fOnPvm%2F6BKLxBl5yaXKEBOU%3D&so=1&ut=6&uter=0&serv=1&uc=3200815480&ti=068bcab50ae430c76ab74a0ec081f6478aeaf931d588ef1d&hflag=30&from_type=3&adg=c_27c3e5646efeb0a285ed61da2f2b4efa&reqlabel=250528_f_d65145a864f582e2f3dbba9e5394cf48_-1_d809f0140adb93bd76c0f2fcee63b1b8&by=themis&resvsflag=1-12-0-1-1-1

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/126033775-4d60e1a7-86b6-4493-bba7-5939b025c80a.png)
出现了同样的问题，你删除记录再解析一次，再试试看

**Comment by po888375** [comment]
> ![image](https://user-images.githubusercontent.com/44130602/126033775-4d60e1a7-86b6-4493-bba7-5939b025c80a.png)
> 出现了同样的问题，你删除记录再解析一次，再试试看

嗯，这是新解析的，还是一样的问题
https://bjbgp01.baidupcs.com/file/5a48d42b1h3bafc86d8155ea36e4d9ef?bkt=en-2e2b5030dd6ff03717cfdfbe7c1916a0bd674ad862f3fb3c2202097bf785e731279f1408cdf63853&fid=890333412-250528-42743983026568&time=1626517246&sign=FDTAXUbGERLQlBHSKfWaqiu-DCb740ccc5511e5e8fedcff06b081203-V7qtwz1on3yCECdXyfqfkXbnI7s%3D&to=14&size=1080759172&sta_dx=1080759172&sta_cs=36&sta_ft=ts&sta_ct=6&sta_mt=5&fm2=MH%2CXian%2CAnywhere%2C%2Cbeijing%2Cany&ctime=1610899132&mtime=1619789703&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=1080759172&vuk=1881996509&iv=0&htype=&randtype=&tkbind_id=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-4f0f77db3c589bb8060b2888f13ee921f7a44657ca8f7b6b3cf4fe1cc3d6f63aeadea9805f43728f&sl=76480590&expires=8h&rt=sh&r=878016444&vbdid=-&fin=9seo%E6%A0%B8%E5%BF%83%E5%86%85%E5%AE%B9-%E9%A1%B5%E9%9D%A2%E5%B8%83%E5%B1%80%E4%B8%8E%E6%95%B0%E6%8D%AE%E5%88%86%E6%9E%90%EF%BC%881%EF%BC%89.ts&rtype=1&dp-logid=9198401318904940581&dp-callid=0.1&tsl=80&csl=80&fsl=-1&csign=jaD0fOnPvm%2F6BKLxBl5yaXKEBOU%3D&so=1&ut=6&uter=0&serv=1&uc=3200815480&ti=af453902c8b3aa6365398ca86b514accc9539903799c4b86305a5e1275657320&hflag=30&from_type=3&adg=c_27c3e5646efeb0a285ed61da2f2b4efa&reqlabel=250528_f_d65145a864f582e2f3dbba9e5394cf48_-1_d809f0140adb93bd76c0f2fcee63b1b8&by=themis&resvsflag=1-12-0-1-1-1

**Comment by po888375** [comment]
这是另外一个文件，也不行
https://bjbgp01.baidupcs.com/file/60aa284f3k0dce1d666e5491f78d0b98?bkt=en-e031c0692dcd5a21f89b9e2c8a90dc637919f0f27f658365a9d68ba9786c5539c15d3be4cd510fa5&fid=890333412-250528-597883847997561&time=1626517336&sign=FDTAXUbGERLQlBHSKfWaqiu-DCb740ccc5511e5e8fedcff06b081203-zEajaLeOmQkP%2BvXK1I5PrRpU5V4%3D&to=14&size=346444520&sta_dx=346444520&sta_cs=35&sta_ft=ts&sta_ct=6&sta_mt=5&fm2=MH%2CXian%2CAnywhere%2C%2Cbeijing%2Cany&ctime=1608782691&mtime=1619789703&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=346444520&vuk=1881996509&iv=0&htype=&randtype=&tkbind_id=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-cde6562dba20057b2df4a176244428ad93f293f6ec69e1aef6ec5dd6af9189b6989a027ca1cc6bf6&sl=76480590&expires=8h&rt=sh&r=675276180&vbdid=-&fin=5%E6%A0%B8%E5%BF%83%E7%AE%97%E6%B3%951%EF%BC%9A%E5%90%8E%E7%BB%AD%E6%90%9C%E7%B4%A2%E8%AF%8D%E5%AE%9E%E6%88%98%E8%BF%90%E7%94%A8%EF%BC%881%EF%BC%89.ts&rtype=1&dp-logid=9198425347709441978&dp-callid=0.1&tsl=80&csl=80&fsl=-1&csign=jaD0fOnPvm%2F6BKLxBl5yaXKEBOU%3D&so=1&ut=6&uter=0&serv=1&uc=3200815480&ti=068bcab50ae430c705e133bfbaea8f64829aba8f7af8613a&hflag=30&from_type=3&adg=c_27c3e5646efeb0a285ed61da2f2b4efa&reqlabel=250528_f_d65145a864f582e2f3dbba9e5394cf48_-1_d809f0140adb93bd76c0f2fcee63b1b8&by=themis&resvsflag=1-12-0-1-1-1

**Comment by yuantuo666** [comment]
这两个链接也出现了同样问题
暂不清楚是什么原因引起的，能提供一下分享链接吗

**Comment by po888375** [comment]
> 这两个链接也出现了同样问题
> 暂不清楚是什么原因引起的，能提供一下分享链接吗

嗯嗯，分享连接是这个：链接:https://pan.baidu.com/s/1weV3KYNE5ybxFPMCIZU-iA 提取码:yq7b 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by po888375** [comment]
知道问题了，原来是SVIP账号过期了

**Comment by lc6464** [comment]
视频文件建议使用标准的 视频 H.264 音频 AAC 编码的，MP4 封装的格式上传。
还有就是建议提问之前自行检查一下帐号、网络等状态。
