### ISSUE TITLE
【寻求帮助】Download do not work

### ISSUE THREAD

**Issue by heptahex** [yuantuo666/baiduwp-php#147]
## 描述问题
Analyzed download link not working. After adding download link and user agent to Motrix, Motrix returned error 22. Previously, baiduwp worked perfectly but it's not working anymore.

## 你需要的帮助
Can someone help me to solve my problem? Thank you.

## 您的设备信息
 Linux Manjaro 5.10.49-1, Motrix 1.6.11 Flatpak

**Comment by lc6464** [comment]
Hello, does Motrix's error 22 has more  detailed information?
If so, can you provide it to us?

**Comment by lc6464** [comment]
We think that the reason for this problem may be that your account has been speed-limited.

**Comment by lc6464** [comment]
After Baidu updated the interface, it seems easier to limit the speed.
You can see #113.
But right now we don't have any solutions.

**Comment by heptahex** [comment]
Ok, thank you. Motrix just returned and there was no extra information. But it's working again now.

**Comment by lc6464** [comment]
We are glad to hear that it can work normally.
If you have any more questions, you can open a new issue to us, or reopen this issue.
