### ISSUE TITLE
【BUG 反馈】api.php存在前台SQL注入漏洞

### ISSUE THREAD

**Issue by Eric1253** [yuantuo666/baiduwp-php#148]
## 描述 Bug
漏洞文件：/api.php
漏洞代码：
```php
$dbname = (!empty($_POST["dbname"])) ? $_POST["dbname"] : "";
$dbtable = (!empty($_POST["dbtable"])) ? $_POST["dbtable"] : "";
if (!function_exists('mysqli_connect')) {
	EchoInfo(-2, array("msg" => "<br/>您未安装或未启用 mysqli 扩展，<br/>不能使用数据库功能。<br/>请自行关闭数据库功能。"));
}
$conn = mysqli_connect($servername, $username, $DBPassword);
$GLOBALS['conn'] = $conn;
// Check connection
if (!$conn) {
	EchoInfo(-1, array("msg" => mysqli_connect_error()));
} else {
	// 连接成功，检查数据库是否存在
	$sql = "SELECT * FROM information_schema.SCHEMATA WHERE SCHEMA_NAME = '$dbname';"; // 查询是否有此数据库
	$mysql_query = mysqli_query($conn, $sql);
```
`$dbname`变量未经过任何过滤直接拼接到SQL语句中，此处无回显，可利用时间盲注、布尔盲注进行操作。

## 如何复现此 Bug
1.txt
```
POST /api.php?m=CheckMySQLConnect HTTP/1.1
Host: www.example.com
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: PHPSESSID=mk071heuoq8uvugt6bkm16e5pj
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 62

dbname=1
```
SQLMAP：
```
python sqlmap.py -r 1.txt --dbms=MYSQL -p dbname
```
![image](https://user-images.githubusercontent.com/87115415/126466770-1b146d2e-0fca-475b-8f9d-77a174058c76.png)

## 期望
修复漏洞

## 截图
![image](https://user-images.githubusercontent.com/87115415/126470334-3fa1d3af-baca-4415-a072-f20472271533.png)

## 您的设备信息
Not Need

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by lc6464** [comment]
十分感谢！我们会尽快修复这个 bug！
预计将于明天下午或更早发布更新！

**Comment by MateorChan** [comment]
> 十分感谢！我们会尽快修复这个 bug！
> 
> 预计将于明天下午或更早发布更新！

是不是太简单粗暴了一点…

只是进行转义，如果将特殊字符进行urlencode，再传入的话不久转义不了了吗？

**Comment by lc6464** [comment]
赶出来的修复性更新，很多东西并没有考虑，如你所说，确实很简单粗暴。
最近也没什么时间了啊。

为什么说
> 将特殊字符进行urlencode，再传入的话不就转义不了了
？

**Comment by Eric1253** [comment]
> 赶出来的修复性更新，很多东西并没有考虑，如你所说，确实很简单粗暴。
> 最近也没什么时间了啊。
> 
> 为什么说
> 
> > 将特殊字符进行urlencode，再传入的话不就转义不了了
> 
> ？

我看了一下你的PR，发现你fix的代码是错误的，htmlspecialchars加在了三元条件语句的条件部分...
正确的写法应该是：
```
!empty(条件) ? htmlspecialchars($_POST['xxx']) : "";
```
虽然此处使用htmlspecialchars也没问题，但建议还是使用addslashes函数做转义。
PS：之前那个回复的不是我，他把他的reply给删了...

**Comment by lc6464** [comment]
> 我看了一下你的PR，发现你fix的代码是错误的，htmlspecialchars加在了三元条件语句的条件部分...
> 正确的写法应该是：
> 
> ```
> !empty(条件) ? htmlspecialchars($_POST['xxx']) : "";
> ```
> 
> 虽然此处使用htmlspecialchars也没问题，但建议还是使用addslashes函数做转义。
> PS：之前那个回复的不是我，他把他的reply给删了...

其实我转义的是一整个，而不是条件。
`addslashes` 这个我会去看看的。

**Comment by MateorChan** [comment]
> > 赶出来的修复性更新，很多东西并没有考虑，如你所说，确实很简单粗暴。
> 
> > 最近也没什么时间了啊。
> 
> > 
> 
> > 为什么说
> 
> > 
> 
> > > 将特殊字符进行urlencode，再传入的话不就转义不了了
> 
> > 
> 
> > ？
> 
> 
> 
> 我看了一下你的PR，发现你fix的代码是错误的，htmlspecialchars加在了三元条件语句的条件部分...
> 
> 正确的写法应该是：
> 
> ```
> 
> !empty(条件) ? htmlspecialchars($_POST['xxx']) : "";
> 
> ```
> 
> 虽然此处使用htmlspecialchars也没问题，但建议还是使用addslashes函数做转义。
> 
> PS：之前那个回复的不是我，他把他的reply给删了...

之前回复的是我，想了一下其实拼接SQL避免不了注入问题，索性删了回复。建议还是上个pdo吧

**Comment by lc6464** [comment]
> 之前回复的是我，想了一下其实拼接SQL避免不了注入问题，索性删了回复。建议还是上个pdo吧

谁回复的不是很重要啦，而且我也看得到。
PDO 的话我会去了解一下的，然而我快开学了。
其实现在数据库相关的代码基本上都是 Yuan_Tuo 写的，PHP 用 `mysqli` 连 MySQL 着实很离谱。
~~（感觉 PHP 整个语言都很离谱）~~

刚才去看了一下，PDO 的设计确实就更加“现代”一点了（不知道用什么词来形容好），起码不会有那么多奇奇怪怪的问题。
被 `mysqli` 搞懵的我终于有救了？ ~~（但还是 .NET 香）~~

**Comment by lc6464** [comment]
下一个更新……


~~我也不知道什么时候会发出来。~~

**Comment by MateorChan** [comment]
> > 之前回复的是我，想了一下其实拼接SQL避免不了注入问题，索性删了回复。建议还是上个pdo吧
> 
> 
> 
> 谁回复的不是很重要啦，而且我也看得到。
> 
> PDO 的话我会去了解一下的，然而我快开学了。
> 
> 其实现在数据库相关的代码基本上都是 Yuan_Tuo 写的，PHP 用 `mysqli` 连 MySQL 着实很离谱。
> 
> ~~（感觉 PHP 整个语言都很离谱）~~
> 
> 
> 
> 刚才去看了一下，PDO 的设计确实就更加“现代”一点了（不知道用什么词来形容好），起码不会有那么多奇奇怪怪的问题。
> 
> 被 `mysqli` 搞懵的我终于有救了？ ~~（但还是 .NET 香）~~

看样子你们是还没了解到框架？我以为你们是精简主义。如果是这样的话我推荐还是用一款框架来写，基本上很多东西框架都帮你解决了（就比如sql注入）

**Comment by lc6464** [comment]
> 看样子你们是还没了解到框架？我以为你们是精简主义。如果是这样的话我推荐还是用一款框架来写，基本上很多东西框架都帮你解决了（就比如sql注入）

PHP 框架我有所了解，刚才去查了一下文档，也和我已知的基本一致，但这样会使项目变得臃肿，我们开始开发的时候这个项目可是很小的（你可以看看很早之前的版本都有些什么），只是后来慢慢加了功能，我们也没有考虑过使用框架。

~~还有就是我个人也不怎么喜欢框架~~

Yuan_Tuo 是怎么想的我就不清楚了。

**Comment by lc6464** [comment]
> 看样子你们是还没了解到框架？我以为你们是精简主义。如果是这样的话我推荐还是用一款框架来写，基本上很多东西框架都帮你解决了（就比如sql注入）

PHP 框架我有所了解，刚才去查了一下文档，也和我已知的基本一致，但这样会使项目变得臃肿，我们开始开发的时候这个项目可是很小的（你可以看看很早之前的版本都有些什么），只是后来慢慢加了功能，我们也没有考虑过使用框架。

~~还有就是我个人也不怎么喜欢框架~~

Yuan_Tuo 是怎么想的我就不清楚了。

**Comment by lc6464** [comment]
刚才那个重复的评论是网络原因导致的。

**Comment by MateorChan** [comment]
> 刚才那个重复的评论是网络原因导致的。

我个人的想法是，开源项目一定是希望更多的人来使用和贡献的，这个项目目前也有近2k star。我觉得引入一款框架，或者开发者定义好一些结构和规范，会更有利于别人的加入（指贡献代码）。
一点小建议

**Comment by lc6464** [comment]
> 我个人的想法是，开源项目一定是希望更多的人来使用和贡献的，这个项目目前也有近2k star。我觉得引入一款框架，或者开发者定义好一些结构和规范，会更有利于别人的加入（指贡献代码）。
> 一点小建议

我很赞同你的想法，但无情的事实却是连变量大小写规则都未能完全统一（主要还是历史遗留原因，后来项目比较大了我们也在尽可能规避这些问题），我们会在未来的更新中尽可能统一一下一些规则，也很欢迎你通过提交拉取请求等方式做出贡献。

**Comment by lc6464** [comment]
> 我个人的想法是，开源项目一定是希望更多的人来使用和贡献的，这个项目目前也有近2k star。我觉得引入一款框架，或者开发者定义好一些结构和规范，会更有利于别人的加入（指贡献代码）。
> 一点小建议

我很赞同你的想法，但无情的事实却是连变量大小写规则都未能完全统一（主要还是历史遗留原因，后来项目比较大了我们也在尽可能规避这些问题），我们会在未来的更新中尽可能统一一下一些规则，也很欢迎你通过提交拉取请求等方式做出贡献。

**Comment by yuantuo666** [comment]
这个项目主要是我学习PHP这门语言时的一个产物，最开始对PHP这门语言了解也不是很深，变量规范之类也没有注意，之前一直是以能运行为目的。
确实是因为自己能力问题，没有对整个项目做出完整的规划，以致现在的代码如此的诡异。

但本人目前是个高三学生，在学习和业余爱好上还是需要取舍，但我还是会把精力投入学习，如果之后有能力和机会，一定将这个项目重构，为开源世界做出微薄的贡献。

**Comment by gsons** [comment]
> 这个项目主要是我学习PHP这门语言时的一个产物，最开始对PHP这门语言了解也不是很深，变量规范之类也没有注意，之前一直是以能运行为目的。
> 确实是因为自己能力问题，没有对整个项目做出完整的规划，以致现在的代码如此的诡异。
> 
> 但本人目前是个高三学生，在学习和业余爱好上还是需要取舍，但我还是会把精力投入学习，如果之后有能力和机会，一定将这个项目重构，为开源世界做出微薄的贡献。

UP主可以阅读下那本《php安全之道》 。PHP作为一种弱类型的脚本语言，很多主流的php框架漏洞都是是层出不穷无法杜绝的，

**Comment by yuantuo666** [comment]
在不清楚数据库账号密码的情况下确实注入不了
因涉及数据库操作众多（主要集中在后台操作），目前暂不会采用 PDO，在项目结构优化后会考虑采用

**Comment by yuantuo666** [comment]
此问题早已修复，故关闭该议题
