### ISSUE TITLE
【建议】希望增加秒传连接的解析

### ISSUE THREAD

**Issue by laoqijun** [yuantuo666/baiduwp-php#150]
这个之前在某个js版上有先例，我使用了后觉得非常好用，可这个版本迟迟没有。
希望能加上去。

**Comment by yuantuo666** [comment]
参考一下 #42
如果秒传链接使用广泛的话会考虑加入此功能

**Comment by laoqijun** [comment]
已经可以说是很广泛了。希望能加一下

**Comment by budingjiangya** [comment]
妙传 需要先把文件进行解析保存到网盘目录 之后在把妙传好了的文件进行分享并且进行解析 方法不仅麻烦 同时百度可能随时封锁该接口

**Comment by laoqijun** [comment]
> 

起码能做到。当然我只是建议

**Comment by yuantuo666** [comment]
秒传链接存在法律风险，本项目不会支持
