### ISSUE TITLE
【寻求帮助】不能在本地实体机器上运行这个项目吗

### ISSUE THREAD

**Issue by lq-259** [yuantuo666/baiduwp-php#151]
服务快到期了不是很想续费就尝试在本地部署了，提示提取错误，可能的原因也排除了，没找到调试模式在哪里开启，确实不能在本地运行那就算了
![Screenshot_20210817-162613](https://user-images.githubusercontent.com/60541200/129691350-fedff80e-9142-4460-b8ef-cd8867f1f835.png)

**Comment by yuantuo666** [comment]
本项目没有限制运行机器的，在本地也是可以搭建的
在config.php文件中将 const DEBUG = false ; 改成 const DEBUG = true ; 即可开启调试模式

记得贴上你的调试信息以及系统环境等信息

**Comment by lq-259** [comment]
> 本项目没有限制运行机器的，在本地也是可以搭建的
> 在config.php文件中将 const DEBUG = false ; 改成 const DEBUG = true ; 即可开启调试模式
> 
> 记得贴上你的调试信息以及系统环境等信息

系统：Ubuntu 18.04.5 LTS (GNU/Linux 3.18.124-g4aa1814c63b8 aarch64)
php版本：7.2
nginx版本：1.14
浏览器ua：Mozilla/5.0 (Linux; Android 11; Redmi K20) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Mobile Safari/537.36
调试信息：
![Screenshot_20210819-113839](https://user-images.githubusercontent.com/60541200/130004266-cb03bb52-b3a7-4a67-8a33-c680dd1628da.png)

**Comment by yuantuo666** [comment]
getSign获取百度网盘页面返回的网页是空，应该是网络方面的问题
服务器能成功连接百度服务器吗，尝试ping一下pan.baidu.com

**Comment by lq-259** [comment]
> getSign获取百度网盘页面返回的网页是空，应该是网络方面的问题
> 服务器能成功连接百度服务器吗，尝试ping一下pan.baidu.com

提示的可能原因我都排查过了没问题
![Uploading Screenshot_20210819-155155.png…]()

**Comment by lq-259** [comment]
> getSign获取百度网盘页面返回的网页是空，应该是网络方面的问题
> 服务器能成功连接百度服务器吗，尝试ping一下pan.baidu.com

提示的可能原因我都排查过了没问题
![Screenshot_20210819-155155](https://user-images.githubusercontent.com/60541200/130029995-9b5567ab-d4db-4762-a743-feb5b7034d0c.png)

**Comment by yuantuo666** [comment]
可能是curl和curl扩展的问题，可以检查下这两个

**Comment by yuantuo666** [comment]
本项目没有限制运行环境，可参考此评论配置 docker 环境，仍有问题请再次打开此议题 https://github.com/yuantuo666/baiduwp-php/issues/205#issuecomment-1161345032
