### ISSUE TITLE
【寻求帮助】填写了正确的BDUSS及STOKEN但是设置了出现账户异常

### ISSUE THREAD

**Issue by YooZF** [yuantuo666/baiduwp-php#156]
![异常](https://user-images.githubusercontent.com/90264564/132357894-ba8884cf-a6f4-44a9-ae3d-8a0e929cdb64.jpg)
是非为百度网盘页面更新了，导致该方法无法继续使用了

**Comment by yuantuo666** [comment]
项目没有问题的，demo在正常运行 https://imwcr.cn/api/bdwp/
如果确认填写正确了BDUSS和STOKEN，那就是无法连接百度服务器，要检查是否安装了curl及能否获取百度网盘页面。

**Comment by budingjiangya** [comment]
bduss  获取的不完整 加上直接填入config.php所以没有获取好

**Comment by hmjehbbk** [comment]
你的问题解决了吗？我出现了一样的问题[https://github.com/yuantuo666/baiduwp-php/issues/173](url)

**Comment by lc6464** [comment]
如仍有问题可重开此议题。
