### ISSUE TITLE
使用网页版Demo获取百度网盘解析地址，提示“密码错误”，但是我的分享密码是正确的

### ISSUE THREAD

**Issue by xiaopeng520** [yuantuo666/baiduwp-php#157]
![1](https://user-images.githubusercontent.com/24989126/133912851-1d75df5c-d1cb-4716-a8ef-0cdaafb82a42.png)

**Comment by yuantuo666** [comment]
“密码错误”此密码指的是站点密码，并非提取码（分享密码）
Demo 不开放使用
