### ISSUE TITLE
找不到 BDUSS!【寻求帮助】

### ISSUE THREAD

**Issue by KDLoad** [yuantuo666/baiduwp-php#158]
## 描述问题
我現在在百度网盘網站中找不到 BDUSS！

## 如何复现此问题
复现此问题的步骤:
1. 去百度网盘網站
2. 打开 cookie
3. baidu.com>cookie
4. 找不到 BDUSS！

## 你需要的帮助
找不到 BDUSS

## 截图
![百度网盘-BDUSS](https://user-images.githubusercontent.com/91263511/134506845-8e2900ca-35d7-43e1-b4c3-7cee19aacea4.png)
## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
复制 BDUSS_BFESS 的内容也可以

**Comment by KDLoad** [comment]
但是我複製了在我的Config.php裏，解析時彈出普通帳號錯誤，但我是跟SVIP帳號的BDUSS一樣
