### ISSUE TITLE
远程下载【建议】

### ISSUE THREAD

**Issue by lililixxx1** [yuantuo666/baiduwp-php#161]
既然支持aria2下载，能否支持远程下载。不使用本地下载，用自建的aria2服务器下载。感谢开发者。

**Comment by lc6464** [comment]
支持的啊。
https://github.com/yuantuo666/baiduwp-php/issues/104#issuecomment-821920532

**Comment by pipidaxian** [comment]
我的aria2是在远程的服务器上设置的https协议的RPC，但是推送我看只能是ws协议？有什么办法吗？

**Comment by lc6464** [comment]
> 我的aria2是在远程的服务器上设置的https协议的RPC，但是推送我看只能是ws协议？有什么办法吗？

远程 HTTPS wss 肯定没问题，本地 HTTP / HTTPS 理论上来说 ws / wss 都没问题。
远程 HTTPS ws 理论上来说会出错，远程 HTTP wss 我没测试，也许可以？

远程 HTTPS + WSS 不可能出问题吧？

**Comment by pipidaxian** [comment]
> > 我的aria2是在远程的服务器上设置的https协议的RPC，但是推送我看只能是ws协议？有什么办法吗？
> 
> 远程 HTTPS wss 肯定没问题，本地 HTTP / HTTPS 理论上来说 ws / wss 都没问题。 远程 HTTPS ws 理论上来说会出错，远程 HTTP wss 我没测试，也许可以？
> 
> 远程 HTTPS + WSS 不可能出问题吧？

可能我没表达清楚，我的aria使用的是https协议，相当于是https+https

**Comment by lc6464** [comment]
> 可能我没表达清楚，我的aria使用的是https协议，相当于是https+https

Aria2 不是应该用 WebSocket 吗？
你指的是基于 TLS 的 WebSocket：wss 吗？

**Comment by pipidaxian** [comment]
不是，是这样的
![FEFB84A4-F7CA-41DB-964B-572A10AB62E9](https://user-images.githubusercontent.com/78637637/140618621-3d8e3618-896d-4007-b7ba-2efa712671ae.jpeg)

**Comment by pipidaxian** [comment]
> > 可能我没表达清楚，我的aria使用的是https协议，相当于是https+https
> 
> Aria2 不是应该用 WebSocket 吗？ 你指的是基于 TLS 的 WebSocket：wss 吗？

哦我弄好了，选择了wss就好了，谢谢

**Comment by jsdfhasuh** [comment]
> > > 可能我没表达清楚，我的aria使用的是https协议，相当于是https+https
> > 
> > Aria2 不是应该用 WebSocket 吗？ 你指的是基于 TLS 的 WebSocket：wss 吗？
> 
> 哦我弄好了，选择了wss就好了，谢谢

请问你的远程aria2怎么配置才可以，我的一直不行

**Comment by pipidaxian** [comment]
> > > > 可能我没表达清楚，我的aria使用的是https协议，相当于是https+https
> > > 
> > > 
> > > Aria2 不是应该用 WebSocket 吗？ 你指的是基于 TLS 的 WebSocket：wss 吗？
> > 
> > 
> > 哦我弄好了，选择了wss就好了，谢谢
> 
> 请问你的远程aria2怎么配置才可以，我的一直不行

我是这样设置的
![4CAAC9DC-F9D4-46AB-BA4D-E8378804B210](https://user-images.githubusercontent.com/78637637/140699974-c3566a3d-5998-4c14-95ce-ec59c57dd871.jpeg)

**Comment by pipidaxian** [comment]
> > > > 可能我没表达清楚，我的aria使用的是https协议，相当于是https+https
> > > 
> > > 
> > > Aria2 不是应该用 WebSocket 吗？ 你指的是基于 TLS 的 WebSocket：wss 吗？
> > 
> > 
> > 哦我弄好了，选择了wss就好了，谢谢
> 
> 请问你的远程aria2怎么配置才可以，我的一直不行

我是这样设置的
![4CAAC9DC-F9D4-46AB-BA4D-E8378804B210](https://user-images.githubusercontent.com/78637637/140699974-c3566a3d-5998-4c14-95ce-ec59c57dd871.jpeg)

**Comment by jsdfhasuh** [comment]
我可以连上，但是这个项目好像没办法推送过去

**Comment by jsdfhasuh** [comment]
> > > > > 可能我没表达清楚，我的aria使用的是https协议，相当于是https+https
> > > > 
> > > > 
> > > > Aria2 不是应该用 WebSocket 吗？ 你指的是基于 TLS 的 WebSocket：wss 吗？
> > > 
> > > 
> > > 哦我弄好了，选择了wss就好了，谢谢
> > 
> > 
> > 请问你的远程aria2怎么配置才可以，我的一直不行
> 
> 我是这样设置的 ![4CAAC9DC-F9D4-46AB-BA4D-E8378804B210](https://user-images.githubusercontent.com/78637637/140699974-c3566a3d-5998-4c14-95ce-ec59c57dd871.jpeg)

我可以连上，但是这个项目好像没办法推送过去
