### ISSUE TITLE
【BUG 反馈】Mac下使用无法推送到Motrix

### ISSUE THREAD

**Issue by xieshang** [yuantuo666/baiduwp-php#162]
## 描述 Bug

https://pan.q88q.cyou
Mac环境下使用Motrix下载，发送参数为：ws://localhost:16800/jsonrpc，点击发送提示无法推送。

使用http://localhost:16800/jsonrpc 
提示    WebSocket 地址不符合验证规则，请检查是否填写正确！

使用AriaNG GUI 进行连接，参数是http://localhost:16800/jsonrpc，连接成功

**Comment by lc6464** [comment]
总感觉地址验证正则又出问题了。

**Comment by budingjiangya** [comment]
不是Motrix的问题 因为你是黑苹果导致的 jixia.asia 你试试能不能发送

**Comment by yuantuo666** [comment]
可能与使用的浏览器有关，可以切换浏览器后再尝试

**Comment by yuantuo666** [comment]
可尝试使用 Safari Chrome 等浏览器
因议题长期未回复已关闭，若仍有问题请再次打开
