### ISSUE TITLE
【寻求帮助】服务器错误，请求百度服务器时，未传入sekey参数或参数错误。

### ISSUE THREAD

**Issue by Tiggy-Chan** [yuantuo666/baiduwp-php#163]
![6J$P%7X8` WX7Q8QP P$DSK](https://user-images.githubusercontent.com/79960316/139571359-0e807394-1291-4230-a0c1-a5d6ec1481d2.png)

**Comment by poemplayer** [comment]
我也遇到了，请问解决了吗

**Comment by Tiggy-Chan** [comment]
> 我也遇到了，请问解决了吗
还没

**Comment by yuantuo666** [comment]
能否提供文件分享链接，具体不清楚该错误出现原因，推测和文件有关

**Comment by yuantuo666** [comment]
randsk参数为空，可能是分享链接存在问题，重新分享即可解决
若仍有问题请再次打开议题
