### ISSUE TITLE
怎么增加限制IP流量功能【寻求帮助】

### ISSUE THREAD

**Issue by ks5200** [yuantuo666/baiduwp-php#164]
## 描述问题
请在此填入对你遇到的问题清晰准确的描述。

## 如何复现此问题
复现此问题的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by budingjiangya** [comment]
限制流量功能 需要赞助版  100r

**Comment by lc6464** [comment]
赞助版带有此功能，价格128元。
