### ISSUE TITLE
【BUG 反馈】

### ISSUE THREAD

**Issue by budingjiangya** [yuantuo666/baiduwp-php#165]
## 描述 Bug违规分享的链接 让百度和谐了 直接显示链接异常 而不是文件来晚了之类的
请在此填入对此 Bug 清晰准确的描述。

## 如何复现此 Bug
复现此 Bug 的步骤:
1. xx可以尝试一下解析这个失效的链接
hi，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取 
链接:https://pan.baidu.com/s/1JMNDCE0qywVyByIwnhC2jw 
提取码:xjao
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 期望
对您所期望的情况做一个简单描述。
修复正确的显示内容
## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。
![image](https://user-images.githubusercontent.com/88592129/141603362-75467024-9c1b-42f1-98a2-ad8229ded781.png)
![image](https://user-images.githubusercontent.com/88592129/141603367-15f432b1-324e-4248-95b4-3e414a8785e6.png)

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by lc6464** [comment]
主要是我们也没法判断到底发生了什么，总之这个链接就是有问题，不如直接提示链接异常。
