### ISSUE TITLE
举报网站

### ISSUE THREAD

**Issue by SaigyoujiYukon** [yuantuo666/baiduwp-php#166]
http://baidu.mfs-2020.com/
因为自己也在用这个项目，所以看到ui一眼就认出来了（

**Comment by SaigyoujiYukon** [comment]
![image](https://user-images.githubusercontent.com/40208202/141783732-1c165a81-990c-4a01-9686-3ebaa4ac3554.png)
![image](https://user-images.githubusercontent.com/40208202/141783795-90275d62-f8f5-42bc-a664-0dfa06af0d55.png)

**Comment by yuantuo666** [comment]
感谢反馈，没有找到站长的联系方式。
目前已添加黑名单。
