### ISSUE TITLE
服务器错误(118)

### ISSUE THREAD

**Issue by koreyoshiw** [yuantuo666/baiduwp-php#167]
服务器错误(118)
服务器错误，请求百度服务器时，未传入sekey参数或参数错误。
请打开调试模式，并将错误信息以议题的形式提交到GitHub项目。

链接: https://pan.baidu.com/s/1B5mzBiZZMiqRQVhZc-Jzyw 提取码: wc4u 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by lc6464** [comment]
**请打开调试模式，并将错误信息以议题的形式提交到GitHub项目。**

**Comment by yuantuo666** [comment]
此错误很少在正确配置下出现，如还有问题，请打开调试模式，并将错误信息提交到此issue。
