### ISSUE TITLE
举报删除联系信息的网站

### ISSUE THREAD

**Issue by pro1xyz** [yuantuo666/baiduwp-php#170]
<img src="https://s6.jpg.cm/2021/12/04/L5oPvr.png" alt="vxians" border="0">
https://bbs.leyuz.net/t/221846
https://pan.vxians.tk

**Comment by budingjiangya** [comment]
![image](https://user-images.githubusercontent.com/88592129/144731117-b6c95ca8-1546-4049-bdc1-7e505d805a7d.png)
有点意思昂

**Comment by lc6464** [comment]
http://dupan.cc

**Comment by lc6464** [comment]
http://pan.10zv.com/
