### ISSUE TITLE
【寻求帮助】连续3个号，都是解析不到100G就变黑号，怎么破？

### ISSUE THREAD

**Issue by chenshao** [yuantuo666/baiduwp-php#171]
今天搭了最新版本，本想着给同班同学共享使用，可是每个号都是解析到100G左右就黑了，连续3个SVIP号都是这样。
请问，现在这接口这么容易黑号了吗？

现在手头上只剩下1个号了，不敢再上了，我怕再上也是100G黑号，怕了。

顺便问一下，赞助版本和公开的版本，有什么不一样吗？如果好用的话，我乐意赞助。

**Comment by Aixzk** [comment]
我有一个解析了 400GB 黑了，另一个解析了 650GB 才黑了，相似的是这两个号都是解析了近 2k 个文件。

**Comment by budingjiangya** [comment]
> 我有一个解析了 400GB 黑了，另一个解析了 650GB 才黑了，相似的是这两个号都是解析了近 2k 个文件。

正常 我已经加了700多个svip号了
![image](https://user-images.githubusercontent.com/88592129/146157657-91076fab-d91e-43d2-bc00-865137717621.png)

**Comment by budingjiangya** [comment]
> 今天搭了最新版本，本想着给同班同学共享使用，可是每个号都是解析到100G左右就黑了，连续3个SVIP号都是这样。 请问，现在这接口这么容易黑号了吗？
> 
> 现在手头上只剩下1个号了，不敢再上了，我怕再上也是100G黑号，怕了。
> 
> 顺便问一下，赞助版本和公开的版本，有什么不一样吗？如果好用的话，我乐意赞助。

直接用我的不好吗 都不需要你维护  地址 jixia.asia

**Comment by Galaxy-yy** [comment]
现在外头基于这套php的全是换ua构造出来的，这个用LogStatistic没多少用了，限制非常多。

**Comment by aotuitx** [comment]
所以现在没啥子用了？

**Comment by lc6464** [comment]
百度网盘现有的接口限制太多了，咱也没办法，暂时没找到新的接口，理论上来说和你的账户、IP 的解析次数和解析量都有关。

**Comment by aotuitx** [comment]
> 

只能用客户端顶上了。

**Comment by guling-io** [comment]
> > 我有一个解析了 400GB 黑了，另一个解析了 650GB 才黑了，相似的是这两个号都是解析了近 2k 个文件。
> 
> 正常 我已经加了700多个svip号了 ![image](https://user-images.githubusercontent.com/88592129/146157657-91076fab-d91e-43d2-bc00-865137717621.png)

我去，这么多号？

**Comment by budingjiangya** [comment]
> > > 我有一个解析了 400GB 黑了，另一个解析了 650GB 才黑了，相似的是这两个号都是解析了近 2k 个文件。
> > 
> > 
> > 正常 我已经加了700多个svip号了 ![image](https://user-images.githubusercontent.com/88592129/146157657-91076fab-d91e-43d2-bc00-865137717621.png)
> 
> 我去，这么多号？

https://github.com/yuantuo666/baiduwp-php/issues/171#issuecomment-997434223   已经900多了

**Comment by budingjiangya** [comment]
https://github.com/yuantuo666/baiduwp-php/issues/171#issuecomment-997434223

**Comment by budingjiangya** [comment]
![image](https://user-images.githubusercontent.com/88592129/146713060-58db129e-fba9-48c7-b731-db39744aeaa5.png)

**Comment by budingjiangya** [comment]
> 百度网盘现有的接口限制太多了，咱也没办法，暂时没找到新的接口，理论上来说和你的账户、IP 的解析次数和解析量都有关。

我ip可以无线更换 但是很多号很容易限速  哎造孽

**Comment by laoqijun** [comment]
> > 百度网盘现有的接口限制太多了，咱也没办法，暂时没找到新的接口，理论上来说和你的账户、IP 的解析次数和解析量都有关。
> 
> 我ip可以无线更换 但是很多号很容易限速 哎造孽

你上哪整那么多的？

**Comment by guling-io** [comment]
同问

**Comment by lc6464** [comment]
暂无解决方案，若找到了新的接口会尽快更新，也欢迎各位提交拉取请求以修复此问题。
若有其他问题可重开议题。

**Comment by budingjiangya** [comment]
> > > 百度网盘现有的接口限制太多了，咱也没办法，暂时没找到新的接口，理论上来说和你的账户、IP 的解析次数和解析量都有关。
> > 
> > 
> > 我ip可以无线更换 但是很多号很容易限速 哎造孽
> 
> 你上哪整那么多的？

当然是 利用邮箱系统 无线注册bdwp账户  然后活动低价开svip咯

**Comment by budingjiangya** [comment]
> 当然是 利用邮箱系统 无线注册bdwp账户 然后活动低价开svip咯
