### ISSUE TITLE
【寻求帮助】已获取到文件，但未能获取到下载链接！

### ISSUE THREAD

**Issue by Bouby308** [yuantuo666/baiduwp-php#174]
## 描述问题
已获取到文件，但未能获取到下载链接！
请检查你是否在 config.php 中配置 普通账号 的 BDUSS 和 STOKEN！

昨天早上還沒有問題，但今天開始就是這樣。重新登入百度雲並提取新cookie也不能解決問題。已經檢查SVIP，並未過期。
<img width="484" alt="1" src="https://user-images.githubusercontent.com/25429146/146898886-9d91c087-a603-41a6-aece-0873241eeec4.png">
<img width="970" alt="2" src="https://user-images.githubusercontent.com/25429146/146898895-34bd7285-7a9c-4c03-a6d7-a6b3432da3dc.png">

**Comment by qq188872170** [comment]
你的账号已经被拉黑了

**Comment by Bouby308** [comment]
才50gb,那麽快就被拉黑？拉黑了通常何時解封？

**Comment by qq188872170** [comment]
不可能解封

**Comment by Bearcatail** [comment]
> 才50gb,那麽快就被拉黑？拉黑了通常何時解封？

会解封，但是不清楚具体什么情况下会解封。我写了脚本每天检测一次，以下是我的两个账号记录：

账号A，专用于解析站，2个月前被拉黑了后到现在都没解封，期间这个账号也没在官方 APP 上正常使用过。
账号B，在APP上正常用的同时，还用于解析站，上个月到今天，期间被拉黑过2次，两次都刚好是7天。

**我猜测**是百度并不是根据解析量来拉黑账号的，而是账号的使用情况，如果全是可疑情况的话很可能一直都会被封，例如解析了一次直链，却被多次下载，或者被多个地区的IP下载（也许官方APP暂停下载后继续每一次都是重新获取链接呢）。

至于真实的情况可能会更复杂，我这两个账号可能也只是巧合，样本数据太少，说明不了什么。

**Comment by Cu1nS** [comment]
同樣遇到這個問題，現在連官方客戶端也下不了，除了等之外
再充svip是不是也會解封?

**Comment by budingjiangya** [comment]
换一个普通账户即可 就这么简单

**Comment by iskycc** [comment]
> 换一个普通账户即可 就这么简单

那，如果我的所有普通账号都被拉黑了，换什么呢，哈哈哈

**Comment by budingjiangya** [comment]
> > 换一个普通账户即可 就这么简单
> 
> 那，如果我的所有普通账号都被拉黑了，换什么呢，哈哈哈
![image](https://user-images.githubusercontent.com/88592129/147061168-49c257cf-97a8-4738-ad7f-9ed4ce509e27.png)
跟你看看眼界 你看我缺账户嘛

**Comment by budingjiangya** [comment]
> > 才50gb,那麽快就被拉黑？拉黑了通常何時解封？
> 
> 会解封，但是不清楚具体什么情况下会解封。我写了脚本每天检测一次，以下是我的两个账号记录：
> 
> 账号A，专用于解析站，2个月前被拉黑了后到现在都没解封，期间这个账号也没在官方 APP 上正常使用过。 账号B，在APP上正常用的同时，还用于解析站，上个月到今天，期间被拉黑过2次，两次都刚好是7天。
> 
> **我猜测**是百度并不是根据解析量来拉黑账号的，而是账号的使用情况，如果全是可疑情况的话很可能一直都会被封，例如解析了一次直链，却被多次下载，或者被多个地区的IP下载（也许官方APP暂停下载后继续每一次都是重新获取链接呢）。
> 
> 至于真实的情况可能会更复杂，我这两个账号可能也只是巧合，样本数据太少，说明不了什么。

不是这样的  实际是根据svip的使用量检测的  比如你开一个svip 有4个人登录  然后你拿着解析    你会发现 非常容易限速   另外 地区是根据你服务器ip地址的  其他人下载都是通过用户代理下载的   也就是说不管什么用户下载直连 实际解析都是你服务器ip的地址 
![image](https://user-images.githubusercontent.com/88592129/147061695-48f63af4-d51d-4dc7-b07e-18d5513d41c8.png)
![image](https://user-images.githubusercontent.com/88592129/147061727-f6e2fac0-dea8-4c77-a2a2-a0dfa59206a7.png)

**Comment by qq188872170** [comment]
> 
你的还能解析几百G一个号，我的直接30G就拉黑了

**Comment by budingjiangya** [comment]
> > 
> 
> 你的还能解析几百G一个号，我的直接30G就拉黑了
看运气的  我每天买30 40个号真正可以使用的才不过几个

**Comment by iskycc** [comment]
> > > 
> > 
> > 
> > 你的还能解析几百G一个号，我的直接30G就拉黑了
> > 看运气的  我每天买30 40个号真正可以使用的才不过几个

极下是老哥你的啊，你那个下载ua是怎么自定义为ji-xia的，我还发了个issues，哈哈哈

**Comment by budingjiangya** [comment]
> 

赞助版本的是 可以自定义ua的

**Comment by iskycc** [comment]
> > 
> 
> 赞助版本的是 可以自定义ua的

了解了，我直接用你的算了，话说你这个免费的怎么盈利啊，那么多账号维护起来不是直接亏本

**Comment by budingjiangya** [comment]
> > > 
> > 
> > 
> > 赞助版本的是 可以自定义ua的
> 
> 了解了，我直接用你的算了，话说你这个免费的怎么盈利啊，那么多账号维护起来不是直接亏本

你知道我亏本还不买我的赞助版本 批量下载美滋滋昂

**Comment by iskycc** [comment]
> > > > 
> > > 
> > > 
> > > 赞助版本的是 可以自定义ua的
> > 
> > 
> > 了解了，我直接用你的算了，话说你这个免费的怎么盈利啊，那么多账号维护起来不是直接亏本
> 
> 你知道我亏本还不买我的赞助版本 批量下载美滋滋昂

我要是有钱的话，那我就赞助了，但是我是学生，没钱
