### ISSUE TITLE
可以自定义UA?

### ISSUE THREAD

**Issue by iskycc** [yuantuo666/baiduwp-php#175]
本项目的UA提醒必须设定为LogStatistic，但是我有看到有下载站可以自定义UA为其他UA？例如：jixia.asia
![image](https://user-images.githubusercontent.com/81439128/147064099-0c94e6ed-16a0-44d0-b368-9e134ce08b3d.png)

**Comment by budingjiangya** [comment]
你可以购买赞助版本  好像是120来快    但是现在接口不太行了 很容易限速提前有经济能力维护
