### ISSUE TITLE
【寻求帮助】HTTP 503 服务不可用！暂未安装此程序！

### ISSUE THREAD

**Issue by Origin1699** [yuantuo666/baiduwp-php#176]
首次安装, 访问首页后显示 ： HTTP 503 服务不可用！暂未安装此程序！将在五秒内跳转到安装程序！ 跳转 install.php 页面后，仍然是如此显示，并不停的跳转

**Comment by Origin1699** [comment]
![1sada.png](https://s2.loli.net/2021/12/28/zNRcX2siQ6OJShr.png)

**Comment by Origin1699** [comment]
部分nginx配置
`server {
    listen 80;
    server_name bdp.xxx.com;
    access_log /data/wwwlogs/access_nginx.log combined;
	
    root /www;
    index index.html index.htm index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
	

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/dev/shm/php-cgi.sock;
        fastcgi_index index.php;
        fastcgi_param  SCRIPT_FILENAME /www/index.php;
        include fastcgi_params;
    }
  }`

**Comment by yuantuo666** [comment]
开启了伪静态的功能导致的问题
删除下面的文本即可：

> location / {
>     try_files $uri $uri/ /index.php?$query_string;
> }

**Comment by Origin1699** [comment]
删除这些文本重启nginx后，还是跟之前一样

**Comment by lc6464** [comment]
您可以尝试一下本地在不对 Web 服务器作特殊转换设置的情况下搭建以后把配置文件复制到服务器。

**Comment by lc6464** [comment]
由于您过久没有给出回复，暂时关闭此议题，如有需要可再次打开。
