### ISSUE TITLE
【寻求帮助】BDUSS 和 STOKEN 配置错误问题

### ISSUE THREAD

**Issue by veip007** [yuantuo666/baiduwp-php#177]
![image](https://user-images.githubusercontent.com/12257917/147867745-1a02e228-d477-49d6-802c-bf08ddfc615c.png)
出现上图错误，BDUSS 和 STOKEN是正确的
重新安装还是这个错误
换了一个普通账号和SVIP 也是这个错误
求解~

**Comment by chwl66** [comment]
我出现这个错误是后台SVIP的BDUSS和STOKEN失效，删除后来添加的BDUSS和STOKEN，保留config里面的就不会出错了！

**Comment by yuantuo666** [comment]
请再次检查获取的是否为正确的 BDUSS 和 STOKEN，通过 EditThisCookie 插件获取的参数是没有问题的

**Comment by Vzz1c** [comment]
同样的问题

**Comment by yuantuo666** [comment]
获取完成 Cookie 后 **不要** 点击切换账号或退出登录，否则会 **注销** 之前获取的 BDUSS 和 STOKEN。
正确配置是可以使用此程序的。
如果仍有问题请重新打开议题。
