### ISSUE TITLE
【BUG 反馈】提示普通账号BDUSS和STOKEN失效，更新了无效

### ISSUE THREAD

**Issue by hclasmn** [yuantuo666/baiduwp-php#178]
![image](https://user-images.githubusercontent.com/32213103/148027494-e4ab3fdc-b826-4650-8705-97e6971bfe4e.png)
早上用还可以，下午提示这个了，更新了也无效，不知道是不是百度又改了啥，作者可以测试下么
谢谢

**Comment by hclasmn** [comment]
今天测试已经恢复了，可能百度昨天抽了？

**Comment by hclasmn** [comment]
今天又这样了

**Comment by budingjiangya** [comment]
> 今天又这样了

有的文件就这也  隔天可能就好了

**Comment by hclasmn** [comment]
怀疑黑号了。客户端也连接不上或者速度才1m

**Comment by budingjiangya** [comment]
> 怀疑黑号了。客户端也连接不上或者速度才1m

很正常的
