### ISSUE TITLE
【BUG 反馈】解析易被百度拉黑

### ISSUE THREAD

**Issue by MartPeggy** [yuantuo666/baiduwp-php#179]
## 描述 Bug
在解析了不到100G的文件后即被封禁

## 如何复现此 Bug
不明

## 期望
换用接口

## 截图
![图片](https://user-images.githubusercontent.com/88977170/148948236-8738d17f-767c-40f0-b4a1-edc2fd073547.png)
![图片](https://user-images.githubusercontent.com/88977170/148948339-dd2fd4aa-230c-4103-beed-f8028be5798b.png)

## 您的设备信息
 - 服务器系统信息：华为云centos7.9
 - 服务器 PHP 版本：PHP74
 - 访问项目的浏览器版本： 浏览器名字 	Firefox  浏览器版本 	95.0  系统平台 	Windows  原始UA信息 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0

## 补充信息
感觉接口好危险，被封禁后无论哪个客户端都无法下载文件，手机上直接不显示下载速度

**Comment by MartPeggy** [comment]
好像现在正常了，大概过了一天的时间

**Comment by budingjiangya** [comment]
![image](https://user-images.githubusercontent.com/88592129/149138389-575c83fa-7eba-42e1-829f-d78d614da246.png)
习惯就好 账号是小问题  而且接口最近就这样  解决不了的 你得用钞能力

**Comment by MartPeggy** [comment]
刚刚打电话问客服了，说的是得一个周才能解封

**Comment by budingjiangya** [comment]
> 刚刚打电话问客服了，说的是得一个周才能解封

我号多 对这玩意 无所谓的

**Comment by iskycc** [comment]
> 刚刚打电话问客服了，说的是得一个周才能解封

老哥，请问是如何进行申诉的，百度网盘客服电话是多少呀？我朋友的账号被我弄得也像你那个样子了，现在不知道怎么搞，求助！在线等，挺急的，快过年了，谢谢

**Comment by lc6464** [comment]
暂无解决方案，若找到了新的接口会尽快更新，也欢迎各位提交拉取请求以修复此问题。
若有其他问题可重开议题。
