### ISSUE TITLE
【寻求帮助】百度网盘SVIP账号被拉黑了如何恢复

### ISSUE THREAD

**Issue by iskycc** [yuantuo666/baiduwp-php#180]
## 描述问题
百度网盘SVIP账号被拉黑了，所有的客户端都出现下载一开始就下载失败的情况

## 如何复现此问题
复现此问题的步骤:
1.使用此程序，解析一段时间以后，出现无法解析的情况
2.打开百度网盘客户端，点击任意文件开始下载，均出现下载失败
3.下载失败错误代码为1252017、1252018、1252019等

## 你需要的帮助
如何在百度网盘官方客户端恢复正常下载

## 截图
![image](https://user-images.githubusercontent.com/81439128/151643118-5862e32b-e651-4814-b82a-fd2af469f45e.png)

## 您的设备信息
Ubuntu 18.04 PHP 7.4
Windows 11 百度网盘 7.11.0

## 补充信息
在线等，很急，因为是朋友的账号

**Comment by Aixzk** [comment]
据我所知 SVIP 账号有两种黑号，一种是限制了下载速度（一般<4MB/s），一种就是你这种彻底封禁，官方软件 APP 无法下载也不能播放视频，更加不能用于这个解析项目。

前几个月我用自己的百度账号搭建了个解析站，就只是单纯的自己用，用了一段时间一共解析了 381 个文件（185GB）就被彻底封禁了，封了十几天都没解封就去找在线客服：

![IMG_20220129_171146.jpg](https://user-images.githubusercontent.com/80463781/151655214-9bd44bb0-5617-4b8c-b66b-d16146cb32b9.jpg)

后来也还是一直没解封，我也没打电话让客服处理，过了两个月实在忍不住就取消绑定包月了，SVIP过期后马上就解封了。。

**Comment by iskycc** [comment]
> 据我所知 SVIP 账号有两种黑号，一种是限制了下载速度（一般<4MB/s），一种就是你这种彻底封禁，官方软件 APP 无法下载也不能播放视频，更加不能用于这个解析项目。
> 
> 前几个月我用自己的百度账号搭建了个解析站，就只是单纯的自己用，用了一段时间一共解析了 381 个文件（185GB）就被彻底封禁了，封了十几天都没解封就去找在线客服：
> 
> ![IMG_20220129_171146.jpg](https://user-images.githubusercontent.com/80463781/151655214-9bd44bb0-5617-4b8c-b66b-d16146cb32b9.jpg)
> 
> 后来也还是一直没解封，我也没打电话让客服处理，过了两个月实在忍不住就取消绑定包月了，SVIP过期后马上就解封了。。

了解了，看来目前最有效的方法就是重新注册一个账号，谢谢你
