### ISSUE TITLE
【寻求帮助】

### ISSUE THREAD

**Issue by wjf1** [yuantuo666/baiduwp-php#182]
![image](https://user-images.githubusercontent.com/50832152/153406301-bc59301e-f616-4b69-84b1-bc9860525cc6.png)
![image](https://user-images.githubusercontent.com/50832152/153406370-b324d105-a07f-404b-bf12-c9ed2f6231ba.png)
用的虚拟主机，点提交了没反应请问是怎么回事

**Comment by budingjiangya** [comment]
不支持虚拟主机运行好像

**Comment by budingjiangya** [comment]
那你看 数据库连接的上嘛 或者说是你自己的原因倒是数据库没连接上

**Comment by wjf1** [comment]
没，虚拟主机自带的有数据库

**Comment by budingjiangya** [comment]
> 没，虚拟主机自带的有数据库

自己检查 数据库地址 跟数据库名称 密码

**Comment by yuantuo666** [comment]
没反应一般是js文件没有成功加载，请检查文件目录是否完整
鉴于此议题长期没有回复，如果还有问题请重新打开。
