### ISSUE TITLE
【寻求帮助】这个源码的是免费版的吗？付费版的怎么买？增加了哪些功能？

### ISSUE THREAD

**Issue by hmjehbbk** [yuantuo666/baiduwp-php#183]
看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？

**Comment by budingjiangya** [comment]
> 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？

 啥批量下载 最多就限制流量之类的

**Comment by hmjehbbk** [comment]
> > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> 
> 啥批量下载 最多就限制流量之类的

人家说这个免费版的不能用要付费版的才能用  还说接口经常被限制要自己找接口  那接口要怎么自己找

**Comment by budingjiangya** [comment]
> > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > 
> > 
> > 啥批量下载 最多就限制流量之类的
> 
> 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找

可以用的  就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip  然后让一堆朋友解析 你看一个账号能解析多少文件

**Comment by budingjiangya** [comment]
> > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > 
> > 
> > 啥批量下载 最多就限制流量之类的
> 
> 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找

接口确实不太行了  账号太容易限速 拉黑 黑号了  要么就显示多人登录

**Comment by hmjehbbk** [comment]
> > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > 
> > > 
> > > 啥批量下载 最多就限制流量之类的
> > 
> > 
> > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> 
> 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件

付费的解析不限速  是吗

**Comment by budingjiangya** [comment]
> > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > 
> > > > 
> > > > 啥批量下载 最多就限制流量之类的
> > > 
> > > 
> > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > 
> > 
> > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> 
> 付费的解析不限速 是吗

都不限速啊  黑号  就是 账号拿去解析这个  账号直接报废 废掉了

**Comment by hmjehbbk** [comment]
> > > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > > 
> > > > > 
> > > > > 啥批量下载 最多就限制流量之类的
> > > > 
> > > > 
> > > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > > 
> > > 
> > > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> > 
> > 
> > 付费的解析不限速 是吗
> 
> 都不限速啊 黑号 就是 账号拿去解析这个 账号直接报废 废掉了

废掉了是什么意思啊  这个废掉的号在度盘客户端还能正常使用吗？废掉仅仅是指不能再做解析吧

**Comment by budingjiangya** [comment]
> > > > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > > > 
> > > > > > 
> > > > > > 啥批量下载 最多就限制流量之类的
> > > > > 
> > > > > 
> > > > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > > > 
> > > > 
> > > > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> > > 
> > > 
> > > 付费的解析不限速 是吗
> > 
> > 
> > 都不限速啊 黑号 就是 账号拿去解析这个 账号直接报废 废掉了
> 
> 废掉了是什么意思啊 这个废掉的号在度盘客户端还能正常使用吗？废掉仅仅是指不能再做解析吧

账号你都登录不了 了  废掉了    就算开了svip  账号也用不了了下载没速度  你跟百度网盘反馈  他说你违规使用 废掉了

**Comment by hmjehbbk** [comment]
> > > > > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 啥批量下载 最多就限制流量之类的
> > > > > > 
> > > > > > 
> > > > > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > > > > 
> > > > > 
> > > > > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> > > > 
> > > > 
> > > > 付费的解析不限速 是吗
> > > 
> > > 
> > > 都不限速啊 黑号 就是 账号拿去解析这个 账号直接报废 废掉了
> > 
> > 
> > 废掉了是什么意思啊 这个废掉的号在度盘客户端还能正常使用吗？废掉仅仅是指不能再做解析吧
> 
> 账号你都登录不了 了 废掉了 就算开了svip 账号也用不了了下载没速度 你跟百度网盘反馈 他说你违规使用 废掉了

那你的废号情况是什么样的

**Comment by budingjiangya** [comment]
> > > > > > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 啥批量下载 最多就限制流量之类的
> > > > > > > 
> > > > > > > 
> > > > > > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > > > > > 
> > > > > > 
> > > > > > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> > > > > 
> > > > > 
> > > > > 付费的解析不限速 是吗
> > > > 
> > > > 
> > > > 都不限速啊 黑号 就是 账号拿去解析这个 账号直接报废 废掉了
> > > 
> > > 
> > > 废掉了是什么意思啊 这个废掉的号在度盘客户端还能正常使用吗？废掉仅仅是指不能再做解析吧
> > 
> > 
> > 账号你都登录不了 了 废掉了 就算开了svip 账号也用不了了下载没速度 你跟百度网盘反馈 他说你违规使用 废掉了
> 
> 那你的废号情况是什么样的

扔了呗 废掉就仍

**Comment by hmjehbbk** [comment]
> > > > > > > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 啥批量下载 最多就限制流量之类的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > > > > > > 
> > > > > > > 
> > > > > > > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> > > > > > 
> > > > > > 
> > > > > > 付费的解析不限速 是吗
> > > > > 
> > > > > 
> > > > > 都不限速啊 黑号 就是 账号拿去解析这个 账号直接报废 废掉了
> > > > 
> > > > 
> > > > 废掉了是什么意思啊 这个废掉的号在度盘客户端还能正常使用吗？废掉仅仅是指不能再做解析吧
> > > 
> > > 
> > > 账号你都登录不了 了 废掉了 就算开了svip 账号也用不了了下载没速度 你跟百度网盘反馈 他说你违规使用 废掉了
> > 
> > 
> > 那你的废号情况是什么样的
> 
> 扔了呗 废掉就仍

我的意思是特定的时间会有多少个号废掉  比如一天多少个号废掉   在多少使用人数  特定时间内会有多少号废掉

**Comment by budingjiangya** [comment]
> > > > > > > > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 啥批量下载 最多就限制流量之类的
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> > > > > > > 
> > > > > > > 
> > > > > > > 付费的解析不限速 是吗
> > > > > > 
> > > > > > 
> > > > > > 都不限速啊 黑号 就是 账号拿去解析这个 账号直接报废 废掉了
> > > > > 
> > > > > 
> > > > > 废掉了是什么意思啊 这个废掉的号在度盘客户端还能正常使用吗？废掉仅仅是指不能再做解析吧
> > > > 
> > > > 
> > > > 账号你都登录不了 了 废掉了 就算开了svip 账号也用不了了下载没速度 你跟百度网盘反馈 他说你违规使用 废掉了
> > > 
> > > 
> > > 那你的废号情况是什么样的
> > 
> > 
> > 扔了呗 废掉就仍
> 
> 我的意思是特定的时间会有多少个号废掉 比如一天多少个号废掉 在多少使用人数 特定时间内会有多少号废掉

时间不固定  一天废掉30到40个号   每天解析16t到20t

**Comment by hmjehbbk** [comment]
> > > > > > > > > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 啥批量下载 最多就限制流量之类的
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 付费的解析不限速 是吗
> > > > > > > 
> > > > > > > 
> > > > > > > 都不限速啊 黑号 就是 账号拿去解析这个 账号直接报废 废掉了
> > > > > > 
> > > > > > 
> > > > > > 废掉了是什么意思啊 这个废掉的号在度盘客户端还能正常使用吗？废掉仅仅是指不能再做解析吧
> > > > > 
> > > > > 
> > > > > 账号你都登录不了 了 废掉了 就算开了svip 账号也用不了了下载没速度 你跟百度网盘反馈 他说你违规使用 废掉了
> > > > 
> > > > 
> > > > 那你的废号情况是什么样的
> > > 
> > > 
> > > 扔了呗 废掉就仍
> > 
> > 
> > 我的意思是特定的时间会有多少个号废掉 比如一天多少个号废掉 在多少使用人数 特定时间内会有多少号废掉
> 
> 时间不固定 一天废掉30到40个号 每天解析16t到20t

你的网站可以批量下载吗？文件夹解析吗？我看这个只能一个个去解析，要是遇到电子书这种文件目录多  文件小的不是很麻烦？

**Comment by budingjiangya** [comment]
> > > > > > > > > > > > > 看到说自定义UA是要买赞助版的源码，在哪买，还想要有批量解析下载的功能，源码作者可以出来回复下吗？
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 啥批量下载 最多就限制流量之类的
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 人家说这个免费版的不能用要付费版的才能用 还说接口经常被限制要自己找接口 那接口要怎么自己找
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 可以用的 就是账号很容易限速 没钱建议别瞎试了 你可以自己部署一个 自己开一个svip 然后让一堆朋友解析 你看一个账号能解析多少文件
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 付费的解析不限速 是吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 都不限速啊 黑号 就是 账号拿去解析这个 账号直接报废 废掉了
> > > > > > > 
> > > > > > > 
> > > > > > > 废掉了是什么意思啊 这个废掉的号在度盘客户端还能正常使用吗？废掉仅仅是指不能再做解析吧
> > > > > > 
> > > > > > 
> > > > > > 账号你都登录不了 了 废掉了 就算开了svip 账号也用不了了下载没速度 你跟百度网盘反馈 他说你违规使用 废掉了
> > > > > 
> > > > > 
> > > > > 那你的废号情况是什么样的
> > > > 
> > > > 
> > > > 扔了呗 废掉就仍
> > > 
> > > 
> > > 我的意思是特定的时间会有多少个号废掉 比如一天多少个号废掉 在多少使用人数 特定时间内会有多少号废掉
> > 
> > 
> > 时间不固定 一天废掉30到40个号 每天解析16t到20t
> 
> 你的网站可以批量下载吗？文件夹解析吗？我看这个只能一个个去解析，要是遇到电子书这种文件目录多 文件小的不是很麻烦？

不能下载文件夹 百度不支持  可以批量下载文件  提前得付费

**Comment by hmjehbbk** [comment]
> 

这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢

**Comment by budingjiangya** [comment]
> > 
> 
> 这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢

买不到的 你下载完成文件管理会 自动分类好啊  第几本 第几本  文件管理器会分类的

**Comment by hmjehbbk** [comment]
> > > 
> > 
> > 
> > 这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢
> 
> 买不到的 你下载完成文件管理会 自动分类好啊 第几本 第几本 文件管理器会分类的

你的网站可以批量下载吗

**Comment by budingjiangya** [comment]
> > > > 
> > > 
> > > 
> > > 这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢
> > 
> > 
> > 买不到的 你下载完成文件管理会 自动分类好啊 第几本 第几本 文件管理器会分类的
> 
> 你的网站可以批量下载吗

可以 提前得付费

**Comment by hmjehbbk** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢
> > > 
> > > 
> > > 买不到的 你下载完成文件管理会 自动分类好啊 第几本 第几本 文件管理器会分类的
> > 
> > 
> > 你的网站可以批量下载吗
> 
> 可以 提前得付费

我要源码

**Comment by budingjiangya** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢
> > > > 
> > > > 
> > > > 买不到的 你下载完成文件管理会 自动分类好啊 第几本 第几本 文件管理器会分类的
> > > 
> > > 
> > > 你的网站可以批量下载吗
> > 
> > 
> > 可以 提前得付费
> 
> 我要源码

没有卖的 自己去开发去

**Comment by hmjehbbk** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢
> > > > > 
> > > > > 
> > > > > 买不到的 你下载完成文件管理会 自动分类好啊 第几本 第几本 文件管理器会分类的
> > > > 
> > > > 
> > > > 你的网站可以批量下载吗
> > > 
> > > 
> > > 可以 提前得付费
> > 
> > 
> > 我要源码
> 
> 没有卖的 自己去开发去

你不是有吗？我不会开发

**Comment by budingjiangya** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢
> > > > > > 
> > > > > > 
> > > > > > 买不到的 你下载完成文件管理会 自动分类好啊 第几本 第几本 文件管理器会分类的
> > > > > 
> > > > > 
> > > > > 你的网站可以批量下载吗
> > > > 
> > > > 
> > > > 可以 提前得付费
> > > 
> > > 
> > > 我要源码
> > 
> > 
> > 没有卖的 自己去开发去
> 
> 你不是有吗？我不会开发

我有 我凭什么给你呢？ 给钱也不给

**Comment by hmjehbbk** [comment]
> > > 
> > 
> > 
> > 这种批量下载解析的源码付费的怎么买？对于像电子书这样批量下载后怎么放进正确的文件目录呢
> 
> 买不到的 你下载完成文件管理会 自动分类好啊 第几本 第几本 文件管理器会分类的

麻烦帮我召唤一下lc6464 想买赞助版都找不到人的

**Comment by lc6464** [comment]
你可别召唤了，这个仓库提供的是开源的免费版。
我这周五下午放假，请在本周五或周六用QQ联系我，https://lcwebsite.cn/web/contact.aspx
联系早了我这边回复不了。
