### ISSUE TITLE
【寻求帮助】账号都正常，解析提示根目录yunData获取失败

### ISSUE THREAD

**Issue by hmjehbbk** [yuantuo666/baiduwp-php#184]
账号都正常，解析提示根目录yunData获取失败
![2](https://user-images.githubusercontent.com/47794702/155629682-067386e9-eb1b-4e57-a459-7e79c01ba9a8.png)
![3](https://user-images.githubusercontent.com/47794702/155629685-8126fb23-d78d-4583-8e93-a325ab127967.png)
![4](https://user-images.githubusercontent.com/47794702/155629688-75db2be0-c7a1-46f2-aadc-9925d1139bf0.png)
![1](https://user-images.githubusercontent.com/47794702/155629690-ddb77f26-d3be-426f-94f4-769c3658eccd.png)

**Comment by budingjiangya** [comment]
小部分文件会遇到这种问题  文件问题

**Comment by hmjehbbk** [comment]
> 小部分文件会遇到这种问题 文件问题

你的数据库里一般会有几个在使用中的会员切换账号   我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改  那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢

**Comment by hmjehbbk** [comment]
> > > 小部分文件会遇到这种问题 文件问题
> > 
> > 
> > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> 
> 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)

需要网页上保持登录吗？我看我一把网页上的账号退掉  这个数据库会员账号就显示失效了？  你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用

**Comment by budingjiangya** [comment]
> > > > 小部分文件会遇到这种问题 文件问题
> > > 
> > > 
> > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > 
> > 
> > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> 
> 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用

我每天放入30到50个号  提供给  几千人使用 网址 https://jixia.asia/  可以去试试   至于放了多少号 自己看左边不显示2千6百多了吗

**Comment by hmjehbbk** [comment]
> > > > > 小部分文件会遇到这种问题 文件问题
> > > > 
> > > > 
> > > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > > 
> > > 
> > > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> > 
> > 
> > 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用
> 
> 我每天放入30到50个号 提供给 几千人使用 网址 https://jixia.asia/ 可以去试试 至于放了多少号 自己看左边不显示2千6百多了吗

那个2000多是指这是放入数据库的第几个号，但是数据库列表里的号不是这么多啊   你一般数据库在用的是多少  我看你的一个截图里面数据库是有7个会员号

**Comment by budingjiangya** [comment]
> > > > > > 小部分文件会遇到这种问题 文件问题
> > > > > 
> > > > > 
> > > > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > > > 
> > > > 
> > > > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> > > 
> > > 
> > > 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用
> > 
> > 
> > 我每天放入30到50个号 提供给 几千人使用 网址 https://jixia.asia/ 可以去试试 至于放了多少号 自己看左边不显示2千6百多了吗
> 
> 那个2000多是指这是放入数据库的第几个号，但是数据库列表里的号不是这么多啊 你一般数据库在用的是多少 我看你的一个截图里面数据库是有7个会员号

你咋看出是只加了7个号的  我不理解

**Comment by hmjehbbk** [comment]
> > > > > > > 小部分文件会遇到这种问题 文件问题
> > > > > > 
> > > > > > 
> > > > > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > > > > 
> > > > > 
> > > > > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> > > > 
> > > > 
> > > > 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用
> > > 
> > > 
> > > 我每天放入30到50个号 提供给 几千人使用 网址 https://jixia.asia/ 可以去试试 至于放了多少号 自己看左边不显示2千6百多了吗
> > 
> > 
> > 那个2000多是指这是放入数据库的第几个号，但是数据库列表里的号不是这么多啊 你一般数据库在用的是多少 我看你的一个截图里面数据库是有7个会员号
> 
> 你咋看出是只加了7个号的 我不理解

不是我刚才在其他问题里看到你的截图  然后看到那个截图上显示数据库中目前有7个在使用的会员号

**Comment by budingjiangya** [comment]
> > > > > > > > 小部分文件会遇到这种问题 文件问题
> > > > > > > 
> > > > > > > 
> > > > > > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > > > > > 
> > > > > > 
> > > > > > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> > > > > 
> > > > > 
> > > > > 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用
> > > > 
> > > > 
> > > > 我每天放入30到50个号 提供给 几千人使用 网址 https://jixia.asia/ 可以去试试 至于放了多少号 自己看左边不显示2千6百多了吗
> > > 
> > > 
> > > 那个2000多是指这是放入数据库的第几个号，但是数据库列表里的号不是这么多啊 你一般数据库在用的是多少 我看你的一个截图里面数据库是有7个会员号
> > 
> > 
> > 你咋看出是只加了7个号的 我不理解
> 
> 不是我刚才在其他问题里看到你的截图 然后看到那个截图上显示数据库中目前有7个在使用的会员号

没看到  反正每天要加 几十个号

**Comment by hmjehbbk** [comment]
> > > > > > > > > 小部分文件会遇到这种问题 文件问题
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > > > > > > 
> > > > > > > 
> > > > > > > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> > > > > > 
> > > > > > 
> > > > > > 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用
> > > > > 
> > > > > 
> > > > > 我每天放入30到50个号 提供给 几千人使用 网址 https://jixia.asia/ 可以去试试 至于放了多少号 自己看左边不显示2千6百多了吗
> > > > 
> > > > 
> > > > 那个2000多是指这是放入数据库的第几个号，但是数据库列表里的号不是这么多啊 你一般数据库在用的是多少 我看你的一个截图里面数据库是有7个会员号
> > > 
> > > 
> > > 你咋看出是只加了7个号的 我不理解
> > 
> > 
> > 不是我刚才在其他问题里看到你的截图 然后看到那个截图上显示数据库中目前有7个在使用的会员号
> 
> 没看到 反正每天要加 几十个号

为什么我的解析出来的地址下载速度就很慢，别人就能跑满速，解析出来的地址开头都是一样的

**Comment by budingjiangya** [comment]
> > > > > > > > > > 小部分文件会遇到这种问题 文件问题
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用
> > > > > > 
> > > > > > 
> > > > > > 我每天放入30到50个号 提供给 几千人使用 网址 https://jixia.asia/ 可以去试试 至于放了多少号 自己看左边不显示2千6百多了吗
> > > > > 
> > > > > 
> > > > > 那个2000多是指这是放入数据库的第几个号，但是数据库列表里的号不是这么多啊 你一般数据库在用的是多少 我看你的一个截图里面数据库是有7个会员号
> > > > 
> > > > 
> > > > 你咋看出是只加了7个号的 我不理解
> > > 
> > > 
> > > 不是我刚才在其他问题里看到你的截图 然后看到那个截图上显示数据库中目前有7个在使用的会员号
> > 
> > 
> > 没看到 反正每天要加 几十个号
> 
> 为什么我的解析出来的地址下载速度就很慢，别人就能跑满速，解析出来的地址开头都是一样的

因为你的号质量不行 别人的号质量哈  什么是质量号的号  就是一个正常账号  第一天开svip 马上拿去解析  你自己详细成本吧

**Comment by hmjehbbk** [comment]
> > > > > > > > > > > 小部分文件会遇到这种问题 文件问题
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用
> > > > > > > 
> > > > > > > 
> > > > > > > 我每天放入30到50个号 提供给 几千人使用 网址 https://jixia.asia/ 可以去试试 至于放了多少号 自己看左边不显示2千6百多了吗
> > > > > > 
> > > > > > 
> > > > > > 那个2000多是指这是放入数据库的第几个号，但是数据库列表里的号不是这么多啊 你一般数据库在用的是多少 我看你的一个截图里面数据库是有7个会员号
> > > > > 
> > > > > 
> > > > > 你咋看出是只加了7个号的 我不理解
> > > > 
> > > > 
> > > > 不是我刚才在其他问题里看到你的截图 然后看到那个截图上显示数据库中目前有7个在使用的会员号
> > > 
> > > 
> > > 没看到 反正每天要加 几十个号
> > 
> > 
> > 为什么我的解析出来的地址下载速度就很慢，别人就能跑满速，解析出来的地址开头都是一样的
> 
> 因为你的号质量不行 别人的号质量哈 什么是质量号的号 就是一个正常账号 第一天开svip 马上拿去解析 你自己详细成本吧

那以前开过会员但是没有做过解析   现在会员过期了  又重新开会员  我拿来做解析，这样的号质量算是好的吗？确保号不被废掉的安全红线大概是怎样的

**Comment by budingjiangya** [comment]
> > > > > > > > > > > > 小部分文件会遇到这种问题 文件问题
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 你的数据库里一般会有几个在使用中的会员切换账号 我看到说cookie登录想要数据库中添加的账号不失效要确保账号网页上保持登录并且密码不能改 那要是我添加的账号越来越多要怎么保持这些账号在网页的批量登录状态呢
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 换号点切换账号 别点 退出账号 ![image](https://user-images.githubusercontent.com/88592129/155664735-aa319b35-58dd-44a9-b14b-b55d60ba752f.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 需要网页上保持登录吗？我看我一把网页上的账号退掉 这个数据库会员账号就显示失效了？ 你的数据库里放了几个在用的会员号？一般多少个号能满足对应多少人的解析使用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我每天放入30到50个号 提供给 几千人使用 网址 https://jixia.asia/ 可以去试试 至于放了多少号 自己看左边不显示2千6百多了吗
> > > > > > > 
> > > > > > > 
> > > > > > > 那个2000多是指这是放入数据库的第几个号，但是数据库列表里的号不是这么多啊 你一般数据库在用的是多少 我看你的一个截图里面数据库是有7个会员号
> > > > > > 
> > > > > > 
> > > > > > 你咋看出是只加了7个号的 我不理解
> > > > > 
> > > > > 
> > > > > 不是我刚才在其他问题里看到你的截图 然后看到那个截图上显示数据库中目前有7个在使用的会员号
> > > > 
> > > > 
> > > > 没看到 反正每天要加 几十个号
> > > 
> > > 
> > > 为什么我的解析出来的地址下载速度就很慢，别人就能跑满速，解析出来的地址开头都是一样的
> > 
> > 
> > 因为你的号质量不行 别人的号质量哈 什么是质量号的号 就是一个正常账号 第一天开svip 马上拿去解析 你自己详细成本吧
> 
> 那以前开过会员但是没有做过解析 现在会员过期了 又重新开会员 我拿来做解析，这样的号质量算是好的吗？确保号不被废掉的安全红线大概是怎样的

建议开了svip直接用吧别做解析  或者去淘宝买个一天的拿去解析自己试试 看看多容易黑号

**Comment by hmjehbbk** [comment]
具体描述下有多容易黑号啊

**Comment by budingjiangya** [comment]
> 具体描述下有多容易黑号啊

一个号解析100来个文件就黑号了 有的 号刚添加进去就黑了

**Comment by budingjiangya** [comment]
> 具体描述下有多容易黑号啊

自己去 其他文件里面看啊很多人都问过了

**Comment by hmjehbbk** [comment]
> > 具体描述下有多容易黑号啊
> 
> 自己去 其他文件里面看啊很多人都问过了

手机回复查看很不方便  所以希望在固定的帖子里得到简单明了的答案

**Comment by budingjiangya** [comment]
> > > 具体描述下有多容易黑号啊
> > 
> > 
> > 自己去 其他文件里面看啊很多人都问过了
> 
> 手机回复查看很不方便 所以希望在固定的帖子里得到简单明了的答案

为什么不自己去实验了 非要问别人有啥用  别人说的也不一定是正确的

**Comment by hmjehbbk** [comment]
> > > > 具体描述下有多容易黑号啊
> > > 
> > > 
> > > 自己去 其他文件里面看啊很多人都问过了
> > 
> > 
> > 手机回复查看很不方便 所以希望在固定的帖子里得到简单明了的答案
> 
> 为什么不自己去实验了 非要问别人有啥用 别人说的也不一定是正确的

先问再实验  电脑不在身边

**Comment by hmjehbbk** [comment]
> > > > 具体描述下有多容易黑号啊
> > > 
> > > 
> > > 自己去 其他文件里面看啊很多人都问过了
> > 
> > 
> > 手机回复查看很不方便 所以希望在固定的帖子里得到简单明了的答案
> 
> 为什么不自己去实验了 非要问别人有啥用 别人说的也不一定是正确的

黑号不是废号吧  黑号只是暂时出现问题  客户端使用是正常的吗

**Comment by budingjiangya** [comment]
> > > > > 具体描述下有多容易黑号啊
> > > > 
> > > > 
> > > > 自己去 其他文件里面看啊很多人都问过了
> > > 
> > > 
> > > 手机回复查看很不方便 所以希望在固定的帖子里得到简单明了的答案
> > 
> > 
> > 为什么不自己去实验了 非要问别人有啥用 别人说的也不一定是正确的
> 
> 黑号不是废号吧 黑号只是暂时出现问题 客户端使用是正常的吗

使用的锤子  登录直接让你申诉 不知道你听谁说的

**Comment by hmjehbbk** [comment]
> > 具体描述下有多容易黑号啊
> 
> 一个号解析100来个文件就黑号了 有的 号刚添加进去就黑了

这个100应该是24小时之内吧   只要24小时之内控制不超过100多个就好了

**Comment by budingjiangya** [comment]
> > > 具体描述下有多容易黑号啊
> > 
> > 
> > 一个号解析100来个文件就黑号了 有的 号刚添加进去就黑了
> 
> 这个100应该是24小时之内吧 只要24小时之内控制不超过100多个就好了

20多块钱一个svip解析100来个文件就废掉了你觉得划算吗 我为什么不直接用百度网盘呢？
什么逻辑

**Comment by hmjehbbk** [comment]
> > > > 具体描述下有多容易黑号啊
> > > 
> > > 
> > > 一个号解析100来个文件就黑号了 有的 号刚添加进去就黑了
> > 
> > 
> > 这个100应该是24小时之内吧 只要24小时之内控制不超过100多个就好了
> 
> 20多块钱一个svip解析100来个文件就废掉了你觉得划算吗 我为什么不直接用百度网盘呢？ 什么逻辑

你能想想这两个红线是不是有关联呢？svip直接网盘登录是可以登10个设备，超过这个数就会异常要72小时申诉处理或者系统检测到安全风险   而这里超会的解析文件数  差不多就是10✘10，是不是相当于解析等于10个会员号然后分配给10台设备  超过就出问题

**Comment by budingjiangya** [comment]
> > > > > 具体描述下有多容易黑号啊
> > > > 
> > > > 
> > > > 一个号解析100来个文件就黑号了 有的 号刚添加进去就黑了
> > > 
> > > 
> > > 这个100应该是24小时之内吧 只要24小时之内控制不超过100多个就好了
> > 
> > 
> > 20多块钱一个svip解析100来个文件就废掉了你觉得划算吗 我为什么不直接用百度网盘呢？ 什么逻辑
> 
> 你能想想这两个红线是不是有关联呢？svip直接网盘登录是可以登10个设备，超过这个数就会异常要72小时申诉处理或者系统检测到安全风险 而这里超会的解析文件数 差不多就是10✘10，是不是相当于解析等于10个会员号然后分配给10台设备 超过就出问题

跟使用解析人数没有任何关系  自己去看看  https://jixia.icu   看他每天多少人使用 自己部署试试看看黑号不就完事了？

**Comment by hmjehbbk** [comment]
我网页一退出账号  添加cookie登录的账号就会失效  怎么办

**Comment by budingjiangya** [comment]
> 

自己操作有问题吧没遇到过

**Comment by hmjehbbk** [comment]
> > 
> 
> 自己操作有问题吧没遇到过

我看你有篇贴回复说有无限ip，这个项目里面对换ip也有需求的吗

**Comment by budingjiangya** [comment]
> > > 
> > 
> > 
> > 自己操作有问题吧没遇到过
> 
> 我看你有篇贴回复说有无限ip，这个项目里面对换ip也有需求的吗

当然咯  服务器不能换ip就是残废

**Comment by hmjehbbk** [comment]
> > > > 
> > > 
> > > 
> > > 自己操作有问题吧没遇到过
> > 
> > 
> > 我看你有篇贴回复说有无限ip，这个项目里面对换ip也有需求的吗
> 
> 当然咯 服务器不能换ip就是残废

对ip怎么操作才能确保服务器的解析呢

**Comment by budingjiangya** [comment]
有个东西叫做 ddns ip同步&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 【寻求帮助】账号都正常，解析提示根目录yunData获取失败 (Issue #184)





      
自己操作有问题吧没遇到过
  
我看你有篇贴回复说有无限ip，这个项目里面对换ip也有需求的吗
  
当然咯 服务器不能换ip就是残废
  
对ip怎么操作才能确保服务器的解析呢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by budingjiangya** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 自己操作有问题吧没遇到过
> > > 
> > > 
> > > 我看你有篇贴回复说有无限ip，这个项目里面对换ip也有需求的吗
> > 
> > 
> > 当然咯 服务器不能换ip就是残废
> 
> 对ip怎么操作才能确保服务器的解析呢

还有一个东西叫  api

**Comment by hmjehbbk** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 自己操作有问题吧没遇到过
> > > > 
> > > > 
> > > > 我看你有篇贴回复说有无限ip，这个项目里面对换ip也有需求的吗
> > > 
> > > 
> > > 当然咯 服务器不能换ip就是残废
> > 
> > 
> > 对ip怎么操作才能确保服务器的解析呢
> 
> 还有一个东西叫 api
你那个数据库显示有7个使用账号的在这里，你现在的数据库里提示的是有几个这样的号呢，那个几千只是你总共号的编码，不是数据库的在用会员号数量
![1](https://user-images.githubusercontent.com/47794702/155824025-ee62e578-1c87-457c-97b3-5918bd4af34b.png)
[https://github.com/yuantuo666/baiduwp-php/issues/174](url)

**Comment by hmjehbbk** [comment]
还看到你的一个回复说赞助版的要120元买，在哪里买？  假如我的站每天有人申请使用，我怎么样设置这个使用的人使用一个月后自动过期呢

**Comment by budingjiangya** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 自己操作有问题吧没遇到过
> > > > > 
> > > > > 
> > > > > 我看你有篇贴回复说有无限ip，这个项目里面对换ip也有需求的吗
> > > > 
> > > > 
> > > > 当然咯 服务器不能换ip就是残废
> > > 
> > > 
> > > 对ip怎么操作才能确保服务器的解析呢
> > 
> > 
> > 还有一个东西叫 api
> > 你那个数据库显示有7个使用账号的在这里，你现在的数据库里提示的是有几个这样的号呢，那个几千只是你总共号的编码，不是数据库的在用会员号数量
> > ![1](https://user-images.githubusercontent.com/47794702/155824025-ee62e578-1c87-457c-97b3-5918bd4af34b.png)
> > [https://github.com/yuantuo666/baiduwp-php/issues/174](url)

我也没说 是一次性加几千个啊  我是让你看账号解析了多少t了还没废掉

**Comment by budingjiangya** [comment]
> 还看到你的一个回复说赞助版的要120元买，在哪里买？ 假如我的站每天有人申请使用，我怎么样设置这个使用的人使用一个月后自动过期呢

看见 项目下面的  收款码不  转账120   截图联系lc

**Comment by hmjehbbk** [comment]
> > 还看到你的一个回复说赞助版的要120元买，在哪里买？ 假如我的站每天有人申请使用，我怎么样设置这个使用的人使用一个月后自动过期呢
> 
> 看见 项目下面的 收款码不 转账120 截图联系lc

买了赞助版会多哪些功能呢

**Comment by lc6464** [comment]
赞助版QQ联系我购买，周末才有空，周中在校上课。
在浏览器里切换账号同时保持 Cookies 不失效很简单，在 DevTools 的应用程序选项卡下的 Cookies 里把已有的 Cookies 全删了就行，或者在 InPrivate 里登录，获取了 Cookies 以后关闭所有 InPrivate 窗口，然后再重新开一个 InPrivate 窗口获取下一个就行。
另外本项目**暂停**维护，没空。

**Comment by hmjehbbk** [comment]
> 赞助版QQ联系我购买，周末才有空，周中在校上课。 在浏览器里切换账号同时保持 Cookies 不失效很简单，在 DevTools 的应用程序选项卡下的 Cookies 里把已有的 Cookies 全删了就行，或者在 InPrivate 里登录，获取了 Cookies 以后关闭所有 InPrivate 窗口，然后再重新开一个 InPrivate 窗口获取下一个就行。 另外本项目**暂停**维护，没空。

老板我来了  你在线吗？

**Comment by hmjehbbk** [comment]
> 赞助版QQ联系我购买，周末才有空，周中在校上课。 在浏览器里切换账号同时保持 Cookies 不失效很简单，在 DevTools 的应用程序选项卡下的 Cookies 里把已有的 Cookies 全删了就行，或者在 InPrivate 里登录，获取了 Cookies 以后关闭所有 InPrivate 窗口，然后再重新开一个 InPrivate 窗口获取下一个就行。 另外本项目**暂停**维护，没空。

给你联系站长的邮箱发邮件没人回复  不知道你qq多少

**Comment by hmjehbbk** [comment]
> > > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 自己操作有问题吧没遇到过
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我看你有篇贴回复说有无限ip，这个项目里面对换ip也有需求的吗
> > > > > > > 
> > > > > > > 
> > > > > > > 当然咯 服务器不能换ip就是残废
> > > > > > 
> > > > > > 
> > > > > > 对ip怎么操作才能确保服务器的解析呢
> > > > > 
> > > > > 
> > > > > 还有一个东西叫 api
> > > > > 你那个数据库显示有7个使用账号的在这里，你现在的数据库里提示的是有几个这样的号呢，那个几千只是你总共号的编码，不是数据库的在用会员号数量
> > > > > ![1](https://user-images.githubusercontent.com/47794702/155824025-ee62e578-1c87-457c-97b3-5918bd4af34b.png)
> > > > > [https://github.com/yuantuo666/baiduwp-php/issues/174](url)
> > > 
> > > 
> > > 我也没说 是一次性加几千个啊 我是让你看账号解析了多少t了还没废掉
> > 
> > 
> > 数据库里放10个会员号1天大概能满足多少人的解析需求呢
> 
> 你自己开会员试试不就知道了？

麻烦帮我召唤一下lc6464   想买赞助版都找不到人的

**Comment by lc6464** [comment]
> 给你联系站长的邮箱发邮件没人回复 不知道你qq多少

不都说了周末才有空吗？
如果你的邮箱是 174******5@qq.com，请查收回信，如果不是，那我没收到。
另外，QQ 咨询链接不是放在联系站长页面了嘛？
周五再联系我，我这周五下午放假。

**特别说明：当前的赞助版也没有解决账号容易被限速的问题！**

**Comment by yuantuo666** [comment]
yunData 获取失败可能和系统环境有关，项目代码目前是可以使用的
如果仍存在问题，请重新打开议题
