### ISSUE TITLE
【建议】这个项目已经(暂时)挂了，大家暂时不要搭建了。秒封

### ISSUE THREAD

**Issue by dylanbai8** [yuantuo666/baiduwp-php#185]
# 项目作者(因私人原因)可能暂时没有时间更新了，大家等等吧。

# 接口已废，秒封，秒黑。

# 暂时不要搭建了。等作者回归

**Comment by budingjiangya** [comment]
可以试试 https://jixia.icu/   不好好的嘛 不是已经挂了是你号质量差

**Comment by dylanbai8** [comment]
> 可以试试 https://jixia.icu/ 不好好的嘛 不是已经挂了是你号质量差

# 你每个issues都打来打广告，滥用issues，无耻！

# 每个issues都有你的广告！滥用issues，无耻！

# 滥用issues，无耻引流！ [湘ICP备2022001632号]

**Comment by budingjiangya** [comment]
> > 可以试试 https://jixia.icu/ 不好好的嘛 不是已经挂了是你号质量差
> 
> # 你每个issues都打来打广告，滥用issues，无耻！
> # 每个issues都有你的广告！滥用issues，无耻！
> # 滥用issues，无耻引流！ [湘ICP备2022001632号]

啊对对对 为什么 我的没挂呢？ 每天都不限速呢？

**Comment by dylanbai8** [comment]
# 没人不让你交流，这是反馈问题，共享代码的地方！
# 你每个issues都发广告，引流公众号 滥用issues 无耻！
# 你在每个issues留言的目的不是交流，而是推广 发广告链接！

**Comment by budingjiangya** [comment]
> # 没人不让你交流，这是反馈问题，共享代码的地方！
> # 你每个issues都发广告，引流公众号 滥用issues 无耻！
> # 你在每个issues留言的目的不是交流，而是推广 发广告链接！

### 我寻思我发什么广告了？  我发了链接有问题么 发个链接就引流了？

**Comment by budingjiangya** [comment]
![image](https://user-images.githubusercontent.com/88592129/155828218-e261f6fc-c7cb-4bd0-ac1b-c7aa0becb3be.png)
![image](https://user-images.githubusercontent.com/88592129/155828231-1abb5f78-c044-43b1-bdc0-c1e8a8bb041c.png)
![image](https://user-images.githubusercontent.com/88592129/155828237-a26550f5-5247-497a-8f58-166612878a43.png)
![image](https://user-images.githubusercontent.com/88592129/155828259-6e3e31ec-e38d-4001-8210-c24bd6e14229.png)
没挂 就没挂 看看账号解析的时间 号是容易限速  多加一些不就完事了

**Comment by lc6464** [comment]
项目**暂停**维护，没空。
都在读高中呢，一个高二一个高三。
