### ISSUE TITLE
【寻求帮助】版主求现身，我微信给你买了赞助版，我在哪里可以找到赞助版

### ISSUE THREAD

**Issue by hmjehbbk** [yuantuo666/baiduwp-php#186]
买了赞助版，但是现在没人现身？？？

**Comment by yuantuo666** [comment]
提供一下邮箱或QQ号

**Comment by hmjehbbk** [comment]
> 提供一下邮箱或QQ号

1743350575@qq.com

**Comment by hmjehbbk** [comment]
> 提供一下邮箱或QQ号

提供了之后呢？

**Comment by lc6464** [comment]
你这个买了赞助版，是在没有联系 Yuan_Tuo 或我也没有提供任何说明的情况下直接对 Yuan_Tuo 转账了？
这种情况你只能等了，Yuan_Tuo 在备考，忙得很，运气好的话等上几天到一两周，运气不好的话等到七月份左右。
你不是对我转账的，我这边无法证实，所以我不能给你提供代码。
如果有其他问题可以问我，周末有空，https://lcwebsite.cn/web/contact.aspx
请使用QQ在本周五或周六联系。

暂时关闭此 Issue，如有需要可以再次开启。
