### ISSUE TITLE
【建议】是否考虑加入文件蜈蚣下载

### ISSUE THREAD

**Issue by filecxx** [yuantuo666/baiduwp-php#187]
是否考虑加入文件蜈蚣下载

软件的功能可以见网站 http://www.filecxx.com/ 相信你不会失望。

另外通过网页调用下载的JS脚本非常简单，只需要一个JS函数的调用，参见：

http://www.filecxx.com/zh_CN/documentation/create_address.html

非常感谢。

**Comment by yuantuo666** [comment]
因软件过于小众，暂不考虑
