### ISSUE TITLE
【举报】“极下解析” 涉嫌诈骗 https://jixia.icu 举报

### ISSUE THREAD

**Issue by gfr687412** [yuantuo666/baiduwp-php#189]
## 为什么 issues 全都是“极下解析”的广告，你们是一伙的吗？付了款不能用 诈骗啊？

# 伪造同行邮件截图洗白，卑鄙无耻！

**Comment by budingjiangya** [comment]
你可得了吧 故意尬黑 让发现 还换号来了笑死我了

**Comment by budingjiangya** [comment]
你尽管诽谤，拿不出实际证据  恶意造谣 污蔑诽谤  侵犯隐私 该项目已有 2.6k关注 影响重大  
(一)引发群体性事件的;
(二)引发公共秩序混乱的;
(三)诽谤多人，造成恶劣社会影响的;
(四)损害个人形象，严重危害他人利益的;
第二百四十六条　以暴力或者其他方法公然侮辱他人或者捏造事实诽谤他人，情节严重的，处三年以下[有期徒刑](http://www.64365.com/baike/yqtx/)、[拘役](http://www.64365.com/baike/jy/)、[管制](http://www.64365.com/baike/gz1/)或者[剥夺政治权利](http://www.64365.com/baike/bdzzql/)。

等我收集好证据 看谁蹲监狱 你尽管污蔑

**Comment by budingjiangya** [comment]
伪造所谓"同行邮件"截图洗白？有这个必要么？？ 你自己污蔑就污蔑 此视频为证   
   https://wz.jixia.icu/wumie/wumingshiwumie.mp4

**Comment by lc6464** [comment]
差不多得了，极下提供的付费服务和我们没有任何关系，我们也已经把他的那些链接隐藏了。
另外，如果你真的认为极下的付费服务是诈骗，请拿出证据，而不是无理取闹！
