### ISSUE TITLE
项目失效了，已获取到文件，但未能获取到下载链接！

### ISSUE THREAD

**Issue by gimgoo** [yuantuo666/baiduwp-php#196]
已获取到文件，但未能获取到下载链接！

请检查你是否在 config.php 中配置 普通账号 的 BDUSS 和 STOKEN！

未配置 或 普通账号失效均会导致失败！（账号失效的原因包括但不限于 退出登录、修改密码）

![image](https://user-images.githubusercontent.com/31849284/163419942-6dbd36a5-d6e3-4452-9e77-6da31a086551.png)

![image](https://user-images.githubusercontent.com/31849284/163419862-034dc5f6-3189-47a1-be48-72e9ecbe89be.png)

**Comment by yuantuo666** [comment]
账号配置问题，按照自行解决

**Comment by gimgoo** [comment]
都不是第一次用啦，按照提示特地更新普通账号的 BDUSS 跟 STOKEN，没用

**Comment by gimgoo** [comment]
我百度网盘现在还在登着呢，不存在失效问题

**Comment by yuantuo666** [comment]
打开 debug 把错误页面截图发送一下

**Comment by gimgoo** [comment]
那我明天再看看吧，我确实更新了普通账号的 BDUSS 跟 STOKEN，管理界面也显示正常了，但是点击获取下载链接就是不行

**Comment by gimgoo** [comment]
重新获取 BDUSS 跟 STOKEN。仍然一个样

![image](https://user-images.githubusercontent.com/31849284/163526429-0c5e7d82-da08-4ea2-9716-11ef404b41e7.png)

![image](https://user-images.githubusercontent.com/31849284/163526483-c4bbef45-1dbf-40c3-8788-f06c3bc5b552.png)

**Comment by gimgoo** [comment]
表示非常不理解，怎么会是普通账号有问题，没改密码，网页也还登录着，后台检测也是正常

**Comment by gimgoo** [comment]
你的DEMO是旧版的，试一下是不是新版有问题吧
