### ISSUE TITLE
【BUG 反馈】项目失效，普通账号配置没有问题，获取下载链接失败

### ISSUE THREAD

**Issue by danjiu** [yuantuo666/baiduwp-php#198]
获取下载链接失败
已获取到文件，但未能获取到下载链接！

请检查你是否在 config.php 中配置 普通账号 的 BDUSS 和 STOKEN！

未配置 或 普通账号失效均会导致失败！（账号失效的原因包括但不限于 退出登录、修改密码）

在论坛里查找了一下发现了加我三个同类型问题 都没有得到解决 如果在config.php 中 改35行为ture 则会出现界面代码

有什么解决方法吗

![image](https://user-images.githubusercontent.com/34980120/164596302-a5339b67-0a4a-4bff-9180-4647fb1a50ad.png)

![image](https://user-images.githubusercontent.com/34980120/164596904-ecea32d1-4e3e-47b2-ba13-18401f4f4ab4.png)

![image](https://user-images.githubusercontent.com/34980120/164596673-b7414584-ca04-497d-8685-8fd1d0c10da2.png)

@yuantuo666 @lc6464

**Comment by yuantuo666** [comment]
打开debug，将**获取下载链接失败页面**调试信息截图发送出来（调试信息只包含解析文件和账号的基本信息，担心安全问题也可发送至我的邮箱：yuantuo666@gmail.com）

**Comment by yuantuo666** [comment]
![Screenshot_20220422_122953_com microsoft emmx](https://user-images.githubusercontent.com/44130602/164603765-300d6841-a68b-4430-a072-677789c9be0f.jpg)
![Screenshot_20220422_123017_com microsoft emmx](https://user-images.githubusercontent.com/44130602/164603769-fa69f412-8a0d-44b4-ab50-5c2c677b1a43.jpg)
04.22 12:30 测试没有问题

**Comment by danjiu** [comment]
> 

我重新上传安装了，不过我感觉还会也有人出现了这种情况，我应该是安装的github全部源码，而不是php程序，会不会是这方面的原因导致的。

**Comment by yuantuo666** [comment]
两种都可以的，程序那个压缩包只是剔除了一些无关的文件

**Comment by danjiu** [comment]
> 两种都可以的，程序那个压缩包只是剔除了一些无关的文件
又不行了
![image](https://user-images.githubusercontent.com/34980120/164605318-1788c967-55fb-4d5c-8f28-2175dee59469.png)


![image](https://user-images.githubusercontent.com/34980120/164605301-69b88546-b3c9-4068-bf5c-9572b472c575.png)

**Comment by danjiu** [comment]
> 两种都可以的，程序那个压缩包只是剔除了一些无关的文件

以发送调试信息在你的邮箱里了，名称就是此主题的名称

**Comment by yuantuo666** [comment]
需要的不是网页源码
需要发送打开debug后，网页显示的调试信息
