### ISSUE TITLE
Blacklists提交

### ISSUE THREAD

**Issue by QAQ5555** [yuantuo666/baiduwp-php#199]
https://xbd.fuliti.com/
以上网站使用本项目源码，删除作者信息。
哔哩哔哩UID11076983 _不言不厌_

**Comment by budingjiangya** [comment]
![image](https://user-images.githubusercontent.com/88592129/168539391-2ed4a124-33de-4549-a052-da4f53da41d9.png)

**Comment by budingjiangya** [comment]
![c955523bb0cee95c05c529dd411af09](https://user-images.githubusercontent.com/88592129/168539960-def4bc4e-d44e-4425-abc0-2e4e49c5a489.png)
这个是他的联系方式

**Comment by yuantuo666** [comment]
已联系站长添加项目地址，感谢反馈

**Comment by fuliti** [comment]
> 已联系站长添加项目地址，感谢反馈

我已经加上，如果还是把我的信息给放在上面，不加以管理，我已经联系当地派出所，不要为了一个地址的小事，大家法庭上见。

**Comment by fuliti** [comment]
> ![c955523bb0cee95c05c529dd411af09](https://user-images.githubusercontent.com/88592129/168539960-def4bc4e-d44e-4425-abc0-2e4e49c5a489.png) 这个是他的联系方式

还有你，麻烦以后做事情的时候，过过脑子，虽然这是国外的网站，但我真要不惜一切追究责任，你照样跑不掉。

**Comment by Rs529811807** [comment]
这个作者真牛逼啊，私自曝光别人信息，是谁给你这个权利的。莫非以为这个是国外网站，国家真管不到啊。这种属于违法的。既然都开源出来了。你管那么多闲事做啥。别人改成啥样子，关你鸟事啊。开源不起来，就不要开源。打着开源口号，源码留后门。真不是一般人能做出来的事情

**Comment by yuantuo666** [comment]
相关信息已隐藏
另，那种图片也不是我发的

**Comment by Rs529811807** [comment]
不好意思啊，说错人了，不是作者你。那这个曝光别人信息的这个兄弟，真牛逼啊。简直是幼儿园的智力。
