### ISSUE TITLE
如果不是bug帮我看看怎么解决，谢了

### ISSUE THREAD

**Issue by qcppl5** [yuantuo666/baiduwp-php#20]
发现一个bug，不知道算不算，如果分享链接里有一个文件夹名称有空格就会提示

Warning: count(): Parameter must be an array or an object that implements Countable in /www/wwwroot/xxx/index.php on line 143

Warning: count(): Parameter must be an array or an object that implements Countable in /www/wwwroot/xxx/index.php on line 145
![Screenshot_20200825-203612](https://user-images.githubusercontent.com/61025967/91175157-eb388980-e712-11ea-8a91-22a1fdb3bc02.jpg)

**Comment by rometuo** [comment]
一样希望能修复

**Comment by yuantuo666** [comment]
请先尝试更新版本，如果还是不行，发一下报错的分享链接
