### ISSUE TITLE
【寻求帮助】为啥都开源了，还找我要授权费用啊，是不是双标啊

### ISSUE THREAD

**Issue by Rs529811807** [yuantuo666/baiduwp-php#201]
为啥都开源了，还找我要授权费用啊，是不是双标啊

**Comment by yuantuo666** [comment]
？

**Comment by yuantuo666** [comment]
赞助版和开源版是两个版本
并没有找你要“授权费用”这一事

请提供更多信息

**Comment by Rs529811807** [comment]
我就想问一句话，你既然开源出来了，我拿你的源码二开，为啥还要留你的信息在网站上。既然开源不起来，就不要开啊，这个是github.com啊

**Comment by Rs529811807** [comment]
前几天才找我麻烦，就是一个垃圾。打着开源的旗号，到处骗钱

**Comment by yuantuo666** [comment]
https://github.com/yuantuo666/baiduwp-php/blob/master/LICENSE
请你查看本项目协议，在你安装此项目时也已经同意保留项目信息
开源不代表可以允许你肆意妄为地删除作者信息

**Comment by Rs529811807** [comment]
这个是github.com啊，大哥，你开源不起来就不要开

**Comment by yuantuo666** [comment]
请你自己阅读项目协议

> A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

**only requiring preservation of copyright and license notices**

**Comment by Rs529811807** [comment]
全球最大开源网站，开源不起来，就不要渣渣

**Comment by Rs529811807** [comment]
垃圾中的战斗机，还好意思说，，赞助版和开源版是两个版本
并没有找你要“授权费用”这一事。

**Comment by yuantuo666** [comment]
https://go.usoft8.cn/
这个是你的网站吧

**Comment by Rs529811807** [comment]
开源不起来，就不要开了，垃圾中的垃圾

**Comment by Rs529811807** [comment]
这个网站要是给禁止了，他这个人就是垃圾中的垃圾。打着开源的旗号，名利都想要。借着github的流量来宣传，真牛逼啊

**Comment by yuantuo666** [comment]
![图片](https://user-images.githubusercontent.com/44130602/169966599-593835a9-a552-448c-9d64-c00ac67f8034.png)
不论是那个版本，安装页面都有保留版权提示，是你先违反了协定

**Comment by Rs529811807** [comment]
这是github啊。打着开源的旗号，来赚钱，真是牛逼，开源不起来，就不要开

**Comment by yuantuo666** [comment]
https://go.usoft8.cn/
这个是你的网站吧

**Comment by Rs529811807** [comment]
要就给我发律师函，这个是github.com。。。你告到法院，你都打不赢，哈哈哈

**Comment by Rs529811807** [comment]
这个网站是国外的。不受中国管理的。

**Comment by Rs529811807** [comment]
你开源不起来就不要开。

**Comment by yuantuo666** [comment]
https://go.usoft8.cn/
这个是你的网站吧

**Comment by Rs529811807** [comment]
简直双标中的极品。开源不起来就不要开

**Comment by Rs529811807** [comment]
开源了，还留有后门。真是极品中的极品
