### ISSUE TITLE
【寻求帮助】关于提速思路问题

### ISSUE THREAD

**Issue by ifeisier** [yuantuo666/baiduwp-php#202]
能提供以下思路吗？
例如：这个项目中使用了一些百度网盘的接口，这些接口都是怎么找到的？

**Comment by yuantuo666** [comment]
解析思路：用会员账号获取文件下载地址，返回给访客
接口来源：百度网盘网页端抓包

**Comment by lc6464** [comment]
如还有问题可重开议题。

**Comment by ifeisier** [comment]
> 解析思路：用会员账号获取文件下载地址，返回给访客 接口来源：百度网盘网页端抓包

感觉说了，，但是感觉又没说

**Comment by ifeisier** [comment]
@yuantuo666 
请问 UA 怎么找？
