### ISSUE TITLE
请问这个网站的页面用的是这个解析么？

### ISSUE THREAD

**Issue by aotuitx** [yuantuo666/baiduwp-php#203]
https://www.kelongwo.com/project/baidu_pan/

这个网址，也就是 antdownload

**Comment by lc6464** [comment]
看起来很像。

**Comment by ifeisier** [comment]
会这个的多了去了，，，我现在一直用着一个，也没有流量限制。

**Comment by lc6464** [comment]
> 会这个的多了去了，，，我现在一直用着一个，也没有流量限制。

多是多，但总有一些特征的。

**Comment by aotuitx** [comment]
了解了
