### ISSUE TITLE
【BUG 反馈】 无法下载文件

### ISSUE THREAD

**Issue by Minecraft3193092** [yuantuo666/baiduwp-php#204]
## 无法下载文件
描述 : 无法下载文件
检测到当前链接异常，保存到网盘重新分享后可获得更好的体验~
。

## 如何复现此 Bug
复现此 Bug 的步骤:
1. 1TGjKx5y7zIy_ysAgmrEHeQ 提取码:fle6
2. 按 Submit 按鈕

**Comment by lc6464** [comment]
分享的文件已被删除。
若仍有问题请重开议题。
