### ISSUE TITLE
为何我每次设置SVIP账号都会被限速！

### ISSUE THREAD

**Issue by a87736426** [yuantuo666/baiduwp-php#206]
每次一设置SVIP账号   都没解析过多少次   就直接被限速了！求解  什么原因造成的呢！服务器IP也换过了的！（然后换过别的SVIP账号  也还是解析没多少次又被限速了）  作者帮解决下  看时候什么问题喂！非常感谢

**Comment by lc6464** [comment]
接口问题，暂无解决办法。
另外就是现在的 UA 有点问题，你可以自行尝试更换。

**Comment by lc6464** [comment]
如有更多问题可再次打开议题。
