### ISSUE TITLE
【寻求帮助】aria2下载很慢

### ISSUE THREAD

**Issue by 773780238** [yuantuo666/baiduwp-php#207]
为什么aria2的下载速度很慢
![屏幕截图(2)](https://user-images.githubusercontent.com/15882646/175764939-eec7c7d0-5bc8-44e0-811c-02ec1e71727e.png)

**Comment by lc6464** [comment]
检查一下你的网络，有没有可能是网络或者代理的问题？

**Comment by GreenTeodoro839** [comment]
检查网络，如果正常就是黑号了

**Comment by lc6464** [comment]
如果您还有更多问题，请重开议题。
