### ISSUE TITLE
【寻求帮助】统计代码是什么

### ISSUE THREAD

**Issue by a87736426** [yuantuo666/baiduwp-php#209]
通常用于设置隐藏的统计代码是什么呢   这功能都没用过的！不懂怎么设置   作者有没有现有的统计代码呢！方便提供下不呢

**Comment by yuantuo666** [comment]
可以试试 百度统计

**Comment by lc6464** [comment]
统计代码如无需要忽略即可。
第三方统计代码会一定程度上影响用户对你的网站的评价，谨慎使用。
虽然说现在互联网上保持隐私太难了，但是看到明晃晃的跟踪器，还是会反感的。

**Comment by a87736426** [comment]
> 
好的！

**Comment by a87736426** [comment]
> 统计代码如无需要忽略即可。 第三方统计代码会一定程度上影响用户对你的网站的评价，谨慎使用。 虽然说现在互联网上保持隐私太难了，但是看到明晃晃的跟踪器，还是会反感的。

哈哈  你讲得也有道理哦！谢谢

**Comment by lc6464** [comment]
> 哈哈 你讲得也有道理哦！谢谢

主要看需要吧。

这个议题的标题是另外的问题吗？

**Comment by a87736426** [comment]
> 



> > 哈哈 你讲得也有道理哦！谢谢
> 
> 主要看需要吧。
> 
> 这个议题的标题是另外的问题吗？

不算呢！你回复得很满意！只是没用过  感觉这功能有点新奇而已

**Comment by lc6464** [comment]
请问还有别的问题吗？

**Comment by a87736426** [comment]
> 

没有了的！
