### ISSUE TITLE
【建议】是否考虑增加对百度网盘企业账号的支持

### ISSUE THREAD

**Issue by DingKuiqing** [yuantuo666/baiduwp-php#210]
## 描述建议
企业账号原生支持非客户端下载、打包下载、多线程下载等特性。且相比SVIP账号具有更不易触发的风控，是否考虑增加对企业账号的支持。（如果需要企业账号进行测试本人可以提供）

## 补充信息
已经有站点通过魔改本项目实现了该建议
**避免广告嫌疑，已隐藏**

谢谢大佬做出的贡献

**Comment by yuantuo666** [comment]
感谢你的提议，目前版本的获取下载链接api基本处于不可用的状态，如果下载数量一多就会黑号
如果企业账号没有这些限制将获得更好体验
今天我去研究一下

**Comment by yuantuo666** [comment]
能否提供一下企业账号
我的邮箱：yuantuo666@gmail.com
是百度网盘企业版吗：https://pan.baidu.com/disk/cert#/web/home

**Comment by lc6464** [comment]
值得尝试。

**Comment by DingKuiqing** [comment]
> 能否提供一下企业账号 我的邮箱：[yuantuo666@gmail.com](mailto:yuantuo666@gmail.com) 是百度网盘企业版吗：https://pan.baidu.com/disk/cert#/web/home

是您引用的链接的企业版 已经给您的邮箱发送了包含账号密码的邮件 由于是自建邮箱 可能被标记Spam 请您查收 谢谢

**Comment by DingKuiqing** [comment]
请问有进展吗 我注意到我之前的邮件里好像提供了错误的账号信息
如果需要的话 我可以直接寄出百度网盘企业版的员工邀请链接

**Comment by yuantuo666** [comment]
感谢你提供的帮助，已有其他作者尝试百度网盘企业版，但限制比较多，如正常用户申请企业账号较难、大量解析文件容易封号等；
且 企业版 web 前端的加密较为复杂，故暂不考虑支持百度网盘企业账号
