### ISSUE TITLE
【寻求帮助】请问下获取传进来参数，以及根据BDUSS生成链接并返回的相关逻辑在哪里

### ISSUE THREAD

**Issue by swhoro** [yuantuo666/baiduwp-php#212]
想自己用其它语言写一个最简单的服务器，当作练手
奈何没学过php，想来问一下相关的逻辑时放在哪个文件中

**Comment by yuantuo666** [comment]
https://github.com/yuantuo666/baiduwp-php/blob/master/index.php#L314  此处是下载页面的逻辑部分

**Comment by lc6464** [comment]
如仍有问题可重新打开此议题。
