### ISSUE TITLE
[微信API] 解析错误 未知错误代码:mispwd-9【BUG 反馈】

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#214]
## 描述 Bug
请在此填入对此 Bug 清晰准确的描述。

## 如何复现此 Bug
复现此 Bug 的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 期望
对您所期望的情况做一个简单描述。

## 
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by yuantuo666** [comment]
提取码填写错误

**Comment by diannaodiy** [comment]
{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":379207691678247559}您好，点击下载以后出现这个是什么原因。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月22日(星期四) 晚上9:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] [微信API] 解析错误 未知错误代码:mispwd-9【BUG 反馈】 (Issue #214)





 
提取码填写错误

**Comment by yuantuo666** [comment]
下载时没有设置ua，请查看使用帮助
