### ISSUE TITLE
【寻求帮助】[微信API] 解析错误

### ISSUE THREAD

**Issue by hwmbing11** [yuantuo666/baiduwp-php#217]
$_GET:
/www/wwwroot/baiduwangpan.com/index.php:139:
array (size=0)
  empty
$_POST:
/www/wwwroot/baiduwangpan.com/index.php:141:
array (size=2)
  'surl' => string '1GZk7b-tUnQVOSBLoRogGxg' (length=23)
  'pwd' => string 'gk14' (length=4)
GetList():
/www/wwwroot/baiduwangpan.com/functions.php:362:
array (size=10)
  'errno' => int -130
  'request_id' => int 422347730027857864
  'errtype' => string 'mispwd-9' (length=8)
  'server_time' => int 1664014604
  'data' => 
    array (size=18)
      'title' => string '' (length=0)
      'expiredType' => int 0
      'link_ctime' => int 1602431883
      'fileNums' => int 0
      'has_more' => boolean false
      'list' => 
        array (size=0)
          empty
      'user' => 
        array (size=1)
          'avatar' => string 'https://himg.bdimg.com/sys/portrait/item/public.1.7d876613.wYKGTDAMPR21qUCX9eKrTA.jpg' (length=85)
      'uname' => string '新虎枫****1103' (length=17)
      'uk' => int 3929310051
      'shareid' => int 4194460699
      'wx_name' => string '阿亮' (length=6)
      'wx_headurl' => string 'https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKrfCKXQsgfx72ssnSxfQAmcJCkbXa4iclkDxlcDiahAEcqibwlpMbiaCBwu8HKTa0kb3IjrplsNDuhLg/132' (length=132)
      'hitrisk' => int 0
      'appeal_status' => int 0
      'sharetype' => int 0
      'view_visited' => int 0
      'view_limit' => int 0
      'expired_type' => int 0
  'cfrom_id' => int 0
  'is_zombie' => int 0
  'vip_level' => int 6
  'vip_point' => int 29090
  'vip_type' => int 2

**Comment by yuantuo666** [comment]
提取码错误导致的问题
参见 #214 #218

**Comment by yuantuo666** [comment]
[v2.2.3](https://github.com/yuantuo666/baiduwp-php/releases/tag/v2.2.3) 更新至此版本及更高可解决此问题
