### ISSUE TITLE
【BUG 反馈】无法正常获取文件夹有关信息

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#219]
## 描述 Bug
无法正常获取文件夹有关信息。

**Comment by yuantuo666** [comment]
百度前天（09.28）封了获取 sign 参数的接口，导致分享下载功能目前不可用
近期将寻找其他可替代方案解决问题

**Comment by diannaodiy** [comment]
您好。最近百度规则又修改了吗&nbsp;


弧光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月7日(星期五) 凌晨0:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 【BUG 反馈】无法正常获取文件夹有关信息 (Issue #219)





 
关闭 #219 通过 42962bd 完成。
 
—
 直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了该线程。Message ID: ***@***.***&gt;
