### ISSUE TITLE
1.4.1版本，正常情况无法进入获取下载链接

### ISSUE THREAD

**Issue by Fsouth** [yuantuo666/baiduwp-php#22]
参数有误", "POST 传参出现问题！请不要自行构建表单提交！

**Comment by yuantuo666** [comment]
请尝试刷新浏览器缓存后重新获取

**Comment by yuantuo666** [comment]
1.4.1版本更新了static/functions.js文件
直接覆盖安装的话，浏览器和服务器会有缓存
更换浏览器或者删除缓存就可以进入

电脑端可以按Ctrl+F5强制刷新

**Comment by sd362318** [comment]
同样出现这个问题，浏览器的无痕模式也一样

**Comment by yuantuo666** [comment]
请尝试清理服务器缓存

**Comment by yuantuo666** [comment]
实在不行就把functions.js改个名字，曲线救国

**Comment by sd362318** [comment]
把functions.js删除重新pull一下，强制刷新，无痕浏览，更换浏览器，问题依旧

**Comment by fcki1984** [comment]
可能是你vps开了缓存。

> 把functions.js删除重新pull一下，强制刷新，无痕浏览，更换浏览器，问题依旧

可能是你vps开启了缓存，重启nginx,php。
或者你用了cf，登录cf，清除缓存。
