### ISSUE TITLE
【建议】看到一个可以网页解析登录二维码就可以直接使用的，baiduwp是否可以跟进升级迭代？

### ISSUE THREAD

**Issue by 81354791** [yuantuo666/baiduwp-php#220]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/50453959/193234811-bc4bce1c-9a96-4102-ab59-9c7b18e72b1c.png">
测试网址：https://go.top25点top/go?key=mianfeivip#

**Comment by yuantuo666** [comment]
你所提到的功能是登录百度网盘账号，与项目无关，将不会考虑在本项目中添加
