### ISSUE TITLE
【BUG 反馈】无法解析文件或文件夹

### ISSUE THREAD

**Issue by Acker777** [yuantuo666/baiduwp-php#222]
## 描述 Bug
输入地址解析后页面空白

## 如何复现此 Bug
复现此 Bug 的步骤:
和往常一样打开网站，发现需要更新，完后就这样了

## 截图
![image](https://user-images.githubusercontent.com/44842303/195760773-89ab7657-0dbf-44d3-ad6e-1872d3bf1532.png)

## 您的设备信息
 - 服务器系统信息：Linux VM-8-9-ubuntu 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - 服务器 PHP 版本：PHP 7.0.33
 - 访问项目的浏览器版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

## 补充信息
应该不是BDUSS或STOKEN的问题，后台显示是正常的
![image](https://user-images.githubusercontent.com/44842303/195761777-0752a168-9f30-473e-9ec1-d204c904a96b.png)

**Comment by yuantuo666** [comment]
是否完整更新了最新版本，正常应该不会出现这种情况
如果不是版本问题，请将调试模式开启（config.php 中的 DEBUG 参数改为 true）后，将错误信息截图发至此issue

**Comment by Acker777** [comment]
![image](https://user-images.githubusercontent.com/44842303/197559411-19a8fc8c-9e4f-483b-8c91-150f44c8eb15.png)

**Comment by Acker777** [comment]
![image](https://user-images.githubusercontent.com/44842303/197562938-aa370a56-187d-4672-9d6d-fa79d53f9475.png)
版号好像没更新

**Comment by yuantuo666** [comment]
感谢反馈，已更新版本号
