### ISSUE TITLE
【寻求帮助】解析出现 [微信API] 解析错误 错误代码 999

### ISSUE THREAD

**Issue by pyq8** [yuantuo666/baiduwp-php#223]
帐号什么的都正常，安装也正常，用的2.2.3版本【最新的】
但一解析，就是 [微信API] 解析错误，让打开调式模式，具体不知道怎么开。
![image](https://user-images.githubusercontent.com/115851554/195963023-b4a81925-8591-4f62-a939-23c92d030a97.png)
![image](https://user-images.githubusercontent.com/115851554/195963046-0722fcb0-5e11-400a-84b9-fb0e0bcc7c66.png)

**Comment by qingqiuai** [comment]
![image](https://user-images.githubusercontent.com/113910218/196876551-8699b0b8-d819-44e5-8518-4d9e1563fb41.png)
我的也是这样子

**Comment by yuantuo666** [comment]
999报错应该是请求失败，重试应该可以解决

**Comment by yuantuo666** [comment]
打开调试模式方法：
编辑 `config.php` 文件中 `const DEBUG = false;` 为 `const DEBUG = true;`

**Comment by yuantuo666** [comment]
> ![image](https://user-images.githubusercontent.com/113910218/196876551-8699b0b8-d819-44e5-8518-4d9e1563fb41.png) 我的也是这样子 最新版2.2.3

已修复此问题，请更新至 2.2.5 版本

**Comment by lc6464** [comment]
如有更多问题可重开议题。
