### ISSUE TITLE
【BUG 反馈】最新2.2.3版，无法解析大文件，错误代码9019

### ISSUE THREAD

**Issue by Turing-China** [yuantuo666/baiduwp-php#224]
![image](https://user-images.githubusercontent.com/107291340/196907243-257a616b-951c-490e-bd45-0c5f47a0e42b.png)

**Comment by diannaodiy** [comment]
没有解决吗

**Comment by yuantuo666** [comment]
最新版本已经解决此问题 https://github.com/yuantuo666/baiduwp-php/releases/tag/v2.2.4.1
