### ISSUE TITLE
【BUG 反馈】解析分享链接抱错9019

### ISSUE THREAD

**Issue by Turing-China** [yuantuo666/baiduwp-php#225]
使用最新版本
2.2.4.1

下载第一个文件报9019
下载第二个文件有时候会成功

![image](https://user-images.githubusercontent.com/107291340/199455750-7133bd8b-80d5-4058-99df-4251827926d8.png)

分享链接
https://pan.baidu.com/share/init?surl=odIzG8kNYQq3wHadfOwrtQ
分享密码
gta6

**Comment by ShiAhaoM** [comment]
多试几次.第一个第二个都有这个问题.我点个三四次都成功了

**Comment by Turing-China** [comment]
> 多试几次.第一个第二个都有这个问题.我点个三四次都成功了

不行的

**Comment by bzy-080408** [comment]
是不是百度换服务器了

> 多试几次.第一个第二个都有这个问题.我点个三四次都成功了

不行没用
链接https://pan.baidu.com/s/1nawfwOcwbYLR6pDRoc22nQ
提取码10eq
是不是百度换服务器时候改API了

**Comment by diannaodiy** [comment]
是不是需要等更新了

**Comment by Java-Zhe** [comment]
这个问题又复现了

**Comment by Turing-China** [comment]
> 这个问题又复现了

自己已经解决了，小问题

**Comment by diannaodiy** [comment]
> 

求方法

**Comment by tianxuanzhizi** [comment]
同求

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/200150632-0992d120-5da0-4741-876a-5ffc64c86ea7.png)
![image](https://user-images.githubusercontent.com/44130602/200150636-a3d1bdf0-171e-4db1-9797-2e96dafe9925.png)
11月06日 10:04 测试没有问题

**Comment by aLIEz-xue** [comment]
> ![image](https://user-images.githubusercontent.com/44130602/200150632-0992d120-5da0-4741-876a-5ffc64c86ea7.png)
> ![image](https://user-images.githubusercontent.com/44130602/200150636-a3d1bdf0-171e-4db1-9797-2e96dafe9925.png)
> 11月06日 10:04 v2.2.4.1 测试没有问题

测试了，确实没问题了

**Comment by wildwolfkisskill** [comment]
提交链接和提取码下面的密码是什么密码？

**Comment by yybxrsp258** [comment]
> 多试几次.第一个第二个都有这个问题.我点个三四次都成功了

![image](https://user-images.githubusercontent.com/65845535/202619145-abcf66b1-878c-4728-a583-0826faa91122.png)

**Comment by yybxrsp258** [comment]
我也出现这个问题了，求解决办法

**Comment by yybxrsp258** [comment]
> > 多试几次.第一个第二个都有这个问题.我点个三四次都成功了
> 
> ![image](https://user-images.githubusercontent.com/65845535/202619145-abcf66b1-878c-4728-a583-0826faa91122.png)

版本是2.2.4.1

**Comment by Turing-China** [comment]
>  china.turing@gmail.com

**Comment by yybxrsp258** [comment]
你好，寻求一下9019错误解决办法，付费解答也可

Turing-China ***@***.***> 于2022年11月18日周五 14:54写道：

**Comment by Turing-China** [comment]
> 
已回复

**Comment by diannaodiy** [comment]
> > > 多试几次. 第一个第二个都有这个问题. 我点个三四次都成功了
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/65845535/202619145-abcf66b1-878c-4728-a583-0826faa91122.png)
> 
> 版本是2.2.4.1

你的解决了吗？

**Comment by Turing-China** [comment]
> > > > 多试几次. 第一个第二个都有这个问题. 我点个三四次都成功了
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/65845535/202619145-abcf66b1-878c-4728-a583-0826faa91122.png)
> > 
> > 
> > 版本是2.2.4.1
> 
> 你的解决了吗？

已解决

**Comment by yuantuo666** [comment]
将 `functions.php` 中 `getDlink` 函数的 Cookie 参数[(line 227)](https://github.com/yuantuo666/baiduwp-php/blob/master/functions.php#L227)修改为完整的 Cookie 即可解决此问题
代码将稍后更新

**Comment by yuantuo666** [comment]
已修复此问题，请更新至 2.2.5 版本
