### ISSUE TITLE
无法正常获取文件夹有关信息。

### ISSUE THREAD

**Issue by Hsdipro** [yuantuo666/baiduwp-php#226]
输入链接就会变成这样

我是从旧版本文件覆盖上来的

![image](https://user-images.githubusercontent.com/63788568/201507733-eb9273cb-c0a1-4ae7-9e34-11a9597f9620.png)

**Comment by yuantuo666** [comment]
尝试删除 config.php 文件后重新安装

**Comment by lc6464** [comment]
如有更多问题可重开议题。
