### ISSUE TITLE
【BUG 反馈】2.2.4.1版本出现9019错误

### ISSUE THREAD

**Issue by laoqijun** [yuantuo666/baiduwp-php#227]
日志
$_GET:array(1) {
  ["download"]=>
  string(0) ""
}
$_POST:array(6) {
  ["fs_id"]=>
  string(15) "548808049032267"
  ["time"]=>
  string(10) "1668912826"
  ["sign"]=>
  string(40) "533babf39e4c9623056a98a5712a6ba7957e43ec"
  ["randsk"]=>
  string(44) "J2CHf2G7u+FFVxUc9GN0ZPN62II6BSrwNdyZexZuCzk="
  ["share_id"]=>
  string(11) "55122884699"
  ["uk"]=>
  string(13) "1100657678046"
}
getDlink():array(3) {
  ["errno"]=>
  int(9019)
  ["errmsg"]=>
  string(11) "need verify"
  ["request_id"]=>
  int(8654740566099277337)
}

网址：[mf.网盘.top](https://mf.xn--vzyr4p.top/)
复现方法：正常解析即可
![image](https://user-images.githubusercontent.com/32598564/202880522-c2f27c7c-f0cd-427b-8fa6-025428a6da00.png)

**Comment by diannaodiy** [comment]
等更新吧

**Comment by richiecole** [comment]
等更新吧`

**Comment by Turing-China** [comment]
**完美解决**

![微信图片_20221123171713](https://user-images.githubusercontent.com/107291340/203509949-4f890448-f026-47b1-b8f0-f781b3c866d0.png)

**Comment by wec246810** [comment]
> **完美解决**
> 
> ![微信图片_20221123171713](https://user-images.githubusercontent.com/107291340/203509949-4f890448-f026-47b1-b8f0-f781b3c866d0.png)
用的客户端有啥意思，都知道的方法

**Comment by Turing-China** [comment]
> > **完美解决**
> > ![微信图片_20221123171713](https://user-images.githubusercontent.com/107291340/203509949-4f890448-f026-47b1-b8f0-f781b3c866d0.png)
> > 用的客户端有啥意思，都知道的方法

这是我自己写的客户端，这个字母我只能说10个字符搞定

**Comment by Turing-China** [comment]
> 听起来好牛~~~~~~~求你自用的客户端~~&nbsp; &nbsp; ***@***.***&nbsp; 一江烟花 ***@***.*** 清华园中学 教师 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年11月23日(星期三) 晚上9:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [yuantuo666/baiduwp-php] 【BUG 反馈】2.2.4.1版本出现9019错误 (Issue #227) 完美解决 用的客户端有啥意思，都知道的方法 这是我自己写的客户端，这个字母我只能说10个字符搞定 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

china.turing@gmail.com

**Comment by jasonpan168** [comment]
2022年11月23日，测试显示9019错误代码，不知道啥情况，还有就是网站特卡，基本无法访问，刚安装正常，安装一会后卡的要飞起，服务器4核8G，

**Comment by Turing-China** [comment]
> 2022年11月23日，测试显示9019错误代码，不知道啥情况，还有就是网站特卡，基本无法访问，刚安装正常，安装一会后卡的要飞起，服务器4核8G，

帮修复9019 china.turing@gmail.com

**Comment by yuantuo666** [comment]
将 `functions.php` 中 `getDlink` 函数的 Cookie 参数[(line 227)](https://github.com/yuantuo666/baiduwp-php/blob/master/functions.php#L227)修改为完整的 Cookie 即可解决此问题
代码将稍后更新

**Comment by richiecole** [comment]
嘿嘿，谢谢啦，等待更新代码~~
&nbsp;


一江烟花
***@***.***

清华园中学
教师


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月24日(星期四) 上午9:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 【BUG 反馈】2.2.4.1版本出现9019错误 (Issue #227)





 
将 functions.php 中 getDlink 函数的 Cookie 参数(line 227)修改为完整的 Cookie 即可解决此问题
 代码将稍后更新

**Comment by jasonpan168** [comment]
> 将`functions.php`中`getDlink`函数的Cookie 参数[(line 227)](https://github.com/yuantuo666/baiduwp-php/blob/master/functions.php#L227)修改为完整的Cookie 即可解决此问题代号码后 更新

![微信截图_20221124100138](https://user-images.githubusercontent.com/104338733/203677531-d4871b35-748b-4446-854a-130e1ab77862.png)
![微信截图_20221124100109](https://user-images.githubusercontent.com/104338733/203677533-23dec057-880e-45d7-a717-d320f7230ee8.png)

改了227行，添加了cookie，点击下载后没有任何提示

**Comment by yuantuo666** [comment]
> > 将`functions.php`中`getDlink`函数的Cookie 参数[(line 227)](https://github.com/yuantuo666/baiduwp-php/blob/master/functions.php#L227)修改为完整的Cookie 即可解决此问题代号码后 更新
> 
> ![微信截图_20221124100138](https://user-images.githubusercontent.com/104338733/203677531-d4871b35-748b-4446-854a-130e1ab77862.png) ![微信截图_20221124100109](https://user-images.githubusercontent.com/104338733/203677533-23dec057-880e-45d7-a717-d320f7230ee8.png)
> 
> 改了227行，添加了cookie，点击下载后没有任何提示

需要设置抓包获取的完整cookie，而且不能有回车

**Comment by yuantuo666** [comment]
已修复此问题，请更新至 2.2.5 版本

**Comment by laoqijun** [comment]
OK

**Comment by laoqijun** [comment]
> 已修复此问题，请更新至 2.2.5 版本

OK
