### ISSUE TITLE
【BUG 反馈】错误代码9019

### ISSUE THREAD

**Issue by guoluyuan** [yuantuo666/baiduwp-php#228]
已经填写普通账号完整cookie，还是解析文件下载链接时提示9019

**Comment by ShiAhaoM** [comment]
虽然我不知道代码9091是什么意思
如果你没打错字的话.我想你这问题在于用错了账号吧。
普通账号只是列出来文件
SVIP才是解析地址

**Comment by yuantuo666** [comment]
需要通过抓包获取完整cookie，详细方法见安装页面

获取cookie后不要退出登录，否则账号信息会失效
如果仍然无法使用，请尝试使用浏览器 隐私/无痕模式（在edge中为 InPrivate 窗口） 登录账号抓包，获取cookie后直接关闭窗口

正确配置完整cookie是可以使用的

**Comment by yuantuo666** [comment]
参考此网页获取完整 cookie 并配置即可正常使用
https://blog.imwcr.cn/2022/11/24/%e5%a6%82%e4%bd%95%e6%8a%93%e5%8c%85%e8%8e%b7%e5%8f%96%e7%99%be%e5%ba%a6%e7%bd%91%e7%9b%98%e7%bd%91%e9%a1%b5%e7%89%88%e5%ae%8c%e6%95%b4-cookie/
