### ISSUE TITLE
【寻求帮助】2.2.5普通账号限速问题

### ISSUE THREAD

**Issue by richiecole** [yuantuo666/baiduwp-php#229]
## 描述问题
2.2.5限速，从我几天前装好网页的时候，就一直限速。
![QQ截图20221201174511](https://user-images.githubusercontent.com/79833785/205021626-8294446c-6a01-49ef-ae1d-6930819b916e.jpg)

**Comment by richiecole** [comment]
哦哦。。。。。。
&nbsp;


一江烟花
***@***.***

清华园中学
教师


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月2日(星期五) 下午4:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 【寻求帮助】2.2.5普通账号限速问题 (Issue #229)





 
普通账号没有效果的家人.你有没有仔细看文档
 此项目的原理是利用SVIP也就是超级会员解析直链地址通过伪造UA满速下载
 普通账号只是解析你分享出来有什么文件而已

**Comment by yuantuo666** [comment]
> 普通账号没有效果的家人.你有没有仔细看文档 此项目的原理是利用SVIP也就是超级会员解析直链地址通过伪造UA满速下载 普通账号只是解析你分享出来有什么文件而已

这个解释是正确的
如有问题请再次打开此议题
