### ISSUE TITLE
关于php版的stoken和bduss一点点建议（解决svip的stoken时限问题）

### ISSUE THREAD

**Issue by Ecalose** [yuantuo666/baiduwp-php#23]
我发现js版可以实现类似pd的分享下载功能，他仅需svip的bduss，stoken可以填自己的
“const BDUSS = '' //**INPUT YOUR BDUSS HERE**
const STOKEN = '' //**INPUT YOUR STOKEN HERE**
const SVIPBDUSS = '' //**INPUT YOUR SVIP BDUSS HERE**
const INDEX_URL = '' // Input your index url here“
而bduss存活时间要比stoken长的多，若php版能实现该功能，则可以只需更换普通账号的bduss和stoken就行，无需后续获取svip的stoken

**Comment by yuantuo666** [comment]
1.4.2版已经增加此功能

**Comment by Ecalose** [comment]
> 1.4.2版已经增加此功能

老哥稳健
