### ISSUE TITLE
能否设置特殊权限【建议】

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#231]
## 描述建议
就是个别客户设置特殊权限，比如一般用户每天只能解析20个，特殊用户每天可以解析100个，分开设置。特殊客户可以不需要登录根据IP区分就行了。或者是登录用户是特殊用户，不登录用户属于体验用户。只是建议而已。
## 此建议将如何工作
工作步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 相关的技术
如果您有能力，您可以在此提供一些技术帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 补充信息
您可以在这里输入其他有关此建议的信息。

**Comment by yuantuo666** [comment]
暂不考虑为本项目增加此功能。但你可以对本项目进行二次开发，遵循 MIT 协议保留作者版权即可，引起的任何问题将与作者无关，详情参考 MIT 协议。
