### ISSUE TITLE
已经按着教程做了

### ISSUE THREAD

**Issue by ss20934091** [yuantuo666/baiduwp-php#233]
![Screenshot_20230128_145937_idm internet download manager plus](https://user-images.githubusercontent.com/123817994/215270881-28dbbecf-1f26-4e66-b976-d66fe193c085.jpg)
怎么办啊

**Comment by yuantuo666** [comment]
没有见过这个错误代码
打开调试模式后，把错误信息截图下
打开调试模式方法：修改config.php文件中 const DEBUG = false; 将 false 改为 true

**Comment by yuantuo666** [comment]
如果你不是站长，那应该是分享链接有问题，重新分享下试试。

**Comment by yuantuo666** [comment]
尝试重新分享，如果仍然无法下载，可能是文件存在问题。请提供文件相关分享链接。

**Comment by yuantuo666** [comment]
如有问题请再打开此议题
