### ISSUE TITLE
链接错误 无法正常获取文件夹有关信息。

### ISSUE THREAD

**Issue by csrase** [yuantuo666/baiduwp-php#236]
链接错误 
无法正常获取文件夹有关信息。

## 截图
![22](https://user-images.githubusercontent.com/121145065/218041848-b622f697-cd17-4c4f-9bf3-1a0cfdbe9ec7.png)

## 您的设备信息
 - 服务器系统信息：Ubuntu 20.04 LTS x86_64
 - 服务器 PHP 版本：7.4

## 补充信息
版本是v2.2.5

**Comment by yuantuo666** [comment]
这个是获取 sign 出错，尝试重试 或者 修改 SVIP_BDUSS 和 SVIP_STOKEN

**Comment by csrase** [comment]
已解决
