### ISSUE TITLE
【建议】能不能提供api文档

### ISSUE THREAD

**Issue by haig233** [yuantuo666/baiduwp-php#237]
## 描述建议
看见api.php里面提供了一些api，有没有api文档提供一下

**Comment by yuantuo666** [comment]
本项目没有对外公开的api 你指的是什么api文档

**Comment by yuantuo666** [comment]
目前项目还没有完成前后端分离，也就是说，api.php中的部分接口都是功能残缺的，所以暂时没有api文档

**Comment by haig233** [comment]
好吧，那后续再说

**Comment by yuantuo666** [comment]
`3.0.0` 版本已将 API 部分分离并提供 [API 文档](https://github.com/yuantuo666/baiduwp-php/blob/master/docs/API.md)
