### ISSUE TITLE
IP下载数量限制好像有问题【BUG 反馈】

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#238]
## 描述 Bug
我IP下载限制是每个IP15次。但是我数了下，在IPV6下有的IP几十次甚至上百次。导致服务器IP直接被封。不知是不是IP限制对ipv6无效？或者能不能增强一下限制手段，谢谢了。

## 如何复现此 Bug
复现此 Bug 的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 期望
对您所期望的情况做一个简单描述。

## 截图
![image](https://user-images.githubusercontent.com/114161089/218481767-319cd765-d80b-4c9a-82d3-08b887b2158e.png)
![image](https://user-images.githubusercontent.com/114161089/218482082-5fd72475-adb5-4117-98d3-7d49ae0b64b4.png)

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by diannaodiy** [comment]
<img width="582" alt="微信截图_20230213222242" src="https://user-images.githubusercontent.com/114161089/218483849-e06b2889-1826-40eb-aba3-4433ef2e7c56.png">
这个是IPV6的数据

**Comment by yuantuo666** [comment]
如果要进行次数限制，请关闭网站IPv6功能，因为单个用户很容易拥有多个IPv6，不能作为判断的标准。
参考文章: [谁不想要 2^64 个 IP 的代理池 ？](https://zu1k.com/posts/tutorials/http-proxy-ipv6-pool/)
