### ISSUE TITLE
【寻求帮助】我想了解一下原理

### ISSUE THREAD

**Issue by Java-Zhe** [yuantuo666/baiduwp-php#239]
我对这个项目十分感兴趣，但奈何不懂PHP，自己搭建几次失败率也很高，偶尔搭建成功后过两天就凉了，我想了解一下该项目的实现原理，是怎么获取到高速下载链接的，想用Java语言实现一下，README.md文件中底部的SpringBoot版原作者已经删了，PHP代码读不懂，还请赐教

**Comment by yuantuo666** [comment]
这个问题我不能回答，请自行查看 PHP 代码
