### ISSUE TITLE
无法正常下载 anti-hotlinking

### ISSUE THREAD

**Issue by yuanzhidao** [yuantuo666/baiduwp-php#24]
设置好UA之后 点击下载链接
会跳转到http://www.baidupcs.com/403.html
显示
{ "error_code":31326, "error_msg":"anti hotlinking" }

用了官方国内节点也是这样

**Comment by yuantuo666** [comment]
右键复制 在IDM中新建链接

**Comment by yuanzhidao** [comment]
好的谢谢
