### ISSUE TITLE
【寻求帮助】提示无法正常获取文件夹

### ISSUE THREAD

**Issue by SRY-CTB** [yuantuo666/baiduwp-php#240]
## 描述 Bug
安装后，提示无法正常获取文件夹

## 如何复现此 Bug
复现此 Bug 的步骤:
我重新安装了网站，在不同的服务器上，出现了相同的问题

## 期望
对您所期望的情况做一个简单描述。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息
 - windows 2012 和乌班图8 都安装了宝塔面板
 - 服务器 PHP 版本  一样的7.1

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by yuantuo666** [comment]
检查 curl 及其 PHP 插件是否正常，本地是否能连接百度网盘服务器

**Comment by xkatld** [comment]
解决了么兄弟 我这也报这个了

**Comment by zhx47** [comment]
> 检查 curl 及其 PHP 插件是否正常，本地是否能连接百度网盘服务器

![image](https://user-images.githubusercontent.com/61264955/222073679-c4302d7c-7b11-4bfb-a770-a3ebf652d210.png)
你好，我这里应该是获取到了文件信息，但是依旧提示解析有问题

以下是完整的调试信息，辛苦作者帮忙看看
$_GET:array(0) {
}
$_POST:array(2) {
  ["surl"]=>
  string(23) "1EuvUu40fYhae5Sab5u5ZUA"
  ["pwd"]=>
  string(4) "9hjt"
}
GetList():array(11) {
  ["errno"]=>
  int(0)
  ["request_id"]=>
  int(230472159038078157)
  ["errtype"]=>
  int(0)
  ["server_time"]=>
  int(1677655943)
  ["data"]=>
  array(20) {
    ["title"]=>
    string(31) "/杂项/powerdesigner_72386.zip"
    ["expiredType"]=>
    int(1)
    ["link_ctime"]=>
    int(1677655701)
    ["fileNums"]=>
    int(1)
    ["has_more"]=>
    bool(false)
    ["list"]=>
    array(1) {
      [0]=>
      array(12) {
        ["category"]=>
        string(1) "6"
        ["fs_id"]=>
        string(15) "659747018028396"
        ["isdir"]=>
        string(1) "0"
        ["local_ctime"]=>
        string(10) "1590462939"
        ["local_mtime"]=>
        string(10) "1590463019"
        ["md5"]=>
        string(32) "12615bb69j5cbbe6947a9c58bbd10de6"
        ["path"]=>
        string(31) "/杂项/powerdesigner_72386.zip"
        ["server_ctime"]=>
        string(10) "1590463144"
        ["server_filename"]=>
        string(23) "powerdesigner_72386.zip"
        ["server_mtime"]=>
        string(10) "1666054020"
        ["size"]=>
        string(9) "645620654"
        ["dlink"]=>
        string(335) "http://d.pcs.baidu.com/file/12615bb69j5cbbe6947a9c58bbd10de6?fid=3107864580-250528-659747018028396&dstime=1677655943&rt=sh&sign=FDtAERJoKy-DCb740ccc5511e5e8fedcff06b081203-mknKrs2pnKRXiWb%2Fm71SNwkA6Ag%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=230472159038078157&dp-callid=0&r=538999351&clienttype=25&vuk=3107864580&file_type=0&sh=1"
      }
    }
    ["user"]=>
    array(1) {
      ["avatar"]=>
      string(85) "https://himg.bdimg.com/sys/portrait/item/public.1.9d4226aa.7bCFn0oj96K0lHBt5Qg1rg.jpg"
    }
    ["uname"]=>
    string(6) "张*47"
    ["uk"]=>
    int(3107864580)
    ["shareid"]=>
    int(46857041369)
    ["wx_name"]=>
    string(6) "张*47"
    ["wx_headurl"]=>
    string(85) "https://himg.bdimg.com/sys/portrait/item/public.1.9d4226aa.7bCFn0oj96K0lHBt5Qg1rg.jpg"
    ["hitrisk"]=>
    int(0)
    ["appeal_status"]=>
    int(0)
    ["sharetype"]=>
    int(0)
    ["view_visited"]=>
    int(0)
    ["view_limit"]=>
    int(0)
    ["expired_type"]=>
    int(1)
    ["seckey"]=>
    string(44) "v5HHOckFSORPM4TC8MTC87zs-V-qZnqjQVq35iykVZc~"
    ["hit_ogc"]=>
    bool(false)
  }
  ["cfrom_id"]=>
  int(0)
  ["is_zombie"]=>
  int(0)
  ["vip_point"]=>
  int(13390)
  ["vip_level"]=>
  int(4)
  ["svip10_id"]=>
  string(0) ""
  ["vip_type"]=>
  int(2)
}

**Comment by zhx47** [comment]
> 检查 curl 及其 PHP 插件是否正常，本地是否能连接百度网盘服务器

找到原因了，因为安装的时候未配置会员账号，后续再设置页面补充后无法解决，在config.php中重新配置后恢复正常

**Comment by yuantuo666** [comment]
账号配置问题，请检查Cookie、BDUSS、STOKEN、SVIP_BDUSS、SVIP_STOKEN设置

**Comment by zhx47** [comment]
> > 账号配置问题，请检查Cookie、BDUSS、STOKEN、SVIP_BDUSS、SVIP_STOKEN设置
> 
> 不设置SVIP_BDUSS、SVIP_STOKEN 是没办法使用吗。。

和普通账号设置成同一个吧

**Comment by HelplessMan** [comment]
> > > 账号配置问题，请检查Cookie、BDUSS、STOKEN、SVIP_BDUSS、SVIP_STOKEN设置
> > 
> > 
> > 不设置SVIP_BDUSS、SVIP_STOKEN 是没办法使用吗。。
> 
> 和普通账号设置成同一个吧

![image](https://user-images.githubusercontent.com/9101275/224234329-71ae991d-30d7-464a-b439-3bcf09385ec4.png)
可以了。识别到文件了，但是我在点击下载以后。控制台出现这个错误: `VM875:1 Uncaught ReferenceError: confirmdl is not defined`
