### ISSUE TITLE
【建议】可否自动检测浏览器ua

### ISSUE THREAD

**Issue by laoqijun** [yuantuo666/baiduwp-php#241]
检测浏览器的ua后自动使用浏览器的ua进行解析
能简化下载和在线观看视频的流程

**Comment by Pandaft** [comment]
试过，可行，但不完全可行，并不是所有的 UA 都能进行解析。

**Comment by laoqijun** [comment]
> 试过，可行，但不完全可行，并不是所有的 UA 都能进行解析。

这个确实。有些ua会出错，可以考虑检测特殊字符后用另一种方式解析，但这样容易缩减账号寿命

**Comment by yuantuo666** [comment]
不支持，百度限制了浏览器UA
