### ISSUE TITLE
【BUG 反馈】

### ISSUE THREAD

**Issue by laoqijun** [yuantuo666/baiduwp-php#242]
## 描述 Bug
推送到aria2的时候提示22 HTTP返回头无法识别

## 如何复现此 Bug
复现此 Bug 的步骤:
1. 修改functions.js文件里的user-agent参数为wssb
2. 正常解析并推送即可

## 截图
![1676971129528_print_screen_take_photo](https://user-images.githubusercontent.com/32598564/220302185-38f3c360-7645-4a3a-af6b-c6e268cbe747.png)

## 补充信息
网站：https://mf.网盘.top

**Comment by yuantuo666** [comment]
链接过期，删除数据库记录后重新解析
或设置的UA存在问题
