### ISSUE TITLE
【BUG 反馈】can't download file

### ISSUE THREAD

**Issue by kedaitinh12** [yuantuo666/baiduwp-php#243]
I was set User-Agent：netdisk to IDM + chrome but download still failed
https://pan.baidu.com/s/1xdMQ5syYcS65iqGgx6qP9Q pass:97vd

**Comment by yuantuo666** [comment]
Demo site was closed currently, please try again when the demo site open again.

**Comment by kedaitinh12** [comment]
Ok, thanks
