### ISSUE TITLE
【寻求帮助】一直提示升级2.2.6

### ISSUE THREAD

**Issue by lukemin** [yuantuo666/baiduwp-php#244]
但是最新版的只有2.2.5

**Comment by yuantuo666** [comment]
能否将提示升级提示截图发出来，同时加上访问下面这个链接的截图（将HOST改为你自己的服务器地址）
https://HOST/api.php?m=CheckUpdate

**Comment by lukemin** [comment]
{"code":2,"version":"2.2.5","PreRelease":false,"file_url":"","page_url":"https://github.com/yuantuo666/baiduwp-php/releases/tag/v2.2.5","info":["Try-Get-Version-Include-PreRelease","Enforce-Check","Include-PreRelease","Invalid-Version"],"now_version":"2.2.6"}

**Comment by lc6464** [comment]
你部署的实例版本有问题，不应是2.2.6，如果你是直接 clone 项目并部署的，建议你使用最新的发行版。
如果确认要使用 master 分支版本，你可以手动在各个 PHP 文件中查找版本号并改为2.2.5以临时解决此问题。

**Comment by yuantuo666** [comment]
master分支是还未发布的2.2.6版本，建议使用release的版本：https://github.com/yuantuo666/baiduwp-php/releases/tag/v2.2.5
