### ISSUE TITLE
微信API

### ISSUE THREAD

**Issue by m1371339094** [yuantuo666/baiduwp-php#245]
An error happened.
To know more about it, you can translate the information following.
Raw Title:[微信API] 解析错误
Raw Message:未知错误代码:5
请打开调试模式，并将错误信息以议题的形式提交到[GitHub项目](https://github.com/yuantuo666/baiduwp-php/issues)。

发生这种事怎么办？

**Comment by Everlastinglove21** [comment]
未知错误代码:999
请打开调试模式，并将错误信息以议题的形式提交到[GitHub项目](https://github.com/yuantuo666/baiduwp-php/issues)。
我也是

**Comment by Bobo-Jia** [comment]
同样的问题

**Comment by yuantuo666** [comment]
请打开调试模式，即修改config.php中的DEBUG项为true
再次进入后截图调试日志提交到此议题

**Comment by yuantuo666** [comment]
请安装最新版本后再次尝试，并将错误信息截图发至此issue
https://github.com/yuantuo666/baiduwp-php/releases/latest

**Comment by yuantuo666** [comment]
不存在此分享链接或提取码错误，重新分享连接即可
