### ISSUE TITLE
999【BUG 反馈】

### ISSUE THREAD

**Issue by xxslsp** [yuantuo666/baiduwp-php#247]
## 描述 Bug
请在此填入对此 Bug 清晰准确的描述。

## 如何复现此 Bug
复现此 Bug 的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 期望
对您所期望的情况做一个简单描述。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by yuantuo666** [comment]
请提供更多信息

**Comment by yuantuo666** [comment]
请安装最新版本后再次尝试，并将错误信息截图发至此issue

**Comment by yuantuo666** [comment]
如仍有问题请补充并重新打开此议题
