### ISSUE TITLE
【BUG 反馈】版本2.2.6，错误代码9019

### ISSUE THREAD

**Issue by wakaka123wakaka** [yuantuo666/baiduwp-php#248]
## 描述 Bug
使用最新的2.2.6源码安装，普通账号和会员账号都是使用的同一个账号，可以正常解析，但是下载会报错9019

## 期望
对您所期望的情况做一个简单描述。

## 截图
![image](https://user-images.githubusercontent.com/34087959/224106545-f7b0b94e-d6de-4fe6-b815-a40bf4e2cba3.png)

![image](https://user-images.githubusercontent.com/34087959/224104719-392dc4a9-4ae4-4d83-a3fd-3ecf04f54429.png)
![image](https://user-images.githubusercontent.com/34087959/224104843-ad467c4f-b3f5-4366-956d-06260167cce7.png)

## 您的设备信息
 - 服务器系统信息Linux VM-0-15-debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
 - 服务器 PHP 版本php7.2
 - 访问项目的浏览器版本（Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by yuantuo666** [comment]
完整的Cookie是从网页版抓包获取的吗
也有人反馈说Mac抓的Cookie用不了

我明天再看下，这个报错应该和Cookie有关

**Comment by wakaka123wakaka** [comment]
我是通过mac版本的百度网盘客户端设置代理抓的包

**Comment by tpjaord1983** [comment]
问题一样存在。。

**Comment by wakaka123wakaka** [comment]
> 问题一样存在。。

现在有哪个版本是可以正常使用的吗

**Comment by Crystron39** [comment]
一样的问题（）

**Comment by tpjaord1983** [comment]
作者还是不要升级了 不升级还能用，升级了反而用不了了 
好伤心啊

**Comment by yuantuo666** [comment]
9019是普通账号的Cookie问题
测试使用 Windows Chrome 抓包网页版获取的 Cookie 没有问题

**Comment by yuantuo666** [comment]
> 作者还是不要升级了 不升级还能用，升级了反而用不了了 好伤心啊

新版本这部分代码也没有修改的，可能是我更新的时间和百度限制账号的时间重合了

**Comment by Crystron39** [comment]
> > 作者还是不要升级了 不升级还能用，升级了反而用不了了 好伤心啊
> 
> 新版本这部分代码也没有修改的，可能是我更新时，百度也限制了一批账号 再说了，旧版本也没有限制使用，你仍然可以使用旧版本：https://github.com/yuantuo666/baiduwp-php/releases


老哥我试了下,确实是我自己的问题，不好意思哈兄弟（）
cookie没复制全，后来拿2.2.5安装成功的数据再次安装2.2.6的时候回显0无法修改来着，刚刚试了下删干净重新部署就可以了。


总之在使用2.2.6的时候是没有问题的


[tpjaord1983](https://github.com/tpjaord1983)这哥们真会说话，吃饭会噎死你咋还吃呢（）

**Comment by wakaka123wakaka** [comment]
> 9019是普通账号的Cookie问题
> 
> 测试使用 Windows Chrome 抓包网页版获取的 Cookie 没有问题

我的普通账号和会员账号是一个，我是用的mac抓包的

**Comment by yuantuo666** [comment]
> > 9019是普通账号的Cookie问题
> > 测试使用 Windows Chrome 抓包网页版获取的 Cookie 没有问题
> 
> 我的普通账号和会员账号是一个，我是用的mac抓包的

用Chrome的无痕模式登录再抓包试试，抓完包之后直接关闭无痕窗口就行了
找请求host是pan.baidu.com的，然后复制完整的Cookie
如果还是不行可能是账号被封禁了，那就没办法了

**Comment by yuantuo666** [comment]
Cookie 配置错误 或 账号封禁会出现 8001 9013 9019 报错
2.2.7版本已添加对应提示，按照提示更换 Cookie 即可解决

**Comment by yuantuo666** [comment]
9019 错误为设置的账号 Cookie 或 BDUSS + STOKEN 有问题

参加以下解决方案：
检查下账号状态，看能不能网页版打开分享链接里的文件夹：
1. 打不开的话就是账号被封禁了
2. 如果可以打开的话，就是Cookie 或 BDUSS + STOKEN 失效了，重新抓包获取并设置就行

**Comment by sai875** [comment]
现在我也遇到了这个问题，9019错误，重新抓包过三次了，没用

**Comment by yuantuo666** [comment]
> 

有问题的截图吗，可以的话把你抓包获取到的 Cookie 发送给我看下，我的邮箱是 yuantuo666@gmail.com
抓包的时候找请求地址是 https://pan.baidu.com/api/quota 开头的，不然获取到的可能是不完整的 Cookie

**Comment by yuantuo666** [comment]
参考教程抓包 https://blog.imwcr.cn/2022/11/24/%e5%a6%82%e4%bd%95%e6%8a%93%e5%8c%85%e8%8e%b7%e5%8f%96%e7%99%be%e5%ba%a6%e7%bd%91%e7%9b%98%e7%bd%91%e9%a1%b5%e7%89%88%e5%ae%8c%e6%95%b4-cookie/
我这边测试只要是正常的账号都是可以使用的

**Comment by sai875** [comment]
> 



> > 现在我也遇到了这个问题，9019错误，重新抓包过三次了，没用
> 
> 有问题的截图吗，可以的话把你抓包获取到的 Cookie 发送给我看下，我的邮箱是 [yuantuo666@gmail.com](mailto:yuantuo666@gmail.com) 抓包的时候找请求地址是 https://pan.baidu.com/api/quota 开头的，不然获取到的可能是不完整的 Cookie

请求地址不是
https://pan.baidu.com/disk/main吗？

**Comment by sai875** [comment]
> > 现在我也遇到了这个问题，9019错误，重新抓包过三次了，没用
> 
> 有问题的截图吗，可以的话把你抓包获取到的 Cookie 发送给我看下，我的邮箱是 [yuantuo666@gmail.com](mailto:yuantuo666@gmail.com) 抓包的时候找请求地址是 https://pan.baidu.com/api/quota 开头的，不然获取到的可能是不完整的 Cookie

发给你了

**Comment by yuantuo666** [comment]
> > > 现在我也遇到了这个问题，9019错误，重新抓包过三次了，没用
> > 
> > 
> > 有问题的截图吗，可以的话把你抓包获取到的 Cookie 发送给我看下，我的邮箱是 [yuantuo666@gmail.com](mailto:yuantuo666@gmail.com) 抓包的时候找请求地址是 https://pan.baidu.com/api/quota 开头的，不然获取到的可能是不完整的 Cookie
> 
> 发给你了

账号已经被限制了，更换其他账号试试吧

**Comment by sai875** [comment]
> 

请问如何看账号是否被限制？

**Comment by yuantuo666** [comment]
> > 
> 
> 请问如何看账号是否被限制？

9019 错误可能是 Cookie 失效，也有可能是被限制。因为 Cookie 是有效的，所以是被限制了。

**Comment by sai875** [comment]
> > > 
> > 
> > 
> > 请问如何看账号是否被限制？
> 
> 9019错误可能是Cookie失效，也有可能是被限制了。因为Cookie是有效的，所以是被限制了。

那除了换账号还有别的办法吗？

**Comment by yuantuo666** [comment]
普通账号 Cookie 使用自己的账号就可以了，会员账号 BDUSS 才使用可能会黑号的。正常使用普通账号 Cookie 不会失效/限制。

**Comment by sai875** [comment]
> 

好吧

**Comment by sai875** [comment]
> 普通账号Cookie 使用自己的账号就可以了，会员账号BDUSS 才使用可能会黑号的。经常使用普通账号Cookie 不会失效/限制。

我发现，他这个是刷新一次cookie变一次，咋回事？

**Comment by sai875** [comment]
> 普通账号Cookie 使用自己的账号就可以了，会员账号BDUSS 才使用可能会黑号的。经常使用普通账号Cookie 不会失效/限制。

我发现，他这个是刷新一次cookie变一次，咋回事？

**Comment by dan3577** [comment]
![image](https://github.com/yuantuo666/baiduwp-php/assets/52194615/edfcf0bd-a2e5-4749-8046-4f5a4a9c7987)
按照制作者说的，抓https://pan.baidu.com/api/quota的cookie，一直提示上面的内容，，不知道怎么解决，求助~~

**Comment by yuantuo666** [comment]
> > 普通账号Cookie 使用自己的账号就可以了，会员账号BDUSS 才使用可能会黑号的。经常使用普通账号Cookie 不会失效/限制。
> 
> 我发现，他这个是刷新一次cookie变一次，咋回事？

有的参数例如 BAIDUID 是每次刷新都会更新的，BDUSS参数是不会随刷新更新的。

**Comment by eson-sheng** [comment]
我还原回 v3.0.2 就可以使用了 
<img width="488" alt="image" src="https://github.com/yuantuo666/baiduwp-php/assets/20348816/17eb780e-0fe5-408b-8f37-64d9ca45d1ef">

**Comment by yuantuo666** [comment]
> 我还原回 v3.0.2 就可以使用了 <img alt="image" width="488" src="https://user-images.githubusercontent.com/20348816/273506053-17eb780e-0fe5-408b-8f37-64d9ca45d1ef.png">

新 v4.0.0+ 版本需要进入后台设置页面配置普通和 SVIP 帐号的 cookie。不兼容以前老版本的配置文件，需要重新配置。

**Comment by xuexiaokang** [comment]
普通账号在pan.baidu.com看文件的时候总是要输入网页验证码，是不是这个原因导致获取文件下载地址失败，作者能否增加一个输入验证码的地方来解决这个问题呢？谢谢

**Comment by yuantuo666** [comment]
> 普通账号在pan.baidu.com看文件的时候总是要输入网页验证码，是不是这个原因导致获取文件下载地址失败，作者能否增加一个输入验证码的地方来解决这个问题呢？谢谢

并不是验证码的问题，我这边测试，正确设置的普通账号 Cookie 至少可以用一个月。
