### ISSUE TITLE
【建议】可不可以多选文件，然后下载

### ISSUE THREAD

**Issue by SongZihui-sudo** [yuantuo666/baiduwp-php#249]
## 描述建议
可以一次选择多个文件，批量获取其链接下载

## 此建议将如何工作
工作步骤:
1. 可以设置多选框
2. 选择多个文件
3. 加一个按钮批量获取选中的文件链接

**Comment by hktrace** [comment]
这建议不错~~~但是容易导致黑号或者响应时间比较久.

**Comment by yuantuo666** [comment]
这个功能可以实现
但法律原因本项目不会增加此功能

**Comment by SongZihui-sudo** [comment]
哦哦，🌝



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月10日(周五) 下午2:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yuantuo666/baiduwp-php] 【建议】可不可以多选文件，然后下载 (Issue #249)




 
这个功能可以实现
 但法律原因本项目不会增加此功能
