### ISSUE TITLE
解析链接之后，跳转为白板页面

### ISSUE THREAD

**Issue by cchope278** [yuantuo666/baiduwp-php#25]
只要输入分享链接格式正确，提取码随便输，都能跳转，只不过条状之后为白板页面

**Comment by yuantuo666** [comment]
请问使用的是什么版本，方便的话打开debug模式截图一下

**Comment by cchope278** [comment]
我用的是1.4.2最新版，把debug改为TRUE，网站直接跳500。另外，bduss和svip_bduss我是填的一样的。
开启debug后的截图链接：https://user-images.githubusercontent.com/65363889/91651119-2e03b400-eabb-11ea-95b3-8223403e0937.png
网址：52gjy.cn

**Comment by yuantuo666** [comment]
请检查服务器是否安装cURL扩展

**Comment by Penghaiku** [comment]
http://laochuan520.cn/pan/
此网页已经删除作者信息，请添加黑名单

**Comment by yuantuo666** [comment]
> http://laochuan520.cn/pan/
> 此网页已经删除作者信息，请添加黑名单

感谢反馈
