### ISSUE TITLE
无法打开文件获取下载地址【寻求帮助】

### ISSUE THREAD

**Issue by XMahoniX** [yuantuo666/baiduwp-php#251]
## 无法打开文件获取下载地址
原先点击文件，会弹出新标签，并且里面有该文件的下载链接，但是更新后就无法打开文件了，一直点击都没反应
（刚刚重新安装了旧版本，没有上述的问题，可以正常打开下载页面，也可以正常下载）

## 你需要的帮助
解决无法打开下载地址标签的问题，应该是BUG，因为旧版本完全没这个问题

## 截图
框起来的无法点击打开
![QQ截图20230315113305](https://user-images.githubusercontent.com/44489677/225199330-42adedd8-f6dc-43cd-8881-678f93dbfab0.png)
下方三个小文件可以直接通过IDM获取下载链接，使用百分浏览器(因为这个浏览器没有装IDM插件)点击下方三个会显示 `{"error_code":31326,"error_msg":"user is not authorized, hitcode:107","request_id":551354198430479915}`

下面是旧版本正常打开的页面
![QQ截图20230315114507](https://user-images.githubusercontent.com/44489677/225201030-21b61803-674a-4d01-924e-a44fa68ab722.png)

## 您的设备信息
电脑：Win10专业版
PHP：7.3.4
浏览器：edge dev，百分浏览器

## 补充信息
旧版本没有上述的问题，只在更新后出现

**Comment by yuantuo666** [comment]
感谢反馈，2.2.6版本确实存在此问题，是判断是否使用数据库的逻辑出错了，下一版本将会修复

**Comment by yuantuo666** [comment]
> 2.2.7版本如上问题 {"error_code":31362,"error_msg":"sign error","error_info":"","request_id":8755440985286721635}

请查看使用帮助，你这个是没有设置下载UA
