### ISSUE TITLE
【BUG 反馈】3.0.0 根目录文件被识别为文件夹

### ISSUE THREAD

**Issue by a2803401120** [yuantuo666/baiduwp-php#255]
## 描述 Bug
更新3.0.0后 压缩包文件被识别成目录导致无法解析

![QQ图片20230404153032](https://user-images.githubusercontent.com/54971249/229720571-775260a7-e0e0-4b76-b6c0-47402ca4add8.png)
![QQ图片20230404153040](https://user-images.githubusercontent.com/54971249/229720603-e0f5bf15-5665-48c7-8f56-76a03fd4c052.png)

**Comment by yuantuo666** [comment]
能否提供下分享链接 我这边测试没有问题的
![image](https://user-images.githubusercontent.com/44130602/229778189-88758a72-1371-4d30-931b-a90fc6323995.png)

**Comment by yuantuo666** [comment]
已经成功复现了，根目录下的文件会被识别成文件夹
问题原因是百度网盘API返回的 isdir 参数是字符串型的，下一版本将修复这个bug

![image](https://user-images.githubusercontent.com/44130602/229779519-2c99057f-6a7d-424c-bbe0-a6ac87510055.png)

**Comment by lc6464** [comment]
> 这个只能等下个版本发布才能修复嘛

在目前的最新版本中已经修复。
