### ISSUE TITLE
【BUG 反馈】

### ISSUE THREAD

**Issue by Crystron39** [yuantuo666/baiduwp-php#256]
## 描述 Bug
解析链接内容为压缩包时无法正常解析

在分享链接为文件夹时可正常解析，在分享链接根目录非文件夹，是压缩包时无法解析
![图片](https://user-images.githubusercontent.com/114121223/229989523-76e57b96-d4d6-491b-add4-4568ee5244a9.png)
图一分享链接为文件夹，打开后解析压缩包成功

![图片](https://user-images.githubusercontent.com/114121223/229989206-1ffb2316-979b-4ed5-be29-c7f48f081668.png)
图二为直接分享压缩包，会尝试进入下级目录，无法正常解析

**Comment by Crystron39** [comment]
压缩包会被认为是目录继续尝试进入下级目录

**Comment by yuantuo666** [comment]
感谢提出，昨天已有人反馈这个bug，主分支已经修复，之后会发布新版本

**Comment by yuantuo666** [comment]
参见 https://github.com/yuantuo666/baiduwp-php/issues/255
