### ISSUE TITLE
【建议】可以麻烦分一下完整包和更新包吗大佬

### ISSUE THREAD

**Issue by kaisawl** [yuantuo666/baiduwp-php#258]
每一次更新都需要重新搭建，因为我修改了蛮多的东西，一覆盖就白搞了，可以专门弄个更新内容的覆盖包咩

**Comment by yuantuo666** [comment]
先回答你的这个建议，目前还是不方便实现这个功能，但如果之后有了更新系统，可以尝试实现。

**先解释下，之后前端代码不会有大的修改。**因为3.0.0版本进行了前后端分离，所以有大量修改，但之后的更新前端的代码基本上不会进行大的修改了（除非使用新框架重构）。

关于更新的内容，你可以点击图中的所示链接查看对应版本(演示的是3.0.0)和最新代码的区别。
![image](https://user-images.githubusercontent.com/44130602/230315937-95ef171d-7f8f-4130-886f-898bf6664fa1.png)

至于更新系统，理论上可以根据 git diff 获得对应版本之间修改的文件，然后再将这些版本的文件进行打包就可以制作出更新包。

**Comment by yuantuo666** [comment]
目前已经开始制作项目官网和获取更新包部分了
![image](https://user-images.githubusercontent.com/44130602/231533171-91f8980f-339c-4e27-9848-f9c137634818.png)

**Comment by yuantuo666** [comment]
因内外多种因素，本项目将不会增加更多新功能，仅维护现存的 BUG。若接口失效，本项目将停止更新。
