### ISSUE TITLE
更新最新版以后页面一片空白【BUG 反馈】

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#259]
## 描述 Bug
请在此填入对此 Bug 清晰准确的描述。

## 如何复现此 Bug
复现此 Bug 的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 期望
对您所期望的情况做一个简单描述。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。
![image](https://user-images.githubusercontent.com/114161089/230320101-88a91d27-9f01-4674-a588-b75e7147ed89.png)

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by yuantuo666** [comment]
新版本修改了路由规则，所有的页面现在都在一个html中，你访问的可能不是正确的地址，点击下首页应该就可以加载出来

**Comment by yuantuo666** [comment]
可以提供下你访问的地址是什么吗，域名可以替换，但不要删除域名后面的参数

**Comment by diannaodiy** [comment]
我删除了原有的重新安装了好像也是一样的，我的网址是https://www.360fandu.cn/

**Comment by yuantuo666** [comment]
我访问没有问题的，可能是你浏览器有缓存，Ctrl+F5强制刷新试试
![image](https://user-images.githubusercontent.com/44130602/230322321-5e65399e-c469-4aee-bb1c-0bbda6a21972.png)

**Comment by diannaodiy** [comment]
好的谢谢

**Comment by yuantuo666** [comment]
另外你的cdn配置似乎出了问题，好像强制缓存了api接口的请求，你可以检查下相关的设置，不然可能导致无法使用的问题
![image](https://user-images.githubusercontent.com/44130602/230322941-00efe534-ec56-479d-a1ef-e3e6e0c66dd0.png)

**Comment by diannaodiy** [comment]
我刚刚以为是CDN问题，已经取消CDN了。

**Comment by yuantuo666** [comment]
如果没有问题可以关闭这个议题了
