### ISSUE TITLE
都设置好了  但出现个问题

### ISSUE THREAD

**Issue by 1479697882** [yuantuo666/baiduwp-php#26]
![Screenshot_2020-08-31-17-15-26-898_com mmbox xbrowser](https://user-images.githubusercontent.com/39453108/91704453-3852aa80-ebae-11ea-9d5a-9b63ca4c08c3.jpg)

**Comment by yuantuo666** [comment]
这个是版本更新导致的，更换设备或刷新缓存后重试即可

**Comment by 1479697882** [comment]
好的解决了&nbsp; 多谢😁



---原始邮件---
发件人: "yuantuo666"<notifications@github.com&gt;
发送时间: 2020年8月31日(周一) 晚上10:44
收件人: "yuantuo666/baiduwp-php"<baiduwp-php@noreply.github.com&gt;;
抄送: "era-Platelet"<1479690882@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [yuantuo666/baiduwp-php] 都设置好了  但出现个问题 (#26)




 
这个是版本更新导致的，更换设备或刷新缓存后重试即可
