### ISSUE TITLE
【建议】为啥一直显示这个

### ISSUE THREAD

**Issue by Violexjj** [yuantuo666/baiduwp-php#260]
![QQ图片20230408141151](https://user-images.githubusercontent.com/126398596/230706598-60f37328-6f1c-451e-a790-bc91a7d9ecc5.png)

**Comment by yuantuo666** [comment]
设置的普通账号Cookie有问题

检查下账号状态，看能不能打开分享链接里的文件夹：
1. 打不开的话就是账号被封禁了
2. 如果可以打开的话，就是Cookie失效了，重新抓包获取Cookie设置就行

**Comment by Violexjj** [comment]
> 设置的普通账号Cookie有问题
> 
> 检查下账号状态，看能不能打开分享链接里的文件夹：
> 
> 1. 打不开的话就是账号被封禁了
> 2. 如果可以打开的话，就是Cookie失效了，重新抓包获取Cookie
如果被封禁了呢，怎么解决（为啥会被封禁）

**Comment by yuantuo666** [comment]
被封禁了可以向百度官方申请解封或者更换其他账号
可能是短时间内下载太多导致的封禁

**Comment by yuantuo666** [comment]
使用百度网盘网页版访问其他人的分享链接，查看能否打开里面的文件夹

**Comment by yuantuo666** [comment]
> ![image](https://user-images.githubusercontent.com/126398596/230721835-5992a911-df92-4a3b-a242-efbe1dc8af4a.png) 就显示这个
> 
> > 被封禁了可以向百度官方申请解封或者更换其他账号 可能是短时间内下载太多导致的封禁

打开不了就是被封禁了，这个无法判断具体是什么情况

**Comment by Violexjj** [comment]
> 使用百度网盘网页版访问其他人的分享链接，查看能否打开里面的文件夹

能打开

**Comment by Violexjj** [comment]
> > ![image](https://user-images.githubusercontent.com/126398596/230721835-5992a911-df92-4a3b-a242-efbe1dc8af4a.png) 就显示这个
> > > 被封禁了可以向百度官方申请解封或者更换其他账号 可能是短时间内下载太多导致的封禁
> 
> 打开不了就是被封禁了，这个无法判断具体是什么情况

哎。。

**Comment by yuantuo666** [comment]
报错9019是无法判断 账号失效 还是 被封禁，需要打开百度网盘网页版的分享链接，能打开分享链接里面的文件夹，说明账号没有被封禁，重新抓包获取Cookie就可以了

**Comment by Violexjj** [comment]
> 报错9019是无法判断 账号失效 还是 被封禁，需要打开百度网盘网页版的分享链接，能打开分享链接里面的文件夹，说明账号没有被封禁，重新抓包获取Cookie就可以了

重新抓包获取Cookie是啥意思

**Comment by yuantuo666** [comment]
https://blog.imwcr.cn/2022/11/24/%e5%a6%82%e4%bd%95%e6%8a%93%e5%8c%85%e8%8e%b7%e5%8f%96%e7%99%be%e5%ba%a6%e7%bd%91%e7%9b%98%e7%bd%91%e9%a1%b5%e7%89%88%e5%ae%8c%e6%95%b4-cookie/ 获取之后手动设置到config.php 或者 重新安装

**Comment by Violexjj** [comment]
![截图20230408210628](https://user-images.githubusercontent.com/126398596/230722997-4f6abd4e-4f59-43ca-9ff3-6006b552dea4.png)
![截图20230408210641](https://user-images.githubusercontent.com/126398596/230723019-60485bf5-e8f8-4650-aa3a-74a81a72f02d.png)
我界面是这样的，是要安装什么东西吗，在哪安装？？
要付费购买吗

**Comment by yuantuo666** [comment]
你删除源代码，重新安装就有这个页面

**Comment by Violexjj** [comment]
![截图20230408210628](https://user-images.githubusercontent.com/126398596/230723074-16b2e2e3-2f65-46e3-a2b8-138fa6a52f40.png)

**Comment by Violexjj** [comment]
我都不知道哪里可以安装，我这个直接就是打开网页

**Comment by yuantuo666** [comment]
那你联系搭建网站的人吧
