### ISSUE TITLE
【建议】有赞助二维码吗？

### ISSUE THREAD

**Issue by wonchong** [yuantuo666/baiduwp-php#261]
## 描述建议
请在此填入对此建议清晰准确的描述。

## 此建议将如何工作
工作步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 相关的技术
如果您有能力，您可以在此提供一些技术帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 补充信息
您可以在这里输入其他有关此建议的信息。

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/230755742-d60f9793-f627-4c2c-b375-8793be48cc49.png)
点这里可以看到哦
