### ISSUE TITLE
请问这种界面是什么问题【BUG 反馈】

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#262]
## 描述 Bug
升级完正常用了两天，今天有会员反映用 不了。测试时下边的图片。

## 如何复现此 Bug
复现此 Bug 的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 期望
对您所期望的情况做一个简单描述。

## 截图
![微信截图_20230409195625](https://user-images.githubusercontent.com/114161089/230771343-de81f590-05ec-49c2-b965-ca0f34a34ad5.png)

如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by yuantuo666** [comment]
提供下分享链接和提取码

**Comment by diannaodiy** [comment]
链接：https://pan.baidu.com/s/1Ff1mvg4txYW1ZHH2Qy_ufQ?pwd=6666 
提取码：6666 
密码是：www.10zv.net

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/230771640-8b645fa5-4073-4053-abfe-5caa42e82116.png)
我这边本地测试没有问题

**Comment by diannaodiy** [comment]
我的解析网站是www.360fandu.cn 是不是服务器又被封了？

**Comment by yuantuo666** [comment]
你的网站测试也没有问题
![image](https://user-images.githubusercontent.com/44130602/230772029-1c2c5e5e-6850-4951-8b9e-37cc033c202f.png)

**Comment by diannaodiy** [comment]
好的，我再找下问题

**Comment by yuantuo666** [comment]
仍有问题请重新打开此议题
