### ISSUE TITLE
【BUG反馈】获取到限速地址没有正常返回

### ISSUE THREAD

**Issue by husnda** [yuantuo666/baiduwp-php#264]
## 描述问题
尝试获取直链失败

## 如何复现此问题
复现此问题的步骤:
1. **点击分享链接中的大型文件，弹出报错：获取下载链接失败 (999)
错误 -> {"error_code":302,"request_id":111723289855693646}**

## 你需要的帮助
报错产生的原因是什么？如何解决？

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息debian：
 - 服务器 PHP 版本PHP7：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
SVIP账号限速了，更换SVIP账号就可以解决

**Comment by husnda** [comment]
> SVIP账号限速了，更换SVIP账号就可以解决

只是普通账号，可不可以理解为“只有SVIP账号才能获取大文件的直链，且即便是SVIP账户也可能被限速”？
另外，设置页面【超级会员账号】有如下描述：
> 用来获取文件高速下载地址，必须为SVIP账号，否则将获取到限速地址。
如果填入的是普通账号，理应获取到限速地址，实际上连限速地址都无法获取，是否描述不合理呢？

**Comment by yuantuo666** [comment]
是的，这是一个bug，之后会修复。但限速地址无法下载，所以建议你更换SVIP账号。

**Comment by husnda** [comment]
另外，近期部署的时候，发现PHP7.0会报错，可以提pr吗？

**Comment by yuantuo666** [comment]
欢迎提pr
