### ISSUE TITLE
Google插件方式有效，下载4-6m/s,但是IDM为啥总提示没有权限？

### ISSUE THREAD

**Issue by w37fhy** [yuantuo666/baiduwp-php#27]
请教下，Google插件设置好以后，用浏览器的下载可以达到最高6m/s,但是IDM一直不成功

报错：
![QQ截图20200911152250](https://user-images.githubusercontent.com/64185417/92882849-e11cc780-f442-11ea-813f-f985cba319de.jpg)
已设置UA：
![QQ截图20200911152319](https://user-images.githubusercontent.com/64185417/92882885-e9750280-f442-11ea-9969-01690ccec052.jpg)

**Comment by yuantuo666** [comment]
需要 **手动复制链接** 再 **新建下载** 才行

直接点击不会传入设置的ua

**Comment by w37fhy** [comment]
> 需要 **手动复制链接** 再 **新建下载** 才行
> 
> 直接点击不会传入设置的ua

我确实是手动复制连接，新建下载的~
另外问一下，如果使用的人多了会被百度封掉这个svip账号是么？还会有哪些负面结果？是不是可以理解成我如果分享给粉丝用，我最好还是新注册一个百度云账号开通svip然后抓取cookie写在config里。
根据你的经验，大约多久或者多少人使用后会被封?

**Comment by yuantuo666** [comment]
1.更换idm版本试下
2.使用太多会限速，不会封号
目前来看百度设置的流量阈值应该是5TB左右
3.但限速过一段时间会解除，这个时间暂不清楚
