### ISSUE TITLE
【BUG 反馈】错误代码999是什么问题

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#270]
## 描述 Bug
请在此填入对此 Bug 清晰准确的描述。
账号失效以后，重新换了账号就出现这个问题了。
## 如何复现此 Bug
复现此 Bug 的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 期望
对您所期望的情况做一个简单描述。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。
![微信截图_20230416151847](https://user-images.githubusercontent.com/114161089/232280054-d7994ed5-5254-4f9a-a0fe-b9f189d64d89.png)

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by yuantuo666** [comment]
不清楚是什么原因导致的，提供下文件分享链接，网站地址

**Comment by diannaodiy** [comment]
网站是 www.360fandu.cn

**Comment by diannaodiy** [comment]
密码是 10zv.com

**Comment by yuantuo666** [comment]
获取真实链接失败 HTTP/1.1 400 Bad Request

SVIP_BDUSS 设置错了吧，自己检查下，程序没问题

**Comment by diannaodiy** [comment]
好的非常感谢。是BDUSS问题，多了一个空格。。。。
