### ISSUE TITLE
【建议】是否可以提供批量解析功能？

### ISSUE THREAD

**Issue by DoraShin** [yuantuo666/baiduwp-php#271]
## 描述建议
有些文件夹下的文件数量很多（比如公开课或者游戏的分卷压缩包），建议对文件夹下的所有文件提供批量解析发送到Aria2的功能。

**Comment by yuantuo666** [comment]
参见 https://github.com/yuantuo666/baiduwp-php/issues/249

**Comment by yuantuo666** [comment]
另外批量解析也会导致SVIP账号很快被封禁，如有大量下载需求建议使用官方客户端下载

**Comment by GreenTeodoro839** [comment]
> 其实我在想能不能将cookie注入到百度网盘客户端，不然有时候买的是一天的共享号就没法登陆了

手机登录小米联运版网盘，可以避免被踢
