### ISSUE TITLE
【建议】希望能支持直接从url中解析

### ISSUE THREAD

**Issue by RnJ4** [yuantuo666/baiduwp-php#272]
## 描述建议
比如我有一个分享链接为 https://pan.baidu.com/s/xxxxxxxxxxx?pwd=1234
在浏览器中把url改为自己的解析网站，然后直接跳转解析（https://自己的网站.com/s/xxxxxxxxxxx?pwd=1234）

## 此建议将如何工作
工作步骤:
加一个/s/的页面路由用于直接解析

**Comment by yuantuo666** [comment]
对于分享链接 https://pan.baidu.com/s/xxxxxxxxxxx?pwd=1234 来说，
本项目可以实现自动识别 https://example.com/#/xxxxxxxxxxx?pwd=1234
但是不能实现 https://example.com/s/xxxxxxxxxxx?pwd=1234 中提取

#273 实现了自动识别 https://example.com/#/ 后面所携带的提取链接，即下面的方式也都可以正常获取（需要正确 urlEncode ）

- https://example.com/#/链接: https://pan.baidu.com/s/xxxxxxxxxxx 提取码: 1234
- https://example.com/#/https://pan.baidu.com/s/xxxxxxxxxxx 提取码: 1234
- https://example.com/#/https://pan.baidu.com/s/xxxxxxxxxxx?pwd=1234
- https://example.com/#/s/xxxxxxxxxxx?pwd=1234
- https://example.com/#/xxxxxxxxxxx?pwd=1234

**Comment by yuantuo666** [comment]
如果你执意要实现 识别 https://example.com/s/xxxxxxxxxxx?pwd=1234
可以自行配置 Nginx 或 Apache 的重定向规则，将其重定向 https://example.com/#/xxxxxxxxxxx?pwd=1234
这样就符合了上面的要求

例如 Nginx 可以这样配置
```
location /s/ {
    rewrite ^/s/(.*)$ /#/$1 redirect;
}
```
