### ISSUE TITLE
【BUG 反馈】MD5错误，无法加速

### ISSUE THREAD

**Issue by liaosunny123** [yuantuo666/baiduwp-php#274]
## 描述 Bug
MD5错误，无法加速，和秒传的MD5不一致

## 期望
可以和秒传的MD5一致，或者提供秒传的MD5以方便解析下载

**Comment by yuantuo666** [comment]
百度接口返回的就是错误的 MD5
已经尝试修复了，部分文件在修复后可以获得正确的 MD5，但部分文件仍然是错误的 MD5

正确的 MD5 可用通过向直链发起 HEAD 请求获得，但 MD5 和加速有什么关系，你能再解释下你的想法吗？

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/233787962-7befdb42-66c7-47e7-8672-6c3df68fc570.png)

参考这里 https://pan.baidu.com/union/doc/Zl0jb6i29

**Comment by liaosunny123** [comment]
那应该怎么获取正确的MD5诶，你说的通过HEAD请求是，可以说的详细一下吗？
MD5下载是因为目前有一些其他服务的api，可以通过提交dlink和md5重新得到一个下载的链接，而这个md5和秒传，或者说正确的md5一样。

**Comment by yuantuo666** [comment]
你说的其他服务指的是什么，是百度官方的服务吗，还是第三方服务？
因为你没有提供足够的信息，我判断不了你意图是什么，百度也有意设计这个策略，在不清楚具体你要拿来干什么的情况下，直接说出来对你我都不好。
如果你能在issue中提供更多信息，或者通过邮件联系我解释清楚其他服务是什么以及你具体要干什么，我会告诉你获取md5的详细步骤，谢谢理解。

我的邮箱： yuantuo666@gmail.com

**Comment by liaosunny123** [comment]
已通过邮件详细叙述，后续可以通过邮件交流
