### ISSUE TITLE
【BUG 反馈】无法获取下载链接，提示“获取下载链接失败”是啥原因

### ISSUE THREAD

**Issue by github-24** [yuantuo666/baiduwp-php#275]
![image](https://user-images.githubusercontent.com/31309840/235298885-2b925e5a-cef8-4fda-99e8-9818a7e4b7c7.png)

**Comment by yuantuo666** [comment]
会员账号被限速，需要更换SVIP_BDUSS

**Comment by yuantuo666** [comment]
仍有问题请重新打开议题，新版本已修复此问题
