### ISSUE TITLE
【点击获取直连就报这个错31360，网盘号是正常的】

### ISSUE THREAD

**Issue by HZ-ZY** [yuantuo666/baiduwp-php#276]
![0d6d573e71eb3de7a6d47ea6a18af94](https://user-images.githubusercontent.com/64133885/236495442-f8b7342c-d4c0-4928-bbff-8d156d75eac1.png)
![image](https://user-images.githubusercontent.com/64133885/236495587-92326c7a-7807-47af-93df-2d27e1c81f33.png)

**Comment by HZ-ZY** [comment]
http://38.60.32.78:7777

**Comment by HZ-ZY** [comment]
账号adminadmin

**Comment by HZ-ZY** [comment]
您看看哈

**Comment by yuantuo666** [comment]
看样子是普通账号设置的问题，我用其他的分享链接也获取不了下载地址

**Comment by yuantuo666** [comment]
检查下安装时设置的 Cookie 是否是正确的，要通过网页版抓包请求获得

**Comment by HZ-ZY** [comment]
普通账号一定要设置吗，就是说一定要一个普通账号做载体是吗？

**Comment by yuantuo666** [comment]
仍有问题请重新打开议题
