### ISSUE TITLE
连接服务器过程中出现异常，消息：Unexpected end of JSON input

### ISSUE THREAD

**Issue by mali321321** [yuantuo666/baiduwp-php#278]
![QQ截图20230514203905](https://github.com/yuantuo666/baiduwp-php/assets/84053987/7cbd198d-60a2-43ba-9710-95b8cdfa91e6)

**Comment by yuantuo666** [comment]
检查服务器状态，尝试重启服务器

**Comment by mali321321** [comment]
我用的虚拟主机，换了两个主机都是这样

**Comment by yuantuo666** [comment]
发下你的网站地址

**Comment by mali321321** [comment]
http://pdd.liusui.gq/#/index

**Comment by yuantuo666** [comment]
500 Internal Server Error 

估计是虚拟主机的问题，检查下PHP版本，是不是7.0以上。实在不行用项目首页推荐的虚拟主机。

**Comment by mali321321** [comment]
使用首页推荐的主机完美解决，谢谢！

**Comment by yuantuo666** [comment]
好的，下次提 **issue** 的时候尽量 **描述清楚问题** 和 **你能提供的所有信息**，完成 issue 之后记得 **closed** 掉，这次我帮你 close 了。
