### ISSUE TITLE
错误了

### ISSUE THREAD

**Issue by qingyun-studio** [yuantuo666/baiduwp-php#28]
$_GET:array(1) {
  ["download"]=>
  string(0) ""
}
$_POST:array(8) {
  ["fs_id"]=>
  string(15) "630684620439602"
  ["time"]=>
  string(10) "1601694459"
  ["sign"]=>
  string(40) "d8b18a282e277904091520f7a9b5166784860c91"
  ["randsk"]=>
  string(0) ""
  ["share_id"]=>
  string(10) "1517242993"
  ["uk"]=>
  string(13) "1103758388794"
  ["bdstoken"]=>
  string(32) "ac488f7c561ab58ac7814971769b95e3"
  ["filesize"]=>
  string(9) "439671345"
}
getDlink():array(3) {
  ["errno"]=>
  int(118)
  ["request_id"]=>
  int(6411981040309367820)
  ["server_time"]=>
  int(1601694490)
}

**Comment by yuantuo666** [comment]
麻烦发下分享链接
