### ISSUE TITLE
【寻求帮助】求助！这个是什么情况

### ISSUE THREAD

**Issue by XiHua0522** [yuantuo666/baiduwp-php#281]
![image](https://github.com/yuantuo666/baiduwp-php/assets/98436743/5c43517e-84f3-4dfe-8275-176ae9623882)
安装的时候会如图所示报错
在edge和chrome上都会这样，但在手机浏览器上部署的话就没有这样的问题，解析也是能正常解析
我以为是机子的问题，第一次是在虚拟主机上部署的，后来换了阿里云的服务器也是会有一样的问题
经测试在华为手机浏览器上没有任何问题

**Comment by XiHua0522** [comment]
pan.e-lise.shop
这是已经部署好了网站，貌似PC浏览器不能正常解析

**Comment by yuantuo666** [comment]
本项目引用了 jsdelivr 的资源，可能是你电脑的网络环境有问题，无法访问这些资源导致的。

**Comment by XiHua0522** [comment]
不应该啊，我测试了三四个设备都是同样的情况，后面再测试的时候试了下在连接代理的情况下就没问题了

**Comment by yuantuo666** [comment]
https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js
例如这样的资源，都是通过 jsdelivr 加载的，你可以看看能否正常访问。

**Comment by XiHua0522** [comment]
> 
这个是可以打开的，会不会还是怪主机的问题？

**Comment by yuantuo666** [comment]
我这边PC是可以打开的，手机端也正常。

**Comment by XiHua0522** [comment]
> 我这边PC是可以打开的，手机端也正常。

好吧，那估计就是我这儿的问题了，谢谢你的回答
