### ISSUE TITLE
【寻求帮助】docker 的挂载位置在哪呢

### ISSUE THREAD

**Issue by Rpower666** [yuantuo666/baiduwp-php#282]
## 使用了命令

```java
docker run --network mysql-network --ip 172.28.0.3 -p 8080:80 yuantuo666/baiduwp-php
````

但不知道他的挂载位置在哪，需要进行设置congfig.php，实现tgbot转换网盘下载链接

**Comment by yuantuo666** [comment]
问题和项目无关，请检查 docker 文档

Docker 默认安装的情况下，会使用 /var/lib/docker/ 目录作为存储目录。

**Comment by Eisaichen** [comment]
可以考虑下载源文件，然后把Config文件夹挂载进去
###
  baiduwp-php:
    image: yuantuo666/baiduwp-php
    container_name: baiduwp-php
    networks:
      - mysqldb
    ports:
      - 127.0.0.1:10380:8000
    restart: unless-stopped
    volumes:
      - "/srv/containers/baiduwp-php/config:/app/config"
###
