### ISSUE TITLE
【寻求帮助】怎么获取SVIP会员剩余天数呀

### ISSUE THREAD

**Issue by HZ-ZY** [yuantuo666/baiduwp-php#283]
怎么获取SVIP会员剩余天数呀

**Comment by HZ-ZY** [comment]
![image](https://github.com/yuantuo666/baiduwp-php/assets/64133885/6e28ee05-a169-4a70-9adc-70aaf212b317)
这一块代码看的不是很懂

**Comment by yuantuo666** [comment]
看这里和 AccountStatus 函数，框内代码做了个缓存
