### ISSUE TITLE
解析出来的加速链接1个小时就失效了，有啥办法延长时间不

### ISSUE THREAD

**Issue by HZ-ZY** [yuantuo666/baiduwp-php#285]
解析出来的加速链接1个小时就失效了，有啥办法延长时间不，大文件一个小时内下载不完

**Comment by yuantuo666** [comment]
百度的限制，没有办法修改过期时间
但是百度的链接支持断点续传，如果使用的是aria2下载，可以手动替换过期的地址为重新获取的地址，可以继续下载

**Comment by HZ-ZY** [comment]
以前我记得是8小时不知道啥时候改了
![image](https://github.com/yuantuo666/baiduwp-php/assets/64133885/6384f5b6-fff1-4e34-b135-1a1774547ca7)

**Comment by lovejing0306** [comment]
> 解析出来的加速链接1个小时就失效了，有啥办法延长时间不，大文件一个小时内下载不完

你好，请问解析密码在哪里可以获取到？

**Comment by yuantuo666** [comment]
> 

请询问网站站长

**Comment by lovejing0306** [comment]
怎么联系网站站长？

Yuan_Tuo ***@***.***>于2023年6月16日 周五10:56写道：
