### ISSUE TITLE
请帮忙看看这个问题是帐号问题还是程序问题谢谢【BUG 反馈】

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#287]
## 描述 Bug
请在此填入对此 Bug 清晰准确的描述。

## 如何复现此 Bug
复现此 Bug 的步骤:
可以正常获取文件，但是点击就失败，换过3个百度网盘帐号。
## 期望
对您所期望的情况做一个简单描述。

## 截图
![image](https://github.com/yuantuo666/baiduwp-php/assets/114161089/d93ededc-56a5-4d27-840c-ffc65531ef2a)

如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by diannaodiy** [comment]
网站是www.360fandu.cn

**Comment by Markli66** [comment]
跟一下问题，我在服务器同样SVIP账号和普通账号一样，但是错误提示是获取链接超时。
错误代码是：
超时，自动获取sign和timestamp成功
获取真实链接失败  HTTP/1.1 403 Forbidden\r\nConnection: keep-alive\r\nContent-Type: text/plain;

错误 -> {"error_code":31360,"error_msg":"expire time out error","request_id":21464219975530192}

请问这是因为服务器IP被频闭了吗？

**Comment by diannaodiy** [comment]
> 跟一下问题，我在服务器同样SVIP账号和普通账号一样，但是错误提示是获取链接超时。 错误代码是： 超时，自动获取sign和timestamp成功 获取真实链接失败 HTTP/1.1 403 Forbidden\r\nConnection: keep-alive\r\nContent-Type: text/plain;
> 
> 错误 -> {"error_code":31360,"error_msg":"expire time out error","request_id":21464219975530192}
> 
> 请问这是因为服务器IP被频闭了吗？

解决了吗？

**Comment by Markli66** [comment]
是Token过期的问题，登陆帐号之后一台电脑一台浏览器不能再退出。

**Comment by yuantuo666** [comment]
> ![微信截图_20230720191449](https://user-images.githubusercontent.com/114161089/254866521-67ffb4b3-bd57-416a-9282-ed24b15a9ba2.png) 换了服务器，居然安装不了了。

第二行写出了错误，普通账号 Cookie 配置错误了

07/23 14:09 测试程序没有问题

**Comment by diannaodiy** [comment]
> > ![微信截图_20230720191449](https://user-images.githubusercontent.com/114161089/254866521-67ffb4b3-bd57-416a-9282-ed24b15a9ba2.png)换了服务器，居然安装不了了。
> 
> 第二行写出了错误，普通账号 Cookie 配置错误了
> 
> 07/23 14:09 测试程序没有问题

解决了，发现一个BUG就是用微软的跟谷歌浏览器获取的COOKIE都不能用，需要用其它浏览器才可以。不知道是不是百度升级了算法。
