### ISSUE TITLE
【寻求帮助】询问百度网盘链接限速逻辑

### ISSUE THREAD

**Issue by Markli66** [yuantuo666/baiduwp-php#288]
## 描述问题
想请教一下，目前解析的时候返回的地址有：
https://bjbgp01.baidupcs.com/
https://nd6.baidupcs.com/
https://dp0.baidupcs.com/
https://qd2.cache.baidupcs.com/
等的开头的下载地址，不太确定这些地址开头的下载链接都代表什么意思。
是否可以通过这些地址的开头来对获取的链接是否为高速或者是否失败作为判断呢？

## 如何复现此问题
复现此问题的步骤:
1.首先我的后台设置了三个VIP账号，普通账号依旧是三个VIP账号里的其中一个。
2. 修改了Parse.php下的代码，将原有解析文件夹列表的函数给进行了注释。不再支持文件夹解析，当然远离其实就是在这个arrary下返回一个错错误信息。
3. 修改的代码段：else {
				// //文件夹
				// $FileData[] = array(
				// 	"isdir" => 1,
				// 	"name" => $file["server_filename"],
				// 	"path" => $file["path"],
				// 	"size" => $file["size"],
				// 	"uploadtime" => $file["server_ctime"]
				// );
				 return array(
                 "error" => 1,
                 "message" =>'不支持文件夹解析'
            );
			}
		}
4. 在后台观察解析的数据有以上的不同的解析返回地址。
5. 会员账号模式设置的所有账号轮换模式。

## 你需要的帮助
主要想请教一下返回的这些具体的解析链接分别是代表什么意思。不太确定的是，假设我设置的是所有账号轮换模式的情况下，如果所有VIP账号都失效了我使用的普通账号依然是VIP当中的一个，是否会出现解析不出来的情况。

## 截图
这是会员账号设置的截图：
![微信截图_20230723222643](https://github.com/yuantuo666/baiduwp-php/assets/51303387/e33f2314-5ebb-4986-8402-874605508233)
这是存储的解析返回后的数据：
![微信截图_20230723222748](https://github.com/yuantuo666/baiduwp-php/assets/51303387/aa7c7761-232a-42d8-9bd6-9799451b73dc)
![微信截图_20230723222800](https://github.com/yuantuo666/baiduwp-php/assets/51303387/301a6714-8195-4f37-9b55-94cbb6c4a539)

## 您的设备信息
 - CentoOS 服务器
 - PHP版本是使用宝塔面板自动创建的PHP—74
 -

## 补充信息
其实大概的问题就是假如我设置了无视限速的模式，VIP账号和普通账号的token以及Cookie没有问题的情况下，自己又做了限制次数和IP的调整以及解析文件夹的限制，是否能够保证即使他获取的不是高速下载地址，依然返回的链接能够正常的去使用。可能表达的比较复杂，我尽可能的完整复现我的情况。因为对接口进行了一些研究，自己也做了修改。可能会有些出入。

**Comment by yuantuo666** [comment]
1. 不同的域名前缀对应的是百度的不同服务器，例如 北京BGP 服务器 bjbgp01.baidupcs.com 青岛缓存服务器 qd2.cache.baidupcs.com 等。原先限速链接都是 qdall01.baidupcs.com 开头，目前百度修改了逻辑，无法通过域名前缀判断是否限速。
2. 目前（23年7月份）观测到百度对SVIP账号的限速/封禁采用的是对实际下载量的统计。即一定的时间粒度内下载量超过阈值就会被限速或封禁。
3. 账号限速之后返回的连接就是限速的，没有办法破解限速。如果账号被封禁，那么将不会返回下载链接，而是错误码 9013/9019 等。
