### ISSUE TITLE
【寻求帮助】获取下载链接失败999，errorcode302

### ISSUE THREAD

**Issue by 809781347** [yuantuo666/baiduwp-php#289]
## 描述问题
获取下载链接失败，请问这是账号的问题吗

[
![image](https://github.com/yuantuo666/baiduwp-php/assets/100351684/831a2098-b717-4fa1-83e1-5f4eaa2d33c9)
](url)

**Comment by yuantuo666** [comment]
是账号问题，SVIP账号被限速，需要更换账号

**Comment by 809781347** [comment]
了解了！谢谢捏
