### ISSUE TITLE
盘内下载怎么搞？

### ISSUE THREAD

**Issue by eternal2056** [yuantuo666/baiduwp-php#29]
研究了一下，发现只能分享下载。
这么说的话，想下载自己盘内的，只能分享过后再解析？

**Comment by yuantuo666** [comment]
是的 因为普通账号获取生成的pcs链接有限制（其他账户无法获取真实下载地址），不是同一个账号无法下载，所以必须使用分享下载。

**Comment by eternal2056** [comment]
你的意思是 SVIP账号 就可以获取 自己盘内的文件的真实下载地址吗？
但是我实际操作中，获取到的下载地址，有些文件可以下载，但是有些文件下载不了。
我获取的方式如下：
http://d.pcs.baidu.com/rest/2.0/pcs/file?ver=4.0&app_id=250528&method=locatedownload&path={any}

**Comment by yuantuo666** [comment]
这个与是否是SVIP无关

**Comment by yuantuo666** [comment]
盘内下载 获取的pcs只能在自己的bduss下转跳获得真实地址

**Comment by yuantuo666** [comment]
比如 A的账号在网盘内获取了pcs链接 那么B账号通过这个链接是获取不到下载地址的

**Comment by eternal2056** [comment]
pcs链接是 d.pcs.baidu.com 发起请求后返回的链接吗？ 还是别的方法获取的？
那么我想用 A的账号获取PCS链接，并且在A的账号获取下载地址可行吗？该怎么获取下载地址呢？

**Comment by yuantuo666** [comment]
这个我没有测试，只能给你提供一下思路：用SVIP账号的cookie直接访问pcs链接，转跳后就可以得到真实地址（50MB以下），对于大文件可以尝试传入ua获取真实链接。

**Comment by eternal2056** [comment]
好的，谢谢你提供思路。
