### ISSUE TITLE
cookie如何抓包

### ISSUE THREAD

**Issue by 212721** [yuantuo666/baiduwp-php#292]
根本不会抓包，百度云如何抓包cookie

## 描述问题
请在此填入对你遇到的问题清晰准确的描述。

## 如何复现此问题
复现此问题的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
在安装页面有完整Cookie抓包的介绍链接，因为最近博客使用的CDN停止服务了所以进入不了，现在已经修复，再贴一次链接：https://blog.imwcr.cn/2022/11/24/%e5%a6%82%e4%bd%95%e6%8a%93%e5%8c%85%e8%8e%b7%e5%8f%96%e7%99%be%e5%ba%a6%e7%bd%91%e7%9b%98%e7%bd%91%e9%a1%b5%e7%89%88%e5%ae%8c%e6%95%b4-cookie/

**Comment by yuantuo666** [comment]
1. 使用 Edge 浏览器打开已经登录的百度网盘网页版

2. 按下 F12 打开开发者工具

或者 对 百度网盘logo 右键，选择 检查

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-1.png
打开开发者工具
3. 选择 网络 选项卡

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-2.png
网络选项卡
4. 刷新页面

5. 找到一个 请求 URL 为 https://pan.baidu.com 开头的请求，一般第一个就可以

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-3.png
寻找请求
6. 在请求的详细信息页面往下滑找到 Cookie 参数

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-4.png
寻找Cookie
7. 对 Cookie 右键复制值

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-5.png
复制Cookie
8. 粘贴到安装页面

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-6.png
粘贴Cookie

**Comment by 212721** [comment]
谢谢🙏



在 2023-08-15 16:37:23，"Yuan_Tuo" ***@***.***> 写道：

使用 Edge 浏览器打开已经登录的百度网盘网页版

按下 F12 打开开发者工具

或者 对 百度网盘logo 右键，选择 检查

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-1.png
打开开发者工具
3. 选择 网络 选项卡

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-2.png
网络选项卡
4. 刷新页面

找到一个 请求 URL 为 https://pan.baidu.com 开头的请求，一般第一个就可以

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-3.png
寻找请求
6. 在请求的详细信息页面往下滑找到 Cookie 参数

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-4.png
寻找Cookie
7. 对 Cookie 右键复制值

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-5.png
复制Cookie
8. 粘贴到安装页面

https://blog.imwcr.cn/wp-content/uploads/2022/11/image-6.png
粘贴Cookie
