### ISSUE TITLE
【BUG 反馈】php7.4,mysql环境下GetDBBDUSS()函数工作异常

### ISSUE THREAD

**Issue by 827821562** [yuantuo666/baiduwp-php#293]
## 描述 Bug

bug出现的地方GetDBBDUSS()函数，非本地模式下解析账号恒为-1

## 如何复现此 Bug
复现此 Bug 的步骤:
1. 非本地模式下解析账号恒为-1，且确定数据库账号可用以及数据库连接正常
![image](https://github.com/yuantuo666/baiduwp-php/assets/103015382/f4bf373f-6988-4fcd-838b-7916c70a73d3)

## 期望
修正解析账号问题

## 截图
![image](https://github.com/yuantuo666/baiduwp-php/assets/103015382/f4bf373f-6988-4fcd-838b-7916c70a73d3)
![image](https://github.com/yuantuo666/baiduwp-php/assets/103015382/7f75490f-2b0b-4ce4-be31-fadc84006053)

## 您的设备信息
 - 服务器系统信息Ubuntu 20.04.5 LTS
 - 服务器 PHP 版本7.4
 - 数据库 MYSQL Ver 14.14 Distrib 5.6.50, for Linux (x86_64) using  EditLine wrapper
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）chorme 115.0.5790.171

## 补充信息
上述截图的第二个是我的修复方式，不知道其他人是否遇到本问题，作出此修改后可以正常显示解析账号

**Comment by yuantuo666** [comment]
感谢反馈，目前主分支确实存在此问题并且成功复现，检查发现是 双引号(") 引起的问题，如果使用的是 MySQL，列名和表名应该使用 反勾号(`)

![image](https://github.com/yuantuo666/baiduwp-php/assets/44130602/35ed7725-3267-4196-8742-5d49f001a279)
