### ISSUE TITLE
【寻求帮助】后台无法访问，反馈个bug

### ISSUE THREAD

**Issue by dan3577** [yuantuo666/baiduwp-php#295]
## 描述问题
访问后台提示如下

Not Found
The requested URL was not found on this server.
Apache/2.4.56 (Debian) Server at 150.xx.77.xx Port 8080

1. 删除docker版的baiduwp-php后重新装，会无限提示重新安装，内容是http503不可用，请输入完整ck（但是ck是根据教程抓的，url和作者说的是一样的），因为重新安装会自动填入上一次安装填写的Cookie信息，重装也就没有再次填一遍ck。重新删掉自动填写的ck，再手动填一次就解决了访问主页提示重新安装的问题了。。

2. 后台访问不了，我重新访问安装界面ip:port/install.php重新安装了一下解决了。。。
现在都解决了，记录一下。

3. 有一样问题的可以参考一下我的方式

## 您的设备信息
Docker version 1.13.1, build 7d71120/1.13.1
Linux ser701007685822 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x8 6_64 x8 6_64 GNU/Linux

**Comment by dan3577** [comment]
重装的时候
最后一步docker run --network mysql-network --ip 172.28.0.3 -p 8088:80 yuantuo666/baiduwp-php
执行后，提示如下:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.28.0.3. Set the 'ServerName' directive globally to suppress this message

**Comment by yuantuo666** [comment]
> 重装的时候 最后一步docker run --network mysql-network --ip 172.28.0.3 -p 8080:80 yuantuo666/baiduwp-php 执行后，提示如下: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.28.0.3. Set the 'ServerName' directive globally to suppress this message

这个报错不影响的，这个是没有设置域名导致的，大部分人用docker也不会用到域名解析

**Comment by yuantuo666** [comment]
> ## 描述问题
> 访问后台提示如下
> 
> Not Found The requested URL was not found on this server. Apache/2.4.56 (Debian) Server at 150.xx.77.xx Port 8080
> 
> 1. 删除docker版的baiduwp-php后重新装，会无限提示重新安装，内容是http503不可用，请输入完整ck（但是ck是根据教程抓的，url和作者说的是一样的），因为重新安装会自动填入上一次安装填写的Cookie信息，重装也就没有再次填一遍ck。重新删掉自动填写的ck，再手动填一次就解决了访问主页提示重新安装的问题了。。
> 2. 后台访问不了，我重新访问安装界面ip:port/install.php重新安装了一下解决了。。。
>    现在都解决了，记录一下。
> 3. 有一样问题的可以参考一下我的方式
> 
> ## 您的设备信息
> Docker version 1.13.1, build 7d71120/1.13.1 Linux ser701007685822 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x8 6_64 x8 6_64 GNU/Linux

v3.0.x版本是直接判断cookie中的关键词来判断是否成功的，可以在网页端进行打开分享链接、下载等操作生成相关的关键词再抓包获取。原先只需要bduss和stoken两个参数就可以获取列表信息和下载，今年百度修改了相关策略，不完整的cookie会报错9019，具体需要的参数还有待测试，所以目前推荐的做法就是填写完整的cookie。

**Comment by yuantuo666** [comment]
请更新最新4.0.0版本尝试 https://github.com/yuantuo666/baiduwp-php/releases/tag/v4.0.0
如仍有问题请重新打开议题
