### ISSUE TITLE
【寻求帮助】bduss和stoken添加问题

### ISSUE THREAD

**Issue by C315703603** [yuantuo666/baiduwp-php#296]
Table \'sfydb_6586355.bdwp_svip\' doesn\'t exist
![24XK0{ PKGLLONX}$AKO KY](https://github.com/yuantuo666/baiduwp-php/assets/103497700/369db132-7453-4b0b-9e1c-ca0badd8e161)

**Comment by xiaojieen** [comment]
有人解决吗

**Comment by lc6464** [comment]
看起来是数据库没有正常初始化，或者直接强改了 `config.php`，也有可能是数据库那边出问题了。

**Comment by yuantuo666** [comment]
请尝试使用 release 中的最新版本，目前正在进行重构，暂时不会修复主分支中存在的 bug

**Comment by C315703603** [comment]
![DKBVCN~T}YE5$S@Y1ADG(6G](https://github.com/yuantuo666/baiduwp-php/assets/103497700/02d79d1b-df1f-43ff-927e-7ab348e545bc)
重新安装不勾选保留以前数据库数据的话提交会出现这个。

**Comment by yuantuo666** [comment]
请更新最新4.0.0版本尝试 https://github.com/yuantuo666/baiduwp-php/releases/tag/v4.0.0
如仍有问题请重新打开议题
