### ISSUE TITLE
【建议】

### ISSUE THREAD

**Issue by yaoysyao** [yuantuo666/baiduwp-php#298]
## 描述建议
能否支持文件夹下载

## 此建议将如何工作
工作步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 相关的技术
如果您有能力，您可以在此提供一些技术帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 补充信息
您可以在这里输入其他有关此建议的信息。

**Comment by yuantuo666** [comment]
参见 https://github.com/yuantuo666/baiduwp-php/issues/271
