### ISSUE TITLE
【寻求帮助】油猴脚本如何配合该网页版

### ISSUE THREAD

**Issue by Markli66** [yuantuo666/baiduwp-php#299]
## 描述问题
能否将此接口的API作为油猴脚本的后台使用？

## 如何复现此问题
复现此问题的步骤:
1.
2、

## 你需要的帮助
最近在学习油猴脚本的写作，希望能够写出来一个脚本依靠PHP网页版本作为后台进行解析。但是不清楚该从那个接口下手，譬如油猴脚本具体该从那个接口开始请求，获取的直链传递的方法是哪里？能否请教一下学习思路？

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
API 相关信息可参考这个：https://github.com/yuantuo666/baiduwp-php/blob/master/docs/API.md
另：建议不要公开，如果要公开，请自行考虑可能的法律风险，本项目的参与者将不承担任何法律风险
