### ISSUE TITLE
verifyPwd返回errno:105

### ISSUE THREAD

**Issue by UnknownObject000** [yuantuo666/baiduwp-php#30]
执行verifyPwd函数,返回:
```
<pre>verifyPwd():array(3) { 
["errno"]=>
  int(105)
  ["err_msg"]=>
  string(0) ""
  ["request_id"]=>
  int(8796716117421243224)
}
</pre>1
```

分享链接:
1H2HFWGVJNgxVOwvbw4lpNQ
密码:
7kwi
该链接经确认有效,密码正确.

**Comment by UnknownObject000** [comment]
使用错误的密码,除```request_id```外输出不发生变化.

**Comment by yuantuo666** [comment]
![Screenshot_20201006_224202_com android chrome](https://user-images.githubusercontent.com/44130602/95217023-52268380-0825-11eb-977a-04ac4c6a6ef3.jpg)
使用demo获取没有问题，

**Comment by yuantuo666** [comment]
暂不清楚这个错误代码的问题
你可以尝试更换服务器IP地址

**Comment by UnknownObject000** [comment]
> 暂不清楚这个错误代码的问题
> 你可以尝试更换服务器IP地址

更换IP尝试继续得到错误码105

**Comment by lc6464** [comment]
#45 
您好，这个问题在如今正在开发的版本中已经得到彻底解决，您可以等待下一个版本的发布，也可以直接 clone 储存库以提前体验（不建议，因为可能不稳定）。

**Comment by lc6464** [comment]
#45
