### ISSUE TITLE
 RPC地址没有错用的是Motrix改成16800那个端口 然后点发送就报Aria下载错误【寻求帮助】

### ISSUE THREAD

**Issue by qaz11ac** [yuantuo666/baiduwp-php#303]
## 描述问题
请在此填入对你遇到的问题清晰准确的描述。

## 如何复现此问题
复现此问题的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by lc6464** [comment]
请提供更为详细的信息。

**Comment by qaz11ac** [comment]
> 请提供更为详细的信息。

![微信图片_20230914185945](https://github.com/yuantuo666/baiduwp-php/assets/144626630/d4d2243a-8862-4be4-969b-26cff109a8e2)

**Comment by yuantuo666** [comment]
Motrix是什么报错呢

**Comment by yuantuo666** [comment]
https://github.com/yuantuo666/baiduwp-php/issues/305
