### ISSUE TITLE
【寻求帮助】4.0.0 版本报错 403 Forbidden 您没有权限访问该网页

### ISSUE THREAD

**Issue by Zwas1337** [yuantuo666/baiduwp-php#307]
在我更新4.0.0版本后我就访问不了网页了，用的本地，没有使用服务器，上面写着禁止，您没有权限访问该网页

**Comment by Zwas1337** [comment]
4.0.0版本的问题

**Comment by lc6464** [comment]
请添加截图。

**Comment by yuantuo666** [comment]
4.0.0和以前的架构不同，使用了ThinkPHP框架，入口文件在/public下的index.php，并且需要设置相关伪静态。

建议使用docker来运行程序。
如执意要自行搭建，请搜索 “你所使用的环境+ThinkPHP部署教程”，例如“宝塔面板ThinkPHP部署教程”
