### ISSUE TITLE
install安装过程出现数据库初始化失败【寻求帮助】

### ISSUE THREAD

**Issue by lianggegod** [yuantuo666/baiduwp-php#308]
出错图床[https://img.gejiba.com/images/3f25649d5613b252c8789354f68e0486.png](url)
8.1安装扩展[https://img.gejiba.com/images/7eff2bc91d4b9c09e7003e1a0274fc0b.png](url)
PHP用的8.1
MySQL用的 5.6

**Comment by yuantuo666** [comment]
数据库名没有填写。

**Comment by yuantuo666** [comment]
此 issue 问题描述不清楚，详细信息参见 https://github.com/yuantuo666/baiduwp-php/issues/311
