### ISSUE TITLE
【建议】增加通过环境变量快速配置项目的功能

### ISSUE THREAD

**Issue by cooliceycold** [yuantuo666/baiduwp-php#312]
请问可以直接环境变量配置数据库之类的跳过安装吗?
我想在zeabur 或者render上部署 会清数据回到未安装状态 
而且我昨天临时部署配置了一下  似乎大于2G的文件无法解析  不清楚是啥问题

**Comment by yuantuo666** [comment]
测试可以顺利在 zeabur 上部署，不停止服务的情况下是不会清空数据的。
一般的 docker 容器停止之后重新启动是不会清除数据的，或者就是在启动时挂载目录来实现数据持久化。

确实可以考虑增加 外部配置文件 或者 通过环境变量进行快速配置项目

**Comment by yuantuo666** [comment]
如果有无法解析的情况，请附上链接和测试截图开新的 issue，一个 issue 对应一个问题

**Comment by yuantuo666** [comment]
因内外多种因素，本项目将不会增加新功能，仅维护现存的 BUG。若接口失效，本项目将停止更新。
