### ISSUE TITLE
【BUG 反馈】舊版連結無法使用

### ISSUE THREAD

**Issue by samuel990419** [yuantuo666/baiduwp-php#313]
## 描述 Bug
使用oneleaf和許多版本的本工具都無法使用，這個連結https://pan.baidu.com/share/link?shareid=206488&uk=1778675540&third=0

## 如何复现此 Bug
复现此 Bug 的步骤:
1. 打開工具
2. 輸入該連結
3. 報錯

## 期望
希望能成功解析

**Comment by yuantuo666** [comment]
2.2.0 版本就兼容了旧版本链接，后面因为使用频率不高，加上百度接口修改，就没有继续兼容。
相关代码已经编写完成（https://github.com/yuantuo666/baiduwp-php/commit/e921de91e5f50b3a45fcec88b4f070568f17f829），下一个版本将会重新兼容旧版本链接。
