### ISSUE TITLE
【BUG 反馈】会员账号不切换

### ISSUE THREAD

**Issue by yybxrsp258** [yuantuo666/baiduwp-php#314]
## 描述 Bug
账号不能切换，一直使用一个账号

## 如何复现此 Bug
复现此 Bug 的步骤:
后台网站设置切换随机账号，无论开启与否都使用一个账号

## 期望
希望作者验证并修复一下

## 截图
![image](https://github.com/yuantuo666/baiduwp-php/assets/65845535/a59af955-44e6-4951-8864-3b1039700394)

**Comment by yuantuo666** [comment]
是指不能随机使用账号吗，还是指不会在账号封禁之后切换

**Comment by imyyer** [comment]
> 是指不能随机使用账号吗，还是指不会在账号封禁之后切换

是指不能随机账号，我也是

**Comment by yuantuo666** [comment]
https://github.com/yuantuo666/baiduwp-php/blob/7bc2eeb9fdcc53d7dc284d1c10507b9f1755dd17/app/Parse.php#L271C45-L271C49
这里的代码写错了，应该将 `desc` 修改为 `asc`
下一个版本修复这个问题
