### ISSUE TITLE
【寻求帮助】如何像旧版本一样会员账号轮换解析？

### ISSUE THREAD

**Issue by imyyer** [yuantuo666/baiduwp-php#315]
现在新版本更新了，如何像旧版本一样会员账号轮换模式？那个随机账号解析好像没有用，还是固定一个来解析的，反正我就是想要解析一个文件换一个账号，顺序不顺序都无所谓。还有就是那个更新那里说优化API，请问这里能细说下吗？

**Comment by imyyer** [comment]
旧版本的API是不能用了还是说新版本的更加稳定？

**Comment by yuantuo666** [comment]
仍然可以使用旧版本的API，只是如果有漏洞或者 bug 不会再有维护了。新版本的随机帐号功能设计是用来实现轮换帐号的，可能是逻辑有问题所以没效果，下一个版本会修复这个问题。

**Comment by imyyer** [comment]
> 仍然可以使用旧版本的API，只是如果有漏洞或者 bug 不会再有维护了。新版本的随机帐号功能设计是用来实现轮换帐号的，可能是逻辑有问题所以没效果，下一个版本会修复这个问题。

好的

**Comment by yuantuo666** [comment]
重复 https://github.com/yuantuo666/baiduwp-php/issues/314
