### ISSUE TITLE
【寻求帮助】如何自定义API接口的路由

### ISSUE THREAD

**Issue by Markli66** [yuantuo666/baiduwp-php#316]
## 描述问题
通过查阅接口文档得知，/parse/link是去获取真实下载链接的接口，文档中其余操作，其实可以通过浏览器获取文件id后通过官方pan.xx的接口来获取sing 或是fast_id等，那么这个时候假如我这些操作都自己内部操作完成，只获取某一个具体文件的真实下载链接的情况下，又不想暴露XX(域名)/parse/link 的接口 那么请问有何种策略可以将他隐藏起来。通过指定某一个二级域名或者是其他方式来获取真实下载链接呢？

## 如何复现此问题
复现此问题的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
修改 /route/app.php 中对应的路由即可 https://github.com/yuantuo666/baiduwp-php/blob/e921de91e5f50b3a45fcec88b4f070568f17f829/route/app.php#L23C12-L23C12

**Comment by Markli66** [comment]
非常感谢，感觉长脑子了。
