### ISSUE TITLE
【建议】支持网址前缀，BaseURL

### ISSUE THREAD

**Issue by Eisaichen** [yuantuo666/baiduwp-php#318]
## 描述建议
支持网址前缀，BaseURL
例如可以在`mydomain.com/pdown/`路径下工作
3.x以及之前的版本不存在此问题，但4.x的新架构只在根目录下工作

## 此建议将如何工作
工作步骤:
1. 添加BaseURL设置项
2. 修改源码中Hard-coded路径

**Comment by yuantuo666** [comment]
旧版本因为入口文件在根目录下，很容易就可以实现这个功能，并且可以在子目录下搭建使用。

但是新系统使用了 ThinkPHP 框架，支持端口监听启动和入口文件启动（在/ public 文件夹下），这两种情况都不适合在子目录下搭建，不按照要求搭建反而可能导致数据泄露。

如果你想要实现该功能，可以尝试任意一种方法：
1. 修改 nginx 或 apache 配置，将子目录下请求转发到 PHP 服务。
2. 修改 ThinkPHP 路由配置（ /route/app.php ），给所有的路由添加一个 group 路由，实现该功能。

综上所述，目前的架构没必要支持该功能，有这个需求可按照上面步骤自行修改。
