### ISSUE TITLE
功能建议及问题

### ISSUE THREAD

**Issue by design-1996** [yuantuo666/baiduwp-php#32]
推送到aria2下载总是失败。试了多次就成功过一次。建议提供aria2直接下载地址复制，手动添加到aria2上进行下载。就用的作者你提供的演示地址

**Comment by design-1996** [comment]
手机上推送成功，电脑上推送失败。。。。。

**Comment by yuantuo666** [comment]
检查一下你电脑端的版本和是否开启了RPC
下载链接可以直接复制粘贴到可以设置ua的下载器下载
aria2设置ua即可下载

**Comment by design-1996** [comment]
> 检查一下你电脑端的版本和是否开启了RPC
> 下载链接可以直接复制粘贴到可以设置ua的下载器下载
> aria2设置ua即可下载

我是服务器部署的aria2。手机能成功推送，pc都检测不到。设置是一模一样的的，用的谷歌浏览器

**Comment by yuantuo666** [comment]
请尝试自己研究~
