### ISSUE TITLE
【BUG 反馈】下载链接保存数据库报错 - Out of range value for column `size` 

### ISSUE THREAD

**Issue by huangbh1024** [yuantuo666/baiduwp-php#321]
![image](https://github.com/yuantuo666/baiduwp-php/assets/72372968/7df3f85c-da1d-47de-813b-1ee23a9b9ec4)
![image](https://github.com/yuantuo666/baiduwp-php/assets/72372968/a8dbeb90-2fa8-4b98-abf8-34b61ed2bf6e)

**Comment by yuantuo666** [comment]
请修改 .env 中的 APP_DEBUG=false 为 APP_DEBUG=true 启动调试模式
再获取下载链接，将返回的内容抓包贴上来

**Comment by huangbh1024** [comment]
> 请修改 .env 中的 APP_DEBUG=false 为 APP_DEBUG=true 启动调试模式 再获取下载链接，将返回的内容抓包贴上来

![image](https://github.com/yuantuo666/baiduwp-php/assets/72372968/8f9a4831-fe34-4239-b316-a27560553643)

**Comment by yuantuo666** [comment]
看上去是无法连接百度服务器

**Comment by huangbh1024** [comment]
> 看上去是网络问题，无法连接百度服务器，并不是程序的问题

刷新后重新获取，报错就变成这个了
![image](https://github.com/yuantuo666/baiduwp-php/assets/72372968/d0dae000-a505-4a73-ac79-9edcf2dc4f49)

**Comment by huangbh1024** [comment]
> 看上去是网络问题，无法连接百度服务器，并不是程序的问题

刷新后重新获取，报错变成这个了
![image](https://github.com/yuantuo666/baiduwp-php/assets/72372968/3cf32802-9cb4-40a5-9687-5cdd155244fd)

**Comment by yuantuo666** [comment]
切换到 Response 这个 tab 下面，然后将内容复制后贴上来，相关隐私信息可以删除

**Comment by huangbh1024** [comment]
> 切换到 Response 这个 tab 下面，然后将内容复制后贴上来，相关隐私信息可以删除

{
  "code": 10501,
  "message": "SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'size' at row 1",
  "traces": [
    {
      "name": "think\\db\\exception\\PDOException",
      "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/think-orm/src/db/PDOConnection.php",
      "line": 836,
      "code": 10501,
      "message": "SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'size' at row 1",
      "trace": [
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/think-orm/src/db/PDOConnection.php",
          "line": 899,
          "function": "getPDOStatement",
          "class": "think\\db\\PDOConnection",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/think-orm/src/db/PDOConnection.php",
          "line": 860,
          "function": "queryPDOStatement",
          "class": "think\\db\\PDOConnection",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/think-orm/src/db/PDOConnection.php",
          "line": 989,
          "function": "pdoExecute",
          "class": "think\\db\\PDOConnection",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/think-orm/src/db/BaseQuery.php",
          "line": 1166,
          "function": "insert",
          "class": "think\\db\\PDOConnection",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/app/Parse.php",
          "line": 329,
          "function": "insert",
          "class": "think\\db\\BaseQuery",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/app/controller/Parse.php",
          "line": 37,
          "function": "download",
          "class": "app\\Parse",
          "type": "::"
        },
        {
          "function": "link",
          "class": "app\\controller\\Parse",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Container.php",
          "line": 345,
          "function": "invokeArgs",
          "class": "ReflectionMethod",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/route/dispatch/Controller.php",
          "line": 110,
          "function": "invokeReflectMethod",
          "class": "think\\Container",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 59,
          "function": "think\\route\\dispatch\\{closure}",
          "class": "think\\route\\dispatch\\Controller",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 66,
          "function": "think\\{closure}",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/route/dispatch/Controller.php",
          "line": 113,
          "function": "then",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/route/Dispatch.php",
          "line": 52,
          "function": "exec",
          "class": "think\\route\\dispatch\\Controller",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Route.php",
          "line": 755,
          "function": "run",
          "class": "think\\route\\Dispatch",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 59,
          "function": "think\\{closure}",
          "class": "think\\Route",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/app/middleware/CheckPassword.php",
          "line": 19,
          "function": "think\\{closure}",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "function": "handle",
          "class": "app\\middleware\\CheckPassword",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Middleware.php",
          "line": 134,
          "function": "call_user_func"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 85,
          "function": "think\\{closure}",
          "class": "think\\Middleware",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 66,
          "function": "think\\{closure}",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Route.php",
          "line": 756,
          "function": "then",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Http.php",
          "line": 208,
          "function": "dispatch",
          "class": "think\\Route",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Http.php",
          "line": 198,
          "function": "dispatchToRoute",
          "class": "think\\Http",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 59,
          "function": "think\\{closure}",
          "class": "think\\Http",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/middleware/SessionInit.php",
          "line": 58,
          "function": "think\\{closure}",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "function": "handle",
          "class": "think\\middleware\\SessionInit",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Middleware.php",
          "line": 134,
          "function": "call_user_func"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 85,
          "function": "think\\{closure}",
          "class": "think\\Middleware",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/think-trace/src/TraceDebug.php",
          "line": 71,
          "function": "think\\{closure}",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "function": "handle",
          "class": "think\\trace\\TraceDebug",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Middleware.php",
          "line": 134,
          "function": "call_user_func"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 85,
          "function": "think\\{closure}",
          "class": "think\\Middleware",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Pipeline.php",
          "line": 66,
          "function": "think\\{closure}",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Http.php",
          "line": 199,
          "function": "then",
          "class": "think\\Pipeline",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/vendor/topthink/framework/src/think/Http.php",
          "line": 162,
          "function": "runWithRequest",
          "class": "think\\Http",
          "type": "->"
        },
        {
          "file": "/www/wwwroot/fuckwp.xxx.cn/public/index.php",
          "line": 20,
          "function": "run",
          "class": "think\\Http",
          "type": "->"
        }
      ],
      "source": {
        "first": 827,
        "source": [
          "            } else {\n",
          "                if ($this->reConnectTimes < 4 && $this->isBreak($e)) {\n",
          "                    $this->reConnectTimes++;\n",
          "\n",
          "                    return $this->close()->getPDOStatement($sql, $bind, $master, $procedure);\n",
          "                }\n",
          "            }\n",
          "\n",
          "            if ($e instanceof \\PDOException) {\n",
          "                throw new PDOException($e, $this->config, $this->getLastsql());\n",
          "            } else {\n",
          "                throw $e;\n",
          "            }\n",
          "        }\n",
          "    }\n",
          "\n",
          "    /**\n",
          "     * 执行语句.\n",
          "     *\n"
        ]
      }
    }
  ],
  "datas": {
    "PDO Error Info": {
      "SQLSTATE": "22003",
      "Driver Error Code": 1264,
      "Driver Error Message": "Out of range value for column 'size' at row 1"
    },
    "Database Status": {
      "Error Code": 10501,
      "Error Message": "SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'size' at row 1",
      "Error SQL": "INSERT INTO `records` SET `ip` = '120.41.130.11' , `ua` = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' , `name` = '20436_PureSkyDIY_STAR_MI11UP_V12.5.17.0.RKACNXM_0c5335af30_TwoInOne_11.zip' , `size` = 3949427675 , `md5` = '664dc4064d2157fa42634b66adb3cd99' , `link` = 'http://bjbgp01.baidupcs.com/file/4c02129deve609e9ac9088fecbc88689?bkt=en-07c9b0a504a37060deada4f6260e1641d255533b89deeecc05e87be0fe96593e8999b8278f8bc443&fid=3522021481-250528-338997487234205&time=1696730010&sign=FDTAXUbGERQlBHSKfWaqiu-DCb740ccc5511e5e8fedcff06b081203-bQ9l%2FO3GATxDq%2B5WVeyPkbB%2F8YY%3D&to=14&size=3949427675&sta_dx=3949427675&sta_cs=1&sta_ft=zip&sta_ct=7&sta_mt=7&fm2=MH%2CBaoding%2CAnywhere%2C%2C%E5%B9%BF%E4%B8%9C%2Cany&ctime=1660619229&mtime=1662895293&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=3949427675&vuk=782805242&iv=2&htype=&randtype=&tkbind_id=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-7494c2c3ff9f1574cad8928373256ed6cfecb1cac7a9b2e0eaed5a048a8bec87b9c1b4ef6000ecab&expires=8h&rt=sh&r=981128078&vbdid=-&fin=20436_PureSkyDIY_STAR_MI11UP_V12.5.17.0.RKACNXM_0c5335af30_TwoInOne_11.zip&rtype=1&dp-logid=8809392562848265934&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=O%2F8QJiBGVJNIFhqIzn8eyHkqD5M%3D&so=1&ut=1&uter=0&serv=0&uc=3200815480&ti=e292035734ac5995e1687e538f02a58e30a8d7b4303a2e55305a5e1275657320&hflag=30&from_type=3&adg=c_750a7ab806371112f41636a983e1a5c9&reqlabel=250528_f_e8a55db5097c5ef5eb46c151979775cc_-1_832542484c58a0fcc01cfcee3a2e4094&by=themis&resvsflag=1-12-0-1-1-1' , `time` = '2023-10-08 09:53:30' , `account` = 1"
    },
    "Database Config": {
      "type": "mysql",
      "hostname": "127.0.0.1",
      "database": "baiduwp",
      "hostport": "3306",
      "dsn": "",
      "params": [],
      "charset": "utf8",
      "prefix": "",
      "deploy": 0,
      "rw_separate": false,
      "master_num": 1,
      "slave_no": "",
      "read_master": false,
      "fields_strict": true,
      "fields_cache": false,
      "trigger_sql": true,
      "builder": "",
      "query": "",
      "break_reconnect": false,
      "break_match_str": [],
      "auto_param_bind": true
    }
  },
  "tables": {
    "GET Data": [],
    "POST Data": {
      "fs_id": "338997487234205",
      "timestamp": "1696730008",
      "sign": "1f532a50dc6d6c334dc2d33cb5d3872373477293",
      "randsk": "q5mJ1B7cJG8xnts4JEv458i0V1QhrN2Ga%2BhSltqJSSo%3D",
      "shareid": "17095931514",
      "surl": "1tSdaz7h-mvWrJlU2B7S-VQ",
      "pwd": "d3nm",
      "uk": "3522021481"
    },
    "Files": null,
    "Cookies": {
      "PHPSESSID": "xxx",
      "thinkphp_show_page_trace": "0|0"
    },
    "Session": {
      "admin": true,
      "Password": "xxx"
    },
    "Server/Request Data": {
      "USER": "www",
      "HOME": "/home/www",
      "HTTP_X_FORWARDED_FOR": "120.41.130.11",
      "HTTP_X_CLIENT_SCHEME": "http",
      "HTTP_X_ALICDN_DA_VIA": "27.152.185.46,47.120.230.72",
      "HTTP_VIA": "cn3189.l1, l2sm92-3.l2",
      "HTTP_REFERER": "http://fuckwp.xxx.cn/",
      "HTTP_PRAGMA": "no-cache",
      "HTTP_ORIGIN": "http://fuckwp.xxx.cn",
      "HTTP_EAGLEEYE_TRACEID": "1b98b91a16967300098081784e",
      "HTTP_COOKIE": "xxx",
      "HTTP_CONTENT_TYPE": "application/x-www-form-urlencoded",
      "HTTP_CACHE_CONTROL": "no-cache",
      "HTTP_ALI_SWIFT_STAT_HOST": "fuckwp.xxx.cn",
      "HTTP_ALI_SWIFT_LOG_HOST": "fuckwp.xxx.cn",
      "HTTP_ALI_SWIFT_FORCE_TTL_CODE": "400=0",
      "HTTP_ALI_CDN_REAL_PORT": "54257",
      "HTTP_ALI_CDN_REAL_IP": "120.41.130.11",
      "HTTP_ALI_CDN_APPVIEW_NAME": "cdn-tengine",
      "HTTP_ACCEPT_LANGUAGE": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7,en-US;q=0.6,ru;q=0.5",
      "HTTP_ACCEPT_ENCODING": "gzip, deflate",
      "HTTP_ACCEPT": "application/json",
      "HTTP_CONTENT_LENGTH": "220",
      "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
      "HTTP_HOST": "fuckwp.xxx.cn",
      "PATH_INFO": "",
      "REDIRECT_STATUS": "200",
      "SERVER_NAME": "fuckwp.xxx.cn",
      "SERVER_PORT": "80",
      "SERVER_ADDR": "172.19.158.244",
      "REMOTE_PORT": "32096",
      "REMOTE_ADDR": "47.120.230.88",
      "SERVER_SOFTWARE": "nginx/1.22.1",
      "GATEWAY_INTERFACE": "CGI/1.1",
      "REQUEST_SCHEME": "http",
      "SERVER_PROTOCOL": "HTTP/1.1",
      "DOCUMENT_ROOT": "/www/wwwroot/fuckwp.xxx.cn/public",
      "DOCUMENT_URI": "/index.php",
      "REQUEST_URI": "/parse/link",
      "SCRIPT_NAME": "/index.php",
      "CONTENT_LENGTH": "220",
      "CONTENT_TYPE": "application/x-www-form-urlencoded",
      "REQUEST_METHOD": "POST",
      "QUERY_STRING": "s=/parse/link",
      "SCRIPT_FILENAME": "/www/wwwroot/fuckwp.xxx.cn/public/index.php",
      "FCGI_ROLE": "RESPONDER",
      "PHP_SELF": "/index.php",
      "REQUEST_TIME_FLOAT": 1696730009.820458,
      "REQUEST_TIME": 1696730009
    }
  }
}

**Comment by yuantuo666** [comment]
应该是数据库 size 的类型有问题，下一个版本会修复这个问题

**Comment by huangbh1024** [comment]
> 应该是数据库 size 的类型有问题，下一个版本会修复这个问题

好的

**Comment by czjnihao** [comment]
把数据库中 的size 类型 从int 改成bigint  解析大文件就不会报错了
