### ISSUE TITLE
【寻求帮助】

### ISSUE THREAD

**Issue by zhiyungezhu** [yuantuo666/baiduwp-php#322]
## 描述问题
请在此填入对你遇到的问题清晰准确的描述。

## 如何复现此问题
复现此问题的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by zhiyungezhu** [comment]
解压并设置完以后，网页刷新提示这个，试了很多操作还是不行。
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.33
![image](https://github.com/yuantuo666/baiduwp-php/assets/140409713/f110a203-04e6-471b-bcea-d9120fb26742)

**Comment by yuantuo666** [comment]
PHP 版本太低了，4.0.0+ 版本需要最低 PHP 8.0 版本

**Comment by zhiyungezhu** [comment]
天，应该是大于8.0版本才对，我昨天安装8.0版本以后还是提示有问题，刚刚重新试了8.2就没问题了，再请教个问题呢，现在是3.0.2版本，使用IDM下载会下载成401或者下图这样，怎么修复呢？之前还好好的
![image](https://github.com/yuantuo666/baiduwp-php/assets/140409713/55107538-1339-4e9f-9265-87127c98c465)

**Comment by yuantuo666** [comment]
PHP 8.0.30 测试是没问题的（Docker 的 php:8.0 镜像）。旧版本不会有后续维护，建议更新到最新版本重试，仍有问题请开新议题描述问题并提供复现的步骤。
