### ISSUE TITLE
【寻求帮助】未知错误代码：2

### ISSUE THREAD

**Issue by Markli66** [yuantuo666/baiduwp-php#323]
## 描述问题
请在此填入对你遇到的问题清晰准确的描述。

## 如何复现此问题
复现此问题的步骤:
1. 下载请求的时候出现未知错误代码
具体返回JSON参数为：
{
    "readyState": 4,
    "responseHeaders": "alt-svc: h3=\":443\"; ma=86400\r\ncache-control: no-store, no-cache, must-revalidate\r\ncf-cache-status: DYNAMIC\r\ncf-ray: 814104249f8a284c-SEA\r\ncontent-encoding: br\r\ncontent-type: text/html; charset=UTF-8\r\ndate: Tue, 10 Oct 2023 18:44:43 GMT\r\nexpires: Thu, 19 Nov 1981 08:52:00 GMT\r\nnel: {\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}\r\npragma: no-cache\r\nreport-to: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=msyApHEVIZOHGGQ5s9B3fVv78AUXVmdEMrfJX0ihEGlMaVPI2QnWcxz0mBnl0A%2FvZZ%2BiRUIS0SXRCLJ9G87sW2qT2NSpnijr75DGGKskgshbWY3W6deDEupym0XX3bvDMTyAJLQGhWbCwI34lp9Q\"}],\"group\":\"cf-nel\",\"max_age\":604800}\r\nserver: cloudflare\r\nstrict-transport-security: max-age=31536000\r\nset-cookie: PHPSESSID=0qq8335gelji222plumtlo2qm2; path=/\r\nvary: Accept-Encoding\r\n",
    "finalUrl": "https://bdwp.cclocal.top/",
    "status": 200,
    "statusText": "",
    "DONE": 4,
    "HEADERS_RECEIVED": 2,
    "LOADING": 3,
    "OPENED": 1,
    "UNSENT": 0,
    "RESPONSE_TYPE_TEXT": "text",
    "RESPONSE_TYPE_ARRAYBUFFER": "arraybuffer",
    "RESPONSE_TYPE_BLOB": "blob",
    "RESPONSE_TYPE_DOCUMENT": "document",
    "RESPONSE_TYPE_JSON": "json",
    "RESPONSE_TYPE_STREAM": "stream"
}

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
抓包抓错了，这是 Cloudflare 统计的返回数据，需要先打开debug模式才可以抓包看到详细信息，具体方式参见 https://github.com/yuantuo666/baiduwp-php/issues/321#issuecomment-1751889650

**Comment by Markli66** [comment]
在获取列表的时候这个URL为

**Comment by Markli66** [comment]
在获取列表这一步，请求https://pan.baidu.com/share/wxlist?channel=weixin&version=2.2.2&clienttype=25&web=1&qq-pf-to=pcqq.c2c 
 的时候返回了false 
 想知道这个message在浏览器中这样子显示{"success":false,"message":"\u901a\u77e5\u4e00\u4e0b\u7ba1\u7406\u5458\u83b7\u53d6\u5217\u8868\u7684\u4ee3\u7406\u8d26\u53f7\u51fa\u73b0\u95ee\u98989019"}

**Comment by yuantuo666** [comment]
> 在获取列表这一步，请求https://pan.baidu.com/share/wxlist?channel=weixin&version=2.2.2&clienttype=25&web=1&qq-pf-to=pcqq.c2c 的时候返回了false 想知道这个message在浏览器中这样子显示{"success":false,"message":"\u901a\u77e5\u4e00\u4e0b\u7ba1\u7406\u5458\u83b7\u53d6\u5217\u8868\u7684\u4ee3\u7406\u8d26\u53f7\u51fa\u73b0\u95ee\u98989019"}

这个接口不是本项目使用的，因为种种原因也不方便透露更多的信息。

**Comment by Markli66** [comment]
理解了，非常感谢。

**Comment by Markli66** [comment]
请问一下是否有方法，能够在一台设备获取多个Cookie，根据代码提示listError方法是用来判断的状态码进行的Json参数解析，向上推论getList方法进行调用，那么也就是说如果我只添加一个Cookie的时候，从接收网页入口提交的分享链接开始就已经获取过一次list了。这样是不是存在二次使用账号的情况？如果能够时间将Cookie的某个值进行替换从而保活N+个Cookie的话是否逻辑会比较好些？

**Comment by yuantuo666** [comment]
> 请问一下是否有方法，能够在一台设备获取多个Cookie，根据代码提示listError方法是用来判断的状态码进行的Json参数解析，向上推论getList方法进行调用，那么也就是说如果我只添加一个Cookie的时候，从接收网页入口提交的分享链接开始就已经获取过一次list了。这样是不是存在二次使用账号的情况？如果能够时间将Cookie的某个值进行替换从而保活N+个Cookie的话是否逻辑会比较好些？

获取 list 不会封号。
