### ISSUE TITLE
index.php(18): think\Container->__get('http')【寻求帮助】

### ISSUE THREAD

**Issue by qiurigao** [yuantuo666/baiduwp-php#324]
Fatal error: Uncaught Error: Call to undefined function think\helper\ctype_lower() in /www/d/vendor/topthink/think-helper/src/helper/Str.php:181 Stack trace: #0 /www/d/vendor/topthink/framework/src/think/Container.php(446): think\helper\Str::snake('app') #1 /www/d/vendor/topthink/framework/src/think/Container.php(394): think\Container->bindParams(Object(ReflectionMethod), Array) #2 /www/d/vendor/topthink/framework/src/think/Container.php(253): think\Container->invokeClass('think\\Http', Array) #3 /www/d/vendor/topthink/framework/src/think/Container.php(132): think\Container->make('think\\Http') #4 /www/d/vendor/topthink/framework/src/think/Container.php(514): think\Container->get('http') #5 /www/d/public/index.php(18): think\Container->__get('http') #6 {main} thrown in /www/d/vendor/topthink/think-helper/src/helper/Str.php on line 181

**Comment by yuantuo666** [comment]
能否提供复现的方法？看上去并不是本项目的 bug 而是 ThinkPHP 的 bug

**Comment by yuantuo666** [comment]
建议使用 docker 搭建，应该是 PHP 的版本或者配置有问题，并不是本程序的问题。
