### ISSUE TITLE
【寻求帮助】解析比较大的文件就会显示获取下载链接失败，解析小一些的文件就能够正常解析

### ISSUE THREAD

**Issue by echothesky** [yuantuo666/baiduwp-php#326]
## 描述问题。
运行是正常的，解析一些小一点的文件的时候很正常可以解析到链接，但解析一些大一点的文件，例如4.5G大小的文件时就会解析失败

## 如何复现此问题
网址：www.echothesky.eu.org
cookie是使用edge浏览器的网页抓取的

## 您的设备信息
 使用的宝塔面板搭建，
php版本8.2.4，mysql版本5.7.40，
系统为Ubuntu 20.04 LTS x86_64(Py3.7.9)，
web服务器使用的是Apache 2.4.57
使用的是国外的vps

希望大佬能够在百忙之中抽空解答，谢谢！

**Comment by echothesky** [comment]
![屏幕截图 2023-11-02 200931](https://github.com/yuantuo666/baiduwp-php/assets/106248959/632a4b54-8e2f-4129-8572-b4f2535b6098)
忘记贴图了，补一下

**Comment by yuantuo666** [comment]
修改 .env 中 APP_DEBUG 为 true，然后在浏览器按 F12 抓包看具体的报错是什么，可以截图贴上来。

**Comment by echothesky** [comment]
> 修改 .env 中 APP_DEBUG 为 true，然后在浏览器按 F12 抓包看具体的报错是什么，可以截图贴上来。
![image](https://github.com/yuantuo666/baiduwp-php/assets/106248959/a2ab2385-3132-40bc-bb3f-b6f305fc8f23)

**Comment by echothesky** [comment]
> > 修改 .env 中 APP_DEBUG 为 true，然后在浏览器按 F12 抓包看具体的报错是什么，可以截图贴上来。
> > ![image](https://user-images.githubusercontent.com/106248959/280160503-a2ab2385-3132-40bc-bb3f-b6f305fc8f23.png)

如图所示

**Comment by echothesky** [comment]
![image](https://github.com/yuantuo666/baiduwp-php/assets/106248959/f2f743f1-5e50-47af-b514-743a3dcc3d40)
配置文件修改如上

**Comment by yuantuo666** [comment]
和 https://github.com/yuantuo666/baiduwp-php/issues/321 一样的问题，文件大小超过了限制
