### ISSUE TITLE
【BUG 反馈】大于4G的文件下载失败

### ISSUE THREAD

**Issue by codycjy** [yuantuo666/baiduwp-php#327]
## 描述 Bug
在遇到超过4GB的文件时，获取链接时会出现服务端500错误
`SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'size' at row 1`

## 如何复现此 Bug
复现此 Bug 的步骤:
1. 找到一个大于4GB的文件（我个人遇到的是22GiB的），生成分享链接
2. 解析链接并下载

## 期望
在将数据库中records 字段的size列改为bigint后问题解决
是否有需要将size字段修改为bigint，或者转为KiB储存，在一些电影等场景大于4GB的文件还是较为常见的

## 您的设备信息
- 使用docker部署
 - 访问项目的浏览器版本: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

**Comment by yuantuo666** [comment]
和 https://github.com/yuantuo666/baiduwp-php/issues/321 一样的问题，下一版本会修复这一bug
