### ISSUE TITLE
【BUG 反馈】后台设置了网站解析密码，但是前端不显示密码输入框

### ISSUE THREAD

**Issue by 2693114079** [yuantuo666/baiduwp-php#329]
后台设置首页面密码不生效，前端不会出现填写密码的选项
<img width="1035" alt="image" src="https://github.com/yuantuo666/baiduwp-php/assets/87026074/c6a432af-1035-4305-a806-1d9036be48d4">
<img width="975" alt="image" src="https://github.com/yuantuo666/baiduwp-php/assets/87026074/168d71ed-fe0f-4853-a262-05d7808fd1e5">
<img width="785" alt="image" src="https://github.com/yuantuo666/baiduwp-php/assets/87026074/5473d60d-afa5-4e42-86b1-209aeedc6fe2">

**Comment by yuantuo666** [comment]
开启密码后刷新网页，就会出现密码框

**Comment by yuantuo666** [comment]
没出现可能是缓存问题，可以按F12切换到网络选项卡抓包查看有无失败的请求

**Comment by 2693114079** [comment]
不是缓存问题，换浏览器试过了，但是f12发现有一个请求失败的，
![image](https://github.com/yuantuo666/baiduwp-php/assets/87026074/7b4f276f-352f-49c3-b894-b7db4ec48c5b)

**Comment by 2693114079** [comment]
> 没出现可能是缓存问题，可以按F12切换到网络选项卡抓包查看有无失败的请求

不是缓存问题，刷新网页也不会出现密码框，但是我F12下看到一个重要的文件请求失败

我的网站地址：yun.92wk.asia  管理员密1314,你可以看下，辛苦了
![image](https://github.com/yuantuo666/baiduwp-php/assets/87026074/1ada23fd-438a-4093-8027-446f41f1691c)

**Comment by yuantuo666** [comment]
请修改 .env 中的 APP_DEBUG=false 为 APP_DEBUG=true 启动调试模式

**Comment by 2693114079** [comment]
> 请修改 .env 中的 APP_DEBUG=false 为 APP_DEBUG=true 启动调试模式，这样就可以看到详细的报错信息

修改了
![image](https://github.com/yuantuo666/baiduwp-php/assets/87026074/3afcc031-e873-455a-859c-81a113ed7078)

**Comment by yuantuo666** [comment]
看上去是 Session 启动失败了，可能是你的 PHP 环境搭建过别的项目，修改过默认的 PHP 配置导致的

**Comment by yuantuo666** [comment]
可以试试删除 app/controller/Auth.php 第 15 行 session_start(); 看看能否解决问题
