### ISSUE TITLE
请教一下作者百度端的限制问题。

### ISSUE THREAD

**Issue by chenshao** [yuantuo666/baiduwp-php#33]
1.作者说过，每个SVIP帐号，大概5T后会被限速，请问这个5T是指每天5T呢，还是累积到5T？
2.除了SVIP帐号会被限速，那服务器IP会被禁止访问百度接口吗？如果被禁止的话，是否会过段时间自动解封呢？
3.请问作者，你还知道百度端有哪些限制吗？

请不吝赐教，再次作者感谢开源！

**Comment by yuantuo666** [comment]
1.累计达到5TB限速。
之前的demo账号测试结果：使用一个月，解析（约）5TB文件被限速。
2.服务器IP被禁我没有遇到过。
根据网络上资料推测，解析pcs链接达到5万次后会提示错误，次日解封。不清楚是否与IP被禁是同一种机制。
![-77c887567b214afc](https://user-images.githubusercontent.com/44130602/97189132-38061280-17df-11eb-899c-e371df7eee86.jpg)
上图是一位站长提供的解析pcs链接错误图
一般情况下个人使用一般不会出现封IP的情况。
3.在代码中有注释。
例如获取的下载链接8小时有效、下载文件需要特定的UA等。

如果有共同开发或交流意向，欢迎邮箱联系。

**Comment by Penghaiku** [comment]
百度网盘svip的限速是多久啊？

**Comment by yuantuo666** [comment]
> 百度网盘svip的限速是多久啊？

限速没有具体时间，视情况而定。
如果是官方购买的SVIP账号可以向客服申诉解封，但超过三四次后可能客服也不会解封。

**Comment by Penghaiku** [comment]
>经过测试，多客户端登录，超过限制后，会受到百度网盘官方限制，封禁svip账号5~7天。
**封禁期间有如下异常**：
- 在线播放视频异常
   - 显示“该账号存在违规行为，暂时无法播放视频”
- 下载异常
   - 显示网络异常，或者限速
百度网盘人工客服邮件回复：

>您好， 经过核实， 违反网盘用户协议触发封禁， 一段时间内您可能会遇到下载网络异常、视频无法播放的情况， 建议您从官方>网站下载网盘进行使用， 百度网盘服务账号仅限个人使用， 不得有偿或无偿提供给第三方使用， 请您查看网盘用户使用协议， >按规则进行使用网盘。  感谢您的理解与支持， 祝您生活愉快。




不知道是不是因为baidu_php的原因，还是其他原因；
我的登陆截图如下：
![image](https://user-images.githubusercontent.com/46412151/98429295-d9933b00-20e0-11eb-91e6-65e7a85ac224.png)
![image](https://user-images.githubusercontent.com/46412151/98429304-e3b53980-20e0-11eb-98e5-15947c7d46b2.png)

**Comment by yuantuo666** [comment]
1.4.3版本获取下载列表与下载地址使用的cookie是分开的，此项目并不会自动登录SVIP账号，不会产生登录记录。
出现封禁可能是由于使用第三方客户端或登录客户端过多导致，出现限速可能是由于解析次数过多导致。
