### ISSUE TITLE
【寻求帮助】是否需要一个单独的域名访问

### ISSUE THREAD

**Issue by WernerHai** [yuantuo666/baiduwp-php#331]
以前我是放在主域名的二级目录下使用，现在需要解析域名到/public 目录，是不是只能使用单独的二级域名去解析了？

**Comment by yuantuo666** [comment]
新版本支持了子目录运行，但是还是建议配置单独的域名访问

**Comment by NewNeko-2022** [comment]
> 以前我是放在主域名的二级目录下使用，现在需要解析域名到/public 目录，是不是只能使用单独的二级域名去解析了？

location /neko/ {
	if (!-e $request_filename){
		rewrite  ^/neko/(.*)$  /neko/index.php?s=$1  last;   break;
	}
}
给你一个伪静态子目录范例，也许是对的（

**Comment by yuantuo666** [comment]
因使用 ThinkPHP 框架，v3.0.0版本开始不再支持子目录访问“特性”，建议使用单独域名访问并正确配置权限，以防止潜在的攻击。如实在无法单独分配域名，建议通过反向代理的方式实现子目录访问。
