### ISSUE TITLE
后台添加了2个svip账号cookies,  解析文件提示这个， 版本是最新的 4.02

### ISSUE THREAD

**Issue by liulinbo2023** [yuantuo666/baiduwp-php#332]
后台添加了2个svip账号cookies,  解析文件提示这个， 版本是最新的 4.02
![微信截图_20231109100438](https://github.com/yuantuo666/baiduwp-php/assets/150118790/9b7ce38a-00bc-4961-9f8b-a8bd2d79040d)
没解析几次就出现这个， 添加一个账号好像不会出现这个问题。

**Comment by yuantuo666** [comment]
这个是普通帐号设置错误或者获取下载链接超时了，更新普通帐号并且重新获取下载链接看能不能解决
