### ISSUE TITLE
【建议】增加批量下载，增加系统缓存

### ISSUE THREAD

**Issue by shejige** [yuantuo666/baiduwp-php#333]
## 描述建议
灵感来源https://bd.yyuu.cc/
然后来github搜索没想到搜到了本程序，估计它那个也是改的本源码吧？
增加了一键下载。这样解析是文件夹的时候可以一键下载到本地。下面有截图。
下载到本地自动归纳为文件夹，这点很不错。
本程序很强大就是差个一键下载。需要一个一个点。下载单个或数量不多的还好，多了就不方便了。

## 此建议将如何工作
工作步骤:
1. 增加批量下载
2. 优化后端解析逻辑，并新增“系统缓存”功能，当解析后8小时内再次解析时，直接从数据库中提取上次解析结果，减少API访问频率；

## 截图
![image](https://github.com/yuantuo666/baiduwp-php/assets/79530551/7067e215-c9b8-4973-8042-90e392fc0f29)
![image](https://github.com/yuantuo666/baiduwp-php/assets/79530551/9066ea61-3f93-4fd2-b8ea-644b731c103d)

## 补充信息
参考网站：https://bd.yyuu.cc/home/updatelog

**Comment by yuantuo666** [comment]
参见 https://github.com/yuantuo666/baiduwp-php/issues/271
另：本项目也并非从0开始的研究，是基于 baiduwp 项目的进一步改进。获取下载链接的技术一直都有，但是考虑到法律因素，本项目不会增加批量下载功能。
