### ISSUE TITLE
【寻求帮助】宝塔搭建完4.0版本后出现请求失败，install界面为404

### ISSUE THREAD

**Issue by 809781347** [yuantuo666/baiduwp-php#334]
## 你需要的帮助
是我哪里设置出问题了吗

## 截图
![image](https://github.com/yuantuo666/baiduwp-php/assets/100351684/ab183930-d266-4a65-b724-0bd9259fd18b)
![image](https://github.com/yuantuo666/baiduwp-php/assets/100351684/9fda085c-399b-4ea3-b6e7-cf168bae1d28)

**Comment by yuantuo666** [comment]
需要设置伪静态，参考 https://github.com/yuantuo666/baiduwp-php/issues/307

**Comment by 809781347** [comment]
![image](https://github.com/yuantuo666/baiduwp-php/assets/100351684/7c842eab-9f81-4828-87ad-b2ce7dd7a26c)
伪静态是这样设置的，但还是不行，我没有绑定子目录而是在网站目录指定的子目录 public和这个有关系吗

**Comment by lbj-007** [comment]
![image](https://github.com/yuantuo666/baiduwp-php/assets/22144485/381fdeed-f28a-4f60-802f-6f7c4574b94a)
我也是设置完，都进不去install界面。。。
![image](https://github.com/yuantuo666/baiduwp-php/assets/22144485/3a9ef2f1-5039-49e0-b3c6-4701ad79dae1)
这个子目录页面咋就添加不了

**Comment by yuantuo666** [comment]
> ![image](https://user-images.githubusercontent.com/22144485/282982286-381fdeed-f28a-4f60-802f-6f7c4574b94a.png) 我也是设置完，都进不去install界面。。。 ![image](https://user-images.githubusercontent.com/22144485/282982649-4e9b0098-2d2e-43c9-8384-2ea3abede61b.png) 这个子目录页面咋就添加不了

点击 网站目录 设置子目录

**Comment by yuantuo666** [comment]
> ![image](https://user-images.githubusercontent.com/100351684/281964956-7c842eab-9f81-4828-87ad-b2ce7dd7a26c.png) 伪静态是这样设置的，但还是不行，我没有绑定子目录而是在网站目录指定的子目录 public和这个有关系吗

在最新版本 和 Apache 环境下，宝塔环境是会自动配置的，不需要额外的设置。

**Comment by 809781347** [comment]
> > ![image](https://user-images.githubusercontent.com/100351684/281964956-7c842eab-9f81-4828-87ad-b2ce7dd7a26c.png) 伪静态是这样设置的，但还是不行，我没有绑定子目录而是在网站目录指定的子目录 public和这个有关系吗
> 
> 在最新版本 和 Apache 环境下，宝塔环境是会自动配置的，不需要额外的设置。
改成Apache环境直接网站无法访问了

**Comment by 809781347** [comment]
把服务器系统重装了一遍问题解决了
