### ISSUE TITLE
普通账号正常解析, IDM 下载, 接口报错 502

### ISSUE THREAD

**Issue by lvbibir** [yuantuo666/baiduwp-php#335]
## 描述问题
正常解析, 但是 IDM 无法正常下载, 已配置用户 UA

## 截图
账号 cookie 看着正常
![image](https://github.com/yuantuo666/baiduwp-php/assets/53466270/34fef5d1-8813-424f-854a-6475baf15d27)
IDM UA 配置正确
![image](https://github.com/yuantuo666/baiduwp-php/assets/53466270/53f43150-a233-4405-9c7d-00693f216717)
手动添加下载任务报 502 
![image](https://github.com/yuantuo666/baiduwp-php/assets/53466270/7315547f-b86f-4ccd-9018-82d3d6134f7d)

## 您的设备信息
 docker 版 4.0.2, 未使用数据库

**Comment by yuantuo666** [comment]
成功获取到了下载链接一般就不是本项目的问题。可能是百度的服务器不太稳定，可以等待一段时间重新获取试试。

**Comment by yuantuo666** [comment]
如有问题请重新打开此议题。
