### ISSUE TITLE
【寻求帮助】普通账号正常报错9019

### ISSUE THREAD

**Issue by MRanuo** [yuantuo666/baiduwp-php#337]
使用的腾讯云2g2g3m服务器，端口已全开

**Comment by yuantuo666** [comment]
参见 https://github.com/yuantuo666/baiduwp-php/issues/248

**Comment by MRanuo** [comment]
> 参见 #248

![{0024DE1E-D8D6-4804-A266-B024A346B9E0}](https://github.com/yuantuo666/baiduwp-php/assets/69956918/cb37106e-f67b-485b-90ff-8903ba207af4)
![{E98061A6-7D10-44aa-BBEC-C89FF611DD9D}](https://github.com/yuantuo666/baiduwp-php/assets/69956918/fec81229-f64c-4d79-b02b-8abef085ac0d)
那个我看了，但是并没能解决问题，我换了好几个普通账号都没法解决。

**Comment by yuantuo666** [comment]
你抓包的链接是什么呢 需要是 pan.baidu.com 下面的链接

**Comment by MRanuo** [comment]
> pan.baidu.com

Request URL:
https://pan.baidu.com/aipan/search

**Comment by MRanuo** [comment]
> 你抓包的链接是什么呢 需要是 pan.baidu.com 下面的链接

因为chrome取消左上角的小锁头看cookie的功能，所以用f12抓的cookie，我又用edge重新抓了，还是一样。

**Comment by MRanuo** [comment]
> 你抓包的链接是什么呢 需要是 pan.baidu.com 下面的链接

我已经通过退回3.02解决了。感谢帮助
