### ISSUE TITLE
【寻求帮助】4.02版本开了随机账号解析好像一直都是一个账号解析，改怎么办呢？

### ISSUE THREAD

**Issue by liulinbo2023** [yuantuo666/baiduwp-php#339]
## 描述问题
请在此填入对你遇到的问题清晰准确的描述。

## 如何复现此问题
复现此问题的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
是的，已经确认这个是 bug 了，参见 https://github.com/yuantuo666/baiduwp-php/issues/314
最近太忙了，一直没时间修复
