### ISSUE TITLE
请问下如何开启IP限制和每天解析个数

### ISSUE THREAD

**Issue by zhucaidan** [yuantuo666/baiduwp-php#34]
请问下如何开启IP解析次数限制？是要开启Mysql吗？

还有个问题就是该如何限制指定IP的解析次数呢？
默认是一个IP一天一次，config中没有看到关于次数的设置

**Comment by yuantuo666** [comment]
需要开启MySQL数据库，并在config.php中设置MySQL服务器参数：
USING_DB 设置为 true
DbConfig 填写数据库信息

暂不支持设置解析次数，请自己研究该功能。
tips: index.php中333-352行
