### ISSUE TITLE
【建议】希望增加多密码功能及根据密码统计下载次数、使用流量

### ISSUE THREAD

**Issue by NewNeko-2022** [yuantuo666/baiduwp-php#340]
希望增加多密码功能及根据密码统计下载次数、使用流量（最好有周期总流量/日总流量限制
用于5人群均摊公车（限制的原因主要是实际的发生了，我朋友的朋友一定也会遵守约定不外传...导致pan账户暂时封禁的问题）
虽然大概率代理工具是人手一个的，可以通过仅白名单ip访问来区分限制，但终究不方便（代理可能经常换ip或者节点本身就是负载均衡的随机ip）
如果可以，希望可以为4.x添加类似3.x的配置方案，比如像3.x版本可以通过直接复制，然后通过随机路径名来区分用户，和单独配置密码，和单独库来统计使用(希望能在这个基础上添加不论ip的周期总量限制)。

**Comment by yuantuo666** [comment]
理论上来说，你描述的需求是可以是可以实现的，但也请你理解，本人精力有限，没时间来完成这个需求。如果有感兴趣的同学，欢迎提起 PR 来实现这个功能。

这里我可以提供另外一种实现的方式：
可以使用 docker 搭建多个不同的服务，不同服务密码不同，使用 SQLite 数据库即可，用不同的路径 / 端口对应不同的服务，每个人使用其中一个服务即可。
