### ISSUE TITLE
【建议】添加mac+IP控制下载次数

### ISSUE THREAD

**Issue by xtyyyy1230** [yuantuo666/baiduwp-php#341]
## 添加mac+控制下载次数
目前IP控制不了开IP代理的用户不停换IP下载。

## 此建议将如何工作
工作步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 相关的技术
如果您有能力，您可以在此提供一些技术帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 补充信息
您可以在这里输入其他有关此建议的信息。

**Comment by yuantuo666** [comment]
浏览器没有权限获取 Mac 地址，此提议无法实现

**Comment by xtyyyy1230** [comment]
目前他们挠过限制的方法是手动清空浏览cooker后，重新加载解析就又可以下载了。
限制不了恶意下载，导致会员账号被封。
想请教老大有何方法限制，现在免费提供给网友使用被大批量下载导致普通用户用不了，
而且会造成会员账号被限制与封禁。
太痛苦了！
救老大出手整冶整冶！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuantuo666/baiduwp-php"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月19日(星期天) 中午12:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuantuo666/baiduwp-php] 【建议】添加mac+IP控制下载次数 (Issue #341)





 
浏览器没有权限获取 Mac 地址，此提议无法实现
