### ISSUE TITLE
【建议】通过添加用户管理模块管控下载次数

### ISSUE THREAD

**Issue by xtyyyy1230** [yuantuo666/baiduwp-php#342]
## 给解析系统添加用户管理系统
如后台开启用户管理功能后，需要解析的用户必须注册登录验证。
用户登录成功后，提供给用户下载次数限制。

## 此建议将如何工作
工作步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 相关的技术
如果您有能力，您可以在此提供一些技术帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 补充信息
您可以在这里输入其他有关此建议的信息。

**Comment by Eisaichen** [comment]
这就是个web app，感觉没必要
就算加了验证，可能也会因为作者水平不同、精力有限等等原因而不够安全，而且每个web app都带验证的话也很麻烦
如果需要验证，目前比较普遍的做法是自己为web app部署外部OIDC实现认证和SSO

**Comment by yuantuo666** [comment]
这个需求包括添加用户管理系统、用户注册和登录验证、针对每一个用户的下载次数限制等功能。

但是这个工具的设计初衷是为了提供百度网盘分享链接的下载链接，而不是作为一个完整的用户管理系统。
添加过于细化的用户管理系统和针对每一个用户的下载次数限制超出了该项目的范围。

如果你感兴趣可以在遵循许可证的前提下进一步开发满足需求，相关的项目如下：
- https://github.com/dylanbai8/simple_website_card_secret_authorization_system 仅适用于 baiduwp-php v2.x.x 老版本
- https://github.com/zoujingli/ThinkAdmin 适用 baiduwp-php v3.x.x 版本
- https://github.com/karsonzhang/fastadmin 适用 baiduwp-php v3.x.x 版本
