### ISSUE TITLE
普通账号的cookie在哪添加

### ISSUE THREAD

**Issue by lbj-007** [yuantuo666/baiduwp-php#343]
![image](https://github.com/yuantuo666/baiduwp-php/assets/22144485/d69c10a8-e6ab-4fa5-9dec-e042055ab173)
为啥没有找到普通账号cookie的添加入口

**Comment by lbj-007** [comment]
找到了。。

**Comment by yuantuo666** [comment]
> 在哪，我还是没找到

管理页面的网站设置里面
