### ISSUE TITLE
【BUG 反馈】添加cookie出现错误

### ISSUE THREAD

**Issue by laoqijun1** [yuantuo666/baiduwp-php#344]
更新失败
Unexpected token '<', "
![image](https://github.com/yuantuo666/baiduwp-php/assets/128939868/41d520d6-0c25-403d-b76a-f331a45aec12)

**Comment by yuantuo666** [comment]
1. 修改 .env 文件中 APP_DEBUG 为 true 打开开发者模式
2. 按 F12 打开开发者工具抓包看看，应该是哪里的代码有点 bug，麻烦把报错的返回报文内容完整的贴上来

**Comment by laoqijun1** [comment]
> 1. 修改 .env 文件中 APP_DEBUG 为 true 打开开发者模式
> 2. 按 F12 打开开发者工具抓包看看，应该是哪里的代码有点 bug，麻烦把报错的返回报文内容完整的贴上来

解决了
雨云的防火墙的问题
关了就好了
