### ISSUE TITLE
使用docker安装后台密码是多少？

### ISSUE THREAD

**Issue by muzikeji** [yuantuo666/baiduwp-php#345]
我直接使用docker无数据库安装的，然后进后台要密码。请问密码怎么获取？![image](https://github.com/yuantuo666/baiduwp-php/assets/52457863/63f99783-92fe-48d8-a225-097decdba887)

**Comment by yuantuo666** [comment]
密码是你安装时第一个填空设置的

**Comment by muzikeji** [comment]
> 密码是你安装时第一个填空设置的

我什么都没设置 刚才去试了下 密码留空即可进入
