### ISSUE TITLE
大佬可以把UI改成透明的页面吗？

### ISSUE THREAD

**Issue by kkkqaq** [yuantuo666/baiduwp-php#346]
这里是文件链接
https://wwcu.lanzouj.com/ibxOC1golged

截图
![ss8](https://github.com/yuantuo666/baiduwp-php/assets/150981719/da269eda-e08c-4060-b140-043094eaa3ea)

**Comment by lc6464** [comment]
感觉就是一个毛玻璃效果+彩色背景，实现不难，但是在旧浏览器上效果可能会不好，不考虑兼容性也可以，但是感觉改掉整个站点的样式是个不小的工程。而且我个人觉得太花哨了（个人喜欢类似于 GitHub 深色模式这种深色纯色的）。
