### ISSUE TITLE
【寻求帮助】新手请问各位大佬如何使用此软件

### ISSUE THREAD

**Issue by 17726** [yuantuo666/baiduwp-php#350]
我从release下载了4.0.3的baiduwp-php-v4.0.3.zip
![image](https://github.com/yuantuo666/baiduwp-php/assets/112075023/9303062e-6af8-4186-a51a-b4cdccf3ed10)
但是解压之后我不知道该做什么才能使用这个软件，也找不到exe程序，
希望大佬解答

**Comment by yuantuo666** [comment]
参考首页 README 写的方法安装：https://github.com/yuantuo666/baiduwp-php/blob/master/README_ZH.md#-%E5%AE%89%E8%A3%85%E5%8F%8A%E8%AE%BE%E7%BD%AE

**Comment by 17726** [comment]
> 参考首页 README 写的方法安装：https://github.com/yuantuo666/baiduwp-php/blob/master/README_ZH.md#-%E5%AE%89%E8%A3%85%E5%8F%8A%E8%AE%BE%E7%BD%AE
唔唔，没看到，谢谢大佬up

**Comment by 17726** [comment]
参考首页 README 写的方法安装：https://github.com/yuantuo666/baiduwp-php/blob/master/README_ZH.md#-%E5%AE%89%E8%A3%85%E5%8F%8A%E8%AE%BE%E7%BD%AE
唔唔，没看到，谢谢大佬up
看了眼似乎好难唔wwww（现大一网安专业）
我还是再学几年吧
![0BC446E2](https://github.com/yuantuo666/baiduwp-php/assets/112075023/176df47c-ea32-4f42-99de-a8d9e98b4e96)
