### ISSUE TITLE
【寻求帮助】admin 后台打不开

### ISSUE THREAD

**Issue by xw589589** [yuantuo666/baiduwp-php#351]
## 描述问题
admin 后台打不开

## 如何复现此问题
复现此问题的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
![53ecd5a9bab5d252928b3275ba5d46f](https://github.com/yuantuo666/baiduwp-php/assets/76859642/c87a08e1-84a1-4dfe-80ac-05382c502764)

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by xw589589** [comment]
访问后台他就会跳到这个页面

**Comment by yuantuo666** [comment]
可能是伪静态配置存在问题。如果使用的是宝塔面板参考 https://blog.csdn.net/zhichaosong/article/details/104889198 里的5.2.4伪静态配置，如果是其他环境，请提供更详细的信息。

**Comment by yuantuo666** [comment]
宝塔面板有没有设置网站目录，网站安装过了吗

**Comment by xw589589** [comment]
设置了网站目录，网站安装过了.

**Comment by yuantuo666** [comment]
如果docker安装仍有问题，请重新打开此议题。
