### ISSUE TITLE
【寻求帮助】Termux无法登录后台

### ISSUE THREAD

**Issue by 1Q23LYC45** [yuantuo666/baiduwp-php#352]
## 描述问题
登上后台能提示登录成功，但是几秒后网页自动刷新还是提示输入管理员密码。

## 如何复现此问题
复现此问题的步骤:
1. 解压缩源码到/sdcard/nginx/vhost/baiduwp-php/
2. 在配置文件中新建Server块并设置网站
3. 浏览器打开127.0.0.1:8003并按提示部署
4. 部署完了登录不了后台

## 你需要的帮助
如何登录后台？不登录后台添加不上账号，不能解析大于50MB的文件。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。
![IMG_20240131_000353](https://github.com/yuantuo666/baiduwp-php/assets/143373643/b92e4a27-f4a8-4abf-b16d-dd00d3442eb3)

## 您的设备信息
 - 服务器系统信息：
```
Linux localhost 5.10.149-android12-9-g3e52debca1cf-dirty #1 SMP PREEMPT Wed Sep 27 04:17:39 UTC 2023 aarch64 Android
```
 - 服务器 PHP 版本：
```
PHP 8.2.8 (cli) (built: Nov 14 2023 10:12:44) (NTS)   Copyright (c) The PHP Group                           Zend Engine v4.2.8, Copyright (c) Zend Technologies
```
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：
```
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Mobile Safari/537.36
```

## 补充信息
可以在Qemu中的Win7+NGINX1.16+SQLite3+PHP8.2.15成功部署并正常登录后台，只不过，太卡了，啥都加载不出来...........不用任何虚拟机和任何容器都特别卡，安装页面卡了半分钟才加载完成。

**Comment by yuantuo666** [comment]
描述的很清楚，但是这看上去并不是该项目的问题。在原生的 Linux 和 Windows 上本项目都可以顺利的运行。猜测卡顿是QEMU导致的，建议更换环境。

**Comment by 1Q23LYC45** [comment]
已知我这个环境有问题，我应该怎么修改配置在不用容器和虚拟机的情况下部署？测试了好像只有Z-Blog，Typecho，WordPress能正常使用，Laravel和Thinkphp全不行。谢谢大佬。

**Comment by yuantuo666** [comment]
正常登录之后会存储 SESSION（使用本地硬盘保存），看上去是这一步有一些问题所以导致登录状态没有保存，可以检查一下文件夹权限和程序运行权限相关的设置。

**Comment by 1Q23LYC45** [comment]
好的，谢谢了。
