### ISSUE TITLE
【寻求帮助】虚拟主机【雨云】阿里云的二级域名绑定public目录，打开链接出现500错误

### ISSUE THREAD

**Issue by begger-and-king** [yuantuo666/baiduwp-php#354]
虚拟主机【雨云】阿里云的二级域名绑定public目录，打开链接出现500错误，救助大佬

![微信图片_20240204220003](https://github.com/yuantuo666/baiduwp-php/assets/75322385/af667840-18d6-4ee7-ad59-d685a9978f96)
![微信图片_20240204220008](https://github.com/yuantuo666/baiduwp-php/assets/75322385/55a2c2d9-39e0-4fac-8348-30d2ef4b7398)
![微信图片_20240204220013](https://github.com/yuantuo666/baiduwp-php/assets/75322385/bb6e4d77-3259-4b61-b09d-fb24a4811580)
![微信图片_20240204220057](https://github.com/yuantuo666/baiduwp-php/assets/75322385/cdb481b4-1e9c-4491-9392-7822e06051d1)

**Comment by begger-and-king** [comment]
@yuantuo666

**Comment by yuantuo666** [comment]
easypanel 的解压功能有个 bug，你可以试试用 FTP 上传文件

**Comment by begger-and-king** [comment]
> easypanel 的解压功能有个 bug，你可以试试用 FTP 上传文件

是将解压后的文件都上传到wwwroot/目录下，对嘛

**Comment by yuantuo666** [comment]
<img width="1404" alt="image" src="https://github.com/yuantuo666/baiduwp-php/assets/44130602/a2a9312c-fef7-4dee-aae9-0fef60e7df4e">

**Comment by begger-and-king** [comment]
> <img alt="image" width="1404" src="https://private-user-images.githubusercontent.com/44130602/302266426-a2a9312c-fef7-4dee-aae9-0fef60e7df4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzEzNDksIm5iZiI6MTcwNzEzMTA0OSwicGF0aCI6Ii80NDEzMDYwMi8zMDIyNjY0MjYtYTJhOTMxMmMtZmVmNy00ZGVlLWFhZTktMGZlZjYwZTdkZjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkOGNmMTZhYzQzZDAwYjAwOTU1ZTY1OWNiZmIxZGEzZTNhMzU2NjNiYjM1OTFkNWRmODZjNTRiNmE1MGU0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcMgFTGpC6HCUTatNdQQzCFv7GNJig_vB_TVUxhcp5I"

然后我把解压后的文件，放在改名之后的文件夹里面，输入pan.ziyuanshare.cc/install  出现错误

**Comment by begger-and-king** [comment]
![Uploading 微信图片_20240205191232.png…]()

**Comment by begger-and-king** [comment]
![微信图片_20240205191232](https://github.com/yuantuo666/baiduwp-php/assets/75322385/9690ac61-5619-4949-a223-35028896bf30)

**Comment by begger-and-king** [comment]
获取文件列表失败连接服务器过程中出现异常，消息：Failed to fetch
@yuantuo666

**Comment by yuantuo666** [comment]
按 F12 打开开发者工具看控制台里报错了什么

**Comment by begger-and-king** [comment]
控制台报错
![微信图片_20240206103156](https://github.com/yuantuo666/baiduwp-php/assets/75322385/4361d90c-7270-491c-90c9-001d9a5d34c8)

**Comment by yuantuo666** [comment]
![image](https://github.com/yuantuo666/baiduwp-php/assets/44130602/ccec5bf6-66eb-497a-a9d6-7b90d2463c6b)
域名 DNS 配置有问题，请自行排查。

**Comment by yuantuo666** [comment]
项目在发布新版本前会在雨云和 Docker 环境进行测试。如有部署问题，请自行排查或寻求网站托管服务提供商的帮助。建议使用 Docker 部署减少环境配置出现的问题，如有需要，也可参见 Dockerfile 配置进行环境配置。
