### ISSUE TITLE
【BUG 反馈】

### ISSUE THREAD

**Issue by H-Bole** [yuantuo666/baiduwp-php#355]
## 描述 Bug
重大bug，百度网盘已更新cookie格式，目前3.0版本已无法解析

## 如何复现此 Bug
复现此 Bug 的步骤:
1. 在config.php更换cookie
2. 打开解析站，提示cookie无效

## 期望
对您所期望的情况做一个简单描述。

## 截图
等会附上

## 补充信息
请问大家是否一样

**Comment by yuantuo666** [comment]
感谢你提供的信息，但测试显示没有问题。如果项目无法继续解析，本项目将会直接存档。
