### ISSUE TITLE
【寻求帮助】docker 安装mysql失败，不能使用数据库功能

### ISSUE THREAD

**Issue by begger-and-king** [yuantuo666/baiduwp-php#356]
## 描述问题
docker 安装mysql失败，没有添加上数据库，后续要怎么才能连接上数据库呢

网站：http://154.3.1.20:8080/#/index

**Comment by H-Bole** [comment]
我给出一种办法，直接在宝塔面板建立mysql数据库，给ip开放权限权限就行，这样在docker直接连接服务器ip就可以使用它的数据库了

**Comment by yuantuo666** [comment]
如果无法安装 MySQL 数据库，可以直接使用 SQLite 数据库。如有 docker 安装问题，请自行搜索解决或前往 docker 论坛进行问题反馈。
有其他问题请重新打开此议题。
