### ISSUE TITLE
后台设置以后提示更新失败【寻求帮助】

### ISSUE THREAD

**Issue by diannaodiy** [yuantuo666/baiduwp-php#359]
## 描述问题
后台不能更新参数。提示更新失败
## 如何复现此问题
复现此问题的步骤:
后台更新Cookie就会这样，后来我试着设置下载次数等参数，也是如此

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
![微信截图_20240227083806](https://github.com/yuantuo666/baiduwp-php/assets/114161089/fe90eb59-1256-4a3d-a36c-7aa7d090a3d4)

如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by begger-and-king** [comment]
建议用docker部署

**Comment by yuantuo666** [comment]
初步判断是环境配置问题，请提供具体环境或者尝试 docker 配置。

**Comment by lc6464** [comment]
建议使用 docker 部署，如有任何问题可再次开启议题。
