### ISSUE TITLE
【寻求帮助】突然网站服务器返回异常 HTTP 状态码：HTTP 500 

### ISSUE THREAD

**Issue by lingyue-xiaoyu** [yuantuo666/baiduwp-php#362]
![1710210016158](https://github.com/yuantuo666/baiduwp-php/assets/129644893/381e05a4-abef-4b3a-9f26-d4318626f95a)

**Comment by yuantuo666** [comment]
请提供更多环境信息，也可以将 DEBUG 模式打开抓包调试寻找详细错误原因，参考此处开启调试模式 https://doc.thinkphp.cn/v8_0/debug_mode.html

**Comment by huangbh1024** [comment]
一样的报错，解决了吗
