### ISSUE TITLE
【功能性建议】

### ISSUE THREAD

**Issue by rexhang** [yuantuo666/baiduwp-php#363]
## 描述建议
1、希望能够支持PHP 7
2、希望支持勾选批量下载，包含文件夹

---

Thankyou~

**Comment by yuantuo666** [comment]
1. v3.0 版本基于 ThinkPHP 8.0 框架构建，框架要求最低 PHP 版本 8.0，故无法支持 PHP 7。参见 https://doc.thinkphp.cn/v8_0/setup.html
2. 该问题参见 https://github.com/yuantuo666/baiduwp-php/issues/249
