### ISSUE TITLE
【寻求帮助】http500报错

### ISSUE THREAD

**Issue by huangbh1024** [yuantuo666/baiduwp-php#365]
![image](https://github.com/yuantuo666/baiduwp-php/assets/72372968/1a337060-30ee-4b4c-b453-c86fd745c985)
{
    "code": 10501,
    "message": "SQLSTATE[HY000] [2002] Operation timed out",
    "traces": [
        {
            "name": "think\\db\\exception\\PDOException",
            "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-orm/src/db/PDOConnection.php",
            "line": 836,
            "code": 10501,
            "message": "SQLSTATE[HY000] [2002] Operation timed out",
            "trace": [
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-orm/src/db/connector/Mysql.php",
                    "line": 68,
                    "function": "getPDOStatement",
                    "class": "think\\db\\PDOConnection",
                    "type": "->",
                    "args": ["SHOW FULL COLUMNS FROM `records`"]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-orm/src/db/PDOConnection.php",
                    "line": 438,
                    "function": "getFields",
                    "class": "think\\db\\connector\\Mysql",
                    "type": "->",
                    "args": ["`records`"]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-orm/src/db/PDOConnection.php",
                    "line": 376,
                    "function": "getTableFieldsInfo",
                    "class": "think\\db\\PDOConnection",
                    "type": "->",
                    "args": ["records"]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-orm/src/db/PDOConnection.php",
                    "line": 424,
                    "function": "getSchemaInfo",
                    "class": "think\\db\\PDOConnection",
                    "type": "->",
                    "args": ["records"]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-orm/src/db/PDOConnection.php",
                    "line": 476,
                    "function": "getTableInfo",
                    "class": "think\\db\\PDOConnection",
                    "type": "->",
                    "args": ["records", "pk"]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-orm/src/db/Query.php",
                    "line": 325,
                    "function": "getPk",
                    "class": "think\\db\\PDOConnection",
                    "type": "->",
                    "args": ["records"]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-orm/src/db/concern/WhereQuery.php",
                    "line": 43,
                    "function": "getPk",
                    "class": "think\\db\\Query",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/app/controller/System.php",
                    "line": 37,
                    "function": "where",
                    "class": "think\\db\\BaseQuery",
                    "type": "->",
                    "args": ["size", ">=", 52428800]
                },
                {
                    "function": "index",
                    "class": "app\\controller\\System",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Container.php",
                    "line": 345,
                    "function": "invokeArgs",
                    "class": "ReflectionMethod",
                    "type": "->",
                    "args": [{}, []]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/route/dispatch/Controller.php",
                    "line": 110,
                    "function": "invokeReflectMethod",
                    "class": "think\\Container",
                    "type": "->",
                    "args": [
                        {},
                        {
                            "name": "index",
                            "class": "app\\controller\\System"
                        },
                        []
                    ]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Pipeline.php",
                    "line": 59,
                    "function": "think\\route\\dispatch\\{closure}",
                    "class": "think\\route\\dispatch\\Controller",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Pipeline.php",
                    "line": 66,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/route/dispatch/Controller.php",
                    "line": 84,
                    "function": "then",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/route/Dispatch.php",
                    "line": 52,
                    "function": "exec",
                    "class": "think\\route\\dispatch\\Controller",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Route.php",
                    "line": 755,
                    "function": "run",
                    "class": "think\\route\\Dispatch",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Pipeline.php",
                    "line": 59,
                    "function": "think\\{closure}",
                    "class": "think\\Route",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Pipeline.php",
                    "line": 66,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Route.php",
                    "line": 754,
                    "function": "then",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Http.php",
                    "line": 208,
                    "function": "dispatch",
                    "class": "think\\Route",
                    "type": "->",
                    "args": [{}, {}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Http.php",
                    "line": 198,
                    "function": "dispatchToRoute",
                    "class": "think\\Http",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Pipeline.php",
                    "line": 59,
                    "function": "think\\{closure}",
                    "class": "think\\Http",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/middleware/SessionInit.php",
                    "line": 58,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "function": "handle",
                    "class": "think\\middleware\\SessionInit",
                    "type": "->",
                    "args": [{}, {}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Middleware.php",
                    "line": 134,
                    "function": "call_user_func",
                    "args": [[{}, "handle"], {}, {}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->",
                    "args": [{}, {}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/think-trace/src/TraceDebug.php",
                    "line": 71,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "function": "handle",
                    "class": "think\\trace\\TraceDebug",
                    "type": "->",
                    "args": [{}, {}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Middleware.php",
                    "line": 134,
                    "function": "call_user_func",
                    "args": [[{}, "handle"], {}, {}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Pipeline.php",
                    "line": 85,
                    "function": "think\\{closure}",
                    "class": "think\\Middleware",
                    "type": "->",
                    "args": [{}, {}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Pipeline.php",
                    "line": 66,
                    "function": "think\\{closure}",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Http.php",
                    "line": 197,
                    "function": "then",
                    "class": "think\\Pipeline",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/vendor/topthink/framework/src/think/Http.php",
                    "line": 162,
                    "function": "runWithRequest",
                    "class": "think\\Http",
                    "type": "->",
                    "args": [{}]
                },
                {
                    "file": "/www/sites/download.xxxxxx.cn/index/public/index.php",
                    "line": 20,
                    "function": "run",
                    "class": "think\\Http",
                    "type": "->",
                    "args": []
                }
            ],
            "source": {
                "first": 827,
                "source": [
                    "            } else {\n",
                    "                if ($this->reConnectTimes < 4 && $this->isBreak($e)) {\n",
                    "                    $this->reConnectTimes++;\n",
                    "\n",
                    "                    return $this->close()->getPDOStatement($sql, $bind, $master, $procedure);\n",
                    "                }\n",
                    "            }\n",
                    "\n",
                    "            if ($e instanceof \\PDOException) {\n",
                    "                throw new PDOException($e, $this->config, $this->getLastsql());\n",
                    "            } else {\n",
                    "                throw $e;\n",
                    "            }\n",
                    "        }\n",
                    "    }\n",
                    "\n",
                    "    /**\n",
                    "     * 执行语句.\n",
                    "     *\n"
                ]
            }
        }
    ],
    "datas": {
        "PDO Error Info": {
            "SQLSTATE": "HY000",
            "Driver Error Code": 2002,
            "Driver Error Message": "Operation timed out"
        },
        "Database Status": {
            "Error Code": 10501,
            "Error Message": "SQLSTATE[HY000] [2002] Operation timed out",
            "Error SQL": ""
        },
        "Database Config": {
            "type": "mysql",
            "hostname": "47.106.239.45",
            "database": "panDownload",
            "hostport": "3306",
            "dsn": "",
            "params": [],
            "charset": "utf8",
            "prefix": "",
            "deploy": 0,
            "rw_separate": false,
            "master_num": 1,
            "slave_no": "",
            "read_master": false,
            "fields_strict": true,
            "fields_cache": false,
            "trigger_sql": true,
            "builder": "",
            "query": "",
            "break_reconnect": false,
            "break_match_str": [],
            "auto_param_bind": true
        }
    },
    "tables": {
        "GET Data": [],
        "POST Data": [],
        "Files": null,
        "Cookies": {
            "PHPSESSID": "9ad30e282a162ffc007c1b60174239ea",
            "thinkphp_show_page_trace": "0|0"
        },
        "Session": [],
        "Server/Request Data": {
            "HOSTNAME": "949c639fc1c1",
            "PHP_INI_DIR": "/usr/local/etc/php",
            "SHLVL": "1",
            "HOME": "/home/www-data",
            "PHP_LDFLAGS": "-Wl,-O1 -pie",
            "PHP_CFLAGS": "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
            "PHP_VERSION": "8.2.15",
            "COMPOSER_HOME": "/tmp/composer",
            "GPG_KEYS": "39B641343D8C104B2B146DC3F9C39DC0B9698544 E60913E4DF209907D8E30D96659A97C9CF2A795A 1198C0117593497A5EC5C199286AF1F9897469DC",
            "PHP_CPPFLAGS": "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
            "PHP_ASC_URL": "https://www.php.net/distributions/php-8.2.15.tar.xz.asc",
            "PHP_URL": "https://www.php.net/distributions/php-8.2.15.tar.xz",
            "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LD_PRELOAD": "/usr/lib/preloadable_libiconv.so php",
            "PHPIZE_DEPS": "autoconf \t\tdpkg-dev dpkg \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkgconf \t\tre2c",
            "PWD": "/www",
            "PHP_SHA256": "eca5deac02d77d806838275f8a3024b38b35ac0a5d9853dcc71c6cbe3f1f8765",
            "USER": "www-data",
            "HTTP_COOKIE": "PHPSESSID=9ad30e282a162ffc007c1b60174239ea; thinkphp_show_page_trace=0|0",
            "HTTP_ACCEPT_LANGUAGE": "zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7,en-US;q=0.6,ru;q=0.5",
            "HTTP_ACCEPT_ENCODING": "gzip, deflate, br, zstd",
            "HTTP_REFERER": "https://download.xxxxxx.cn/",
            "HTTP_SEC_FETCH_DEST": "empty",
            "HTTP_SEC_FETCH_MODE": "cors",
            "HTTP_SEC_FETCH_SITE": "same-origin",
            "HTTP_SEC_CH_UA_PLATFORM": "\"Windows\"",
            "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
            "HTTP_SEC_CH_UA_MOBILE": "?0",
            "HTTP_ACCEPT": "application/json",
            "HTTP_SEC_CH_UA": "\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"",
            "HTTP_CACHE_CONTROL": "no-cache",
            "HTTP_PRAGMA": "no-cache",
            "HTTP_HOST": "download.xxxxxx.cn",
            "PATH_INFO": "",
            "SCRIPT_FILENAME": "/www/sites/download.xxxxxx.cn/index/public/index.php",
            "REDIRECT_STATUS": "200",
            "SERVER_NAME": "download.xxxxxx.cn",
            "SERVER_PORT": "443",
            "SERVER_ADDR": "172.19.158.245",
            "REMOTE_PORT": "50945",
            "REMOTE_ADDR": "120.41.130.92",
            "SERVER_SOFTWARE": "nginx",
            "GATEWAY_INTERFACE": "CGI/1.1",
            "HTTPS": "on",
            "REQUEST_SCHEME": "https",
            "SERVER_PROTOCOL": "HTTP/2.0",
            "DOCUMENT_ROOT": "/www/sites/download.xxxxxx.cn/index/public",
            "DOCUMENT_URI": "/index.php",
            "REQUEST_URI": "/system",
            "SCRIPT_NAME": "/index.php",
            "CONTENT_LENGTH": "",
            "CONTENT_TYPE": "",
            "REQUEST_METHOD": "GET",
            "QUERY_STRING": "s=/system",
            "FCGI_ROLE": "RESPONDER",
            "PHP_SELF": "/index.php",
            "REQUEST_TIME_FLOAT": 1711590194.227476,
            "REQUEST_TIME": 1711590194
        }
    }
}

**Comment by yuantuo666** [comment]
SQLSTATE[HY000] [2002] Operation timed out 数据库存在问题，检查一下是不是在正常运行
