### ISSUE TITLE
【寻求帮助】通过docker容器链接外部数据库，后台解析IP显示异常

### ISSUE THREAD

**Issue by motian16** [yuantuo666/baiduwp-php#366]
## 描述问题
腾讯云宝塔建站确认伪静态运行目录都设置后报错，又通过docker容器链接外部数据库，后台解析IP显示异常，全都是172.17.0.1，且网站打开极慢

## 如何复现此问题
复现此问题的步骤:
1. 容器以内网IP连接的sq数据库
2. 开了反向代理
3. xxxxxx
4. xxxxxxxx

## 你需要的帮助
请在此填入你需要的帮助。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
报错可以参考这个打开 DEBUG 模式查看详细信息：https://doc.thinkphp.cn/v8_0/debug_mode.html
网站打开缓慢可能是多方面的原因，例如服务器带宽限制，本地网络不稳定等。你可以打开浏览器控制台的网络选项卡，查看具体加载的耗时信息，以方便定位问题。

**Comment by motian16** [comment]
首先谢谢开发者了，我打开了debug模式  发现是网站目录权限设置问题，我习惯把网站设置在/home目录下，勾选了写入后可以正常访问了
![image](https://github.com/yuantuo666/baiduwp-php/assets/89713447/1716dc58-e758-42eb-9ba4-4367fdd0fd08)
加载缓慢的问题
我分别用edge和chrome 强制刷新后的响应截图 代理软件也已经关闭
![image](https://github.com/yuantuo666/baiduwp-php/assets/89713447/a27bafd2-7770-460b-a80a-4d304532732c)
![image](https://github.com/yuantuo666/baiduwp-php/assets/89713447/b7e005f0-8a9a-42d2-8244-75291d0ece04)

[这是响应最长的网址](https://[fastly.jsdelivr.net/npm/sweetalert2@10.14.0/dist/sweetalert2.min.js](https://fastly.jsdelivr.net/npm/sweetalert2@10.14.0/dist/sweetalert2.min.js))
不开代理的话我这边WiFi和电信5g访问这个js也极为缓慢

**Comment by yuantuo666** [comment]
图中的CSS和JS文件是通过 https://fastly.jsdelivr.net/ 这个CDN加载的，可能你的网络环境连接这个CDN有点慢，你可以试试换个 CDN 或者 保存文件到你自己的服务器 然后修改加载的地址。

**Comment by motian16** [comment]
好的，谢谢，我试试吧
