### ISSUE TITLE
有部分文件下载不了，发送失败【BUG 反馈】

### ISSUE THREAD

**Issue by yxjsvsj** [yuantuo666/baiduwp-php#368]
## 描述 Bug
请在此填入对此 Bug 清晰准确的描述。

## 如何复现此 Bug
复现此 Bug 的步骤:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## 期望
对您所期望的情况做一个简单描述。

## 截图
如果条件允许，请在此附上您的截图。您可以使用 Ctrl + V 直接粘贴图片。

## 您的设备信息
 - 服务器系统信息：
 - 服务器 PHP 版本：
 - 访问项目的浏览器版本（可提供 User-Agent 或浏览器名称+版本）：

## 补充信息
您可以在这里输入其他有关此 Bug 的信息。

**Comment by lc6464** [comment]
务必提供详细信息。

**Comment by yxjsvsj** [comment]
![image](https://github.com/yuantuo666/baiduwp-php/assets/146856332/3737dff9-9aa6-4935-acdc-a7805c48bd38)
有些文件下载会这样显示，下载有些又可以下载，配置都是正确的，显示24报错
<img width="1136" alt="d7224ad7b8cf8d7873b2a67c226c85f" src="https://github.com/yuantuo666/baiduwp-php/assets/146856332/9324f344-d88e-4714-ae70-4b5864b8355f">

**Comment by xuexiaokang** [comment]
我总是22错误，要多次下载才能下载成功

**Comment by yuantuo666** [comment]
如无法下载，可能是文件或链接问题。可以尝试重新分享和使用网盘官方客户端下载。
