### ISSUE TITLE
单IP每日限制解析流量设置了最大10GB，但仍可以下载

### ISSUE THREAD

**Issue by candies404** [yuantuo666/baiduwp-php#370]
## 描述问题
单IP每日限制解析流量设置了最大10GB，但仍可以下载

## 如何复现此问题
复现此问题的步骤:
1. 单IP每日限制解析流量设置10GB
2. 然后下载

## 你需要的帮助
按我的理解应该是超过10GB不给下载和下载10GB后对该ip进行限制 ，请问这个是什么问题

## 截图
![image](https://github.com/yuantuo666/baiduwp-php/assets/154443166/2cdf4703-9bde-4b5a-9236-eefe0b1c95f2)
![image](https://github.com/yuantuo666/baiduwp-php/assets/154443166/b8c63f5b-7797-428a-a7a7-5c5bce8fe7bc)

## 您的设备信息
 - 服务器系统信息 Alibaba Cloud 3 (Soaring Falcon) x86_64(Py3.7.16
 - 服务器 PHP 版本 8.1.27
 - 访问项目的浏览器版本 Chrome 123.0.6312.106（正式版本） （64 位）

## 补充信息
您可以在这里输入其他关于您需要的帮助的信息。

**Comment by yuantuo666** [comment]
相关代码在这里，https://github.com/yuantuo666/baiduwp-php/blob/73106353dfe221494c50a28b96ebba364c74e94c/app/Parse.php#L249C10-L249C19 和 
目前的逻辑是，每次解析前查询 IP 解析流量，如果已经解析了超过设置的最大流量，则会拒绝。
图中是正常行为，因为列表是倒序的，就是先解析了 1.45GB 文件，再解析时，没超过 10GB，所以没有拒绝 20GB 文件。但如果继续解析，则会拒绝。
