### ISSUE TITLE
【寻求帮助】最近老报错服务器错误110，IP被百度封禁

### ISSUE THREAD

**Issue by nglyun** [yuantuo666/baiduwp-php#374]
![image](https://github.com/yuantuo666/baiduwp-php/assets/123817987/22b1a15f-93d1-43c8-bc24-a0b552f2de50)
换了服务器IP能用一下，很快就又封了，会是什么原因导致的？有没避免的方法

**Comment by yuantuo666** [comment]
项目仅供个人使用，建议不要公开密码。
