### ISSUE TITLE
【建议】使用服务器帮助用户配置User-Agent，实现代理流量下载

### ISSUE THREAD

**Issue by eureka6** [yuantuo666/baiduwp-php#375]
## 描述建议
如果可以，使用User-Agent这一步能否交给代理服务器处理？

## 此建议将如何工作
工作步骤:
1. 用户输入百度网盘分享链接，获取文件列表
2. 用户选择文件，点击文件名，进入下载界面
3. 用户获得一个**下载链接**，点击**一键下载**后，直接开始下载
4. 这个**下载链接**将会使用**代理服务器**去下载百度网盘的文件，而免去用户配置User-Agent的步骤。

当前下载方法：用户（+User-Agent） **→** 百度网盘官方直链 **→** 需要下载的文件

期望的下载方法：用户 → 代理服务器（+User-Agent） **→** 百度网盘官方直链 **→** 需要下载的文件

## 相关的技术
nginx代理或者caddy代理能否实现呢？

## 补充信息
部分小白用户，不懂配置User-Agent，希望能用代理服务器一键下载，流量都通过代理服务器下载。

**Comment by wang-zhix** [comment]
那代理服务器 得需要多大带宽。 搞服务器的钱可比 网盘会员贵多了

**Comment by yuantuo666** [comment]
理论上是可以实现的，但是本项目将不会增加这个功能
https://github.com/alist-org/alist 项目实现了这个功能，可以参考
