### ISSUE TITLE
【寻求帮助】大佬,arm64不支持吗?提示The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by E2077** [yuantuo666/baiduwp-php#376]
root@OpenWrt:~# docker pull yuantuo666/baiduwp-php
Using default tag: latest
latest: Pulling from yuantuo666/baiduwp-php
b7f91549542c: Pull complete 
0754b57b9b7d: Pull complete 
71e5060f3937: Pull complete 
f25a6e74b7f5: Pull complete 
3f7a772f0363: Pull complete 
ee48c9e915e2: Pull complete 
7f68d274ab3d: Pull complete 
da7aa3fe8a57: Pull complete 
cc24491dbfd3: Pull complete 
2cdf1b584165: Pull complete 
4f4fb700ef54: Pull complete 
9e7e9371aac2: Pull complete 
cc7379c54ead: Pull complete 
695d64297dbd: Pull complete 
516604fac1a6: Pull complete 
Digest: sha256:32b2385211421a55094d609fa5edb6f056483d653e385cd90576c4bb2495f49f
Status: Downloaded newer image for yuantuo666/baiduwp-php:latest
docker.io/yuantuo666/baiduwp-php:latest
root@OpenWrt:~# docker run -d -p 8080:8000 yuantuo666/baiduwp-php
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
d0050f3628ac913eb8f46788186a1c458c5ea6c7fe9f942ca9525f6de79775c8

**Comment by wang-zhix** [comment]
你直接用打包好的docker镜像 肯定是不支持的， 可以尝试使用源码安装

**Comment by yuantuo666** [comment]
镜像是使用 GitHub Workflow 构建的，没有支持 arm64 架构，可以使用 Dockerfile 自行构建
