### ISSUE TITLE
【BUG 反馈】请求失败 连接服务器过程中出现异常，消息：Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by begger-and-king** [yuantuo666/baiduwp-php#377]
大佬这个是什么问题呢
![微信图片_20240521180749](https://github.com/yuantuo666/baiduwp-php/assets/75322385/36f7c18c-a9c5-4580-a236-281bdd32b696)

**Comment by yuantuo666** [comment]
请提供更多环境信息，也可以将 DEBUG 模式打开抓包调试寻找详细错误原因，参考此处开启调试模式 https://doc.thinkphp.cn/v8_0/debug_mode.html

**Comment by begger-and-king** [comment]
> 请提供更多环境信息，也可以将 DEBUG 模式打开抓包调试寻找详细错误原因，参考此处开启调试模式 https://doc.thinkphp.cn/v8_0/debug_mode.html

好的，目前这个问题是解决了，但是baidu网盘似乎换了新的接口，不能正常获取下载直链，一直报9019

**Comment by begger-and-king** [comment]
这个问题有方法解决嘛，大佬
