### ISSUE TITLE
【BUG 反馈】不能解析了，提示普通账号限制！

### ISSUE THREAD

**Issue by jijianjun1996** [yuantuo666/baiduwp-php#378]
![截图20240603210313](https://github.com/yuantuo666/baiduwp-php/assets/60544771/04861564-c3aa-468e-b791-526fb4e934c9)

**Comment by HZ-ZY** [comment]
确实不行了，网盘封禁了

**Comment by begger-and-king** [comment]
切换Cookie也没有办法解决

**Comment by HZ-ZY** [comment]
有大神解决了吗，急急急！~

**Comment by HZ-ZY** [comment]
/api/sharedownload?channel=chunlei&clienttype=12&web=1&encrypt=0&product=share&type=nolimit

**Comment by HZ-ZY** [comment]
获取直链接口废了

**Comment by xiaojieyahu** [comment]
看来大家都一样啊，耐心等待作者修复把

**Comment by HZ-ZY** [comment]
6.3号晚上8-9点之间封的

**Comment by wukongli** [comment]
百度网盘官方改接口了

**Comment by HZ-ZY** [comment]
知道改成哪个了不

**Comment by HZ-ZY** [comment]
我早上调试了下https://pan.baidu.com/api/sharedownload 这个普通账号获取下载链参数clienttype=12改成clienttype=0可以拿到普通下载链接，但是BUDSS转SVIP加速直链会失败一直报403 无权限

**Comment by wukongli** [comment]
有群吗，交流一下

**Comment by HZ-ZY** [comment]
企鹅裙 588394281

**Comment by wukongli** [comment]
怎么搜不到这个群




Lee
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuantuo666/baiduwp-php"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月4日(星期二) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuantuo666/baiduwp-php] 【BUG 反馈】不能解析了，提示普通账号限制！ (Issue #378)





 
企鹅裙 588394281

**Comment by HZ-ZY** [comment]
588394281

**Comment by ghost** [comment]
好像寄了

**Comment by diannaodiy** [comment]
作者放弃了吗？

**Comment by youdu666** [comment]
yuantu大大快拯救我们呀

**Comment by expl0ler** [comment]
同样的问题
