### ISSUE TITLE
已经GG了，下载链接是空的

### ISSUE THREAD

**Issue by 5536086** [yuantuo666/baiduwp-php#4]
获取到的下载链接是空的，是不是GG了？

**Comment by lc6464** [comment]
你是否配置了 SVIP 账户的 BDUSS 和 STOKEN？
是否有好好看 README.md？

**Comment by 5536086** [comment]
> 你是否配置了 SVIP 账户的 BDUSS 和 STOKEN？
> 是否有好好看 README.md？

找到问题了，cook过期了

**Comment by lc6464** [comment]
你们这些有 SVIP 账户的人就是爽
> 在问题解决后不要忘了 Close Issue.

**Comment by Emperormummy** [comment]
想要个SVIP的bduss和stoken，我把普通的填上去了，弄了个寂寞(ಥ_ಥ)

**Comment by lc6464** [comment]
> 想要个SVIP的bduss和stoken，我把普通的填上去了，弄了个寂寞(ಥ_ಥ)

谁不想要呢……

**Comment by lc6464** [comment]
> > 你是否配置了 SVIP 账户的 BDUSS 和 STOKEN？
> > 是否有好好看 README.md？
> 
> 找到问题了，cook过期了

解决问题以后不要忘记关闭 Issue 啊！

**Comment by Emperormummy** [comment]
我想说都有svip了还搭建这玩意儿干啥

**Comment by lc6464** [comment]
> 我想说都有svip了还搭建这玩意儿干啥

- 要有热衷于探索技术的心！
- 就算你有 SVIP ，你依然要靠客户端，而百度网盘客户端干过人事吗？
- 就算你有 SVIP ，除非你愿意把账号借给你的朋友，不然你就没办法使你的朋友高速下载。
- 还有很多原因。
