### ISSUE TITLE
服务器错误(118)

### ISSUE THREAD

**Issue by tdk-kedion** [yuantuo666/baiduwp-php#40]
页面显示信息：

$_GET:array(1) {
  ["download"]=>
  string(0) ""
}
$_POST:array(8) {
  ["fs_id"]=>
  string(15) "372178091059035"
  ["time"]=>
  string(10) "1606243520"
  ["sign"]=>
  string(40) "e730d05a4db7372251217627a00bcade1fd28db1"
  ["randsk"]=>
  string(0) ""
  ["share_id"]=>
  string(10) "3933285505"
  ["uk"]=>
  string(9) "355833574"
  ["bdstoken"]=>
  string(32) "f3f541f77dace2adb627aa66a8a3f52e"
  ["filesize"]=>
  string(10) "4478906368"
}
getDlink():array(3) {
  ["errno"]=>
  int(118)
  ["request_id"]=>
  int(7633115744522352009)
  ["server_time"]=>
  int(1606243605)
}

**Comment by 66hh** [comment]
好像是api炸了

**Comment by 66hh** [comment]
还有，你的bdstoken漏了

**Comment by yuantuo666** [comment]
请检查服务器IP
建议使用独立IP服务器

项目源码于2020年11月25日22:41测试正常运行
![Screenshot_20201125_224138_com android chrome](https://user-images.githubusercontent.com/44130602/100242465-c6e98480-2f6f-11eb-942d-9d9f77dce661.jpg)

**Comment by tdk-kedion** [comment]
重新拉取本地测试也是无法使用，提示118
