### ISSUE TITLE
能不能支持一下秒传链接的下载提取？

### ISSUE THREAD

**Issue by daiaji** [yuantuo666/baiduwp-php#42]
https://greasyfork.org/zh-CN/scripts/397324-%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96
蛮多资源都用秒传了……

**Comment by yuantuo666** [comment]
目前不会。
因为秒传链接只存储了几个关键的md5码，如果需要下载需要转存到网盘里，再获取链接下载。

这就涉及到网盘操作，如果用访客的账号，必须要在云端执行；如果用站长的账号，对下载后文件又需要删除。（软件小妹和naifei都是使用这种方法）

涉及的步骤繁多，有兴趣的可以另开一个项目。
相关接口可以直接抓包网页版获取。

----
对于普通用户，只需要转存文件（一般文件数量比较少）到自己网盘，再分享下载即可。

**Comment by daiaji** [comment]
> 目前不会。
> 因为秒传链接只存储了几个关键的md5码，如果需要下载需要转存到网盘里，再获取链接下载。
> 
> 这就涉及到网盘操作，如果用访客的账号，必须要在云端执行；如果用站长的账号，对下载后文件又需要删除。（软件小妹和naifei都是使用这种方法）
> 
> 涉及的步骤繁多，有兴趣的可以另开一个项目。
> 相关接口可以直接抓包网页版获取。
> 
> 对于普通用户，只需要转存文件（一般文件数量比较少）到自己网盘，再分享下载即可。

创建一个文件夹到vip账户用来接收可以了吧。
顺便收集些资源也挺好的？

访客id有啥用我至今没想明白，这玩意又完全没速度…

**Comment by yuantuo666** [comment]
可以作为一个方案
在线转存也已经有作者实现了 [baidupan-rapidupload](ttps://github.com/TkzcM/baidupan-rapidupload)

**Comment by TkzcM** [comment]
https://github.com/TkzcM/baiduwp/commit/f4b730593c760225dbfacb8ab3b269782902f8de
上游已实现

**Comment by daiaji** [comment]
> [TkzcM/baiduwp@f4b7305](https://github.com/TkzcM/baiduwp/commit/f4b730593c760225dbfacb8ab3b269782902f8de)
> 上游已实现

@yuantuo666 gkd gkd😂

**Comment by yuantuo666** [comment]
目前部分文件无法生成秒传链接，百度可能准备封禁此功能（指无法获取对应的md5，但仍然可以秒传上传）

![IMG_20210403_120019_072](https://user-images.githubusercontent.com/44130602/113467236-606ff800-9474-11eb-8fad-22251762bc65.jpg)
