### ISSUE TITLE
我搭建的程序几天后账号就被限速了

### ISSUE THREAD

**Issue by a8196168** [yuantuo666/baiduwp-php#43]
以前用的好好的，前段时间账号被限速，我以为是我的vip账号经常登录破解版网盘的原因，然后重新注册了百度账号开通会员，然后把cookie填到网站，没怎么用也会被限速，现在没再开会员了，我怀疑是不是cookie被盗用了！或者有没有最新版本能不能解除这个问题

地址：http://wp.wankazy.cn
小弟邮箱：619027892@qq.com

**Comment by yuantuo666** [comment]
1.4.3版本支持保存解析记录。

关于限速状况我不清楚，因为我这边没有测试。
目前没有解决方法。

**Comment by a8196168** [comment]
刚才看了下GitHub，1.4.4可以轮训VIP会员账号并且有后台方便管理，能不能体验一下

**Comment by a8196168** [comment]
> 1.4.3版本支持保存解析记录。
> 
> 关于限速状况我不清楚，因为我这边没有测试。
> 目前没有解决方法。



> 1.4.3版本支持保存解析记录。
> 
> 关于限速状况我不清楚，因为我这边没有测试。
> 目前没有解决方法。

1.4.4版本的从哪里下载！

**Comment by yuantuo666** [comment]
1. 最新版本请QQ联系我私聊获取
2. 正常官方账号_（4-5人合租的一般也可以）_可以解析4-5TB
