### ISSUE TITLE
取消免费次数

### ISSUE THREAD

**Issue by ALICEOFALICE** [yuantuo666/baiduwp-php#44]
希望能取消掉免费次数，内网部署源码后，免费次数没意义，或者改为输入密码就无视免费次数。

**Comment by yuantuo666** [comment]
目前可以使用1.4.2的版本，旧版本没有解析次数限制。
自定义下载次数会在下一版本更新。

**Comment by syxvip** [comment]
没输入密码免费1次，输入密码就自定义免费次数~~

**Comment by yuantuo666** [comment]
最新版本1.4.5已支持
