### ISSUE TITLE
报错verifyPwd():NULL

### ISSUE THREAD

**Issue by WangEdward** [yuantuo666/baiduwp-php#45]
链接和密码均正确，提示：“提取码错误或文件失效！”

``` 
verifyPwd():NULL

Notice: Trying to access array offset on value of type null in /www/wwwroot/pandl/baiduwp-php-1.4.3/functions.php on line 153
```

**Comment by yuantuo666** [comment]
1.请检查服务器网络是否正常
2.curl是否正常工作
3.无密码文件能否正常解析

**Comment by WangEdward** [comment]
> 1.请检查服务器网络是否正常

服务器网络正常，ping 百度通

> 2.curl是否正常工作

curl 可以正常工作

> 3.无密码文件能否正常解析

我没找到无密码文件😅🤣

**Comment by yuantuo666** [comment]
https://pan.baidu.com/s/1pL8uSaB

**Comment by yuantuo666** [comment]
如果无密码文件也无法解析，可能是服务器ip问题，请尝试本地搭建
2021.01.01 18:38代码测试没问题
![image](https://user-images.githubusercontent.com/44130602/103437287-c1fbad00-4c60-11eb-81cf-9328ada9970d.png)

**Comment by lc6464** [comment]
您好，这个问题在如今正在开发的版本中已经得到彻底解决，您可以等待下一个版本的发布，也可以直接 clone 储存库以提前体验（不建议，因为可能不稳定）。
现关闭此议题，如果您还有问题未解决，您可以重新打开议题并发表评论以询问。
