### ISSUE TITLE
1.4.3版本，只能免费用一次

### ISSUE THREAD

**Issue by xiaohared** [yuantuo666/baiduwp-php#46]
您好，今天安装的1.4.3的版本，设置了密码，但是一个ip只能免费解析一次，请问有什么办法能放开限制吗？

**Comment by yuantuo666** [comment]
1.可以使用老版本 ` 1.4.2 ` 。
2.等待下一版本更新。
3.手动修改源代码。

**Comment by yuantuo666** [comment]
最新版本1.4.5已支持自定义解析次数
