### ISSUE TITLE
页脚统计代码显示问题

### ISSUE THREAD

**Issue by tdk-kedion** [yuantuo666/baiduwp-php#47]
不知道是我改了页面内容原因还是本身显示原因，手机上显示页脚统计代码的时候会有问题

**Comment by yuantuo666** [comment]
麻烦截图，谢谢。
建议使用隐藏式的代码统计。

**Comment by lc6464** [comment]
由于长时间没有得到您的回复，我们视您的问题为已解决，若您对此还有疑问，您可以重新打开议题并发表评论以询问。
