### ISSUE TITLE
百度网盘BDUSS重置

### ISSUE THREAD

**Issue by lsj8924** [yuantuo666/baiduwp-php#48]
百度网盘每次重新登录会重置SVIP的BDUSS，讲道理应该每次重新登录都要填写一次BDUSS。但是baiduwp-php好像只要填写一次就行了。这个是百度网盘没有校检吗？还是代码有什么具体的应对措施，我查看代码没有发现。不解之处还请多多指教。

**Comment by yuantuo666** [comment]
百度网盘的设置就是这样，只要不修改密码，bduss就不会改变。

**Comment by lsj8924** [comment]
> 百度网盘的设置就是这样，只要不修改密码，bduss就不会改变。

但是我今天登录百度网盘查看bduss和我之前填写的确实不是同一串了。
