### ISSUE TITLE
可否增加一个自动切换svip账号功能

### ISSUE THREAD

**Issue by syxvip** [yuantuo666/baiduwp-php#49]
上面看到有朋友提了一个 增加免费次数的功能，感觉很棒，能不能加一个判断限速后自动切换svip 账号的BDUSS ，STOKEN 功能。这样就不用手动去换了，限速的账号两天就恢复了，避免每天去耗费大量精力去换，

**Comment by yuantuo666** [comment]
这个功能已经实现了
获取方式联系邮箱yuantuo666@gmail.com

**Comment by syxvip** [comment]
已经给您发邮件，目前未得到回复，请问还有其他联系方式么

**Comment by yuantuo666** [comment]
最新版本1.4.5已支持
