### ISSUE TITLE
能否完善文件夹打开功能

### ISSUE THREAD

**Issue by 2595133804** [yuantuo666/baiduwp-php#5]
能否完善文件夹打开功能

**Comment by lc6464** [comment]
### 我做了个点击文件夹自动跳转到百度网盘官方分享页面的功能。
- 可以看看我提交的 pr
- 或者看看我 fork 的储存库

**Comment by lc6464** [comment]
已在我的开发计划中，预计 1.2.3 或 1.2.4 版本会出。
[我的储存库](https://github.com/lc6464/baiduwp-php "我的储存库")

**Comment by lc6464** [comment]
# 我已经将此功能实现了！
次要版本号改为 3 了，这个升级算比较大的。
- 你可以看看我提交的 PR
- 或者看看我的储存库

**Comment by pongfcnkl** [comment]
> 
> # 我已经将此功能实现了！
> 
> 次要版本号改为 3 了，这个升级算比较大的。
> 
>     * 你可以看看我提交的 PR
> 
>     * 或者看看我的储存库

你这个版本有个bug ，下载文件夹不会提示暂不支持文件夹下载 ，直接跳转出现一个随机数字

**Comment by pongfcnkl** [comment]
> 
> 
> > # 我已经将此功能实现了！
> > 次要版本号改为 3 了，这个升级算比较大的。
> > ```
> > * 你可以看看我提交的 PR
> > 
> > * 或者看看我的储存库
> > ```
> 
> 你这个版本有个bug ，打开文件夹不会提示暂不支持文件夹下载 ，直接跳转出现一个随机数字

**Comment by lc6464** [comment]
> 你这个版本有个bug ，打开文件夹会直接跳转出现一个随机数字

请问你使用的是哪个版本？目前最新的版本是 1.3.0。

**Comment by pongfcnkl** [comment]
> 
> 
> > 你这个版本有个bug ，打开文件夹会直接跳转出现一个随机数字
> 
> 请问你使用的是哪个版本？目前最新的版本是 1.3.0。

我是直接Clone 下来的

**Comment by lc6464** [comment]
> 我是直接Clone 下来的

你看一下你 Clone 的 README.md 或者 php 文件的注释中的版本号，有一个版本我是没有检查的，可能存在 bug.

**Comment by pongfcnkl** [comment]
> 
> 
> > 我是直接Clone 下来的
> 
> 你看一下你 Clone 的 README.md 或者 php 文件的注释中的版本号，有一个版本我是没有检查的，可能存在 bug.

更新了下好了

**Comment by lc6464** [comment]
> 更新了下好了

如果你用的是那个 pre-release 的版本，是有可能存在 bug 的。

最新版目前没发现有 bug ，如果提示打不开目录、无法写入文件、权限问题之类的情况的话，
可能是因为储存 SESSION 的位置 php 无权操作。

附带的文件是目前最新版的程序以及资源的文件压缩版，与程序运行无关的文件的文件均未在内。
版本 `1.3.1`
下载地址：[baiduwp-php.zip](https://github.com/yuantuo666/baiduwp-php/files/5080375/baiduwp-php.zip)

**Comment by lc6464** [comment]
> 能否完善文件夹打开功能

如果你的问题解决了，不要忘了关闭问题哟~
**Don't forget to close this issue!**

**Comment by pongfcnkl** [comment]
> 
> 
> > 更新了下好了
> 
> 如果你用的是那个 pre-release 的版本，是有可能存在 bug 的。
> 
> 最新版目前没发现有 bug ，如果提示打不开目录、无法写入文件、权限问题之类的情况的话，
> 可能是因为储存 SESSION 的位置 php 无权操作。
> 
> 附带的文件是目前最新版的程序以及资源的文件压缩版，与程序运行无关的文件的文件均未在内。
> 版本 `1.3.1`
> 下载地址：[baiduwp-php.zip](https://github.com/yuantuo666/baiduwp-php/files/5080375/baiduwp-php.zip)

要是能不用改ua就能下载就好了

**Comment by lc6464** [comment]
> 要是能不用改ua就能下载就好了

百度云的限制莫得办法。
那个适用于 Chromium 内核的浏览器的更改 UA 的插件我附在 resource 文件夹中了。
