### ISSUE TITLE
1.4.3解析失效 解析后页面为空

### ISSUE THREAD

**Issue by shzxm** [yuantuo666/baiduwp-php#50]
![image](https://user-images.githubusercontent.com/9905297/104124672-08ea5080-538d-11eb-85c3-2626a84877d6.png)

**Comment by yuantuo666** [comment]
1.检查是否修改了源码，正常情况下都有提示页面的。
2.请在config.php中打开debug模式，查看相关信息。
3.检查客户端及服务器网络状况。

**Comment by shzxm** [comment]
> 1.检查是否修改了源代码，正常情况下都有提示页面。。
除了修改config.php 剩下均没有更改
并且重新部署
> 请在config.php中打开调试模式，查看相关信息
打开debug模式后
![image](https://user-images.githubusercontent.com/9905297/104165061-d182af00-5433-11eb-83ed-829698e8b549.png)


> 。3.检查客户端和服务器网络状况。

网络无问题.更换主机后重新部署,同样的问题.

nginx无报错
php7.4.3

**Comment by yuantuo666** [comment]
可能是PHP版本问题，换个7.2的版本试下

**Comment by shzxm** [comment]
> 可能是PHP版本问题，换个7.2的版本试下

已经降级php版本为 `PHP 7.2.34-8+ubuntu20.04.1+deb.sury.org+1`

问题依旧

可否告知php依赖项.我检查下

**Comment by shzxm** [comment]
> 可能是PHP版本问题，换个7.2的版本试下

看到个nginx的报错,

```
2021/01/12 02:42:40 [error] 47937#47937: *2 open() "/var/www/html/baiduwp-php/page/2" failed (2: No such file or directory), client: 222.222.222.222, server: aaa.bbb.ccc, request: "GET /page/2 HTTP/2.0", host: "aaa.bbb.ccc", referrer: "https://aaa.bbb.ccc/"
```

**Comment by shzxm** [comment]
啊.问题解决了.

php7.4.3没问题

是缺少依赖 `php-curl`

感谢作者
