### ISSUE TITLE
问一下有没有判断账号限速显示一个图标是否正常

### ISSUE THREAD

**Issue by a1061244130** [yuantuo666/baiduwp-php#51]
之前好像在哪里看到过有

**Comment by a1061244130** [comment]
还有是否能解决下远程推送问题   和批量下载的问题

**Comment by yuantuo666** [comment]
> 之前好像在哪里看到过有

demo里面有的
最新版本支持，最新的1.4.5版本支持后台管理：①可以自动切换限速账号；②有黑名单、白名单功能；③可查看解析数据；④在后台修改解析次数。
获取方法联系邮箱yuantuo666@gmail.com

**Comment by a1061244130** [comment]
> > 之前好像在哪里看到过有
> 
> 演示有的里面
> 最新版本请立即获取iTunes，最新的1.4.5版本支持后台管理：①可以自动切换限速账号;②有黑名单，白名单功能;③可查看解析数据;④在后台修改解析次数。
> 获取方法联系邮箱[yuantuo666@gmail.com](mailto:yuantuo666@gmail.com)

已经发邮件了
