### ISSUE TITLE
SVIP BDUSS和BDUSS有什么区别，在哪能找到

### ISSUE THREAD

**Issue by jieshuq** [yuantuo666/baiduwp-php#52]
SVIP BDUSS和BDUSS有什么区别，在哪能找到？

**Comment by yuantuo666** [comment]
> 【必填】在③中必须填入SVIP的BDUSS，用于获取下载链接，获取cookie方法同上。

请仔细查看设置方法

**Comment by yuantuo666** [comment]
SVIP BDUSS 指的是 SVIP的BDUSS

**Comment by lc6464** [comment]
BDUSS 用于获取分享链接内的文件列表，而 SVIP BDUSS 用于获取下载链接。
BDUSS 和 STOKEN 必须是同一个账号的，而 SVIP BDUSS 可以与 BDUSS 不同。
BDUSS 可以是普通账户的 BDUSS，而 SVIP BDUSS 必须使用 SVIP 账户。
STOKEN 与 BDUSS 对应，而非 SVIP BDUSS。
其实 BDUSS 和 SVIP BDUSS 都是账号的 BDUSS，只是 SVIP BDUSS 一定要 SVIP 账号才行。

[点击这里](https://pandownload.com/faq/cookie.html)可以查看获取 BDUSS 和 STOKEN 的方法。

**Comment by lc6464** [comment]
如果您还有问题，可以重新打开议题并发送评论以询问。

**Comment by JarvanDing** [comment]
> BDUSS 用于获取分享链接内的文件列表，而 SVIP BDUSS 用于获取下载链接。
> BDUSS 和 STOKEN 必须是同一个账号的，而 SVIP BDUSS 可以与 BDUSS 不同。
> BDUSS 可以是普通账户的 BDUSS，而 SVIP BDUSS 必须使用 SVIP 账户。
> STOKEN 与 BDUSS 对应，而非 SVIP BDUSS。
> 其实 BDUSS 和 SVIP BDUSS 都是账号的 BDUSS，只是 SVIP BDUSS 一定要 SVIP 账号才行。
> 
> [点击这里](https://pandownload.com/faq/cookie.html)可以查看获取 BDUSS 和 STOKEN 的方法。

请问这个意思是，我必须准备2个盘账户来获取不同的 BDUSS？ 我只有一个SVIP账户，一直解析不成功   “已获取到文件，但未能获取到下载链接！”

**Comment by yuantuo666** [comment]
> 请问这个意思是，我必须准备2个盘账户来获取不同的 BDUSS？ 我只有一个SVIP账户，一直解析不成功 “已获取到文件，但未能获取到下载链接！”

你可以使用两个不同账号，即一个普通账号提供STOKEN和BDUSS；会员账号提供SVIP BDUSS（就是会员账号的BDUSS）。

或者均使用会员账号信息：会员账号提供STOKEN、BDUSS和SVIP BDUSS（就是会员账号的BDUSS）。

---
以你的情况，将BDUSS和SVIP BDUSS都设置为会员账号的BDUSS，将STOKEN设成会员账号的STOKEN，后台的账号切换模式改为“本地模式”即可。

**Comment by 1592363624** [comment]
> 

有没有获取的脚本  多账号的时候就比较麻烦了

**Comment by yuantuo666** [comment]
> > 
> 
> 有没有获取的脚本 多账号的时候就比较麻烦了

原来有个浏览器插件，但有时候获取的STOKEN不准确，所以删除了
你可以尝试下： 
1. [GetBaiduPanCookies](https://github.com/dylanbai8/GetBaiduPanCookies)
2. [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg)
