### ISSUE TITLE
为什么换了账号以后还是限速

### ISSUE THREAD

**Issue by a1061244130** [yuantuo666/baiduwp-php#54]
网盘里面下载没有限速啊

**Comment by yuantuo666** [comment]
本项目采用的是分享下载功能哦

**Comment by a1061244130** [comment]
> 本项目采用的是分享下载功能哦

啥意思

**Comment by yuantuo666** [comment]
就是解析下载地址是通过分享页面获取的，并没有保存到网盘里面再下载

**Comment by yuantuo666** [comment]
如果还有问题可以把你的设置截图发我邮箱yuantuo666@gmail.com

**Comment by Ecalose** [comment]
> 就是解析下载地址是通过分享页面获取的，并没有保存到网盘里面再下载

老哥，话说保存到网盘再下载的项目昂

**Comment by yuantuo666** [comment]
> > 就是解析下载地址是通过分享页面获取的，并没有保存到网盘里面再下载
> 
> 老哥，话说保存到网盘再下载的项目昂

本项目没有保存网盘哦
如果要执行这个操作要BDUSS和STOKEN两个cookie

**Comment by Ecalose** [comment]
> > > 就是解析下载地址是通过分享页面获取的，并没有保存到网盘里面再下载
> > 
> > 
> > 老哥，话说保存到网盘再下载的项目昂
> 
> 本项目没有保存网盘哦
> 如果要执行这个操作要BDUSS和STOKEN两个cookie

soga

**Comment by yuantuo666** [comment]
首页的限速标识显示的是上一次的解析数据，设置了新的账号后，需要解析一个大于50MB的文件才能更新首页信息。
