### ISSUE TITLE
145版本如何取消解析的弹窗

### ISSUE THREAD

**Issue by a1061244130** [yuantuo666/baiduwp-php#60]
解析完成后点击获取到的文件会弹出
继续解析？
为保证服务稳定，每个IP每天有20次免费解析次数，是否继续？

这个弹窗如何取消 多文件已经够烦了。。。 这个玩意怎么取消

**Comment by lc6464** [comment]
非常抱歉，此功能在1.4.5版本暂未实现，你可以在 index.php 中将第83行（`Swal.fire({`）至第91行（`if (e.isConfirmed) {`）以及第93（`});`）、94（`}`）行删除。
您也可以选择直接克隆 master 分支，最新一次的提交实现了这个功能，如果有需要我们会进行版本更新。

**Comment by yuantuo666** [comment]
非常抱歉，此功能在1.4.5版本暂未实现，你可以在 index.php 中将第75行（`Swal.fire({`）至第85行（`function() {`）以及第87（`});`）、88（`}`）行删除。
您也可以选择直接克隆 master 分支，最新一次的提交实现了这个功能，如果有需要我们会进行版本更新。
![image](https://user-images.githubusercontent.com/44130602/107764926-effa0400-6d6b-11eb-8f04-033eebbfe52e.png)

**Comment by lc6464** [comment]
您的这个问题已经得到了解决，现在关闭此议题，如果您还有别的问题，您可以随时重新打开此议题。
