### ISSUE TITLE
可否对接QQ群机器人功能

### ISSUE THREAD

**Issue by musaart** [yuantuo666/baiduwp-php#61]
如题，能否增加对接QQ群机器人功能，在群里发送需要解析的地址，返回解析好的地址。

**Comment by yuantuo666** [comment]
具体要对接什么类型的`QQ群机器人`呢，仅PHP语言是完成不了的

**Comment by lc6464** [comment]
这个需求我们似乎只能做到实现一个 API，剩下的就不是我们能完成的了。

**Comment by musaart** [comment]
谢谢，您只要给出一个api即可，正在联系QQ机器人论证可行性




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LC"<notifications@github.com&gt;; 
发送时间: 2021年2月12日(星期五) 晚上8:05
收件人: "yuantuo666/baiduwp-php"<baiduwp-php@noreply.github.com&gt;; 
抄送: "上善若水"<2584623954@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 可否对接QQ群机器人功能 (#61)





 
这个需求我们似乎只能做到实现一个 API，剩下的就不是我们能完成的了。

**Comment by lc6464** [comment]
我们可能会考虑实现这个功能。

**Comment by musaart** [comment]
您可以在telegram机器人上尝试此功能的开发，看到您的相关项目有此类机器人的案例




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LC"<notifications@github.com&gt;; 
发送时间: 2021年2月12日(星期五) 晚上8:10
收件人: "yuantuo666/baiduwp-php"<baiduwp-php@noreply.github.com&gt;; 
抄送: "上善若水"<2584623954@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 可否对接QQ群机器人功能 (#61)





 
我们可能会考虑实现这个功能。

**Comment by lc6464** [comment]
此功能目前正在实现，但不一定会完整实现，我们仍未确定是否要完整实现此功能。

另外，我以及项目的原作者都快开学了，开学后我将会很少（甚至不会）继续完善这个项目，直到暑假，不知项目原作者如何安排。

**Comment by musaart** [comment]
感谢您和原作者的贡献，非常感谢您的回复。没关系的，学业为重，我也在积极想办法实现，争取早日成功，这样和朋友分享会员就会更方便些



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LC"<notifications@github.com&gt;; 
发送时间: 2021年2月16日(星期二) 晚上10:06
收件人: "yuantuo666/baiduwp-php"<baiduwp-php@noreply.github.com&gt;; 
抄送: "上善若水"<2584623954@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 可否对接QQ群机器人功能 (#61)





 
此功能目前正在实现，但不一定会完整实现，我们仍未确定是否要完整实现此功能。
 
另外，我以及项目的原作者都快开学了，开学后我将会很少（甚至不会）继续完善这个项目，直到暑假，不知项目原作者如何安排。

**Comment by lc6464** [comment]
> 感谢您和原作者的贡献，非常感谢您的回复。没关系的，学业为重，我也在积极想办法实现，争取早日成功，这样和朋友分享会员就会更方便些


如果您有什么好的实现方法，您可以通过拉取请求的方式提交到 dev 分支，目前我们已经将管理后台 `settings.php` 里面的部分操作改为提供 API 以 ajax 方式进行了，这也是我们实现此功能的思路。

**Comment by yuantuo666** [comment]
https://github.com/yuantuo666/baiduwp-bot
参考此项目
