### ISSUE TITLE
后台管理删除数据、安装时不清除数据库

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#62]
没用的svip cookie，解析记录，黑白名单，加上就不能清除，如果卡bug导致8小时内链接就不能用，或者手滑设置错了cookie/黑白名单，只能删除数据库重来

**Comment by lc6464** [comment]
我们目前正在开发这个功能，请耐心等待新版本。

**Comment by GreenTeodoro839** [comment]
提个建议，用安装程序安装时，添加个不清除数据库，要不每次更新都要重新添加cookie很麻烦

**Comment by lc6464** [comment]
删除数据功能已经实现，如果您想预先体验，您可以测试 dev 分支的代码，我们将会继续完善。
如果您追求稳定，您可以在我们合并到 master 分支后再使用，或者等待新版本发布。

**Comment by lc6464** [comment]
> 提个建议，用安装程序安装时，添加个不清除数据库，要不每次更新都要重新添加cookie很麻烦

这样的话需要验证数据库结构是否正确，如果这个功能可行，我们会考虑实现这个功能。
如果不对数据库结构进行验证，程序可能会因为数据库结构问题而出现不可预料的后果。

**Comment by yuantuo666** [comment]
安装时不清空数据库功能已经实现，如果您想预先体验，您可以测试 dev 分支的代码，我们将会继续完善。
如果您追求稳定，您可以在我们合并到 master 分支后再使用，或者等待新版本发布。

附最新dev下载链接 https://github.com/yuantuo666/baiduwp-php/archive/dev.zip
