### ISSUE TITLE
客户端错误

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#64]
今天晚上一个人解析了文件，但是怎么都没法下载，浏览器显示一串代码，adm客户端错误，但是我从后台弄的链接就能下载，但发给他还是不能下载，而且他其他文件都正常
复制这段内容后打开百度网盘App，操作更方便哦。 链接:https://pan.baidu.com/s/1XIDP099Yj2Zx8iXyYKO0wQ 提取码:tu9p
![-24be1b77fd136145](https://user-images.githubusercontent.com/77104800/107958258-ba0f8680-6fdc-11eb-90d5-5498fe88955f.jpg)

**Comment by GreenTeodoro839** [comment]
2.00版本，提取的直链：
https://qdcm02.baidupcs.com/file/0e85951a5le5e87cfc96c6c08aa2fd19?bkt=en-2fb6763f1c8fb10155eb3dad569429bb4fdea422420355eff90dd67cc2eb38bf6df63344edfb0529&fid=2452610244-250528-627164325169074&time=1613395797&sign=FDTAXUGERQlBHSKfWaqi-DCb740ccc5511e5e8fedcff06b081203-YuPKiVIzoVW0tUIFIAqyjgrCRgg%3D&to=40&size=4765999189&sta_dx=4765999189&sta_cs=4&sta_ft=zip&sta_ct=6&sta_mt=2&fm2=MH%2CQingdao%2CAnywhere%2C%2Cshandong%2Ccmnet&ctime=1585398163&mtime=1613131866&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=4765999189&vuk=750590469&iv=2&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-582e67e3dfb7e9cf92b88d51db12baf4ccc252ccca655a0242c0fb56ff75e08a952d91ccdcdc9ca0&expires=8h&rt=sh&r=489364983&vbdid=-&fin=ck%E9%98%B2%E6%AD%A2%E4%BD%8E%E4%BA%8E.zip&rtype=1&dp-logid=1064453187356704579&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=iSGCyvX%2BBPMLk2F5i%2FWqdibMYfk%3D&so=1&ut=1&uter=0&serv=0&uc=3200815480&ti=2902ee95632ccf5a71ce782e848e805960bf364b028a742e&hflag=30&from_type=3&adg=c_2e4c9dbb66e2733b710a783d59d6cd9e&reqlabel=250528_f_1573f0bb16d910bc2ef9d34712da7e6d_-1_54cd4cc0cfaa348a188ae57fc1ac1e2b&by=themis

**Comment by yuantuo666** [comment]
![image.png](https://i.loli.net/2021/02/15/dPt3b5frVGHzYQ8.png)
我这边用你的链接测试没有问题的哦
检查一下ua是否正确~

**Comment by yuantuo666** [comment]
另外，你提到的**浏览器显示一串代码**具体是指什么，能复制下或截图吗？

**Comment by GreenTeodoro839** [comment]
{"error_code":31362,"error_msg":"sign error","error_info":"","request_id":1064453187356704579}

**Comment by yuantuo666** [comment]
这个是点击链接之后出现的吧

必须要设置User-Agent才能下载文件

**Comment by GreenTeodoro839** [comment]
好的，谢谢
