### ISSUE TITLE
手机端对话框显示不正常

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#66]
edge，华为浏览器，via，pure浏览器都用了，对话框如图，电脑全部正常，我是用的2.00版，旧版没有这个问题
![Screenshot_20210216_090734](https://user-images.githubusercontent.com/77104800/108006506-9aa54780-7036-11eb-8d56-92d520802308.jpg)

**Comment by lc6464** [comment]
请检查你的服务器的 SweetAlert2 的 CSS 文件是否正常。
我将会在半小时内对你所说的情况进行测试，请稍等。

**Comment by GreenTeodoro839** [comment]
服务器没有问题，我用你们的演示站也有这个bug

**Comment by lc6464** [comment]
经测试，Microsoft Edge 正常状态、Microsoft Edge 在开发人员工具中模拟移动端设备、安卓设备上的 Microsoft Edge 均没问题，服务器上的程序的版本是2.0.0.
`Microsoft Edge 88.0.705.68`
安卓上的 `Microsoft Edge 46.01.4.5140` （2月8日更新）。

![Microsoft Edge](https://user-images.githubusercontent.com/64722907/108008480-6b450980-703b-11eb-9296-2a8c509ed7ca.png)
![模拟移动设备](https://user-images.githubusercontent.com/64722907/108008629-bced9400-703b-11eb-9b56-f81f26af4fdb.png)
![移动设备](https://user-images.githubusercontent.com/64722907/108008532-857ee780-703b-11eb-8f29-73290d02ec04.png)

**Comment by yuantuo666** [comment]
如果可以，麻烦提供一下网站解析密码，以便我们帮你调试

**Comment by yuantuo666** [comment]
检查下看你能不能正常访问这个CSS文件
https://cdn.jsdelivr.net/npm/@sweetalert2/theme-default@4.0.2/default.min.css

**Comment by yuantuo666** [comment]
如果能访问，可能是网站出了问题，这个需要你打开控制台进一步查看。
如果不能访问，可能是网络出了问题，请关闭代理，检查是否能够正常下载CSS文件。

**Comment by GreenTeodoro839** [comment]
我把edge更新到46版本就正常了，原来是45版本，但是其他浏览器（pure，via，华为等）能不能向下兼容，绝大多数人用的是系统自带

**Comment by yuantuo666** [comment]
经测试，华为手机自带浏览器确实存在问题
我们将尽快修复
![Screenshot_20210216_101550_com huawei browser](https://user-images.githubusercontent.com/44130602/108010510-02ac5b80-7040-11eb-8f06-5c7613507e96.jpg)

**Comment by yuantuo666** [comment]
已经找到问题所在并在dev分支中修复
原因是对不支持色彩模式的浏览器没有加载CSS文件
