### ISSUE TITLE
解析量显示不正确

### ISSUE THREAD

**Issue by zhy0715** [yuantuo666/baiduwp-php#67]
![Screenshot_20210216_171228_com huawei browser](https://user-images.githubusercontent.com/65905561/108042309-96028280-707a-11eb-997f-872e1d50bfec.jpg)
不管解析多少，都是2G

**Comment by lc6464** [comment]
您使用的版本是？

**Comment by zhy0715** [comment]
最新的2.0.0

**Comment by yuantuo666** [comment]
似乎这个bug只在低版本的PHP才会触发，原因是整数型溢出

**Comment by yuantuo666** [comment]
已在最新dev分支中修复

**Comment by lc6464** [comment]
您使用的 PHP 是什么版本的？我们想要进一步测试。

**Comment by zhy0715** [comment]
我用的是php7.3
