### ISSUE TITLE
解析文件列表只会解析前100个文件，而不是全部文件

### ISSUE THREAD

**Issue by yuantuo666** [yuantuo666/baiduwp-php#68]
在文件列表页面，由于接口限制，只会加载前100个文件，但显示的是**已全部加载**。

**Comment by yuantuo666** [comment]
一次文件分享（同一目录下）最多包含500个文件

**Comment by lc6464** [comment]
似乎把两个 `已全部加载，共' . count($filejson["list"]) . '个` 改为 `已加载' . count($filejson["list"]) . '个` 就可以了吧？
不过判断是否全部加载要另外写逻辑。

**Comment by newdive** [comment]
之前也遇到过这个问题， 我是通过&nbsp;&nbsp;排序+尝试判断&nbsp;&nbsp;的方法来解决
1、设置 `order` 和 `desc` 参数，保证每次请求的排序都是一致， 最好设置 `order=name`(文件名唯一) 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;这样保证不同 `page` 的数据不会出现重复
2、每次请求设置 `num=100` ,  保证列表最多返回 100 条数据 ，再 加上条件1 中不重复数据的保证
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;所以当返回数据小于100 的时候，则说明没有更多的数据
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;否则需要增加 `page` 参数值再尝试请求， 直至返回的数据条目小于 100
 
另外网盘好像有个统计文件夹里边文件数的接口， 不过这个目前没研究过，不知道怎么弄
但如果可以用上这个接口的话就比较方便 ，可以一次请求就知道总的文件数
（不过文件条目还是得分页请求，这个无解）

**Comment by lc6464** [comment]
这个鸽了多久了？

**Comment by yuantuo666** [comment]
gugugugu




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月2日(星期天) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuantuo666/baiduwp-php] 解析文件列表只会解析前100个文件，而不是全部文件 (#68)





 
这个鸽了多久了？

**Comment by yuantuo666** [comment]
根目录似乎不会出现这个问题

**Comment by yuantuo666** [comment]
https://github.com/yuantuo666/baiduwp-php/commit/6d5831bb7180f2b0b8d7b8ad56afcdaa55748f9f 已修复
