### ISSUE TITLE
获取的链接失效

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#70]
一个小时之前获取的，扔到adm能显示文件名，但是提示是网页请到浏览器打开，打开后报错{ "error_code":31064, "error_msg":"xcode expire time out error" }
解析的直链：https://d6.baidupcs.com/file/2ba598badd98926878c643cf4c8cdc09?bkt=en-4d166c07188776153efa73bb4665913e96c5378fb294b5b653bd7e73456958245ad69a9a47aa3309&xcode=8a6a3e0bef047269be9d584cc3c0fc86568d5a4037901d1f5c88326ff1ad49a38504ee9063c140bb1929ea09df71fa9e0b2977702d3e6764&fid=3671505180-250528-451087160016465&time=1613508951&sign=FDTAXUGERQlBHSKfaqi-DCb740ccc5511e5e8fedcff06b081203-%2F1IBU0hCk8AzfEBP%2BnuHj1GmmJI%3D&to=d6&size=108987771&sta_dx=108987771&sta_cs=1593&sta_ft=rar&sta_ct=7&sta_mt=5&fm2=MH%2CQingdao%2CAnywhere%2C%2Cshandong%2Ccmnet&ctime=1569370507&mtime=1598847919&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=108987771&vuk=750590469&iv=2&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-dc0f56d2bf69f7f51c0c775b2fa63f4390c7c91fd1504414c6530ac43599a3cd6a469ad25f141bed&expires=8h&rt=sh&r=232905013&vbdid=-&fin=%E5%8D%8E%E4%B8%BAMate30+%E7%B3%BB%E5%88%97%E4%B8%BB%E9%A2%98.rar&rtype=1&dp-logid=1094827780997830329&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=iSGCyvX%2BBPMLk2F5i%2FWqd

**Comment by yuantuo666** [comment]
请提供文件分享链接，
另外，这个似乎并不是标准的链接，标准链接结尾应该是theme

**Comment by GreenTeodoro839** [comment]
复制这段内容后打开百度网盘App，操作更方便哦。 链接:https://pan.baidu.com/s/1wxonmEWzcJyGvhzKAn15XA 提取码:0f60

**Comment by yuantuo666** [comment]
我这边测试没问题哦
可能是小概率事件，修复不了
删除记录重新解析就行了
![Screenshot_20210217_125123_com android chrome](https://user-images.githubusercontent.com/44130602/108158052-15499200-711f-11eb-9674-711778113947.jpg)

https://d6.baidupcs.com/file/2ba598badd98926878c643cf4c8cdc09?bkt=en-4d166c07188776153efa73bb4665913e96c5378fb294b5b653bd7e73456958245ad69a9a47aa3309&xcode=95437d727525659f5804caf5fc10f752568d5a4037901d1f3a45e79b6f84b4c4e9e1eeb6b1f68880d656b52424878ab10b2977702d3e6764&fid=3671505180-250528-451087160016465&time=1613537471&sign=FDTAXUGERQlBHSKfaqi-DCb740ccc5511e5e8fedcff06b081203-9Bk3GVBPIL1VcYeVcZHncuT1r58%3D&to=d6&size=108987771&sta_dx=108987771&sta_cs=1594&sta_ft=rar&sta_ct=7&sta_mt=5&fm2=MH%2CQingdao%2CAnywhere%2C%2CNone%2Cany&ctime=1569370507&mtime=1598847919&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=108987771&vuk=2519719524&iv=2&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-dc0f56d2bf69f7f51c0c775b2fa63f4390c7c91fd1504414c6530ac43599a3cd6a469ad25f141bed&expires=8h&rt=sh&r=571709426&vbdid=-&fin=%E5%8D%8E%E4%B8%BAMate30+%E7%B3%BB%E5%88%97%E4%B8%BB%E9%A2%98.rar&rtype=1&dp-logid=1102483373381883377&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=zQiSkkYtr1R6kmnqZ%2F8qCvS3X1w%3D&so=1&ut=1&uter=0&serv=0&uc=3200815480&ti=643d984421895662bc6a79aa582106cbfb5988b449cac8bb&hflag=10&from_type=3&adg=c_4a12f4c0432aa381c95e886fdfa97f95&reqlabel=250528_f_9425616ec3da9dacb316543855206e4e_-1_8f6bbbdc9451d73d51ca59cb5c5c798a&by=themis

**Comment by GreenTeodoro839** [comment]
但是我也没办法删除吧，总不能为了这个重建数据库吧

**Comment by lc6464** [comment]
> 但是我也没办法删除吧，总不能为了这个重建数据库吧


等待新版本更新即可删除。
我们目前正在对即将发布的新版本进行测试。
