### ISSUE TITLE
建议优化深色模式，建议增加背景图

### ISSUE THREAD

**Issue by w1915591935** [yuantuo666/baiduwp-php#73]
下一版本能否加入背景黑夜沉浸

**Comment by yuantuo666** [comment]
因为背景图不是透明的，深色模式下显示的是白色，所以新版本删除了背景图

**Comment by w1915591935** [comment]
好的感谢作者，新增的黑夜模式很好 希望能适配优化下支持背景图沉浸

**Comment by yuantuo666** [comment]
背景图沉浸是指什么呢

**Comment by w1915591935** [comment]
在随意更改背景图的情况下，能够完美的支持黑夜模式。希望适配。少熬夜小心头发/滑稽/滑稽

**Comment by lc6464** [comment]
你的意思是背景透明的图片做背景？
可是图案颜色难搞，或者就深浅色模式使用不同的图片。
其实目前的深色模式令人很不满意，但赶工，You know.

**Comment by lc6464** [comment]
我们暂时不考虑加入背景图，如果未来我们又重新加入背景图，我们将会在此议题通知您。
