### ISSUE TITLE
最新版解析的链接失效很快

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#74]
解析的链接很快就失效，据群友反馈，有效期只有5分钟，热门资源每次都得找我删除记录重新解析。idm报错401，adm提示用浏览器打开。下面是失效的链接（很多，我拿了两个，都是今晚18点左右解析的）。前几天我说存在这种现象，但是今天突然数量暴增
https://d6.baidupcs.com/file/9fb4e5da2600b1a7dbb8b5251481091a?bkt=en-2bd419aa17f4904f4c1b57683a68065861ac0f92de3624e8194e9cdbf303030c67b40cf892edb27a&xcode=dcda70800834e5c64c2a0509d30f04fe7aeeddf0c0d0b8a46b3808e631177b8f71e2aa0b3e10df54a5d4ba4627634ba09717ec4418c70769&fid=3215852543-250528-669172314688951&time=1613730575&sign=FDTAXUGERQlBHSKfaqi-DCb740ccc5511e5e8fedcff06b081203-b89TfjDDlx7m3Tp2BvTiNDsmOvg%3D&to=d6&size=1419008395&sta_dx=1419008395&sta_cs=44883&sta_ft=bin&sta_ct=7&sta_mt=0&fm2=MH%2CQingdao%2CAnywhere%2C%2Cshandong%2Ccmnet&ctime=1415104085&mtime=1613663718&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=1419008395&vuk=1303659421&iv=2&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-b58b691c3c4cc4a8c23546888fe003563c86c3d33eb23dcf7e87943b310cf46d3d6e3661dd81d3c6&expires=8h&rt=sh&r=363296237&vbdid=-&fin=GTA4_setup-6.bin&rtype=1&dp-logid=1154319330030493153&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=iSGCyvX%2BBPMLk2F5i%2FWqdibMYfk%3D&so=1&ut=1&uter=0&serv=0&uc=3200815480&
https://yqcm02.baidupcs.com/file/a00fd067acd4cf000bf39d308b617bad?bkt=en-2e2b5030dd6ff0377964ad79776697e87513a8c3254334e97a41f75f74cbc3017ef35f47882882ac&fid=1938054720-250528-191941991716416&time=1613731828&sign=FDTAXUGERQlBHSKfWaqi-DCb740ccc5511e5e8fedcff06b081203-I9DoZDY9RdLAHWkJbuDYZPVOhvI%3D&to=50&size=110947798&sta_dx=110947798&sta_cs=0&sta_ft=apk&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Cshandong%2Ccmnet&ctime=1566921293&mtime=1566921293&resv0=-1&resv1=0&resv2=rlim&resv3=5&resv4=110947798&vuk=1303659421&iv=2&htype=&randtype=&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=en-92f2f98fde151f1e324ad5c36a0ec86d53d1daff68825609d6ad9e24a33a362bac91160a7c271615&expires=8h&rt=sh&r=624541990&vbdid=-&fin=%E5%85%8D%E8%B4%B9%E9%AB%98%E7%BA%A7cleo-1.6.apk&rtype=1&dp-logid=1154655824592964567&dp-callid=0.1&tsl=0&csl=0&fsl=-1&csign=iSGCyvX%2BBPMLk2F5i%2FWqdibMYfk%3D&so=1&ut=1&uter=0&serv=0&uc=3200815480&ti=4744d9fc935001bfa94b6bd5624cc3b43aa21fcaa5e19460&hflag=30&from_type=0&adg=c_77e99622a

**Comment by yuantuo666** [comment]
因为我和lc都开学了，所以没有时间修复这个问题了，如果嫌删记录麻烦，可以自己修改链接有效期

**Comment by yuantuo666** [comment]
> $sql = "SELECT * FROM `$dbtable` WHERE `md5`='$md5' AND `ptime` > DATE_SUB(NOW(),INTERVAL 8 HOUR);";
将index.php中第331行的8 HOUR改成你想要的时间就可以了
