### ISSUE TITLE
安装报错"数据库导入出错，错误在0行”

### ISSUE THREAD

**Issue by Coinsinic** [yuantuo666/baiduwp-php#76]
最后一步出现报错“安装结果： 数据库导入出错，错误在0行”,使用的是宝塔创建的数据库,php7.4,mysql版本是5.6，应该如何解决？

**Comment by idayske** [comment]
数据库前缀那里输入bdwp

**Comment by Coinsinic** [comment]
已经解决，数据库前缀填写bdwp就可以了
