### ISSUE TITLE
版本说明？

### ISSUE THREAD

**Issue by lc6464** [yuantuo666/baiduwp-php#77]
你 2.1.2 版本的说明呢？
虽然说改动也就一点点，但是好歹也要说明一下你改过吧？
你不但没在 Release 那里写简介，甚至连 README 都还是 2.1.1 的。

**Comment by yuantuo666** [comment]
之前确实没时间弄

**Comment by yuantuo666** [comment]
另外，每个文件都弄一个版本是不是没有必要，每次更新版本都要改一次

**Comment by lc6464** [comment]
> 另外，每个文件都弄一个版本是不是没有必要，每次更新版本都要改一次

这玩意是为了防止用户不同文件版本不一致导致不可预料的意外而设置的。
