### ISSUE TITLE
添加通过二维码扫描获取百度登录凭证的方法

### ISSUE THREAD

**Issue by mnixry** [yuantuo666/baiduwp-php#80]
在使用中, 使用二维码获取登录凭证会更加方便

根据我个人测试, 通过[此处代码](https://github.com/CharlesPikachu/DecryptLogin/blob/master/DecryptLogin/core/baidutieba.py)来通过二维码扫描获取BDUSS等登录凭证是可行的, 且该API至今仍在被百度所使用, 稳定性应该没有问题

另外[此处代码](https://github.com/CharlesPikachu/DecryptLogin/blob/master/DecryptLogin/core/baidupan.py)还支持通过用户名密码登入, 不过实现方式较为复杂, 可作另行考虑

**Comment by musaart** [comment]
这是个好提议

**Comment by lc6464** [comment]
昨晚测试了一下，二维码登录功能经过实验确定可行，但那些程序仍存在一些 bug，我已经通过议题的形式向作者提出。
用户名密码的话，还没研究透。

**Comment by yuantuo666** [comment]
这个功能已经有人通过PHP实现了，会考虑加入的

**Comment by yuantuo666** [comment]
不清楚为什么，通过此方法获取到的BDUSS和STOKEN无法正常使用。
另外，本身就只需要设置一次即可使用本程序，增加此功能没有必要
