### ISSUE TITLE
getSign():no match | 解析根页面时出错 | 账号被百度拉入黑名单

### ISSUE THREAD

**Issue by 212-mei** [yuantuo666/baiduwp-php#83]
百度账号BDUSS和STOKEN确认了好几遍是正确的，链接有效，提取码正确，一直显示 解析根页面时出错！ 可能原因：①提取码错误；②文件失效；③服务器未连接互联网；④服务器未安装curl（或其php插件）；⑤服务器IP被百度封禁。 ！换了好几个链接都是

尝试更换百度账号和服务器ip均无效果，服务器均正确安装php和相应插件

**Comment by whl2606555** [comment]
同样的错误，在服务器上重现操作后发现似乎是functions.php在getSign()函数处正则表达式没有匹配。进一步查看发现是访问https://pan.baidu.com/s/获取数据时被挡在输入提取码。
目前个人推测是这个方法有些变化。

**Comment by tianxuanzhizi** [comment]
+1,好像又有啥bug了

**Comment by 212-mei** [comment]
之前有个大佬说换了好几个账号之后，发现有账号可以用，难道是百度在不限速的前提下增加了解析这个直链的黑名单？

**Comment by yuantuo666** [comment]
我这边测试没有问题
请提供一下链接

**Comment by yuantuo666** [comment]
另外请附上你使用的程序版本

**Comment by 212-mei** [comment]
您说的是分享链接嘛，我换了两个svip账号，三个服务器，不管是什么分享链接，都无法解析，如果需要，可以提供一下联系方式嘛，我加您测试问题，程序是最高版本，我的邮箱是: rtf@live.com

**Comment by yuantuo666** [comment]
是的，请提供一下分享链接

**Comment by 212-mei** [comment]
复制这段内容后打开百度网盘App，操作更方便哦。 链接:https://pan.baidu.com/s/1d5UqTxLgS3QwZAOzw_oXBg 提取码:i9vz

**Comment by yuantuo666** [comment]
正则表达式测试也不存在问题，可能是网络地区问题
我这湖南和香港都测试正常


> <script type="text/javascript" src="/sns/box-static/disk-share/pkg/page-ui_c53c2af.js?t=1614742223176"></script>
> <script type="text/javascript" src="/sns/box-static/disk-share/widget/data/yunData_0ae1fee.js?t=1614742223176"></script>
> <script type="text/javascript">!function(){            locals.setProduct('share');
>                             var yunData = require('disk-share:widget/data/yunData.js');
>                 yunData.setData({"loginstate":0,"username":"","third":0,"flag":2,"file_list":{"errno":0,"list":[{"app_id":"250528","category":1,"delete_fs_id":"0","extent_int3":"1529664763","extent_tinyint1":"0","extent_tinyint2":"0","extent_tinyint3":"0","extent_tinyint4":"0","file_key":"","fs_id":1121613422993896,"isdelete":"0","isdir":0,"local_ctime":1466990587,"local_mtime":1466986049,"md5":"21179b202090cb8131783af18a077dcf","oper_id":"1529664763","parent_path":"%2Fsharelink1529664763-1121613422993896","path":"\/sharelink1529664763-1121613422993896\/06\u57fa\u672c\u6982\u5ff5\u57fa\u672c\u7406\u8bba\u6280\u5de7.mp4","path_md5":"11288340278183334896","privacy":"0","root_ns":673471386,"server_atime":"0","server_ctime":1466990587,"server_filename":"06\u57fa\u672c\u6982\u5ff5\u57fa\u672c\u7406\u8bba\u6280\u5de7.mp4","server_mtime":1598510949,"share":"0","size":55805532,"status":"0","videotag":"0","wpfile":"0","thumbs":{"url1":"https:\/\/thumbnail0.baidupcs.com\/thumbnail\/21179b202090cb8131783af18a077dcf?fid=1529664763-250528-1121613422993896&time=1615474800&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-UmXVUQg4hK57e%2FN6JA1qsLKY9mc%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=469709055032622012&dp-callid=0&file_type=0&size=c140_u90&quality=100&vuk=-&ft=video","url2":"https:\/\/thumbnail0.baidupcs.com\/thumbnail\/21179b202090cb8131783af18a077dcf?fid=1529664763-250528-1121613422993896&time=1615474800&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-UmXVUQg4hK57e%2FN6JA1qsLKY9mc%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=469709055032622012&dp-callid=0&file_type=0&size=c360_u270&quality=100&vuk=-&ft=video","url3":"https:\/\/thumbnail0.baidupcs.com\/thumbnail\/21179b202090cb8131783af18a077dcf?fid=1529664763-250528-1121613422993896&time=1615474800&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-UmXVUQg4hK57e%2FN6JA1qsLKY9mc%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=469709055032622012&dp-callid=0&file_type=0&size=c850_u580&quality=100&vuk=-&ft=video","icon":"https:\/\/thumbnail0.baidupcs.com\/thumbnail\/21179b202090cb8131783af18a077dcf?fid=1529664763-250528-1121613422993896&time=1615474800&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-UmXVUQg4hK57e%2FN6JA1qsLKY9mc%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=469709055032622012&dp-callid=0&file_type=0&size=c60_u60&quality=100&vuk=-&ft=video"}}]},"uk":1529664763,"task_key":null,"task_time":null,"sampling":false,"bdstoken":null,"is_vip":0,"bt_paths":null,"applystatus":null,"sign1":null,"sign2":null,"sign3":null,"timestamp":1615475169,"timeline_status":null,"face_status":null,"srv_ts":null,"need_tips":null,"is_year_vip":0,"show_vip_ad":null,"vip_end_time":null,"is_evip":0,"is_svip":0,"is_auto_svip":0,"photo":"https:\/\/dss0.bdstatic.com\/7Ls0a8Sm1A5BphGlnYG\/sys\/portrait\/item\/netdisk.1.787a7151.nIf8680JlKN-13ESDBKT9g.jpg","linkusername":"w*cr","shareid":1300564616,"sign":"c1fb994a11bf4714d37a64f1c6d3b0adb251879b","public":0,"ctime":1615474032,"description":"","self":false,"visitor_avatar":null,"novelid":false,"visitor_uk":null,"share_page_type":"single","is_master_vip":0,"is_master_svip":0,"errortype":null,"curr_activity_code":0,"activity_end_time":0,"expiredType":603662,"pansuk":"","sharesuk":"S7O-9aIQvYVUbsycABB4kw","unlogin_user_in_small_flow":0,"title_img":null,"followFlag":-1,"add_friend_small_flow":1,"hit_ogc":false,"cfrom_id":"0","LRURPVSDB":null,"openlogo":null,"openyy":null,"owner_vip_level":1,"owner_vip_point":0,"owner_vip_type":0,"guest_vip_level":0,"guest_vip_point":0,"guest_vip_type":0,"hitrisk":0,"appeal_status":0,"sharetype":0,"shorturl":"1qJND50VQEayqkJfwYb12cg","view_visited":0,"view_limit":0,"expired_type":7,"is_zombie":0,"urlparam":[],"XDUSS":"null"});
>                 yunData.setData('SERVERTIME', 1615475170351);
>                 yunData.setData('is_company', Boolean([0][0]));
>                         require("disk-share:widget/system/util/contextExtend.js");
>         }();
> !function(){        var context = require('system-core:context/context.js').instanceForSystem;
>         context.pluginControl.init();
>     }();
> !function(){    require("disk-share:widget/pageModule/share-top-bar/share-top-bar.js");
> }();
> !function(){require("disk-share:widget/pageModule/share-header/share-header.js");
> require("disk-share:widget/pageModule/share-header/service/btns.js");
> }();
> !function(){    require("disk-share:widget/pageModule/share-file-main/fileType/video/video.js");
> }();
> !function(){    require("disk-share:widget/pageModule/share-file-main/share-file-main.js");
> }();
> !function(){        require("disk-share:widget/pageModule/share-file-main/adPanLog.js");
>     }();
> !function(){    require("disk-share:widget/pageModule/share-person-info/share-person-info.js");
> }();
> !function(){require("disk-share:widget/pageModule/share-footer/share-footer.js");
> }();
> !function(){        require("disk-share:widget/pageModule/page-controller/share-single.js");
>         require('disk-share:widget/pageModule/adPlatform/adPlatform.js').getAdResoucre({list: [{'id': 'web-sharelinkpic','w': 200,'h': 200},{'id': 'web-sharesinglebanner','w': 710,'h': 90}]});
>     }();

**Comment by yuantuo666** [comment]
![Screenshot_20210311_231706_com android chrome](https://user-images.githubusercontent.com/44130602/110809640-0d18e880-82c0-11eb-81d5-2c2479e05c00.jpg)
测试解析无问题

**Comment by 212-mei** [comment]
是的，很奇怪，但是确实不止我一个人出了问题，我今天用您的站测试过，是解析成功的，但是我们这边好几个人都出了问题，但是有人换了好几个账号后可以正常使用

**Comment by 212-mei** [comment]
我刚刚换了一个普通的bduss和stoken发现可以了，可能不是svip账号的问题，是普通账号的问题？

**Comment by whl2606555** [comment]
> 正则表达式测试也不存在问题，可能是网络地区问题
> 我这湖南和香港都测试正常
> 
> > <script type="text/javascript" src="/sns/box-static/disk-share/pkg/page-ui_c53c2af.js?t=1614742223176"></script>
> > <script type="text/javascript" src="/sns/box-static/disk-share/widget/data/yunData_0ae1fee.js?t=1614742223176"></script>
> > <script type="text/javascript">!function(){            locals.setProduct('share');
> >                             var yunData = require('disk-share:widget/data/yunData.js');
> >                 yunData.setData({"loginstate":0,"username":"","third":0,"flag":2,"file_list":{"errno":0,"list":[{"app_id":"250528","category":1,"delete_fs_id":"0","extent_int3":"1529664763","extent_tinyint1":"0","extent_tinyint2":"0","extent_tinyint3":"0","extent_tinyint4":"0","file_key":"","fs_id":1121613422993896,"isdelete":"0","isdir":0,"local_ctime":1466990587,"local_mtime":1466986049,"md5":"21179b202090cb8131783af18a077dcf","oper_id":"1529664763","parent_path":"%2Fsharelink1529664763-1121613422993896","path":"\/sharelink1529664763-1121613422993896\/06\u57fa\u672c\u6982\u5ff5\u57fa\u672c\u7406\u8bba\u6280\u5de7.mp4","path_md5":"11288340278183334896","privacy":"0","root_ns":673471386,"server_atime":"0","server_ctime":1466990587,"server_filename":"06\u57fa\u672c\u6982\u5ff5\u57fa\u672c\u7406\u8bba\u6280\u5de7.mp4","server_mtime":1598510949,"share":"0","size":55805532,"status":"0","videotag":"0","wpfile":"0","thumbs":{"url1":"https:\/\/thumbnail0.baidupcs.com\/thumbnail\/21179b202090cb8131783af18a077dcf?fid=1529664763-250528-1121613422993896&time=1615474800&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-UmXVUQg4hK57e%2FN6JA1qsLKY9mc%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=469709055032622012&dp-callid=0&file_type=0&size=c140_u90&quality=100&vuk=-&ft=video","url2":"https:\/\/thumbnail0.baidupcs.com\/thumbnail\/21179b202090cb8131783af18a077dcf?fid=1529664763-250528-1121613422993896&time=1615474800&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-UmXVUQg4hK57e%2FN6JA1qsLKY9mc%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=469709055032622012&dp-callid=0&file_type=0&size=c360_u270&quality=100&vuk=-&ft=video","url3":"https:\/\/thumbnail0.baidupcs.com\/thumbnail\/21179b202090cb8131783af18a077dcf?fid=1529664763-250528-1121613422993896&time=1615474800&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-UmXVUQg4hK57e%2FN6JA1qsLKY9mc%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=469709055032622012&dp-callid=0&file_type=0&size=c850_u580&quality=100&vuk=-&ft=video","icon":"https:\/\/thumbnail0.baidupcs.com\/thumbnail\/21179b202090cb8131783af18a077dcf?fid=1529664763-250528-1121613422993896&time=1615474800&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-UmXVUQg4hK57e%2FN6JA1qsLKY9mc%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=469709055032622012&dp-callid=0&file_type=0&size=c60_u60&quality=100&vuk=-&ft=video"}}]},"uk":1529664763,"task_key":null,"task_time":null,"sampling":false,"bdstoken":null,"is_vip":0,"bt_paths":null,"applystatus":null,"sign1":null,"sign2":null,"sign3":null,"timestamp":1615475169,"timeline_status":null,"face_status":null,"srv_ts":null,"need_tips":null,"is_year_vip":0,"show_vip_ad":null,"vip_end_time":null,"is_evip":0,"is_svip":0,"is_auto_svip":0,"photo":"https:\/\/dss0.bdstatic.com\/7Ls0a8Sm1A5BphGlnYG\/sys\/portrait\/item\/netdisk.1.787a7151.nIf8680JlKN-13ESDBKT9g.jpg","linkusername":"w*cr","shareid":1300564616,"sign":"c1fb994a11bf4714d37a64f1c6d3b0adb251879b","public":0,"ctime":1615474032,"description":"","self":false,"visitor_avatar":null,"novelid":false,"visitor_uk":null,"share_page_type":"single","is_master_vip":0,"is_master_svip":0,"errortype":null,"curr_activity_code":0,"activity_end_time":0,"expiredType":603662,"pansuk":"","sharesuk":"S7O-9aIQvYVUbsycABB4kw","unlogin_user_in_small_flow":0,"title_img":null,"followFlag":-1,"add_friend_small_flow":1,"hit_ogc":false,"cfrom_id":"0","LRURPVSDB":null,"openlogo":null,"openyy":null,"owner_vip_level":1,"owner_vip_point":0,"owner_vip_type":0,"guest_vip_level":0,"guest_vip_point":0,"guest_vip_type":0,"hitrisk":0,"appeal_status":0,"sharetype":0,"shorturl":"1qJND50VQEayqkJfwYb12cg","view_visited":0,"view_limit":0,"expired_type":7,"is_zombie":0,"urlparam":[],"XDUSS":"null"});
> >                 yunData.setData('SERVERTIME', 1615475170351);
> >                 yunData.setData('is_company', Boolean([0][0]));
> >                         require("disk-share:widget/system/util/contextExtend.js");
> >         }();
> > !function(){        var context = require('system-core:context/context.js').instanceForSystem;
> >         context.pluginControl.init();
> >     }();
> > !function(){    require("disk-share:widget/pageModule/share-top-bar/share-top-bar.js");
> > }();
> > !function(){require("disk-share:widget/pageModule/share-header/share-header.js");
> > require("disk-share:widget/pageModule/share-header/service/btns.js");
> > }();
> > !function(){    require("disk-share:widget/pageModule/share-file-main/fileType/video/video.js");
> > }();
> > !function(){    require("disk-share:widget/pageModule/share-file-main/share-file-main.js");
> > }();
> > !function(){        require("disk-share:widget/pageModule/share-file-main/adPanLog.js");
> >     }();
> > !function(){    require("disk-share:widget/pageModule/share-person-info/share-person-info.js");
> > }();
> > !function(){require("disk-share:widget/pageModule/share-footer/share-footer.js");
> > }();
> > !function(){        require("disk-share:widget/pageModule/page-controller/share-single.js");
> >         require('disk-share:widget/pageModule/adPlatform/adPlatform.js').getAdResoucre({list: [{'id': 'web-sharelinkpic','w': 200,'h': 200},{'id': 'web-sharesinglebanner','w': 710,'h': 90}]});
> >     }();

我这边多试了几次，有几次显示链接不存在了。看debug信息和functions.php的话，错误点就是getSign那里没找到匹配，提示no match。

**Comment by idayske** [comment]
同样的问题  等一个解决方法

**Comment by LetMeDecay** [comment]
+1 打开调试之后`getSign()`这里出错的

**Comment by Aixzk** [comment]
出错+1

**Comment by yuantuo666** [comment]
麻烦大家提供一下网页代码以及相关链接，我这边没有出现这个情况

**Comment by yuantuo666** [comment]
之前 whl26***55@gmail.com 发送了网页代码给我，检查后发现JavaScript部分确实不一样，但没有提供相关链接，我这边不好测试

**Comment by Aixzk** [comment]
> 之前 whl26***[55@gmail.com](mailto:55@gmail.com) 发送了网页代码给我，检查后发现JavaScript部分确实不一样，但没有提供相关链接，我这边不好测试

邮箱被屏蔽了，能提供其他联系方式吗

**Comment by yuantuo666** [comment]
已经弄清是怎么回事了

由于账号被百度拉黑，导致获取的文件页面与正常账号不同，检测发现拉黑状态下的页面缺少必要的解析信息，必须使用正常账号才可以获取。
![image](https://user-images.githubusercontent.com/44130602/111037146-d7116b00-845d-11eb-8bd9-c9cdbed18970.png)
缺少相关信息

![image](https://user-images.githubusercontent.com/44130602/111037418-d75e3600-845e-11eb-82a9-4ab57e5882bd.png)
拉黑状态界面及部分代码

>                             <div class="slide-show-left">
>                                 <h2 class="file-name" title="文件名">
>                                     <em class="global-icon-16"></em>
>                                     文件名
>             
>                                 </h2>
>                             </div>
不直接显示文件名，而使用图片格式

> <script type="text/javascript">
>             !function() {
>                 window.yunData = {
>                     skinName: 'dusk',
>                     neglect: 1
>                 };
>                 locals.set('servertime', 1615653185309);
>                 locals.mset({
neglect参数为1，被拉入黑名单

**Comment by yuantuo666** [comment]
解决方案：换成正常账号（普通账号或VIP账号都可以）即可

参见 https://github.com/yuantuo666/baiduwp-php/issues/86#issuecomment-798629103
