### ISSUE TITLE
服务器错误(118) | 解析文件夹和文件出错 | 已经修复由randsk(BDCLND)引起的错误，不清楚是否有其他错误

### ISSUE THREAD

**Issue by dalaoio** [yuantuo666/baiduwp-php#84]
服务器错误(118)
服务器错误，请求百度服务器时，未传入sekey参数或参数错误。
请打开调试模式，并将错误信息复制提交issue到github项目。

第一 BD号我换了好几个 解析失败
但是如果文件是单个的或者不超过1个文件夹的都可以正常获取到

第二 不清楚是不是BD偷摸升级修改了,老号的BDUSS放进去没用,换新注册的号就可以正常获取文件夹/文件

第三 用新注册的号获取到文件/文件夹后 解析下载链接出现错误....请求百度服务器时，未传入sekey参数或参数错误。
换服务器IP也没用,换SVIP号也没用.

$_GET:array(1) {
  ["download"]=>
  string(0) ""
}
$_POST:array(8) {
  ["fs_id"]=>
  string(15) "450506247103269"
  ["time"]=>
  string(10) "1615544880"
  ["sign"]=>
  string(40) "23ddefb24a54bcaf78957520bc012d208e225d5b"
  ["randsk"]=>
  string(0) ""
  ["share_id"]=>
  string(9) "586914725"
  ["uk"]=>
  string(10) "1767948507"
  ["bdstoken"]=>
  string(32) "a6b1ba2bc45b8106c867b2affa978497"
  ["filesize"]=>
  string(10) "3032612864"
}
getDlink():array(3) {
  ["errno"]=>
  int(118)
  ["request_id"]=>
  int(488507983637515462)
  ["server_time"]=>
  int(1615545201)
}

**Comment by yuantuo666** [comment]
看到randsk参数为空，可能是获取失败，可以尝试1.4.3版本，获取方法不一样，看能否解决

**Comment by yuantuo666** [comment]
已经成功复现此问题，发现确实是解析方法更新后造成的
![image](https://user-images.githubusercontent.com/44130602/111035448-97468580-8455-11eb-9c57-e8f864137bc3.png)
1.4.5版本返回信息
![image](https://user-images.githubusercontent.com/44130602/111035466-b513ea80-8455-11eb-9626-729fc3d04931.png)
2.1.4版本返回信息

![image](https://user-images.githubusercontent.com/44130602/111035503-d70d6d00-8455-11eb-97b3-7bbdfab99068.png)
但老版本下获取整个页面确实太耗费资源，目前的解决方法就是重新分享这个文件进行解析
或者考虑获取失败后尝试使用老方法获取

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/111035648-5ac75980-8456-11eb-830d-a611b235e3e7.png)
重新分享后就可以正常解析

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/111035776-e9d47180-8456-11eb-89ea-7b03e3a846ef.png)
将在下一版本修复此问题

**Comment by yuantuo666** [comment]
暂时不要关闭这个议题，麻烦 @dalaoio 使用1.4.5或以前版本再次获取同样的文件

目前推测是文件的问题而不是账号问题，如果是账号问题，则需要进一步研究
这种情况下请发送你**普通账号/VIP账号**（就是设置在config.php中的）的**bduss**和**stoken**到我的邮箱 yuantuo666@gmail.com 并附上你的 **GitHub昵称** 和 **提议号** #84

**Comment by dalaoio** [comment]
> 暂时不要关闭这个议题，麻烦 @dalaoio 使用1.4.5或以前版本再次获取同样的文件
> 
> 目前推测是文件的问题而不是账号问题，如果是账号问题，则需要进一步研究
> 这种情况下请发送你**普通账号/VIP账号**（就是设置在config.php中的）的**bduss**和**stoken**到我的邮箱 [yuantuo666@gmail.com](mailto:yuantuo666@gmail.com) 并附上你的 **GitHub昵称** 和 **提议号** #84

刚看到。
我去测试了下，首先用新注册的号，可以获取套了多层文件夹，但是无法解析文件。
![1](https://user-images.githubusercontent.com/80518047/111051183-22db0900-848c-11eb-99ff-f4a5d8ea314e.png)
用新账号去解析的话，可以获取到直链。前提是你说的那种转存到自己盘重新分享下，这样可以，如果是老的分享链接，是无法解析到直链。一样提示未传入sekey参数。
![2](https://user-images.githubusercontent.com/80518047/111051196-35edd900-848c-11eb-8063-206e4cf4ce67.png)
![3](https://user-images.githubusercontent.com/80518047/111051241-9aa93380-848c-11eb-990a-9f316d8d2e4a.png)

第二，我用老帐号也测试了，直接无法解析到文件夹，即便我转存到自己盘重新分享链接去解析也是一样获取不到文件夹和文件等。
![5](https://user-images.githubusercontent.com/80518047/111051219-6897d180-848c-11eb-9498-b59e5eb08588.png)

`$_GET:array(0) {
}
$_POST:array(2) {
  ["surl"]=>
  string(23) "1V1B5yFNifv_V29QZwZ6aTw"
  ["pwd"]=>
  string(0) ""
}
GetList():array(10) {
  ["errno"]=>
  int(0)
  ["request_id"]=>
  int(522973498297661524)
  ["errtype"]=>
  int(0)
  ["server_time"]=>
  int(1615673595)
  ["data"]=>
  array(20) {
    ["title"]=>
    string(40) "/System/Windows 10 不忘初心精简版"
    ["expiredType"]=>
    int(0)
    ["link_ctime"]=>
    int(1604039482)
    ["fileNums"]=>
    int(1)
    ["has_more"]=>
    bool(false)
    ["list"]=>
    array(1) {
      [0]=>
      array(11) {
        ["category"]=>
        string(1) "6"
        ["fs_id"]=>
        string(15) "112906122894369"
        ["isdir"]=>
        string(1) "1"
        ["local_ctime"]=>
        string(10) "1604039463"
        ["local_mtime"]=>
        string(10) "1604039463"
        ["md5"]=>
        string(0) ""
        ["path"]=>
        string(40) "/System/Windows 10 不忘初心精简版"
        ["server_ctime"]=>
        string(10) "1604039463"
        ["server_filename"]=>
        string(32) "Windows 10 不忘初心精简版"
        ["server_mtime"]=>
        string(10) "1604039523"
        ["size"]=>
        string(1) "0"
      }
    }
    ["user"]=>
    array(1) {
      ["avatar"]=>
      string(109) "https://dss0.bdstatic.com/7Ls0a8Sm1A5BphGlnYG/sys/portrait/item/netdisk.1.46c9ccdc.Ea6Tj7hqmp2rqfcxyZisnQ.jpg"
    }
    ["uname"]=>
    string(10) "ZDF****015"
    ["uk"]=>
    int(1767948507)
    ["shareid"]=>
    int(586914725)
    ["wx_name"]=>
    string(5) "Zerte"
    ["wx_headurl"]=>
    string(127) "https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83eogfHoZbvqETguzHcqJ5Crl7yNaMBCeSibiaMFdYDPvKUDE3FOrB36ZatOS3RTWqGicMvt3O0kbo9ibCg/132"
    ["hitrisk"]=>
    int(0)
    ["appeal_status"]=>
    int(0)
    ["sharetype"]=>
    int(0)
    ["view_visited"]=>
    int(0)
    ["view_limit"]=>
    int(0)
    ["expired_type"]=>
    int(0)
    ["seckey"]=>
    string(32) "QUOHD9u9lHEySHf0cXyKDuaL7krvJSsA"
    ["hit_ogc"]=>
    bool(false)
  }
  ["cfrom_id"]=>
  int(0)
  ["is_zombie"]=>
  int(0)
  ["vip_level"]=>
  int(5)
  ["vip_point"]=>
  int(26985)
  ["vip_type"]=>
  int(2)
}
get_BDCLND():array(1) {
  [0]=>
  string(24) "User-Agent: LogStatistic"
}
getSign():no match
`
在前几天我登老账号时候发现有公告提示，我没注意看，大概好像是交由什么其他公司之类，怀疑是不是新账号多了参数之类。

**Comment by dalaoio** [comment]
目前这种情况在老版本上没有，也就是1.4.5，但是也只能用新注册的号，老号一样无法解析。

**Comment by lc6464** [comment]
我想，是否可以做一个自动更换解析方式的功能，如果用户被百度列入黑名单，自动更换为旧版解析方式，并提醒用户。

**Comment by yuantuo666** [comment]
根据测试情况， @dalaoio 的老账号应该是被拉入了百度的黑名单，不管是新版本还是老版本都无法解析。

而测试的文件可能由于没有密码或者是老文件，通过新版本微信方法是获取不到randsk（BDCLND），使用老版本可以。

在下一版本更新中将加入老版本方法，如果微信方法无法正常获取，将使用老版本方法获取。

**Comment by yuantuo666** [comment]
> 我想，是否可以做一个自动更换解析方式的功能，如果用户被百度列入黑名单，自动更换为旧版解析方式，并提醒用户。

这两个是两个问题
一个问题是账号被拉入黑名单，这个和版本没有关系，无解。只能换正常账号。
另一个问题是更新解析方法后，部分老文件使用新方法无法获取randsk（BDCLND），使用老版本可以。所以在下一版本获取randsk（BDCLND）过程中使用新方法失败后，将尝试老方法获取。

**Comment by lc6464** [comment]
那就账号被列入黑名单以后提醒用户账号被列入黑名单，部分老文件新方法获取不了的可以使用旧方法解析，并提示用户重新分享文件可以获得更好的体验。
