### ISSUE TITLE
提取码错误或文件失效！

### ISSUE THREAD

**Issue by zhucaidan** [yuantuo666/baiduwp-php#85]
使用的是v1.4.3版本，大概从前天开始就失效了

去百度那里重新复制了STOKEN和BDUSS也还是不行

账号本身是VIP的，但是下载任何链接都还是提示“提取码错误或文件失效！”

包括自己账号分享出去的也是，

举个栗子：https://pan.baidu.com/s/1ow-kHQKOh0Q-WOiDUWX-lQ  提取码：9mpb

**Comment by lc6464** [comment]
DUBUS 是什么？

**Comment by zhucaidan** [comment]
> DUBUS 是什么？

BDUSS打错。。

**Comment by lc6464** [comment]
如果你有别的账号的话你可以更换 BDUSS 和 STOKEN 试试，不需要 VIP，普通用户的就可以（当然 VIP 也没问题）。

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/111035876-610a0580-8457-11eb-94a0-ce6d943f97db.png)
测试获取不存在问题，可能是账号原因，请发送你**普通账号/VIP账号**_（就是设置在config.php中的）_的**bduss**和**stoken**到我的邮箱 yuantuo666@gmail.com 并附上你的 **GitHub昵称** 和 **提议号** #85

**Comment by zhucaidan** [comment]
换了个全新账号，config里三个参数都改新账号了，还是一样“根目录yunData获取失败”，可能是服务器IP被拉黑了？

**Comment by zhucaidan** [comment]
换了台服务器和账户。。还是不行，奇怪啊。。难道海外都不行了吗？

**Comment by yuantuo666** [comment]
有可能是文件失效

你可以使用网页版百度网盘访问分享链接，如果文件名是图片格式，说明这个账号被拉黑了。

**Comment by yuantuo666** [comment]
有可能是文件失效

你可以使用网页版百度网盘访问分享链接，如果文件名是图片格式，说明这个账号被拉黑了。

**Comment by zhucaidan** [comment]
> 有可能是文件失效
> 
> 你可以使用网页版百度网盘访问分享链接，如果文件名是图片格式，说明这个账号被拉黑了。

直接打开的话还可以播放（资源是视频），用百度网盘客户端可以正常下载，我一共换了三台服务器都是美国的IP，

同时换了三个账号（一个普通，两个VIP）均不行，可能是百度限制海外IP也不好说，

但是我没有备案域名没法自己测，所以用黑名单的服务器（国内的服务器）但是同样的资源可以解析：

https://pan.baidu.com/s/1gq9bR6JHb8MBI2s5GO_kKg  提取码：ee9r

https://pan.baidu.com/s/1ow-kHQKOh0Q-WOiDUWX-lQ  提取码：9mpb

**Comment by idayske** [comment]
并不是服务器IP的问题  用了一台香港和广州的服务器分别测试  结果是一样的

**Comment by Aixzk** [comment]
> 有可能是文件失效
> 
> 你可以使用网页版百度网盘访问分享链接，如果文件名是图片格式，说明这个账号被拉黑了。

我傻了，折腾半天，VIP账号也没问题啊，用电脑端和APP下载都能高速下载，文件名也不是图片格式，最后发现原来是普通账号被拉黑了……

**Comment by yuantuo666** [comment]
Demo可以获取成功说明是你的设置有问题。
Demo获取失败说明文件有问题。

设置问题仔细查看说明，实在不行将配置文件发我邮箱。我的邮箱 yuantuo666@gmail.com 并附上你的 GitHub昵称 和 议题号 #85 。
文件问题请保存到网盘后重新分享解析。

**Comment by yuantuo666** [comment]
Demo地址 https://imwcr.cn/api/bdwp/

两个文件测试：
![Screenshot_20210315_223743_com android chrome](https://user-images.githubusercontent.com/44130602/111171486-efa98e80-85df-11eb-9cb6-ed458d005e4c.jpg)
![Screenshot_20210315_223741_com android chrome](https://user-images.githubusercontent.com/44130602/111171501-f2a47f00-85df-11eb-81a5-6fd61446349c.jpg)

**Comment by yuantuo666** [comment]
除非你解析几千次几万次，服务器IP一般很少封的

**Comment by zhucaidan** [comment]
> Demo可以获取成功说明是你的设置有问题。
> Demo获取失败说明文件有问题。
> 
> 设置问题仔细查看说明，实在不行将配置文件发我邮箱。我的邮箱 [yuantuo666@gmail.com](mailto:yuantuo666@gmail.com) 并附上你的 GitHub昵称 和 议题号 #85 。
> 文件问题请保存到网盘后重新分享解析。

已发送，请查看

**Comment by idayske** [comment]
今天测试了一下多个账号，如果你的账号在多台设备登录，会有多个cookie ，只有常用的设备cookie才有用
即使是对的BDUSS  STOKEN ，也会导致解析失败  
可以试下改密码强制登出所有设备 ，在获取BDUSS  STOKEN

**Comment by zhucaidan** [comment]
> 今天测试了一下多个账号，如果你的账号在多台设备登录，会有多个cookie ，只有常用的设备cookie才有用
> 即使是对的BDUSS STOKEN ，也会导致解析失败
> 可以试下改密码强制登出所有设备 ，在获取BDUSS STOKEN

好的，我去试试看

**Comment by yuantuo666** [comment]
参见 https://github.com/yuantuo666/baiduwp-php/issues/93
