### ISSUE TITLE
getSign():no match | 解析根页面时出错 | 账号被百度拉入黑名单

### ISSUE THREAD

**Issue by iceboound** [yuantuo666/baiduwp-php#86]
解析根页面时出错！ 可能原因：①提取码错误；②文件失效；③服务器未连接互联网；④服务器未安装curl（或其php插件）；⑤服务器IP被百度封禁。

出现上面的提示，我都排查了
1.提取码没错误
2.文件没失效
3跟5，我ping了pan.baidu.com是没问题的
4.服务器装的宝塔自带的curl

我该咋解决....

**Comment by yuantuo666** [comment]
请发送文件链接

**Comment by yuantuo666** [comment]
宝塔自带安装的LNMP是没有问题的，可能是账号问题或文件问题
如果是最近分享的文件，可能是账号问题

如果是账号问题，请发送你**普通账号/VIP账号**（就是设置在config.php中的）的**bduss**和**stoken**到我的邮箱 yuantuo666@gmail.com 并附上你的 **GitHub昵称** 和 **提议号** #86
也可以直接发送config.php文件

**Comment by yuantuo666** [comment]
![image](https://user-images.githubusercontent.com/44130602/111036971-f4920500-845c-11eb-8c4b-487e2752ab26.png)
发现此页面确实与其他账号获取不同
返回的文件名也是图片格式，估计是被百度加入了黑名单

**Comment by yuantuo666** [comment]
将普通账号换为正常账号即可解决

**Comment by iceboound** [comment]
> 将普通账号换为正常账号即可解决

OK了，换了3个普通账户都不行，然后直接换成会员的账号就行了....
