### ISSUE TITLE
为什么BDUSS,STOKEN为空都可以读取链接

### ISSUE THREAD

**Issue by idayske** [yuantuo666/baiduwp-php#89]
const Sitename = '1';

const BDUSS = '';
const STOKEN = '';
const SVIP_BDUSS = '';

const IsCheckPassword = false;
const Password = '';
const Footer = `<<<'FoOtEr_Made_By_YuanTuo'`

FoOtEr_Made_By_YuanTuo;
const APP_ID = '250528';
const DEBUG = false;

const USING_DB = false;
const DbConfig = array("servername" => "", "username" => "", "DBPassword" => "", "dbname" => "", "dbtable" => "");

const ADMIN_PASSWORD = '123';
const DownloadTimes = 5;
const IsConfirmDownload = false;
const SVIPSwitchMod = 0;

**Comment by idayske** [comment]
但是BDUSS超过一定长度却解析失败

**Comment by yuantuo666** [comment]
只查看列表
你能下载？
