### ISSUE TITLE
yunDATA错误

### ISSUE THREAD

**Issue by GreenTeodoro839** [yuantuo666/baiduwp-php#92]
普通账号换了2个，一个没vip，一个svip，都不行。重新部署，换ip也没用。今天下午突然出现的。我会把bduss,stoken发到readme里的邮箱，希望你能给我一份bduss和stoken测试

**Comment by lc6464** [comment]
请参见 #93 。
我们暂时没有精力解决这个问题，我和原作者都是高中生，近期学业繁忙，没有太多的精力，目前此项目处于不可使用状态，请耐心等待我们的更新，这也许需要很久时间，感谢您的支持和等待，希望下一个版本能给您带来方便。
