### ISSUE TITLE
baiduwp-php项目失效 | 已修复 | 等待合并发行新版本

### ISSUE THREAD

**Issue by yuantuo666** [yuantuo666/baiduwp-php#93]
目前百度网盘网页版已经全面更新网页版代码，将yundata移除，此项目暂时失效。
临近月考，作者没有时间去研究开发了，目前无解。

最后一次解析成功记录是2021-03-18 19:40左右，此后基本上都会失败。

**Comment by changyexing** [comment]
多谢。好人一生平安👏

**Comment by GreenTeodoro839** [comment]
感谢有这个项目，希望以后能够有解决办法。对了，yunDATA好像是获取文件列表用的，能不能跳过这一步，手动获取某些数据直接用svip账号解析？

**Comment by yuantuo666** [comment]
目前那些淘宝盗卖pd修复版的也挂了，不清楚百度会不会恢复以前网页代码。
所有获取文件地址需要的信息都写在代码里了，可以翻看最早的代码，那里面的信息最简洁，也是最重要的。

**Comment by GreenTeodoro839** [comment]
![-1b561d47ead7aedf](https://user-images.githubusercontent.com/77104800/111703907-4a114c00-8879-11eb-80ed-20866c1b241d.jpg)
可否尝试这个？

**Comment by zhucaidan** [comment]
么事，考试重要，这段时间先凑合忍一下百度云客户端，等考完回来再战！

**Comment by GreenTeodoro839** [comment]
没事，考试要紧。目前kd作者的修改版还能用，有bug先忍忍吧 #
![Uploading Screenshot_20210320_222628_com.tencent.mobileqq.jpg…]()

**Comment by yuantuo666** [comment]
正在尝试使用新方法获取，但此方法但缺少会员账号来测试，如果此方法稳定将更新版本。
https://imwcr.cn/api/bdwp/

**Comment by yuantuo666** [comment]
正在尝试修复，可clone dev分支 提前体验 5475652a3333d3ce667eeabf8980f309b9143f07

**Comment by GreenTeodoro839** [comment]
作者你好，我捐赠个svip，已经发到你的邮箱了

**Comment by GreenTeodoro839** [comment]
最新的dev版不能用，安装完打开还是安装界面

**Comment by newdive** [comment]
网页版更新时间是在 20210303 下午左右吧  
目前的属性都放在 `locals`  里边了,  而且应该是重写了locals的相关方法 
获取 `sign`   `timestamp` 等参数是通过 `tplconfig` 这个接口异步获取的，
具体逻辑作者可以在js源码里搜这个接口就知道了
[也可以参考这里 ](https://github.com/syhyz1990/baiduyun/issues/36#issuecomment-798840329)

**Comment by yuantuo666** [comment]
@newdive 感谢你提供的思路
其实这个方法我知道，并且在demo中已经实现
但鉴于js版作者删除了存储库，考虑可能有所原因，所以暂时没有将代码开源
附 js版作者存储库 https://github.com/TkzcM/baiduwp

**Comment by chesley-lhz** [comment]
![IMG_20210328_122513_923](https://user-images.githubusercontent.com/81501294/112742396-d2ea5f00-8fc0-11eb-960d-27a2e6aadf9e.jpg)

此版本修复教程:https://github.com/yuantuo666/baiduwp-php/releases/tag/v2.1.3
将如下代码替换到本图的PHP文件中

function getSign(string $surl, $randsk)
{
  if ($randsk === 1) return 1;
  $result = get('https://api.kinh.cc/BaiDu/Check/GetSign.php?ShareUrl='.$surl, array ('User-Agent: Mozilla/5.0 (BaiDuWP-PHP)','Cookie: BDUSS='.BDUSS.';STOKEN='.STOKEN.';BDCLND='.$randsk));
  return json_decode($result,true);
}
function FileList($sign)
{
  return $sign;
}

来源于KinhDown作者修改

**Comment by yuantuo666** [comment]
@chesley-lhz 不建议这种方法修改，因为这样你的bduss和stoken可能会泄露

**Comment by newdive** [comment]
> @newdive 感谢你提供的思路
> 其实这个方法我知道，并且在demo中已经实现
> 但鉴于js版作者删除了存储库，考虑可能有所原因，所以暂时没有将代码开源
> 附 js版作者存储库 https://github.com/TkzcM/baiduwp

@yuantuo666  js版我还没看过 ，不过我这里说的 js 是指百度网盘网页版本身的代码
当然如果考虑到新接口并未稳定，后续可能会有所变动，也是可以理解的

**Comment by newdive** [comment]
> @newdive 感谢你提供的思路
> 其实这个方法我知道，并且在demo中已经实现
> 但鉴于js版作者删除了存储库，考虑可能有所原因，所以暂时没有将代码开源
> 附 js版作者存储库 https://github.com/TkzcM/baiduwp

@yuantuo666  你提到的js版我还没看过 ，不过我这里说的 js 是指百度网盘网页版本身的代码
当然如果考虑到新接口并未稳定，后续可能会有所变动，也是可以理解的

**Comment by UallenQbit** [comment]
![image](https://user-images.githubusercontent.com/72503738/112749552-9127db80-8ff5-11eb-945f-df4c978bbee8.png)
![image](https://user-images.githubusercontent.com/72503738/112749578-c6342e00-8ff5-11eb-97de-c4edc717e17d.png)
![image](https://user-images.githubusercontent.com/72503738/112749581-c92f1e80-8ff5-11eb-9786-2ef09db97100.png)

信息链接:https://t.me/KinhDownLoad/3494
将如下代码替换到本图的PHP文件中

function getSign(string $surl, $randsk)
{
  if ($randsk === 1) return 1;
  $result = get('https://api.kinh.cc/BaiDu/Check/GetSign.php?ShareUrl='.$surl, array ('User-Agent: Mozilla/5.0 (BaiDuWP-PHP)','Cookie: BDUSS='.BDUSS.';STOKEN='.STOKEN.';BDCLND='.$randsk));
  return json_decode($result,true);
}
function FileList($sign)
{
  return $sign;
}

**Comment by UallenQbit** [comment]
> @ chesley-lhz不建议这种方法修改，因为这样你的bduss和stoken可能会纳入

谁让你在上面写，必须提交呢?

**Comment by yuantuo666** [comment]
前两天月考结束了，现在已经修复了此问题
请尝试更新2.1.4版本
https://github.com/yuantuo666/baiduwp-php/releases/tag/v2.1.4

**Comment by lc6464** [comment]
> 最新的dev版不能用，安装完打开还是安装界面

目前测试结果表明此问题已解决。
还有就是如果你直接访问 `install.php` 那无论如何都是安装界面。
