### ISSUE TITLE
可以正常解析，但是无法显示下载连接，页面空白

### ISSUE THREAD

**Issue by shzxm** [yuantuo666/baiduwp-php#96]
可以正常解析，但是无法显示下载连接
在没有更新修复之前，2.1.3就有同样的问题，但是鉴于1.4.3还可以正常解析，所以退回了1.4.3版本。
现在更新了2.1.4之后，之前2.1.3的问题重现。
2.1.4正常解析界面
![截屏2021-03-29 12 09 09](https://user-images.githubusercontent.com/9905297/112785862-92a1e400-9087-11eb-85bd-62831360d979.png)
随意选择解析文件后，页面变为空白
![截屏2021-03-29 12 09 43](https://user-images.githubusercontent.com/9905297/112785902-a6e5e100-9087-11eb-9524-3c97601ab1c4.png)
php版本7.4.16
![截屏2021-03-29 12 10 46](https://user-images.githubusercontent.com/9905297/112785963-cc72ea80-9087-11eb-9d6a-03e9df5aa078.png)
nginx配置文件
![截屏2021-03-29 12 12 01](https://user-images.githubusercontent.com/9905297/112786050-fb895c00-9087-11eb-9754-c0f39bdde625.png)
baiduwp-php文件权限已给777
![截屏2021-03-29 12 15 31](https://user-images.githubusercontent.com/9905297/112786297-80747580-9088-11eb-98fa-a614703f7663.png)

**Comment by yuantuo666** [comment]
请修改config.php中的DEBUG为true
然后再截图反馈，目前无法判断是什么原因引起的。

**Comment by yuantuo666** [comment]
最好将config.php配置文件也截图反馈，部分关键信息可打码

目前猜测原因：
1.没有开启数据库功能，程序在无数据库情况下运行逻辑存在问题。
2.操作时间过长，超过了最大运行时间。

**Comment by shzxm** [comment]
$_GET:array(1) {
  ["download"]=>
  string(0) ""
}
$_POST:array(8) {
  ["fs_id"]=>
  string(16) "1017645093084842"
  ["time"]=>
  string(10) "1616998033"
  ["sign"]=>
  string(40) "d5f97c1600c196cae01bc41019abd68b7de54af8"
  ["randsk"]=>
  string(50) "e5lVYCv0FEaDWWyOGvicdjhk8%2BSNcVL7SMEcVY%2BL8ZQ%3D"
  ["share_id"]=>
  string(10) "2944308652"
  ["uk"]=>
  string(10) "2969836815"
  ["bdstoken"]=>
  string(32) "2ba9752b22af0b7a12b7b54371ec7270"
  ["filesize"]=>
  string(6) "182009"
}
getDlink():array(4) {
  ["errno"]=>
  int(0)
  ["request_id"]=>
  int(8948953126064665915)
  ["server_time"]=>
  int(1616998044)
  ["list"]=>
  array(1) {
    [0]=>
    array(30) {
      ["category"]=>
      int(6)
      ["delete_fs_id"]=>
      string(1) "0"
      ["extent_int3"]=>
      string(1) "0"
      ["extent_tinyint1"]=>
      string(1) "0"
      ["extent_tinyint2"]=>
      string(1) "0"
      ["extent_tinyint3"]=>
      string(1) "0"
      ["extent_tinyint4"]=>
      string(1) "0"
      ["file_key"]=>
      string(0) ""
      ["fs_id"]=>
      int(1017645093084842)
      ["headurl"]=>
      string(0) ""
      ["isdir"]=>
      int(0)
      ["local_ctime"]=>
      int(1541727547)
      ["local_mtime"]=>
      int(1541727547)
      ["md5"]=>
      string(32) "57fb6774b63063f52bc38509db83407f"
      ["oper_id"]=>
      string(1) "0"
      ["path"]=>
      string(108) "/[0003]塞aa尔cc达ss荒dd野bb之ww息 公众号：switch游戏联盟/[SAVE] 塞尔达传说100%存档.zip"
      ["path_md5"]=>
      string(19) "7825452522348228131"
      ["privacy"]=>
      string(1) "0"
      ["server_atime"]=>
      string(1) "0"
      ["server_ctime"]=>
      int(1541727573)
      ["server_filename"]=>
      string(36) "[SAVE] 塞尔达传说100%存档.zip"
      ["server_mtime"]=>
      int(1601003038)
      ["share"]=>
      string(1) "0"
      ["size"]=>
      int(182009)
      ["videotag"]=>
      string(1) "0"
      ["wpfile"]=>
      string(1) "0"
      ["dlink"]=>
      string(336) "https://d.pcs.baidu.com/file/57fb6774b63063f52bc38509db83407f?fid=2969836815-250528-1017645093084842&dstime=1616998044&rt=sh&sign=FDtAERVJoK-DCb740ccc5511e5e8fedcff06b081203-78o5JMT8pBRnxAT92TTFNzMUWz0%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=8948953126064665915&dp-callid=0&shareid=2944308652&r=117116841&vuk=2969836815&file_type=0"
      ["resource_type"]=>
      int(0)
      ["isenum"]=>
      int(0)
      ["context"]=>
      string(198) "uk=2969836815&primaryid=2944308652&fid_list=[1017645093084842]&product=share&extra=%7B%22sekey%22%3A%22e5lVYCv0FEaDWWyOGvicdjhk8%2BSNcVL7SMEcVY%2BL8ZQ%3D%22%7D&token=c3d14f4d9106b1e8c4eb54d7efe070ee"
    }
  }
}

**Comment by shzxm** [comment]
链接: https://pan.baidu.com/s/1NPUaUe27MEMXXmIgSLtWNw  密码: 3cac

**Comment by shzxm** [comment]
> 最好将config.php配置文件也截图反馈，部分关键信息可打码
> 
> 目前猜测原因：
> 1.没有开启数据库功能，程序在无数据库情况下运行逻辑存在问题。
> 2.操作时间过长，超过了最大运行时间。

开启DEBUG模式后，可以显示解析地址，地址也可用。问题是ui没了。
![截屏2021-03-29 15 06 35](https://user-images.githubusercontent.com/9905297/112799006-5d55c000-90a0-11eb-8106-6fd4a586dd0b.png)
![image](https://user-images.githubusercontent.com/9905297/112799063-6d6d9f80-90a0-11eb-82a2-3e41c319c99e.png)

**Comment by kwxiaozhu** [comment]
试试这个  69ee9e76f7d803a6fce65f052d599e4b1f5582bd

**Comment by shzxm** [comment]
> [ 69ee9e7 ](https://github.com/yuantuo666/baiduwp-php/commit/69ee9e76f7d803a6fce65f052d599e4b1f5582bd)
nginx报错

2021/03/30 15:30:52 [error] 3211028#3211028: *1 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ';' in /var/www/html/baiduwp-php/index.php on line 392" while reading response header from upstream, client: 171.216.67.134, server: pan.shzxm.art, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:",

![image](https://user-images.githubusercontent.com/9905297/112950782-3adda880-916d-11eb-9e11-ebb55839d45f.png)

**Comment by kwxiaozhu** [comment]
不好意思，多加了一个括号    b695792f011a040dcf06a316640b5294ac33c456

**Comment by kwxiaozhu** [comment]
> > [ 69ee9e7 ](https://github.com/yuantuo666/baiduwp-php/commit/69ee9e76f7d803a6fce65f052d599e4b1f5582bd)
> > nginx报错
> 
> 2021/03/30 15:30:52 [error] 3211028#3211028: *1 FastCGI sent in stderr: "PHP message: PHP Parse error: syntax error, unexpected ';' in /var/www/html/baiduwp-php/index.php on line 392" while reading response header from upstream, client: 171.216.67.134, server: request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:",
> 
> ![image](https://user-images.githubusercontent.com/9905297/112950782-3adda880-916d-11eb-9e11-ebb55839d45f.png)

不好意思，多加了一个括号  b695792f011a040dcf06a316640b5294ac33c456

**Comment by shzxm** [comment]
> > > [ 69ee9e7 ](https://github.com/yuantuo666/baiduwp-php/commit/69ee9e76f7d803a6fce65f052d599e4b1f5582bd)
> > > nginx报错
> > 
> > 
> > 2021/03/30 15:30:52 [error] 3211028#3211028: *1 FastCGI sent in stderr: "PHP message: PHP Parse error: syntax error, unexpected ';' in /var/www/html/baiduwp-php/index.php on line 392" while reading response header from upstream, client: 171.216.67.134, server: request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:",
> > ![image](https://user-images.githubusercontent.com/9905297/112950782-3adda880-916d-11eb-9e11-ebb55839d45f.png)
> 
> 不好意思，多加了一个括号 [b695792](https://github.com/yuantuo666/baiduwp-php/commit/b695792f011a040dcf06a316640b5294ac33c456)

直接没办法解析了。。。
![image](https://user-images.githubusercontent.com/9905297/112959831-67e28900-9176-11eb-9aa2-aa84de7d9b78.png)

**Comment by kwxiaozhu** [comment]
> > > > [ 69ee9e7 ](https://github.com/yuantuo666/baiduwp-php/commit/69ee9e76f7d803a6fce65f052d599e4b1f5582bd)
> > > > nginx报错
> > > 
> > > 
> > > 2021/03/30 15:30:52 [error] 3211028#3211028: *1 FastCGI sent in stderr: "PHP message: PHP Parse error: syntax error, unexpected ';' in /var/www/html/baiduwp-php/index.php on line 392" while reading response header from upstream, client: 171.216.67.134, server: request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:",
> > > ![image](https://user-images.githubusercontent.com/9905297/112950782-3adda880-916d-11eb-9e11-ebb55839d45f.png)
> > 
> > 
> > 不好意思，多加了一个括号 [b695792](https://github.com/yuantuo666/baiduwp-php/commit/b695792f011a040dcf06a316640b5294ac33c456)
> 
> 直接没办法解析了。。。
> ![image](https://user-images.githubusercontent.com/9905297/112959831-67e28900-9176-11eb-9aa2-aa84de7d9b78.png)

不应该的，你也是没用数据库吗？我刚又试了下可以正常使用的

**Comment by shzxm** [comment]
> > > > > [ 69ee9e7 ](https://github.com/yuantuo666/baiduwp-php/commit/69ee9e76f7d803a6fce65f052d599e4b1f5582bd)
> > > > > nginx报错
> > > > 
> > > > 
> > > > 2021/03/30 15:30:52 [error] 3211028#3211028: *1 FastCGI sent in stderr: "PHP message: PHP Parse error: syntax error, unexpected ';' in /var/www/html/baiduwp-php/index.php on line 392" while reading response header from upstream, client: 171.216.67.134, server: request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:",
> > > > ![image](https://user-images.githubusercontent.com/9905297/112950782-3adda880-916d-11eb-9e11-ebb55839d45f.png)
> > > 
> > > 
> > > 不好意思，多加了一个括号 [b695792](https://github.com/yuantuo666/baiduwp-php/commit/b695792f011a040dcf06a316640b5294ac33c456)
> > 
> > 
> > 直接没办法解析了。。。
> > ![image](https://user-images.githubusercontent.com/9905297/112959831-67e28900-9176-11eb-9aa2-aa84de7d9b78.png)
> 
> 不应该的，你也是没用数据库吗？我刚又试了下可以正常使用的

对的。我没使用数据库。我看你写的是修复不使用数据库的

**Comment by kwxiaozhu** [comment]
> > > > > > [ 69ee9e7 ](https://github.com/yuantuo666/baiduwp-php/commit/69ee9e76f7d803a6fce65f052d599e4b1f5582bd)
> > > > > > nginx报错
> > > > > 
> > > > > 
> > > > > 2021/03/30 15:30:52 [error] 3211028#3211028: *1 FastCGI sent in stderr: "PHP message: PHP Parse error: syntax error, unexpected ';' in /var/www/html/baiduwp-php/index.php on line 392" while reading response header from upstream, client: 171.216.67.134, server: request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:",
> > > > > ![image](https://user-images.githubusercontent.com/9905297/112950782-3adda880-916d-11eb-9e11-ebb55839d45f.png)
> > > > 
> > > > 
> > > > 不好意思，多加了一个括号 [b695792](https://github.com/yuantuo666/baiduwp-php/commit/b695792f011a040dcf06a316640b5294ac33c456)
> > > 
> > > 
> > > 直接没办法解析了。。。
> > > ![image](https://user-images.githubusercontent.com/9905297/112959831-67e28900-9176-11eb-9aa2-aa84de7d9b78.png)
> > 
> > 
> > 不应该的，你也是没用数据库吗？我刚又试了下可以正常使用的
> 
> 对的。我没使用数据库。我看你写的是修复不使用数据库的

你发的链接有问题，程序处理出错了，你试试把你发的链接转存下再分享下载，我这边可以用
