### ISSUE TITLE
建议增加安装完成后自动删除install.php文件的规则

### ISSUE THREAD

**Issue by lm379** [yuantuo666/baiduwp-php#97]
安装完成后再次访问install.php会直接填写config里的配置，包括数据库名密码什么的

**Comment by yuantuo666** [comment]
需要输入管理员密码才可再次进入安装页面
保留安装文件可以应对 数据库损坏 或 设置错误 等问题，目前暂未考虑删除

**Comment by yuantuo666** [comment]
能够直接进入，说明你已经验证过管理员密码。
