### ISSUE TITLE
服务器错误(110)

### ISSUE THREAD

**Issue by c0py7hat** [yuantuo666/baiduwp-php#98]
getDlink():array(2) {
  ["errno"]=>
  int(110)
  ["request_id"]=>
  int(8954372893676492013)
}
服务器错误(110)
服务器错误，可能服务器IP被百度封禁，请切换账号或更换服务器重试。

换了三次服务器了，更换过账号不是账号问题，换了服务器IP就能解决，但是这个太频繁了，有时候解析几次就封了。

话说不能加个代理头那种的吗以代理的方式请求而不是以服务器IP请求。
x-forwarded-for 这种能行麽

**Comment by yuantuo666** [comment]
提供一下服务器环境以及网络环境

**Comment by yuantuo666** [comment]
一般被封ip很少出现的

**Comment by yuantuo666** [comment]
一般被封ip很少出现的

**Comment by c0py7hat** [comment]
> 一般被封ip很少出现的
> 检查一下网络环境是不是正常，正常情况下不会出现这种情况。

centos8 韩国服务器 宝塔 nginx1.19.6 php7.2 mysql5.7 套了CDN
我也纳闷啊..封的这么频繁

**Comment by yuantuo666** [comment]
有尝试过其他地区的服务器吗，我这边测试都是用香港的服务器，一直没有出现过问题。

**Comment by yuantuo666** [comment]
无非就是账号或者网络的问题
代理的话比较麻烦，又包括去网上获取之类操作，而且高质量的代理需要付费。

仅修改请求头是起不到实际效果的。

**Comment by c0py7hat** [comment]
> 无非就是账号或者网络的问题
> 代理的话比较麻烦，又包括去网上获取之类操作，而且高质量的代理需要付费。
> 
> 仅修改请求头是起不到实际效果的。

好吧...我本想着爬虫可以以代理池方式，这个应该也可以，没测试过其他地区的服务器，这次在封了我就去试下其他地区的。
